cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/RelationType__c.field-meta.xml
<CustomField>
    <fullName>RelationType__c</fullName>
    <description>0	Neurčeno
1	Zastupování nezletilého
2	Zastupování nesvéprávného
3	Plná moc

CIS_UP_TYP_VZTAHU</description>
    <label>Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/AgreementDate__c.field-meta.xml
<CustomField>
    <fullName>AgreementDate__c</fullName>
    <description>Date when the agreement was made</description>
    <label>Agreement Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/integrations/classes/aq/Triggers_Test.cls
@IsTest
private class Triggers_Test {

	@IsTest
	static void testAccountTrigger() {
		Account a = TestDataFactory.getAccount();
		insert a;
		a.Name = 'another name';
		update a;
		delete a;
	}

	@IsTest
	static void testAccountRelationTrigger() {
		AccountRelation__c a = TestDataFactory.getAccountRelation(null, null);
		insert a;
		a.RelationType__c = '0';
		update a;
		delete a;
	}

	@IsTest
	static void testClientZoneTrigger() {
		ClientZone__c z = TestDataFactory.getClientZone(null);
		insert z;
		z.AgreementDate__c = Date.today();
		update z;
		delete z;
	}

	@IsTest
	static void testOpportunityTrigger() {
		Opportunity o = TestDataFactory.getOpportunity();
		insert o;
		o.Name = 'another name';
		update o;
		delete o;
	}

	@IsTest
	static void testTaskTrigger() {
		Task t = TestDataFactory.getTask(new Task());
		insert t;
		t.Subject = 'another subject';
		update t;
		delete t;
	}
}