cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AmendmentNumber__c.field-meta.xml
<CustomField>
    <fullName>AmendmentNumber__c</fullName>
    <label>Amendment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/ClientZoneID__c.field-meta.xml
<CustomField>
    <fullName>ClientZoneID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Zone ID</label>
    <referenceTo>ClientZone__c</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>Account_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelationTypeNEL__c.field-meta.xml
<CustomField>
    <fullName>RelationTypeNEL__c</fullName>
    <label>Relation Type NEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/integrations/classes/handlers/ActivateCZContractRelationsHandler.cls
public with sharing class ActivateCZContractRelationsHandler {

	private ClientZone__c clientZone;
	private Integer amendmentNumber;
	private List<AccountRelation__c> relationsToDeactivate = new List<AccountRelation__c>();
	private List<AccountRelation__c> relationsToActivate = new List<AccountRelation__c>();

	public ActivateCZContractRelationsHandler(String clientZoneId, Integer amendmentNumber) {
		this.clientZone = ReferenceUtility.getClientZoneByExternalId(clientZoneId);
		this.amendmentNumber = amendmentNumber;
	}

	public void handle() {
		queryRelations();
		if (relationsToActivate.isEmpty()) {
			throw new SOAPCommonTypes.BusinessException(204, 'There are no relations to be activated. AmendmentNumber: ' + amendmentNumber);
		}
		deactivateRelations();
		activateRelations();
	}

	private void queryRelations() {
		List<AccountRelation__c> relations;
		if (amendmentNumber == null) {
			relations = [SELECT Id, AmendmentNumber__c FROM AccountRelation__c WHERE RelationTypeNEL__c = '5' AND AmendmentNumber__c = NULL AND (ClientZoneID__c = :clientZone.Id OR RelatedAccount__c = :clientZone.Account__c)];
		} else {
			relations = [SELECT Id, AmendmentNumber__c FROM AccountRelation__c WHERE RelationTypeNEL__c = '5' AND AmendmentNumber__c <= :amendmentNumber AND (ClientZoneID__c = :clientZone.Id OR RelatedAccount__c = :clientZone.Account__c)];
		}
		for (AccountRelation__c relation : relations) {
			if (amendmentNumber == null || relation.AmendmentNumber__c == amendmentNumber) {
				relationsToActivate.add(relation);
			} else {
				relationsToDeactivate.add(relation);
			}
		}
	}

	private void deactivateRelations() {
		for (AccountRelation__c relation : relationsToDeactivate) {
			relation.IsActive__c = false;
		}
		DmlUtility.updateRecords(relationsToDeactivate);
	}

	private void activateRelations() {
		for (AccountRelation__c relation : relationsToActivate) {
			relation.IsActive__c = true;
		}
		DmlUtility.updateRecords(relationsToActivate);
	}
}