cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AmendmentNumber__c.field-meta.xml
<CustomField>
    <fullName>AmendmentNumber__c</fullName>
    <label>Amendment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelationTypeNEL__c.field-meta.xml
<CustomField>
    <fullName>RelationTypeNEL__c</fullName>
    <label>Relation Type NEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id of the client zone used by external systems</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/integrations/classes/handlers/ActivateCZContractRelationsHandlerTest.cls
@IsTest
private class ActivateCZContractRelationsHandlerTest {

	@IsTest
	static void testBehavior() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone = TestDataFactory.getClientZone(new ClientZone__c(
			Account__c = account.Id
		));
		insert clientZone;
		AccountRelation__c accountRelation1 = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			AmendmentNumber__c = 5,
			RelationTypeNEL__c = '5',
			IsActive__c = true
		));
		AccountRelation__c accountRelation2 = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			AmendmentNumber__c = 6,
			RelationTypeNEL__c = '5',
			IsActive__c = false
		));
		AccountRelation__c accountRelation3 = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			AmendmentNumber__c = 6,
			IsActive__c = false
		));
		insert new List<AccountRelation__c>{
			accountRelation1, accountRelation2, accountRelation3
		};

		SF_PersonManagementSOAPService.ActivateCZContractRelationsRequestBody request = new SF_PersonManagementSOAPService.ActivateCZContractRelationsRequestBody();
		request.clientZoneId = clientZone.ExternalId__c;
		request.amendmentNumber = 6;

		Test.startTest();
		ClientZoneService.activateCZContractRelations(request);
		Test.stopTest();

		accountRelation1 = [SELECT Id, IsActive__c FROM AccountRelation__c WHERE Id = :accountRelation1.Id];
		System.assertEquals(false, accountRelation1.IsActive__c);
		accountRelation2 = [SELECT Id, IsActive__c FROM AccountRelation__c WHERE Id = :accountRelation2.Id];
		System.assertEquals(true, accountRelation2.IsActive__c);
		accountRelation3 = [SELECT Id, IsActive__c FROM AccountRelation__c WHERE Id = :accountRelation3.Id];
		System.assertEquals(false, accountRelation3.IsActive__c);
	}

	@IsTest
	static void testNullAmendment() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone = TestDataFactory.getClientZone(new ClientZone__c(
			Account__c = account.Id
		));
		insert clientZone;
		AccountRelation__c accountRelation1 = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			AmendmentNumber__c = 0,
			RelationTypeNEL__c = '5',
			IsActive__c = true
		));
		AccountRelation__c accountRelation2 = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			AmendmentNumber__c = null,
			RelationTypeNEL__c = '5',
			IsActive__c = false
		));
		AccountRelation__c accountRelation3 = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			AmendmentNumber__c = 1,
			RelationTypeNEL__c = '5',
			IsActive__c = false
		));
		insert new List<AccountRelation__c>{
			accountRelation1, accountRelation2, accountRelation3
		};

		SF_PersonManagementSOAPService.ActivateCZContractRelationsRequestBody request = new SF_PersonManagementSOAPService.ActivateCZContractRelationsRequestBody();
		request.clientZoneId = clientZone.ExternalId__c;
		request.amendmentNumber = null;

		Test.startTest();
		ClientZoneService.activateCZContractRelations(request);
		Test.stopTest();

		accountRelation1 = [SELECT Id, IsActive__c FROM AccountRelation__c WHERE Id = :accountRelation1.Id];
		System.assertEquals(true, accountRelation1.IsActive__c);
		accountRelation2 = [SELECT Id, IsActive__c FROM AccountRelation__c WHERE Id = :accountRelation2.Id];
		System.assertEquals(true, accountRelation2.IsActive__c);
		accountRelation3 = [SELECT Id, IsActive__c FROM AccountRelation__c WHERE Id = :accountRelation3.Id];
		System.assertEquals(false, accountRelation3.IsActive__c);
	}

	@IsTest
	static void testError() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone = TestDataFactory.getClientZone(new ClientZone__c(
			Account__c = account.Id
		));
		insert clientZone;

		SF_PersonManagementSOAPService.ActivateCZContractRelationsRequestBody request = new SF_PersonManagementSOAPService.ActivateCZContractRelationsRequestBody();
		request.clientZoneId = clientZone.ExternalId__c;
		request.amendmentNumber = 1;

		Test.startTest();
		try {
			ClientZoneService.activateCZContractRelations(request);
		} catch (SOAPCommonTypes.BusinessException e) {
			System.assertEquals(204, e.getErrorNumber());
		}
		Test.stopTest();
	}
}