cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AccountRole__c.field-meta.xml
<CustomField>
    <fullName>AccountRole__c</fullName>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1501</fullName>
            </value>
            <value>
                <fullName>1502</fullName>
            </value>
            <value>
                <fullName>1503</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>256</fullName>
            </value>
            <value>
                <fullName>512</fullName>
            </value>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>4096</fullName>
            </value>
            <value>
                <fullName>8192</fullName>
            </value>
            <value>
                <fullName>16384</fullName>
            </value>
            <value>
                <fullName>32768</fullName>
            </value>
            <value>
                <fullName>65536</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AmendmentNumber__c.field-meta.xml
<CustomField>
    <fullName>AmendmentNumber__c</fullName>
    <label>Amendment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccountRole__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccountRole__c</fullName>
    <label>Related Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1501</fullName>
            </value>
            <value>
                <fullName>1502</fullName>
            </value>
            <value>
                <fullName>1503</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>256</fullName>
            </value>
            <value>
                <fullName>512</fullName>
            </value>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>4096</fullName>
            </value>
            <value>
                <fullName>8192</fullName>
            </value>
            <value>
                <fullName>16384</fullName>
            </value>
            <value>
                <fullName>32768</fullName>
            </value>
            <value>
                <fullName>65536</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelationTypeNEL__c.field-meta.xml
<CustomField>
    <fullName>RelationTypeNEL__c</fullName>
    <label>Relation Type NEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <description>Platnost vztahu od</description>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <description>Platnost vztahu do</description>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ClosedBy__c.field-meta.xml
<CustomField>
    <fullName>ClosedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that closed the contract about the client zone</description>
    <label>Closed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClientZones</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id of the client zone used by external systems</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/NumberOfAnnexes__c.field-meta.xml
<CustomField>
    <fullName>NumberOfAnnexes__c</fullName>
    <description>Number of annexes related to the contract about the client zone</description>
    <label>Number of Annexes</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/User/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/integrations/classes/handlers/ChangeCZContractRelationsHandler.cls
public with sharing class ChangeCZContractRelationsHandler {

	private SF_PersonManagementSOAPService.ChangeCZContractRelationsRequestBody request;
	private ClientZone__c existingClientZone;
	private List<AccountRelation__c> newRelations = new List<AccountRelation__c>();
	private Map<String, AccountRelation__c> existingRelationsByExternalId;

	public ChangeCZContractRelationsHandler(SF_PersonManagementSOAPService.ChangeCZContractRelationsRequestBody request) {
		this.request = request;
		existingClientZone = ReferenceUtility.getClientZoneById(request.clientZoneId);
		Set<String> relationsExternalIds = ClientZoneService.buildExternalIdsSet(request.relations);
		existingRelationsByExternalId = ClientZoneService.buildExistingRelationsMap([
			SELECT Id, ExternalId__c
			FROM AccountRelation__c
			WHERE ExternalId__c IN :relationsExternalIds
		]);
	}

	public void handle() {
		updateExistingClientZone();
		processRelations();
		DmlUtility.insertRecords(newRelations);
		DmlUtility.updateRecords(existingRelationsByExternalId.values());
	}

	private void updateExistingClientZone() {
		User closedByUser = ReferenceUtility.getUserByCPU(request.closedByCPU);
		existingClientZone.ClosedBy__c = closedByUser.Id;
		existingClientZone.NumberOfAnnexes__c = request.amendmentNumber;
		DmlUtility.updateRecord(existingClientZone);

	}

	private void processRelations() {
		Map<String, Id> accountIdsByGlobalIds = ReferenceUtility.getAccountIdsByGlobalIds(request.relations);
		for (SF_PersonManagementSOAPService.ClientRelationType clientRelation : request.relations) {
			AccountRelation__c relation = existingRelationsByExternalId.get(clientRelation.externalId);
			if (relation == null) {
				relation = new AccountRelation__c(
					Account__c = accountIdsByGlobalIds.get(clientRelation.relatedClientId),
					ExternalId__c = clientRelation.externalId,
					RelatedAccount__c = existingClientZone.Account__c
				);
				newRelations.add(relation);
			}
			relation.ValidFrom__c = Date.today();
			relation.RelatedAccountRole__c = '1502';
			relation.AccountRole__c = '1501';
			relation.RelationTypeNEL__c = '5';
			relation.AmendmentNumber__c = request.amendmentNumber;
			relation.ValidTo__c = clientRelation.validTo;
		}
	}
}