cmss/main/default/objects/Configuration__mdt/Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Generic table for all custom configurations.</description>
    <label>Configuration</label>
    <pluralLabel>Configurations</pluralLabel>
</CustomObject>

cmss/main/default/objects/Configuration__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>choose debug log level, default is 1st value [debug]</description>
    <inlineHelpText>choose debug log level, default is 1st value [debug]</inlineHelpText>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>debug</fullName>
                <default>true</default>
                <label>debug</label>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>warn</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/util/classes/LoggerCleanUpBatch.cls
global class LoggerCleanUpBatch implements Database.Batchable<sObject> {
	public static String ERROR_LEVEL = 'error';
	public static String WARN_LEVEL = 'warn';
	public static String INFO_LEVEL = 'info';
	public static String DEBUG_LEVEL = 'debug';

	global Database.QueryLocator start(Database.BatchableContext bc) {
		Datetime errorTresholdDate = getLogDeleteTreshold('Logger_ErrorLevelDeleteTreshold');
		Datetime warnTresholdDate = getLogDeleteTreshold('Logger_WarnLevelDeleteTreshold');
		Datetime infoTresholdDate = getLogDeleteTreshold('Logger_InfoLevelDeleteTreshold');
		Datetime debugTresholdDate = getLogDeleteTreshold('Logger_DebugLevelDeleteTreshold');

		return Database.getQueryLocator(
			[
				SELECT Id, Level__c, CreatedDate
				FROM Log__c
				WHERE
					(CreatedDate < :errorTresholdDate
					AND Level__c = :ERROR_LEVEL)
					OR (CreatedDate < :warnTresholdDate
					AND Level__c = :WARN_LEVEL)
					OR (CreatedDate < :infoTresholdDate
					AND Level__c = :INFO_LEVEL)
					OR (CreatedDate < :debugTresholdDate
					AND Level__c = :DEBUG_LEVEL)
			]
		);
	}

	public Void execute(Database.BatchableContext jobId, List<Log__c> logList) {
		try {
			if (!logList.isEmpty()) {
				System.debug('Deleting ' + logList.size() + ' Log records.');
				List<Database.DeleteResult> results = Database.delete(logList, false);
				for (Database.DeleteResult result : results) {
					if (!result.isSuccess()) {
						for (Database.Error err : result.getErrors()) {
							Logger.error('Erorr message: ' + err.getMessage() + ' Fields:' + err.getFields());
						}
					}
				}
			}
		} catch (Exception e) {
			Logger.error('An unhandled exception thrown', e);
			throw e;
		} finally {
			Logger.saveLogs();
		}
	}

	public void finish(Database.BatchableContext jobId) {
		System.debug('Execution of LoggerCleanUpBatch finished');
	}

	private Datetime getLogDeleteTreshold(String instanceName) {
		Configuration__mdt treshold = (Configuration__mdt) Configuration__mdt.getInstance(instanceName);
		if (treshold != null && treshold.Value__c != null) {
			return Datetime.now() - Integer.valueOf(treshold.Value__c);
		} else {
			return Datetime.now() - 30;
		}
	}
}