cmss/main/default/objects/Configuration__mdt/Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Generic table for all custom configurations.</description>
    <label>Configuration</label>
    <pluralLabel>Configurations</pluralLabel>
</CustomObject>

cmss/main/default/objects/Configuration__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cmss/main/default/classes/ContentVersionTriggerHandler.cls
public class ContentVersionTriggerHandler extends TriggerHandler {
	public override void beforeInsert() {
		List<String> allowedFileExtensionsList = Configuration__mdt.getInstance('AllowedFileExtensions')
			.Value__c.split(',');       
		for (sObject version : Trigger.new) {
			ContentVersion docVersion = (ContentVersion) version;
			String extension = docVersion.PathOnClient.substringAfterLast('.');
			if (!allowedFileExtensionsList.contains(extension)) {
				docVersion.addError(
					'Soubor nemá platnou koncovku - nahrajte prosím soubor typu: ' +
					allowedFileExtensionsList.toString()
				);
			}
		}
	}
}