cmss/main/default/objects/UserCalendarSetting__c/UserCalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Used for synchronisation with Google Calendar</description>
    <label>User Calendar Setting</label>
    <nameField>
        <displayFormat>UCS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>User Calendar Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Calendar Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/UserCalendarSetting__c/fields/ResourceId__c.field-meta.xml
<CustomField>
    <fullName>ResourceId__c</fullName>
    <externalId>true</externalId>
    <label>Resource Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncActive__c.field-meta.xml
<CustomField>
    <fullName>SyncActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Active</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncToken__c.field-meta.xml
<CustomField>
    <fullName>SyncToken__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCalendarSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/UserCalendarID__c.field-meta.xml
<CustomField>
    <fullName>UserCalendarID__c</fullName>
    <externalId>true</externalId>
    <label>User Calendar ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchExpirationDateTime__c.field-meta.xml
<CustomField>
    <fullName>WatchExpirationDateTime__c</fullName>
    <label>Watch Expiration DateTime</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchId__c.field-meta.xml
<CustomField>
    <fullName>WatchId__c</fullName>
    <label>Watch Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/triggerHandlers/UserCalendarSettingTriggerHandler.cls
public class UserCalendarSettingTriggerHandler extends TriggerHandler {
	private static boolean shouldRunAfterInsertTrigger = true;
	private static final GoogleCalendarSyncService calendarSyncService = new GoogleCalendarSyncService();

	public override void afterInsert() {
		if (!Test.isRunningTest()) {
			initialEventSync(Trigger.new);
		}
	}

	public override void beforeUpdate() {
		stopWatchingUpdate(
			(List<UserCalendarSetting__c>) Trigger.old,
			(Map<Id, UserCalendarSetting__c>) Trigger.newMap
		);
	}

	public override void afterDelete() {
		stopWatching(Trigger.old);
	}

	@testVisible
	private static void initialEventSync(List<UserCalendarSetting__c> newSettings) {
		if (shouldRunAfterInsertTrigger) {
			for (UserCalendarSetting__c setting : newSettings) {
				initialEventSyncFuture(setting.Id);
			}
		}
	}

	@testVisible
	private static void shouldNotRunAfterInsertTrigger() {
		shouldRunAfterInsertTrigger = false;
	}

	@testVisible
	private static void shouldRunAfterInsertTrigger() {
		shouldRunAfterInsertTrigger = true;
	}

	@Future(callout=true)
	private static void initialEventSyncFuture(Id settingsId) {
		UserCalendarSetting__c setting = [
			SELECT Id, OwnerId, UserCalendarId__c, SyncActive__c, SyncToken__c, ResourceId__c, User__c
			FROM UserCalendarSetting__c
			WHERE Id = :settingsId
		];
		InitialCalendarSyncController.sync(setting);
	}

	@testVisible
	private static void stopWatchingUpdate(
		List<UserCalendarSetting__c> oldSettings,
		Map<Id, UserCalendarSetting__c> newSettingsMap
	) {
		List<UserCalendarSetting__c> settingsToStopWatching = new List<UserCalendarSetting__c>();
		for (UserCalendarSetting__c oldSetting : oldSettings) {
			UserCalendarSetting__c newSetting = newSettingsMap.get(oldSetting.Id);
			if (oldSetting.SyncActive__c && !newSetting.SyncActive__c) {
				newSetting.WatchId__c = null;
				newSetting.WatchExpirationDateTime__c = null;
				settingsToStopWatching.add(newSetting);
			}
		}
		stopWatching(settingsToStopWatching);

		for (UserCalendarSetting__c setting : settingsToStopWatching) {
			setting.WatchId__c = null;
			setting.WatchExpirationDateTime__c = null;
		}
	}

	private static void stopWatching(List<UserCalendarSetting__c> settings) {
		for (UserCalendarSetting__c setting : settings) {
			stopWatchingFuture(setting.WatchId__c, setting.ResourceId__c);
		}
	}

	@Future(callout=true)
	private static void stopWatchingFuture(String watchId, String resourceId) {
		calendarSyncService.stopWatch(watchId, resourceId);
	}
}