cmss/main/default/objects/UserCalendarSetting__c/UserCalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Used for synchronisation with Google Calendar</description>
    <label>User Calendar Setting</label>
    <nameField>
        <displayFormat>UCS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>User Calendar Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Calendar Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/UserCalendarSetting__c/fields/ResourceId__c.field-meta.xml
<CustomField>
    <fullName>ResourceId__c</fullName>
    <externalId>true</externalId>
    <label>Resource Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncActive__c.field-meta.xml
<CustomField>
    <fullName>SyncActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Active</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncToken__c.field-meta.xml
<CustomField>
    <fullName>SyncToken__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCalendarSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/UserCalendarID__c.field-meta.xml
<CustomField>
    <fullName>UserCalendarID__c</fullName>
    <externalId>true</externalId>
    <label>User Calendar ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchId__c.field-meta.xml
<CustomField>
    <fullName>WatchId__c</fullName>
    <label>Watch Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/controllers/CalendarSyncStatusControllerTest.cls
@IsTest
private class CalendarSyncStatusControllerTest {
	@IsTest
	static void getUserCalendarSettingTest() {
		UserCalendarSetting__c setting = new UserCalendarSetting__c();
		setting.ResourceId__c = '1234';
		setting.SyncActive__c = true;
		setting.SyncToken__c = '1234';
		setting.User__c = UserInfo.getUserId();
		setting.UserCalendarID__c = '1234@kalendar.com';
		setting.WatchId__c = '1234';
		insert setting;

		Test.startTest();
		UserCalendarSetting__c actualUserSetting = CalendarSyncStatusController.getUserCalendarSetting();
		Test.stopTest();

		System.assertNotEquals(null, actualUserSetting);
		System.assertEquals('1234', actualUserSetting.ResourceId__c);
		System.assertEquals(true, actualUserSetting.SyncActive__c);
		System.assertEquals('1234@kalendar.com', actualUserSetting.UserCalendarID__c);
	}

	@IsTest
	static void validateCalendarConnectionTest() {
		CalloutServiceMockImpl fakeResponse = new CalloutServiceMockImpl(200, 'OK', '', null, null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);

		Test.startTest();
		Boolean resp = CalendarSyncStatusController.validateCalendarConnection('calendar@id.com');
		Test.stopTest();

		System.assertEquals(true, resp);
	}

	@IsTest
	static void createWatchTest() {
		UserCalendarSetting__c setting = new UserCalendarSetting__c();
		setting.ResourceId__c = '1234';
		setting.SyncActive__c = true;
		setting.SyncToken__c = '1234';
		setting.User__c = UserInfo.getUserId();
		setting.UserCalendarID__c = '1234@kalendar.com';
		setting.WatchId__c = '1234';
		insert setting;

		GoogleCalendarSyncService.WatchResponse watchResp = new GoogleCalendarSyncService.WatchResponse();
		watchResp.expiration = 123456789;
		watchResp.id = '12345';
		watchResp.resourceId = 'ResourceId';
		watchResp.token = '12345';

		CalloutServiceMockImpl fakeResponse = new CalloutServiceMockImpl(
			200,
			'OK',
			JSON.serialize(watchResp),
			null,
			null
		);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
		Test.startTest();
		CalendarSyncStatusController.createWatch(setting.Id);
		Test.stopTest();

		UserCalendarSetting__c updatedSetting = [
			SELECT WatchId__c, ResourceId__c
			FROM UserCalendarSetting__c
			WHERE Id = :setting.Id
		];
		System.assertEquals('12345', updatedSetting.WatchId__c);
		System.assertEquals('ResourceId', updatedSetting.ResourceId__c);
	}
}