cmss/main/default/objects/AssetRelationship/fields/ProductTypeAssetId__c.field-meta.xml
<CustomField>
    <fullName>ProductTypeAssetId__c</fullName>
    <label>Product Type Asset Id</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/ContactInformation__c.object-meta.xml
<CustomObject>
    <description>An object to store contact information about clients/prospects/leads/agents/assets</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ContactInformation__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Ulice</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/customer-360/classes/RelatedListWithSharingControllerTest.cls
@IsTest
public class RelatedListWithSharingControllerTest {
	private static Asset asset1;
	private static Asset asset2;
	private static Account acc;

	@TestSetup
	static void makeData() {
		acc = new Account();
		acc.name = 'testAccount';
		insert acc;

		asset1 = new Asset();
		asset1.name = 'testAsset 1';
		asset1.AccountId = acc.Id;

		asset2 = new Asset();
		asset2.name = 'testAsset 2';
		asset2.AccountId = acc.Id;
		insert new List<Asset>{ asset1, asset2 };

		AssetRelationship relationship = new AssetRelationship();
		relationship.AssetId = asset1.Id;
		relationship.RelatedAssetId = asset2.Id;
		relationship.FromDate = System.today().addDays(-5);
		relationship.ToDate = System.today().addDays(5);
		insert relationship;
	}

	@IsTest
	public static void testGetDataForDataTable() {
		Asset testAsset = [SELECT Id FROM Asset WHERE Name = 'testAsset 1'][0];
		List<string> listOfFields = new List<string>{
			'RelatedAssetId',
			'ProductTypeAssetId__c',
			'RelationshipType',
			'RelatedAsset.Account.Name',
			'FromDate',
			'ToDate'
		};
		String myData = RelatedListWithSharingController.getDataForDataTable(
			'AssetRelationship',
			listOfFields,
			'',
			testAsset.Id,
			'AssetId',
			'RelatedAssetId'
		);

		List<AssetRelationship> expectedData = [
			SELECT
				ProductTypeAssetId__c,
				AssetId,
				RelatedAssetId,
				RelationshipType,
				RelatedAsset.Account.Name,
				FromDate,
				ToDate
			FROM AssetRelationship
			WHERE AssetId = :testAsset.Id
		];

		List<SObject> deserializedObjs = (List<SObject>) JSON.deserialize(myData, List<SObject>.class);

		System.assertEquals(expectedData.size(), deserializedObjs.size());
		System.assertEquals(1, deserializedObjs.size());
	}

	@isTest
	public static void testGetFieldsDetails() {
		List<String> listOfFields = new List<String>{ 'Id', 'Email__c', 'Street__c' };
		List<ColumnDTO> myData = RelatedListWithSharingController.getFieldsDetailsWithButtons(
			'ContactInformation__c',
			listOfFields
		);
	}

	@isTest
	public static void testshareRelatedAccount() {
		Id profileId = [SELECT Id, Name FROM Profile WHERE Name = 'CMSS User'].Id;
		Asset AssetToShare = [SELECT Id, Name FROM Asset WHERE Name = 'testAsset 1'][0];

		User testUser = TestDataFactory.getUser(new User(ProfileId = profileId));
		insert testUser;

		List<AccountShare> sharesBefore = [SELECT Id FROM AccountShare];
		Test.startTest();
		System.runAs(testUser) {
			RelatedListWithSharingController.shareRelatedAccount(AssetToShare.Id, false);
		}
		Test.stopTest();
		List<AccountShare> sharesAfter = [SELECT Id FROM AccountShare];

		System.assertEquals(sharesBefore.size() + 1, sharesAfter.size());
	}
}