cmss/main/default/objects/CustomSearchFilter__c/CustomSearchFilter__c.object-meta.xml
<CustomObject>
    <label>Custom Search Filter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Custom Search Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Search Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/CustomSearchFilter__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field Api Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchFilter__c/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>exact match</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>start with</fullName>
            </value>
            <value>
                <fullName>end with</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/CustomSearchFilter__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RelatedObject__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CustomSearchType</valueSetName>
    </valueSet>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchFilter__c/fields/RelatedObject__c.field-meta.xml
<CustomField>
    <fullName>RelatedObject__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ObjectType</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/globalValueSets/CustomSearchType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PersonAccount</fullName>
    </customValue>
    <customValue>
        <fullName>BuildingSavings</fullName>
    </customValue>
    <customValue>
        <fullName>CSOBCurrentAccount</fullName>
    </customValue>
    <customValue>
        <fullName>CreditAndIntermediateLoan</fullName>
    </customValue>
    <customValue>
        <fullName>CreditCases</fullName>
    </customValue>
    <customValue>
        <fullName>InvestmentLifeInsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Mortgages</fullName>
    </customValue>
    <customValue>
        <fullName>PMO</fullName>
    </customValue>
    <customValue>
        <fullName>PensionProducts</fullName>
    </customValue>
    <customValue>
        <fullName>RiskLifeInsurance</fullName>
    </customValue>
    <customValue>
        <fullName>PortfolioManagementChangeRequest</fullName>
    </customValue>
    <customValue>
        <fullName>Master</fullName>
        <isActive>false</isActive>
        <label>Master</label>
    </customValue>
    <masterLabel>Custom Search Type</masterLabel>
</GlobalValueSet>

cmss/main/default/globalValueSets/ObjectType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Asset</fullName>
    </customValue>
    <masterLabel>Object Type</masterLabel>
</GlobalValueSet>

cmss/main/default/classes/service/CustomFilterService.cls
public with sharing class CustomFilterService {
	private String objectType;
	private String productType;
	private Map<String, String> valueLabelMap = new Map<String, String>();

	public CustomFilterService(String objectType, String productType) {
		this.objectType = objectType;
		this.productType = productType;
	}
	public List<CustomFilterItemDto> getCustomFilterMap() {
		List<CustomSearchFilter__c> customFilterList = [
			SELECT
				ProductType__c,
				FieldApiName__c,
				RecordType.DeveloperName,
				RelatedObject__c,
				Filter__c,
				DisplayOrder__c,
				Name
			FROM CustomSearchFilter__c
			WHERE RelatedObject__c = :objectType AND ProductType__c = :productType
			ORDER BY DisplayOrder__c ASC NULLS LAST
		];

		Map<Id, CustomSearchFilter__c> customFilterLabelMap = new Map<Id, CustomSearchFilter__c>(
			[
				SELECT Id, toLabel(ProductType__c)
				FROM CustomSearchFilter__c
				WHERE RelatedObject__c = :objectType AND ProductType__c = :productType
			]
		);

		List<CustomFilterItemDto> dtoItemList = new List<CustomFilterItemDto>();
		createLabelValueMapFromFilter();
		for (CustomSearchFilter__c csf : customFilterList) {
			CustomFilterItemDto dtoItem = new CustomFilterItemDto();
			dtoItem.productType = csf.ProductType__c;
			dtoItem.productTypeLabel = customFilterLabelMap.get(csf.Id).ProductType__c;
			dtoItem.fieldName = csf.FieldApiName__c;
			dtoItem.dataType = csf.RecordType.DeveloperName;
			dtoItem.relatedObject = csf.RelatedObject__c;
			dtoItem.availableFilterList = getAvailableFilterList(csf.Filter__c);
			if (dtoItem.fieldName.indexOf('.') > -1) {
				String relR = csf.FieldApiName__c.substringBefore('.');
				String relC = relR.replace('__r', '__c');
				SObjectType sObjectTypeL2 = Schema.getGlobalDescribe().get(dtoItem.relatedObject);
				List<Schema.sObjectType> parents = sObjectTypeL2.getDescribe()
					.fields.getMap()
					.get(relC)
					.getDescribe()
					.getReferenceTo();
				dtoItem.objectTypeForLabel = String.valueOf(parents[0]);
				dtoItem.fieldNameForLabel = csf.FieldApiName__c.substringAfter('.');
				dtoItem.fieldLabel = csf.Name;
			} else {
				dtoItem.objectTypeForLabel = dtoItem.relatedObject;
				dtoItem.fieldNameForLabel = dtoItem.fieldName;
				dtoItem.fieldLabel = Schema.getGlobalDescribe()
					.get(dtoItem.relatedObject)
					.getDescribe()
					.fields.getMap()
					.get(dtoItem.fieldName)
					.getDescribe()
					.getLabel();
			}
			System.debug('FIELD: ' + csf.FieldApiName__c);
			dtoItemList.add(dtoItem);
		}

		return dtoItemList;
	}

	private void createLabelValueMapFromFilter() {
		Schema.DescribeFieldResult describeFilter = CustomSearchFilter__c.Filter__c.getDescribe();
		List<Schema.PicklistEntry> picklistValList = describeFilter.getPicklistValues();
		for (Schema.PicklistEntry en : picklistValList) {
			valueLabelMap.put(en.getValue(), en.getLabel());
		}
	}

	private List<SelectOption> getAvailableFilterList(String savedFiltersString) {
		if (String.isBlank(savedFiltersString)) {
			return new List<SelectOption>();
		}
		List<String> savedFilters = savedFiltersString.split(';');
		List<SelectOption> labelValueList = new List<SelectOption>();
		for (String val : savedFilters) {
			SelectOption labelValue = new SelectOption(valueLabelMap.get(val), val);
			labelValueList.add(labelValue);
		}
		return labelValueList;
	}
}