cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Client zone access role</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Limited</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Self-registration</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Self-registration Verified Contacts</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Pre-verified User</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Verified User</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>User Agreement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Full Access</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>No Access</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the client zone - active/inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/integrations/classes/handlers/CancelCZContractHandlerTest.cls
@IsTest
public class CancelCZContractHandlerTest {
	@IsTest
	static void testClientZoneUpdate() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone = TestDataFactory.getClientZone(new ClientZone__c(Account__c = account.Id));
		insert clientZone;

		CancelCZContractHandler handler = new CancelCZContractHandler(clientZone);

		Test.startTest();
		handler.handle();
		Test.stopTest();

		ClientZone__c updatedClientZone = [
			SELECT Id, Role__c, Status__c
			FROM ClientZone__c
			WHERE Account__c = :account.Id
		];
		System.assertEquals('8', updatedClientZone.Role__c);
		System.assertEquals('2', updatedClientZone.Status__c);
	}
}