cmss/main/default/objects/AssetAccountRelation__c/AssetAccountRelation__c.object-meta.xml
<CustomObject>
    <label>Asset Account Relation</label>
    <nameField>
        <label>Asset Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AssetAccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference na klienta/prospekta</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Reference na smlouvu</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/RelationType__c.field-meta.xml
<CustomField>
    <fullName>RelationType__c</fullName>
    <description>Typ role (dlžník/spoludlžník...)
Pro UP:  FK CIS_ROLE_UP::KOD
Pro SS/MU/USS/RZP:  FK CIS_DRUH_DISPOZICIE::KOD</description>
    <label>Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>103</fullName>
            </value>
            <value>
                <fullName>104</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>106</fullName>
            </value>
            <value>
                <fullName>107</fullName>
            </value>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>109</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>201</fullName>
            </value>
            <value>
                <fullName>202</fullName>
            </value>
            <value>
                <fullName>203</fullName>
            </value>
            <value>
                <fullName>204</fullName>
            </value>
            <value>
                <fullName>205</fullName>
            </value>
            <value>
                <fullName>206</fullName>
            </value>
            <value>
                <fullName>207</fullName>
            </value>
            <value>
                <fullName>208</fullName>
            </value>
            <value>
                <fullName>209</fullName>
            </value>
            <value>
                <fullName>210</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/customer-360/classes/AssetRelatedListControllerTest.cls
@IsTest
public class AssetRelatedListControllerTest {

	private static Account acc;

	static void makeData() {
		acc = new Account();
		acc.Name = 'testAcc';
		insert acc;

		List<Asset> astInfos = new List<Asset>();
		Asset astInf1 = new Asset(Name = 'testAsset1', AccountId = acc.Id);
		Asset astInf2 = new Asset(Name = 'testAsset2', AccountId = acc.Id);

		astInfos.add(astInf1);
		astInfos.add(astInf2);

		insert astInfos;

		List<Asset> testAsts = [SELECT Id FROM Asset];

		List<AssetAccountRelation__c> asAcRels = new List<AssetAccountRelation__c>();
		AssetAccountRelation__c asAcRel1 = new AssetAccountRelation__c(
			Name = 'Vlastník',
			Account__c = acc.Id,
			Asset__c = testAsts[0].Id,
			RelationType__c = '1'
		);
		AssetAccountRelation__c asAcRel2 = new AssetAccountRelation__c(
			Name = 'Pojistník',
			Account__c = acc.Id,
			Asset__c = testAsts[1].Id,
			RelationType__c = '2'
		);
		AssetAccountRelation__c asAcRel3 = new AssetAccountRelation__c(
			Name = 'Pojištěná osoba',
			Account__c = acc.Id,
			Asset__c = testAsts[1].Id,
			RelationType__c = '3'
		);

		asAcRels.add(asAcRel1);
		asAcRels.add(asAcRel2);
		asAcRels.add(asAcRel3);

		insert asAcRels;
	}

	@IsTest
	static void testGetDataForDataTable() {
		makeData();
		Account testAcc = acc;

		List<String> listOfFields = new List<String>{
			'AccountId', 'Price', 'Name'
		};
		String myData = AssetRelatedListController.getDataForDataTable(
			listOfFields,
			testAcc.Id, null, null
		);

		System.debug('My data:' + myData);
		List<Asset> expectedData = [
			SELECT AccountId, Price, Id, Name
			FROM Asset
			WHERE AccountId = :testAcc.Id
			WITH SECURITY_ENFORCED
			ORDER BY CreatedDate DESC
		];
		// TODO incomplete test
	}

}