cmss/main/default/objects/AssetAccountRelation__c/AssetAccountRelation__c.object-meta.xml
<CustomObject>
    <label>Asset Account Relation</label>
    <nameField>
        <label>Asset Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AssetAccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference na klienta/prospekta</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Reference na smlouvu</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Priority value is used in Assets related list to show correct relations order. See CRM-29, CRM-208</description>
    <formula>CASE( RelationType__c ,
        &quot;1&quot;, 1,
        &quot;2&quot;, 2,
        &quot;3&quot;, 3,
        &quot;4&quot;, 4,
        &quot;5&quot;, 5,
        &quot;6&quot;, 6,
        &quot;7&quot;, 7,
        &quot;8&quot;, 8,
        &quot;9&quot;, 9,
        &quot;10&quot;, 10,
        &quot;101&quot;, 1,
        &quot;102&quot;, 2,
        &quot;103&quot;, 3,
        &quot;104&quot;, 4,
        &quot;105&quot;, 5,
        &quot;106&quot;, 6,
        &quot;107&quot;, 7,
        &quot;108&quot;, 8,
        &quot;109&quot;, 9,
        &quot;201&quot;, 1,
        &quot;202&quot;, 2,
        &quot;203&quot;, 3,
        &quot;204&quot;, 4,
        &quot;205&quot;, 5,
        &quot;206&quot;, 6,
        &quot;207&quot;, 7,
        &quot;208&quot;, 8,
        &quot;209&quot;, 9,
        &quot;210&quot;, 10,
        &quot;211&quot;, 11,
        &quot;301&quot;, 1,
        &quot;303&quot;, 2,
        &quot;304&quot;, 3,
        &quot;401&quot;, 1,
        &quot;402&quot;, 2,
        &quot;403&quot;, 3,
        &quot;404&quot;, 4,
        &quot;405&quot;, 5,
        &quot;406&quot;, 6,
        &quot;407&quot;, 7,
        &quot;408&quot;, 8,
        &quot;409&quot;, 9,
        &quot;410&quot;, 10,
        &quot;411&quot;, 11,
        &quot;412&quot;, 12,
        999)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/RelationType__c.field-meta.xml
<CustomField>
    <fullName>RelationType__c</fullName>
    <description>Typ role (dlžník/spoludlžník...)
Pro UP:  FK CIS_ROLE_UP::KOD
Pro SS/MU/USS/RZP:  FK CIS_DRUH_DISPOZICIE::KOD</description>
    <label>Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>103</fullName>
            </value>
            <value>
                <fullName>104</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>106</fullName>
            </value>
            <value>
                <fullName>107</fullName>
            </value>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>109</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>201</fullName>
            </value>
            <value>
                <fullName>202</fullName>
            </value>
            <value>
                <fullName>203</fullName>
            </value>
            <value>
                <fullName>204</fullName>
            </value>
            <value>
                <fullName>205</fullName>
            </value>
            <value>
                <fullName>206</fullName>
            </value>
            <value>
                <fullName>207</fullName>
            </value>
            <value>
                <fullName>208</fullName>
            </value>
            <value>
                <fullName>209</fullName>
            </value>
            <value>
                <fullName>210</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/customer-360/classes/AssetRelatedListController.cls
public without sharing class AssetRelatedListController {
	@AuraEnabled
	public static String getDataForDataTable(
		List<String> fieldsToShow,
		String accountId,
		String conditionAssets,
		String conditionRelations
	) {
		List<AssetAccountRelation__c> relations = selectRelations(accountId, conditionRelations);
		Set<Id> relatedAssetsIds = getAssetIds(relations);
		String assetsCondition = prepareAssetsCondition(accountId, conditionAssets, new List<Id>(relatedAssetsIds));
		Map<Id, Asset> assetMap = new Map<Id, Asset>(
			(List<Asset>) GenericRelatedListController.queryData('Asset', fieldsToShow, assetsCondition)
		);

		List<Map<String, Object>> assetObjectsFromRelations = new List<Map<String, Object>>();
		// assets from relations, respecting relations order
		for (AssetAccountRelation__c relation : relations) {
			Asset asset = assetMap.get(relation.Asset__c);
			if (asset == null) {
				continue;
			}
			Map<String, Object> untypedMap = convertToUntypedMap(asset);
			untypedMap.put('Relation', relation);
			assetObjectsFromRelations.add(untypedMap);
			assetMap.remove(relation.Asset__c);
		}

		// remaining assets (these will be at the top of list)
		List<Map<String, Object>> assetObjects = new List<Map<String, Object>>();
		for (Asset asset : assetMap.values()) {
			Map<String, Object> untypedMap = convertToUntypedMap(asset);
			assetObjects.add(untypedMap);
		}
		assetObjects.addAll(assetObjectsFromRelations);
		return JSON.serialize(assetObjects);
	}

	private static List<AssetAccountRelation__c> selectRelations(Id accountId, String condition) {
		String query =
			'SELECT Id, toLabel(RelationType__c), Asset__c FROM AssetAccountRelation__c WHERE Account__c = \'' +
				accountId +
				'\'';
		if (!String.isBlank(condition)) {
			query += ' AND ' + condition;
		}
		query += ' ORDER BY Priority__c';
		return (List<AssetAccountRelation__c>) Database.query(query);
	}

	private static Set<Id> getAssetIds(List<AssetAccountRelation__c> relations) {
		Set<Id> ids = new Set<Id>();
		for (AssetAccountRelation__c relation : relations) {
			ids.add(relation.Asset__c);
		}
		return ids;
	}

	private static String prepareAssetsCondition(Id accountId, String condition, List<Id> assetIds) {
		String result = '(AccountId = \'' + accountId + '\'';
		if (!assetIds.isEmpty()) {
			result += ' OR Id IN (\'';
			result += String.join(assetIds, '\',\'');
			result += '\')';
		}
		result += ')';
		if (!String.isBlank(condition)) {
			result += ' AND ' + condition;
		}
		return result;
	}

	private static Map<String, Object> convertToUntypedMap(SObject record) {
		String serialized = JSON.serialize(record);
		Map<String, Object> untypedMap = (Map<String, Object>) JSON.deserializeUntyped(serialized);
		return untypedMap;
	}
}