cmss/main/default/objects/Opportunity/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>Autor, který vytvořil opportunitu</description>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/CreatedDateTime__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateTime__c</fullName>
    <label>Created Date Time</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/DelegatedDate__c.field-meta.xml
<CustomField>
    <fullName>DelegatedDate__c</fullName>
    <description>Datum, kdy byla OP naposledy delegována</description>
    <label>Delegated Date</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>Termín pro dokončení příležitosti -do kdy má OZ příležitost zpracovat</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Opportunity/fields/OriginalAsset__c.field-meta.xml
<CustomField>
    <fullName>OriginalAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asset from which was the opportunity created</description>
    <label>Original Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>Update Date</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/integrations/classes/services/OpportunityService.cls
public with sharing class OpportunityService {

	private static Map<String, String> stateReasonToStageMapping = new Map<String, String>{
		'1' => '2',
		'2' => '2',
		'3' => '3',
		'4' => '4',
		'5' => '5',
		'6' => '1',
		'7' => '7'
	};

	public static String createOpportunity(SF_OpportunitySOAPService.OpportunityType data) {
		if (data.id != null) {
			throw new SOAPCommonTypes.BusinessException(102, 'Invalid attribute specified: cannot specify "id" in createOpportunity');
		}
		Validation.requireAttribute(data.customerGlobalId, 'customerGlobalId');
		Opportunity opportunity = prepareOpportunity(data);
		opportunity.ExternalId__c = UUIDUtil.generateUUID();
		if (data.validFrom == null) {
			opportunity.CreatedDateTime__c = System.now();
			opportunity.ValidFrom__c = System.now();
		}
		if (data.validTo == null) {
			opportunity.CloseDate = Date.today().addDays(90);
			opportunity.ValidTo__c = Date.today().addDays(120);
		}
		opportunity.DueDate__c = Date.today().addDays(90);
		opportunity.UpdateDate__c = System.now();
		SObjectUtil.stripNullFields(opportunity);
		DmlUtility.insertRecord(opportunity);
		return opportunity.ExternalId__c;
	}

	public static void updateOpportunity(SF_OpportunitySOAPService.OpportunityType data) {
		Validation.requireAttribute(data.id, 'id');
		Opportunity opportunity = prepareOpportunity(data);
		opportunity.UpdateDate__c = System.now();
		SObjectUtil.stripNullFields(opportunity);
		DmlUtility.updateRecord(opportunity);
	}

	private static Opportunity prepareOpportunity(SF_OpportunitySOAPService.OpportunityType data) {
		Opportunity o = new Opportunity();
		if (!String.isBlank(data.id)) {
			o.Id = ReferenceUtility.getOpportunityByExternalId(data.id).Id;
		}
		if (data.customerGlobalId != null) {
			o.AccountId = ReferenceUtility.getAccountByGlobalId(data.customerGlobalId).Id;
		}
		o.Description = data.description;
		o.Name = data.subject;
		o.StageName = data.stateReason == null ? '1' : stateReasonToStageMapping.get(data.stateReason);
		o.Reason__c = data.result;
		o.Author__c = data.author;
		if (data.statusManagerCPU != null) {
			o.OwnerId = ReferenceUtility.getUserByCPU(data.statusManagerCPU).Id;
		}
		if (data.validFrom != null) {
			o.CreatedDateTime__c = data.validFrom;
			o.ValidFrom__c = data.validFrom;
		}
		if (data.validTo != null) {
			o.CloseDate = data.validTo.date();
			o.ValidTo__c = data.validTo;
		}
		o.Category__c = data.category;
		if (data.contractNumber != null) {
			o.OriginalAsset__c = ReferenceUtility.getAssetByNumber(data.contractNumber).Id;
		}
		o.DelegatedDate__c = data.delegatedDate;
		return o;
	}
}