cmss/main/default/objects/Opportunity/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>Autor, který vytvořil opportunitu</description>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/opportunity-management/classes/OpportunityController.cls
/**
 * Created by J. Birka on 10.11.2022
 */
public without sharing class OpportunityController {
	@AuraEnabled
	public static Id createOpportunity(String objectIdString) {
		try {
			Id objectId;
			String commAccntNr = [SELECT CommissionAccountNr__c FROM User WHERE Id = :UserInfo.getUserId()][0]
			.CommissionAccountNr__c;
			Opportunity oppty = new Opportunity();
			oppty.Description = 'Sjednání úvěru ze stavebního spoření';
			oppty.Name = 'eÚvěry';
			oppty.StageName = '1';
			oppty.Author__c = commAccntNr;
			oppty.OwnerId = UserInfo.getUserId();
			oppty.ValidFrom__c = System.today();
			oppty.ValidTo__c = System.today().addDays(60);
			oppty.CloseDate = System.today().addDays(60);
			oppty.Category__c = '5';

			if (String.isBlank(objectIdString)) {
				//HomePage context
				insert oppty;
				return oppty.Id;
			} else {
				objectId = Id.valueOf(objectIdString);

				if (objectId.getSobjectType() == Account.SObjectType) {
					//Account context
					oppty.AccountId = objectId;
					insert oppty;
					return oppty.Id;
				} else if (objectId.getSobjectType() == Task.SObjectType) {
					//Task context
					oppty.AccountId = [SELECT AccountId FROM Task WHERE Id = :objectId LIMIT 1][0].AccountId;
					insert oppty;
					return oppty.Id;
				} else if (objectId.getSobjectType() == Opportunity.SObjectType) {
					//Opportunity context
					return objectId;
				} else {
					return null;
				}
			}
		} catch (Exception e) {
			//end Try
			throw new AuraHandledException(e.getMessage());
		}
	}
}