cmss/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/DeactivateDate__c.field-meta.xml
<CustomField>
    <fullName>DeactivateDate__c</fullName>
    <description>Datum, kdy má dojít k deaktivaci příležitosti</description>
    <label>Deactivate Date</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/IsVisibleForNel__c.field-meta.xml
<CustomField>
    <fullName>IsVisibleForNel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Visible For Nel</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/opportunity-management/objects/OpportunityExpirationConfig__mdt/OpportunityExpirationConfig__mdt.object-meta.xml
<CustomObject>
    <label>Opportunity Expiration Config</label>
    <pluralLabel>Opportunity Expiration Configs</pluralLabel>
</CustomObject>

cmss/opportunity-management/objects/OpportunityExpirationConfig__mdt/fields/ChainActivityExpireBatch__c.field-meta.xml
<CustomField>
    <fullName>ChainActivityExpireBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chain Activity Expire Batch</label>
    <type>Checkbox</type>
</CustomField>

cmss/opportunity-management/objects/OpportunityExpirationConfig__mdt/fields/ExpirationDaysFromValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDaysFromValidFrom__c</fullName>
    <label>Expiration Days From Valid From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/opportunity-management/objects/OpportunityExpirationConfig__mdt/fields/ExpirationDaysFromValidTo__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDaysFromValidTo__c</fullName>
    <label>Expiration Days From Valid To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/opportunity-management/classes/OpportunityExpireBatch.cls
public without sharing class OpportunityExpireBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
	@testVisible
	private OpportunityExpirationConfig__mdt cfg;
	@testVisible
	private Datetime validToTreshold;
	@testVisible
	private Datetime validFromTreshold;

	private void loadConfig() {
		this.cfg = [
			SELECT ChainActivityExpireBatch__c, ExpirationDaysFromValidTo__c, ExpirationDaysFromValidFrom__c
			FROM OpportunityExpirationConfig__mdt
			LIMIT 1
		];

		this.validToTreshold = System.now().addDays(-cfg.ExpirationDaysFromValidTo__c.intValue());
		this.validFromTreshold = System.now().addDays(-cfg.ExpirationDaysFromValidFrom__c.intValue());
	}

	public Database.QueryLocator start(Database.BatchableContext jobId) {
		if (cfg == null) {
			loadConfig();
		}
		return Database.getQueryLocator(
			[
				SELECT Id, Name, Reason__c
				FROM Opportunity
				WHERE
					StageName != '8'
					AND Category__c = '3'
					AND (ValidTo__c <= :validToTreshold
					OR (ValidTo__c = NULL
					AND ValidFrom__c <= :validFromTreshold))
			]
		);
	}

	public void execute(Database.BatchableContext jobId, List<sObject> recordList) {
		final Date today = System.today();
		List<Opportunity> toUpdate = new List<Opportunity>();

		for (Opportunity op : (List<Opportunity>) recordList) {
			op.StageName = '8';
			op.DeactivateDate__c = today;
			op.IsVisibleForNel__c = false;
			if (String.isBlank(op.Reason__c)) {
				op.Reason__c = '9';
			}
			toUpdate.add(op);
		}

		update toUpdate;

		List<Task> tasksToUpdate = new List<Task>();
		for (Task tsk : [SELECT Id FROM Task WHERE WhatId IN :toUpdate AND Status != '5']) {
			tsk.DeactivateDate__c = today;
			tsk.Status = '5';
			tasksToUpdate.add(tsk);
		}
		if (tasksToUpdate.size() > 0) {
			update tasksToUpdate;
		}
	}

	public void finish(Database.BatchableContext jobId) {
		if (cfg.ChainActivityExpireBatch__c) {
			ActivityExpireBatch activityBatch = new ActivityExpireBatch();
			Database.executeBatch(activityBatch);
		}
	}

	public void execute(SchedulableContext sc) {
		Database.executeBatch(this);
	}
}