cmss/main/default/objects/Opportunity/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>State Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Open</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Won</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Lost</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/OpportunityStateCodeMapping__mdt/OpportunityStateCodeMapping__mdt.object-meta.xml
<CustomObject>
    <label>Opportunity State Code Mapping</label>
    <pluralLabel>Opportunity State Code Mappings</pluralLabel>
</CustomObject>

cmss/main/default/objects/OpportunityStateCodeMapping__mdt/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <inlineHelpText>Value of Opportunity.StageName field</inlineHelpText>
    <label>StageName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/OpportunityStateCodeMapping__mdt/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <inlineHelpText>Value of Opportunity.StateCode__c field</inlineHelpText>
    <label>StateCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cmss/product-contract/classes/OpportunityTriggerHandlerTest.cls
@Istest
public class OpportunityTriggerHandlerTest {

	@IsTest
	public static void testSetStateCode() {
		Map<String, String> stageToStateMap = new Map<String, String>();
		for (OpportunityStateCodeMapping__mdt mapping : [SELECT StageName__c, StateCode__c FROM OpportunityStateCodeMapping__mdt]) {
			stageToStateMap.put(mapping.StageName__c, mapping.StateCode__c);
		}
		List<Opportunity> opportunities = new List<Opportunity>();
		for (String stage : stageToStateMap.keySet()) {
			opportunities.add(TestDataFactory.getOpportunity(new Opportunity(
				StageName = stageToStateMap.get(stage)
			)));
		}
		Test.startTest();
		insert opportunities;
		Test.stopTest();

		opportunities = [SELECT Id, StageName, StateCode__c FROM Opportunity];
		for (Opportunity opportunity: opportunities) {
			System.assertEquals(stageToStateMap.get(opportunity.StageName), opportunity.StateCode__c);
		}

		Opportunity o = TestDataFactory.getOpportunity(new Opportunity());
		insert o;
		o.StageName = '3';
		update o;
		o = [SELECT Id, StageName, StateCode__c FROM Opportunity WHERE Id = :o.Id];
		System.assertEquals(stageToStateMap.get(o.StageName), o.StateCode__c);
	}
}