cmss/main/e-forms/objects/Document_Configuration__mdt/Document_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Document Configuration</label>
    <pluralLabel>Document Configurations</pluralLabel>
</CustomObject>

cmss/main/e-forms/objects/Document_Configuration__mdt/fields/Migration_Process__c.field-meta.xml
<CustomField>
    <fullName>Migration_Process__c</fullName>
    <label>Migration Process</label>
    <referenceTo>Migration_Process__mdt</referenceTo>
    <relationshipLabel>Document Configurations</relationshipLabel>
    <relationshipName>Document_Configurations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

cmss/main/e-forms/objects/Document_Configuration__mdt/fields/Template_Code__c.field-meta.xml
<CustomField>
    <fullName>Template_Code__c</fullName>
    <label>Template Code</label>
    <length>65</length>
    <type>Text</type>
</CustomField>

cmss/main/e-forms/objects/Migration_Process__mdt/Migration_Process__mdt.object-meta.xml
<CustomObject>
    <label>Migration Process</label>
    <pluralLabel>Migration Processes</pluralLabel>
</CustomObject>

cmss/e-forms/objects/Migration_Process__mdt/fields/Title_CZ__c.field-meta.xml
<CustomField>
    <fullName>Title_CZ__c</fullName>
    <description>CZ Title in the Header, tab title of the migration</description>
    <label>Title CZ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/e-forms/objects/Migration_Process__mdt/fields/Title_EN__c.field-meta.xml
<CustomField>
    <fullName>Title_EN__c</fullName>
    <description>EN Title in the Header, tab title of the migration</description>
    <label>Title EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/e-forms/classes/PcfSignpostController.cls
/**
 * Created by lukas.krbec on 03.06.2022.
 */

public class PcfSignpostController {
	@AuraEnabled
	public static List<WrapedProcess> getRelatedMigrationProcesses(String recordId) {
		List<WrapedProcess> processes = new List<WrapedProcess>();
		String title = UserInfo.getLanguage() == 'cs' ? 'Title_CZ__c' : 'Title_EN__c';
		for (Document_Configuration__mdt p : [SELECT Migration_Process__r.DeveloperName, Migration_Process__r.Title_CZ__c, Migration_Process__r.Title_EN__c, Template_Code__c FROM Document_Configuration__mdt]) {
			processes.add(new WrapedProcess(p.Migration_Process__r.DeveloperName, (String) p.getSobject('Migration_Process__r').get(title), p.Template_Code__c));
		}
		System.debug(processes);
		return processes;
	}
	public class WrapedProcess {
		@AuraEnabled public string developerName { get; set; }
		@AuraEnabled public string title { get; set; }
		@AuraEnabled public string template { get; set; }

		public WrapedProcess(String developerName, String title, String template) {
			this.developerName = developerName;
			this.title = title;
			this.template = template;
		}
	}

	@AuraEnabled
	public static CommunityWrapper isPortalEnabled() {
		CommunityWrapper cw = new CommunityWrapper();
		Site site = [SELECT Id FROM Site WHERE UrlPathPrefix = 's' LIMIT 1];
		//cw.isPortalEnabled = true;
		cw.isPortalEnabled = [SELECT Id, IsPortalEnabled FROM User WHERE Id = :UserInfo.getUserId()].IsPortalEnabled;
		cw.urlPrefix = [SELECT SecureURL FROM SiteDetail WHERE DurableId = :site.Id].SecureUrl;
		return cw;
	}

	public class CommunityWrapper {
		@AuraEnabled
		public Boolean isPortalEnabled;
		@AuraEnabled
		public String urlPrefix;
	}
}