cmss/main/default/objects/LogEvent__e/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

cmss/main/default/objects/LogEvent__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>possible values same as on Log__c object [debug, info, warn, error]</description>
    <label>Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/LoggingSetting__c/LoggingSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>setting of log levels</description>
    <label>Logging Setting</label>
</CustomObject>

cmss/main/default/objects/LoggingSetting__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&apos;debug&apos;</defaultValue>
    <description>possible values: [debug, warn, error, info]</description>
    <inlineHelpText>possible values: [debug, warn, error, info]</inlineHelpText>
    <label>Level</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/util/classes/Logger.cls
public with sharing class Logger {

	private static String logLevel = 'debug';
	private static List<LogEvent__e> logEventsToPublish = new List<LogEvent__e>();

	private Logger() {
		String logLevelPreferred = LoggingSetting__c.getOrgDefaults().Level__c;
		if (logLevelPreferred != null) {
			System.debug('logging level is: ' + logLevelPreferred);
			logLevel = logLevelPreferred;
		}
	}

	public static void log(String level, String message, String ex, String payload) {
		LogEvent__e logEvent = createLogEvent(level, message, ex, payload);
		logEventsToPublish.add(logEvent);
	}

	public static void log(String level, String message, String ex) {
		log(message, ex, '');
	}

	public static void log(String level, String message) {
		log(message, '', '');
	}

	public static LogEvent__e createLogEvent(String logLevel, String message, String ex, String payload) {
		LogEvent__e logEvent = new LogEvent__e();
		logEvent.Message__c = message;
		logEvent.Exception__c = ex;
		logEvent.Level__c = logLevel;
		logEvent.Payload__c = payload;
		return logEvent;
	}

	public static void saveLogs() {
		List<Database.SaveResult> results = EventBus.publish(logEventsToPublish);

		for (Database.SaveResult sr : results) {
			if (sr.isSuccess()) {
				System.debug('Successfully published event.');
			} else {
				for(Database.Error err : sr.getErrors()) {
					System.debug('Error returned: ' +
							err.getStatusCode() +
							' - ' +
							err.getMessage());
				}
			}
		}
	}
}