cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/CustomSearchConfiguration__c.object-meta.xml
<CustomObject>
    <label>Custom Search Configuration</label>
    <nameField>
        <label>CustomSearchConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Search Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/FieldsetName__c.field-meta.xml
<CustomField>
    <fullName>FieldsetName__c</fullName>
    <label>Fieldset Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/FilterCondition__c.field-meta.xml
<CustomField>
    <fullName>FilterCondition__c</fullName>
    <label>Filter Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ObjectType</valueSetName>
    </valueSet>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/OwnerFieldName__c.field-meta.xml
<CustomField>
    <fullName>OwnerFieldName__c</fullName>
    <formula>IF( TEXT(ObjectType__c) = &apos;Asset&apos;, &apos;PortfolioMgmtA__c&apos;, &apos;PortfolioMngmtA__c&apos;)</formula>
    <label>Owner Filed Name</label>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CustomSearchType</valueSetName>
    </valueSet>
</CustomField>

cmss/micro-campaign-custom-search/default/globalValueSets/CustomSearchType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PersonAccount</fullName>
    </customValue>
    <customValue>
        <fullName>BuildingSavings</fullName>
    </customValue>
    <customValue>
        <fullName>CSOBCurrentAccount</fullName>
    </customValue>
    <customValue>
        <fullName>CreditAndIntermediateLoan</fullName>
    </customValue>
    <customValue>
        <fullName>CreditCases</fullName>
    </customValue>
    <customValue>
        <fullName>InvestmentLifeInsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Mortgages</fullName>
    </customValue>
    <customValue>
        <fullName>PMO</fullName>
    </customValue>
    <customValue>
        <fullName>PensionProducts</fullName>
    </customValue>
    <customValue>
        <fullName>RiskLifeInsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Master</fullName>
        <isActive>false</isActive>
        <label>Master</label>
    </customValue>
    <masterLabel>Custom Search Type</masterLabel>
</GlobalValueSet>

cmss/main/default/globalValueSets/ObjectType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Asset</fullName>
    </customValue>
    <masterLabel>Object Type</masterLabel>
</GlobalValueSet>

cmss/micro-campaign-custom-search/default/classes/CustomSearchController.cls
public with sharing class CustomSearchController {
	@AuraEnabled(Cacheable=true)
	public static List<CustomFilterItemDto> getCustomFilterMap(String objectType, String productName) {
		CustomFilterService service = new CustomFilterService(objectType, productName);

		return service.getCustomFilterMap();
	}

	@AuraEnabled(Cacheable=true)
	public static List<RecordTypeInfoDto> loadTypeList() {
		RecordTypeService service = new RecordTypeService();
		return service.loadRecordTypes();
	}

	@AuraEnabled(Cacheable=true)
	public static List<UserHierarchyTreeDto> loadUserHierarchyTree(Id userId) {
		if (userId == null) {
			userId = UserInfo.getUserId();
		}
		UserHierarchyTreeService service = new UserHierarchyTreeService(userId);
		return new List<UserHierarchyTreeDto>{ service.loadUserHierarchyTree() };
	}

	@AuraEnabled
	public static Integer countResults(CustomSearchFilterRequestDto dto) {
		try {
			CustomSoqlService service = new CustomSoqlService(dto);
			return service.getDataCountFromDbDto();
		} catch (System.QueryException e) {
			Logger.error('Error in CustomSearchController.searchResults countResults', e);
			throw new AuraHandledException(e.getMessage());
		} catch (Exception e) {
			Logger.error('Error in CustomSearchController.searchResults countResults', e);
			throw new AuraHandledException(Label.SearchCommonError);
		} finally {
			Logger.saveLogs();
		}
	}

	@AuraEnabled
	public static CustomSearchFilterResponseDto searchResults(CustomSearchFilterRequestDto dto) {
		try {
			CustomSoqlService service = new CustomSoqlService(dto);
			Integer countRecords = service.getDataCountFromDbDto();
			List<SObject> data = service.getDataFromDbDto();
			return new CustomSearchFilterResponseDto(data, countRecords);
		} catch (System.QueryException e) {
			Logger.error('Error in CustomSearchController.searchResults searchResults', e);
			throw new AuraHandledException(e.getMessage());
		} catch (Exception e) {
			Logger.error('Error in CustomSearchController.searchResults searchResults', e);
			throw new AuraHandledException(Label.SearchCommonError);
		} finally {
			Logger.saveLogs();
		}
	}

	@AuraEnabled
	public static List<Id> getAllAccountId(CustomSearchFilterRequestDto dto) {
		CustomSoqlService service = new CustomSoqlService(dto);
		return new List<Id>(service.getAllAccountIdsDbDto());
	}
	@AuraEnabled(Cacheable=true)
	public static List<CustomSearchConfiguration__c> loadBaseConfigurationList(
		String objectApiName,
		String productName
	) {
		return [
			SELECT
				Id,
				Name,
				Description__c,
				FilterCondition__c,
				FieldsetName__c,
				ObjectType__c,
				ProductType__c,
				OwnerFieldName__c,
				DisplayOrder__c
			FROM CustomSearchConfiguration__c
			WHERE ObjectType__c = :objectApiName AND ProductType__c = :productName AND Active__c = TRUE
			ORDER BY DisplayOrder__c ASC NULLS LAST
		];
	}

	@AuraEnabled
	public static List<FieldsetInfoDto> loadFieldsetDetail(String fieldsetName, String objectName) {
		FieldsetService service = new FieldsetService(fieldsetName, objectName);
		return service.getFieldsetInfo();
	}

	@AuraEnabled
	public static void createMicroCampaign(CreateMicroCampaignDto data) {
		try {
			Database.executeBatch(new CreateMicroCampaignBatch(data));
		} catch (Exception e) {
			Logger.error('Error in micro-campaign creation', e);
			throw new AuraHandledException(
				'Unexpected exception: ' +
				e.getMessage() +
				'; transactionId: ' +
				Logger.getTransactionId()
			);
		} finally {
			Logger.saveLogs();
		}
	}
}