cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/CustomSearchConfiguration__c.object-meta.xml
<CustomObject>
    <label>Custom Search Configuration</label>
    <nameField>
        <label>CustomSearchConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Search Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/FieldsetName__c.field-meta.xml
<CustomField>
    <fullName>FieldsetName__c</fullName>
    <label>Fieldset Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/FilterCondition__c.field-meta.xml
<CustomField>
    <fullName>FilterCondition__c</fullName>
    <label>Filter Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ObjectType</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/globalValueSets/ObjectType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Asset</fullName>
    </customValue>
    <masterLabel>Object Type</masterLabel>
</GlobalValueSet>

cmss/micro-campaign-custom-search/default/classes/ValidateSoqlService.cls
public with sharing class ValidateSoqlService {
	public static final String ERROR_FILTER = 'Filter Condition is Wrong';
	public static final String ERROR_FIELDSET = 'Fieldset name is wrong';

	public static void validateCustomSearchConfiguration(
		List<CustomSearchConfiguration__c> CustomSearchConfigurationListToValidate
	) {
		for (CustomSearchConfiguration__c csc : CustomSearchConfigurationListToValidate) {
			String queryFields = '';
			FieldsetService service = new FieldsetService(csc.FieldsetName__c, csc.ObjectType__c);
			queryFields = CustomSoqlService.getQueryFieldsFromFieldSetService(service);
			if (queryFields.length() == 0) {
				csc.FieldsetName__c.addError(ERROR_FIELDSET);
			}
			String query =
				'SELECT ' +
				queryFields +
				' FROM ' +
				csc.ObjectType__c +
				' WHERE ' +
				csc.FilterCondition__c +
				' LIMIT 0';
			try {
				Database.query(query);
			} catch (System.QueryException e) {
				csc.FilterCondition__c.addError(ERROR_FILTER);
			}
		}
	}
}