cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/CustomSearchConfiguration__c.object-meta.xml
<CustomObject>
    <label>Custom Search Configuration</label>
    <nameField>
        <label>CustomSearchConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Search Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/FieldsetName__c.field-meta.xml
<CustomField>
    <fullName>FieldsetName__c</fullName>
    <label>Fieldset Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/FilterCondition__c.field-meta.xml
<CustomField>
    <fullName>FilterCondition__c</fullName>
    <label>Filter Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ObjectType</valueSetName>
    </valueSet>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CustomSearchType</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

cmss/micro-campaign-custom-search/default/globalValueSets/CustomSearchType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PersonAccount</fullName>
    </customValue>
    <customValue>
        <fullName>BuildingSavings</fullName>
    </customValue>
    <customValue>
        <fullName>CSOBCurrentAccount</fullName>
    </customValue>
    <customValue>
        <fullName>CreditAndIntermediateLoan</fullName>
    </customValue>
    <customValue>
        <fullName>CreditCases</fullName>
    </customValue>
    <customValue>
        <fullName>InvestmentLifeInsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Mortgages</fullName>
    </customValue>
    <customValue>
        <fullName>PMO</fullName>
    </customValue>
    <customValue>
        <fullName>PensionProducts</fullName>
    </customValue>
    <customValue>
        <fullName>RiskLifeInsurance</fullName>
    </customValue>
    <customValue>
        <fullName>Master</fullName>
        <isActive>false</isActive>
        <label>Master</label>
    </customValue>
    <masterLabel>Custom Search Type</masterLabel>
</GlobalValueSet>

cmss/main/default/globalValueSets/ObjectType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Asset</fullName>
    </customValue>
    <masterLabel>Object Type</masterLabel>
</GlobalValueSet>

cmss/micro-campaign-custom-search/default/classes/service/ValidateSoqlServiceTest.cls
@IsTest
private class ValidateSoqlServiceTest {
	@TestSetup
	static void beforeTest() {
		CustomSearchConfiguration__c myCustomSearchConfiguration = new CustomSearchConfiguration__c(
			FieldsetName__c = 'Search_Component',
			FilterCondition__c = 'City__c LIKE \'%demo%\'',
			ObjectType__c = 'Account',
			ProductType__c = 'PersonAccount'
		);
		insert myCustomSearchConfiguration;
	}

	@IsTest
	static void validateSoqlServiceTestfromCustomSearchCOnfOkFilter() {
		CustomSearchConfiguration__c myCustomSearchConfiguration2 = new CustomSearchConfiguration__c(
			FieldsetName__c = 'Search_Component',
			FilterCondition__c = 'City__c LIKE \'%s%\' ',
			ObjectType__c = 'Account'
		);

		Test.startTest();
		Database.SaveResult result = Database.insert(myCustomSearchConfiguration2, false);
		System.assert(result.isSuccess());
		System.assert(result.getErrors().size() == 0);

		Test.stopTest();
	}
}