cmss/main/default/objects/User/fields/AgentId__c.field-meta.xml
<CustomField>
    <fullName>AgentId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Agent Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/UserCalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Used for synchronisation with Google Calendar</description>
    <label>User Calendar Setting</label>
    <nameField>
        <displayFormat>UCS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>User Calendar Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Calendar Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncActive__c.field-meta.xml
<CustomField>
    <fullName>SyncActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Active</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCalendarSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/UserCalendarID__c.field-meta.xml
<CustomField>
    <fullName>UserCalendarID__c</fullName>
    <externalId>true</externalId>
    <label>User Calendar ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchExpirationDateTime__c.field-meta.xml
<CustomField>
    <fullName>WatchExpirationDateTime__c</fullName>
    <label>Watch Expiration DateTime</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchId__c.field-meta.xml
<CustomField>
    <fullName>WatchId__c</fullName>
    <label>Watch Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/classes/UpdateUserCalendarSettings_BatchTest.cls
@IsTest
public class UpdateUserCalendarSettings_BatchTest {
	@testSetup
	static void setup() {
		// Create test data
		List<UserCalendarSetting__c> testUcs = new List<UserCalendarSetting__c>();
		User user = TestDataFactory.getUser(new User(AgentId__c = 'UA18439'));

		for (Integer i = 0; i < 2; i++) {
			testUcs.add(
				new UserCalendarSetting__c(
					SyncActive__c = true,
					User__c = user.Id,
					UserCalendarID__c = '123456',
					WatchExpirationDateTime__c = Date.valueOf('2022-04-10'),
					WatchId__c = '12345'
				)
			);
		}
		insert testUcs;
	}

	@IsTest
	private static void updateUserCalendarSettings() {
		UpdateUserCalendarSettings_Batch batch = new UpdateUserCalendarSettings_Batch();

		Test.startTest();
		GoogleCalendarSyncService.WatchResponse mockResponse = new GoogleCalendarSyncService.WatchResponse();
		mockResponse.id = '12345';
		mockResponse.resourceId = '123456';
		mockResponse.token = '1234567';
		mockResponse.expiration = ((Long) ((Datetime) System.Today().addMonths(1)).getTime());

		CalloutServiceMockImpl fakeResponse = new CalloutServiceMockImpl(
			200,
			'OK',
			JSON.serialize(mockResponse),
			null,
			null
		);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
		Database.executeBatch(batch);
		Test.stopTest();

		UserCalendarSetting__c ucs = [
			SELECT WatchId__c, WatchExpirationDateTime__c
			FROM UserCalendarSetting__c
			WHERE UserCalendarID__c = '123456'
			LIMIT 1
		];

		System.assertEquals('12345', ucs.WatchId__c, 'Not expected WatchId__c found');
		System.assertEquals(
			System.Today().addMonths(1),
			ucs.WatchExpirationDateTime__c,
			'Not expected WatchExpirationDateTime__c found'
		);
	}

	@IsTest
	static void getPushNotificationsSiteUrlTest() {
		Test.startTest();
		String pushNotificationsSiteUrl = UpdateUserCalendarSettings_Batch.getPushNotificationsSiteUrl();
		Test.stopTest();

		System.assertEquals('', pushNotificationsSiteUrl);
	}
}