cmss/main/default/objects/User/fields/AgentActivityType__c.field-meta.xml
<CustomField>
    <fullName>AgentActivityType__c</fullName>
    <description>Jedinečný identifikátor pro entitu Typ činnosti přidruženou k entitě Odbytový orgán.</description>
    <label>Agent Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/User/fields/ManagerIds__c.field-meta.xml
<CustomField>
    <fullName>ManagerIds__c</fullName>
    <formula>ManagerId &amp; &quot;, &quot; &amp; Manager.ManagerId &amp; &quot;, &quot; &amp; Manager.Manager.ManagerId &amp; &quot;, &quot; &amp; Manager.Manager.Manager.ManagerId &amp; &quot;, &quot; &amp; Manager.Manager.Manager.Manager.ManagerId</formula>
    <label>Manager Id List</label>
    <type>Text</type>
</CustomField>

cmss/main/default/classes/service/UserHierarchyTreeService.cls
public with sharing class UserHierarchyTreeService {
	private Id userId;

	public UserHierarchyTreeService(Id userId) {
		this.userId = userId;
	}

	public UserHierarchyTreeDto loadUserHierarchyTree() {
		String userId15 = String.valueOf(this.userId).substring(0, 15);
		String queryUserId = '%' + userId15 + '%';
		List<User> userList = [
			SELECT Id, Name, ManagerId, AgentActivityType__c
			FROM User
			WHERE ManagerIds__c LIKE :queryUserId AND IsActive = TRUE
		];

		Map<Id, List<User>> userMap = new Map<Id, List<User>>();

		for (User user : userList) {
			if (userMap.containsKey(user.ManagerId)) {
				userMap.get(user.ManagerId).add(user);
			} else {
				List<User> tmpList = new List<User>();
				tmpList.add(user);
				userMap.put(user.ManagerId, tmpList);
			}
		}

		User currentUser = [SELECT Id, Name, AgentActivityType__c, ManagerId FROM User WHERE Id = :this.userId];
		return userToDto(currentUser, userMap);
	}

	private UserHierarchyTreeDto userToDto(User u, Map<Id, List<User>> userMap) {
		UserHierarchyTreeDto dto = new UserHierarchyTreeDto();
		dto.userId = u.Id;
		dto.name = u.Name;
		dto.functionType = u.AgentActivityType__c;
		dto.children = prepareRecord(u, userMap);
		return dto;
	}

	private List<UserHierarchyTreeDto> prepareRecord(User parentUser, Map<Id, List<User>> userMap) {
		List<UserHierarchyTreeDto> result = null;
		if (userMap.containsKey(parentUser.Id)) {
			result = new List<UserHierarchyTreeDto>();
			UserHierarchyTreeDto parentUserDto = userToDto(parentUser, new Map<Id, List<User>>());
			parentUserDto.userId = parentUser.Id + '_copy';
			result.add(parentUserDto);
			for (User user : userMap.get(parentUser.Id)) {
				UserHierarchyTreeDto dto = userToDto(user, userMap);
				result.add(dto);
			}
		}

		return result;
	}
}