cmss/main/default/objects/User/fields/GlowID__c.field-meta.xml
<CustomField>
    <fullName>GlowID__c</fullName>
    <label>Glow ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/LoginName__c.field-meta.xml
<CustomField>
    <fullName>LoginName__c</fullName>
    <description>Required for SSO</description>
    <externalId>true</externalId>
    <label>Login Name</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/util/classes/OpenAMRegistrationHandlerTest.cls
@IsTest
private class OpenAMRegistrationHandlerTest {
	@IsTest
	static void testCreateUser_loginName() {
		User u = TestDataFactory.getUser(new User(
			LoginName__c = 'test0001'
		));
		insert u;

		Auth.UserData userData1 = new Auth.UserData('test0001', null, null, null, null, null, null, null, null, null, null);
		Auth.UserData userData2 = new Auth.UserData('another', null, null, null, null, null, null, null, null, null, null);

		OpenAMRegistrationHandler registrationHandler = new OpenAMRegistrationHandler();
		User returnedUser = registrationHandler.createUser(null, userData1);
		registrationHandler.updateUser(null, null, null);
		System.assertEquals(u.Id, returnedUser.Id);

		System.assertEquals(null, registrationHandler.createUser(null, userData2));
	}

	@IsTest
	static void testCreateUser_glow() {
		User u = TestDataFactory.getUser(new User(
			GlowID__c = 'test0001'
		));
		insert u;

		Auth.UserData userData1 = new Auth.UserData('test0001', null, null, null, null, null, null, null, null, null, null);
		Auth.UserData userData2 = new Auth.UserData('another', null, null, null, null, null, null, null, null, null, null);

		OpenAMRegistrationHandler registrationHandler = new OpenAMRegistrationHandler();
		User returnedUser = registrationHandler.createUser(null, userData1);
		registrationHandler.updateUser(null, null, null);
		System.assertEquals(u.Id, returnedUser.Id);

		System.assertEquals(null, registrationHandler.createUser(null, userData2));
	}
}