cmss/main/default/objects/KZNotificationSettings__c/KZNotificationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used for configure notifications about expiring or deleting client zone</description>
    <label>KZ Notification Settings</label>
</CustomObject>

cmss/main/default/objects/KZNotificationSettings__c/fields/SendNotifications__c.field-meta.xml
<CustomField>
    <fullName>SendNotifications__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, a valid MailServiceNotification__c record is created, otherwise it is created with an error so the notification does not get sent</description>
    <label>SendNotifications</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/MailServiceNotification__c.object-meta.xml
<CustomObject>
    <label>MailServiceNotification</label>
    <nameField>
        <label>MailServiceNotification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MailServiceNotifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

cmss/main/default/objects/MailServiceNotification__c/fields/FromEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>FromEmailAddress__c</fullName>
    <label>FromEmailAddress</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/NotSentDueToError__c.field-meta.xml
<CustomField>
    <fullName>NotSentDueToError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NotSentDueToError</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/SendAfter__c.field-meta.xml
<CustomField>
    <fullName>SendAfter__c</fullName>
    <label>SendAfter</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/ToEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>ToEmailAddress__c</fullName>
    <label>ToEmailAddress</label>
    <type>Email</type>
</CustomField>

cmss/integrations/classes/handlers/MailNotificationsHandler.cls
public class MailNotificationsHandler {
	private SObject onObject;
	private EmailTemplate emailTemplate;
	private Map<String, String> specialVariableValues;
	private String senderEmail = 'noreply@csobstavebni.cz';
	private List<String> receiverEmails;
	private String emailSubject;
	private String emailBody;
	private String context = '';
	private Boolean disableMailSending = false;

	private List<MailServiceNotification__c> generatedNotifications;

	public MailNotificationsHandler() {
		this.receiverEmails = new List<String>();
		this.generatedNotifications = new List<MailServiceNotification__c>();
	}

	public MailNotificationsHandler setContext(String context) {
		this.context = context;
		setUpDisableMailSending();
		return this;
	}

	public MailNotificationsHandler setEmailTemplate(EmailTemplate emailTemplate) {
		this.emailTemplate = emailTemplate;
		return this;
	}

	public MailNotificationsHandler setEmailTemplate(String emailTemplateDevName) {
		this.emailTemplate = [SELECT HtmlValue, Subject FROM EmailTemplate WHERE DeveloperName = :emailTemplateDevName];
		return this;
	}

	public MailNotificationsHandler setSpecialVariables(Map<String, String> specialVariableValues) {
		this.specialVariableValues = specialVariableValues;
		return this;
	}

	public MailNotificationsHandler setSender(String senderEmail) {
		this.senderEmail = senderEmail;
		return this;
	}

	public MailNotificationsHandler setReceivers(List<String> receiverEmails) {
		this.receiverEmails = receiverEmails;
		return this;
	}

	public void handleInsertNotifications() {
		List<MailServiceNotification__c> notifications = retrieveGeneratedNotifications();
		System.debug(notifications);
		insert notifications;
	}

	public void generateNotifications(SObject sourceObject, List<String> receivers) {
		this.onObject = sourceObject;
		setUpEmail();
		for (String receiverEmail : receivers) {
			generatedNotifications.add(getOneNotification(receiverEmail));
		}
	}

	public List<MailServiceNotification__c> retrieveGeneratedNotifications() {
		return generatedNotifications;
	}

	private MailServiceNotification__c getOneNotification(String receiverEmail) {
		MailServiceNotification__c newNotification = new MailServiceNotification__c();
		newNotification.ToEmailAddress__c = receiverEmail;
		newNotification.FromEmailAddress__c = senderEmail;
		newNotification.Subject__c = emailSubject;
		newNotification.Body__c = emailBody;
		newNotification.SendAfter__c = System.today();
		newNotification.NotSentDueToError__c = disableMailSending;
		return newNotification;
	}

	@TestVisible
	private void setUpEmail() {
		emailBody = processTextation(emailTemplate.HtmlValue);
		emailSubject = processTextation(emailTemplate.Subject);
	}

	private void setUpDisableMailSending() {
		if (context == 'DIGIKZ') {
			KZNotificationSettings__c KZSettings = KZNotificationSettings__c.getOrgDefaults();
			disableMailSending = !KZSettings.SendNotifications__c;
		}
	}

	private String processTextation(String text) {
		String finalText = text;

		while (finalText.contains('{!')) {
			String fieldName = finalText.substringBetween('{!', '}');
			if (this.specialVariableValues != null && this.specialVariableValues.keySet().contains(fieldName)) {
				finalText = finalText.replace('{!' + fieldName + '}', this.specialVariableValues.get(fieldName));
			} else {
				finalText = replaceFirstVarWithFieldValue(finalText, fieldName);
			}
		}
		return finalText;
	}

	private String replaceFirstVarWithFieldValue(String text, String fieldName) {
		String finalText = text;
		List<String> fieldRelation = fieldName.split('\\.');
		SObject childObject = onObject;

		while (fieldRelation.size() > 1) {
			String firstObj = fieldRelation.remove(0);
			childObject = childObject.getSobject(firstObj);
		}
		if (childObject?.get(fieldRelation?.get(0)) != null) {
			finalText = finalText.replace(
				'{!' +
				fieldName +
				'}',
				String.valueOf(childObject.get(fieldRelation.get(0)))
			);
		} else {
			finalText = finalText.replace('{!' + fieldName + '}', '?');
		}
		return finalText;
	}
}