cmss/main/default/objects/IntegrationSettings__c/IntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for integration (endpoints, usernames etc)</description>
    <label>Integration Settings</label>
</CustomObject>

cmss/main/default/objects/IntegrationSettings__c/fields/CertificateName__c.field-meta.xml
<CustomField>
    <fullName>CertificateName__c</fullName>
    <label>Certificate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/IntegrationSettings__c/fields/EsbEndpoint__c.field-meta.xml
<CustomField>
    <fullName>EsbEndpoint__c</fullName>
    <description>Base of common service URL, including protocol and port. Eg: https://ivdr.cmss.cz:443</description>
    <inlineHelpText>Base of common service URL, including protocol and port. Eg: https://ivdr.cmss.cz:443</inlineHelpText>
    <label>Esb Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/IntegrationSettings__c/fields/EsbPassword__c.field-meta.xml
<CustomField>
    <fullName>EsbPassword__c</fullName>
    <label>Esb Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/IntegrationSettings__c/fields/EsbUsername__c.field-meta.xml
<CustomField>
    <fullName>EsbUsername__c</fullName>
    <label>Esb Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/services/ESBService.cls
public virtual class ESBService {
	@testVisible
	protected String ENVELOPE_NS = 'http://schemas.xmlsoap.org/soap/envelope/';
	@testVisible
	protected String V01_NS = 'http://service.cmss.cz/common/CommonMessage/v01';

	@testVisible
	protected String CERTIFICATE_NAME = IntegrationSettings__c.getOrgDefaults().CertificateName__c;
	@testVisible
	protected String ENDPOINT_BASE = IntegrationSettings__c.getOrgDefaults().EsbEndpoint__c;

	@testVisible
	protected DOM.XmlNode populateDoc(DOM.Document doc, Map<String, String> namespaces) {
		DOM.XmlNode envelope = doc.createRootElement('Envelope', ENVELOPE_NS, 'soapenv');
		for (String key : namespaces.keySet()) {
			envelope.setNamespace(key, namespaces.get(key));
		}
		envelope.setNamespace('v01', V01_NS);
		DOM.XmlNode header = envelope.addChildElement('Header', ENVELOPE_NS, 'soapenv');
		new SOAPCommonTypes.OutboundHttpHeader()
			.addWssToHeader(
				header,
				IntegrationSettings__c.getOrgDefaults().EsbUsername__c,
				IntegrationSettings__c.getOrgDefaults().EsbPassword__c
			);
		DOM.XmlNode body = envelope.addChildElement('Body', ENVELOPE_NS, 'soapenv');
		return body;
	}
}