cmss/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

cmss/main/default/objects/Knowledge__kav/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Knowledge__kav/fields/CMSSArticleNumber__c.field-meta.xml
<CustomField>
    <fullName>CMSSArticleNumber__c</fullName>
    <label>CMSS Article Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Knowledge__kav/fields/CurrentlyValid__c.field-meta.xml
<CustomField>
    <fullName>CurrentlyValid__c</fullName>
    <formula>OR(ValidFrom__c &lt;= TODAY(),ValidTo__c &gt;= TODAY(),ValidTo__c = null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currently Valid</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Knowledge__kav/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Knowledge__kav/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Knowledge__kav/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

cmss/app/community/classes/KnowledgeArticlesListController.cls
public with sharing class KnowledgeArticlesListController {
    public KnowledgeArticlesListController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getKnowledgeArticles(String topicId, String recordTypeName, String articlesType) {
        List<Knowledge__kav> knowledgeArticlesList = new List<Knowledge__kav>();

        if (topicId != '' && topicId != null) {
            String knowledgeQuery = 'SELECT Id, Title, CMSSArticleNumber__c, ValidFrom__c, ValidTo__c, Priority__c, Author__c, CurrentlyValid__c, LastPublishedDate, RecordType.Name FROM Knowledge__kav '
                                    + 'WHERE PublishStatus = \'Online\' AND Id in (SELECT EntityId FROM TopicAssignment WHERE TopicId = \'' + topicId + '\')'
                                    + ' AND RecordType.Name = ' + '\'' + recordTypeName + '\' ';

            if (articlesType == 'Actual') {
                knowledgeQuery = knowledgeQuery + ' AND CurrentlyValid__c = true';
            }
            if (articlesType == 'Historical') {
                knowledgeQuery = knowledgeQuery + ' AND CurrentlyValid__c = false';
            }
            
            System.debug('KnowledgeArticlesListController::knowledgeQuery::' + knowledgeQuery);
            knowledgeArticlesList = Database.query(knowledgeQuery);
        }
        return knowledgeArticlesList;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getKnowledgeLabels() {
        Map<String, String> labelsMap = new Map<String, String>();

        String type='Knowledge__kav';

        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType leadSchema = schemaMap.get(type);
        Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();

        for (String fieldName: fieldMap.keySet()) {
            labelsMap.put(fieldName, fieldMap.get(fieldName).getDescribe().getLabel());
        }

        return labelsMap;
    }    
}