cmss/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/Commission__c/fields/BillingDate__c.field-meta.xml
<CustomField>
    <fullName>BillingDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BillingDate</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/CPUSuffix__c.field-meta.xml
<CustomField>
    <fullName>CPUSuffix__c</fullName>
    <label>CPUSuffix</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/EntitlementAmount__c.field-meta.xml
<CustomField>
    <fullName>EntitlementAmount__c</fullName>
    <label>EntitlementAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/OwnerCommissionAcountBase__c.field-meta.xml
<CustomField>
    <fullName>OwnerCommissionAcountBase__c</fullName>
    <label>OwnerCommissionAcountBase</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/PendingAmount__c.field-meta.xml
<CustomField>
    <fullName>PendingAmount__c</fullName>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/RecordNumber__c.field-meta.xml
<CustomField>
    <fullName>RecordNumber__c</fullName>
    <label>RecordNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/CommissionReports__mdt/CommissionReports__mdt.object-meta.xml
<CustomObject>
    <description>List of reports to be allowed for pdf export via custom LWC component</description>
    <label>CommissionReports</label>
    <pluralLabel>CommissionReports</pluralLabel>
</CustomObject>

cmss/main/default/objects/CommissionReports__mdt/fields/Columns__c.field-meta.xml
<CustomField>
    <fullName>Columns__c</fullName>
    <description>comma separated list of API names of columns to be displayed on PDF for each report</description>
    <label>Columns</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

cmss/main/default/objects/CommissionReports__mdt/fields/ReportName__c.field-meta.xml
<CustomField>
    <fullName>ReportName__c</fullName>
    <label>ReportName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/ContactInformation__c.object-meta.xml
<CustomObject>
    <description>An object to store contact information about clients/prospects/leads/agents/assets</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ContactInformation__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Oblast</description>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>100016</fullName>
            </value>
            <value>
                <fullName>100017</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
            <value>
                <fullName>200026</fullName>
            </value>
            <value>
                <fullName>200027</fullName>
            </value>
            <value>
                <fullName>200030</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200051</fullName>
            </value>
            <value>
                <fullName>1000003</fullName>
                <label>sídlo živnostníka</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typ kontaktní informace (domáci telefon, hlavni telefon, mobil, další telefon, hlavni email, další email, trvalá adresa, kontaktní adresa, přechodní adresa, sídlo, …..) - potřeba ješte dořešit číselník a updatnout hodnoty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>200054</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>20007</fullName>
            </value>
            <value>
                <fullName>20008</fullName>
            </value>
            <value>
                <fullName>200081</fullName>
            </value>
            <value>
                <fullName>200082</fullName>
            </value>
            <value>
                <fullName>200088</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference na uživatele, kterému patří kontaktní informace</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ContactInformation</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Shows values from fields Phone, Address, Email or Data Box Number based on the picklist value in field Type__c.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CombinedName__c.field-meta.xml
<CustomField>
    <fullName>CombinedName__c</fullName>
    <formula>IF(ISBLANK(Title), &quot;&quot;, 	Title &amp; &quot; &quot; ) &amp; FirstName &amp; &quot; &quot; &amp; LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Combined Name</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <label>Commission Account Number Base</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/classes/CommissionRunReportController.cls
public with sharing class CommissionRunReportController {
	@AuraEnabled
	public static User getUserInfo() {
		User usr = [
			SELECT Id, Name, CombinedName__c, CommissionAccountNr__c, CommissionAccountBase__c, Profile.Name
			FROM User
			WHERE Id = :UserInfo.getUserId()
		][0];
		return usr;
	}

	@AuraEnabled
	public static ContactInformation__c getContactInfo(Id userId) {
		try {
			ContactInformation__c conInfo = [
				SELECT Id, Value__c
				FROM ContactInformation__c
				WHERE User__c = :userId AND Type__c = '1' AND Subtype__c = '1000003' AND Area__c = '0'
				ORDER BY LastModifiedDate DESC
			][0];
			return conInfo;
		} catch (Exception e) {
			Logger.error('Error in CommissionRunReportController.getContactInfo', e);
			throw new AuraHandledException(e.getMessage());
		} finally {
			Logger.saveLogs();
		}
	}

	@AuraEnabled
	public static Map<String, ReportWrap> getReportsMap() {
		Map<String, CommissionReports__mdt> result = CommissionReports__mdt.getAll();
		Set<String> restultSet = result.keySet();
		Map<String, ReportWrap> reportMap = new Map<String, ReportWrap>();
		for (Report report : [
			SELECT Id, Name, FolderName, DeveloperName, Description
			FROM Report
			WHERE DeveloperName IN :restultSet
			ORDER BY Name
		]) {
			if (!reportMap.containsKey(report.DeveloperName)) {
				reportMap.put(
					report.DeveloperName,
					new ReportWrap(report.DeveloperName, report.Name, report.Id, report.Description)
				);
			}
		}

		if (reportMap.isEmpty()) {
			for (String report : restultSet) {
				if (!reportMap.containsKey(report)) {
					reportMap.put(report, new ReportWrap(report, result.get(report).ReportName__c, '', ''));
				}
			}
		}

		List<String> resultList = new List<String>(restultSet);
		resultList.sort();
		Map<String, ReportWrap> resultSorted = new Map<String, ReportWrap>();
		for (String reportDevName : resultList) {
			resultSorted.put(reportDevName, reportMap.get(reportDevName));
		}
		return resultSorted;
	}

	public class ReportWrap {
		@AuraEnabled
		public String reportDeveloperName;
		@AuraEnabled
		public String reportName;
		@AuraEnabled
		public String reportId;
		@AuraEnabled
		public String reportDescription;

		public ReportWrap(String rDevName, String rLabel, String rId, String rDesc) {
			this.reportDeveloperName = rDevName;
			this.reportName = rLabel;
			this.reportId = rId;
			this.reportDescription = rDesc;
		}
	}

	@AuraEnabled
	public static List<Reports.ReportFilter> getReportFilters(Id reportId) {
		Reports.ReportDescribeResult repDesc = Reports.ReportManager.describeReport(reportId);
		Reports.ReportMetadata repMd = repDesc.getReportMetadata();
		List<Reports.ReportFilter> repFilters = repMd.getReportFilters();
		Reports.StandardDateFilter standardDateFilters = repMd.getStandardDateFilter();
		List<Reports.StandardFilter> standardFilters = repMd.getStandardFilters();

		for (Reports.ReportFilter repFilter : repFilters) {
			System.debug('Filter column: ' + repFilter);
		}
		System.debug('standardDateFilters: ' + standardDateFilters);

		for (Reports.StandardFilter standardFilter : standardFilters) {
			System.debug('standardFilter: ' + standardFilter);
		}

		return repFilters;
	}

	@AuraEnabled
	public static Id runReport(
		Id reportId,
		String fromYear,
		String fromMonth,
		String toYear,
		String toMonth,
		String fromRecord,
		String toRecord,
		String cpu,
		String tribeCpu
	) {
		Reports.ReportDescribeResult repDesc = Reports.ReportManager.describeReport(reportId);
		Reports.ReportMetadata repMd = repDesc.getReportMetadata();
		Reports.StandardDateFilter standardDateFilter = new Reports.StandardDateFilter();
		standardDateFilter.setColumn('Commission__c.BillingDate__c');
		standardDateFilter.setDurationValue('CUSTOM');
		if (!String.isBlank(fromYear) && !String.isBlank(fromMonth)) {
			standardDateFilter.setStartDate(fromYear + '-' + fromMonth + '-' + '01');
		} else {
			standardDateFilter.setStartDate('null');
		}

		if (!String.isBlank(toYear) && !String.isBlank(toMonth)) {
			standardDateFilter.setEndDate(
				toYear +
				'-' +
				toMonth +
				'-' +
				Date.daysInMonth(Integer.valueOf(toYear), Integer.valueOf(toMonth))
			);
		} else {
			standardDateFilter.setEndDate(
				fromYear +
				'-' +
				fromMonth +
				'-' +
				Date.daysInMonth(Integer.valueOf(fromYear), Integer.valueOf(fromMonth))
			);
		}

		//set custom filters
		List<Reports.ReportFilter> repFilters = repMd.getReportFilters();
		if (!String.isBlank(fromRecord)) {
			Reports.ReportFilter fromRecordFilter = new Reports.ReportFilter();
			fromRecordFilter.setColumn('Commission__c.RecordNumber__c');
			fromRecordFilter.setOperator('greaterOrEqual');
			fromRecordFilter.setValue(fromRecord);
			fromRecordFilter.setFilterType('fieldValue');
			repFilters.add(fromRecordFilter);
		}
		if (!String.isBlank(toRecord)) {
			Reports.ReportFilter toRecordFilter = new Reports.ReportFilter();
			toRecordFilter.setColumn('Commission__c.RecordNumber__c');
			toRecordFilter.setOperator('lessOrEqual');
			toRecordFilter.setValue(toRecord);
			toRecordFilter.setFilterType('fieldValue');
			repFilters.add(toRecordFilter);
		}
		if (!String.isBlank(tribeCpu)) {
			Reports.ReportFilter tribeCPUFilter = new Reports.ReportFilter();
			tribeCPUFilter.setColumn('Commission__c.OwnerCommissionAcountBase__c');
			tribeCPUFilter.setOperator('equals');
			tribeCPUFilter.setValue(tribeCpu);
			tribeCPUFilter.setFilterType('fieldValue');
			repFilters.add(tribeCPUFilter);
		}
		if (!String.isBlank(cpu)) {
			Reports.ReportFilter cpuFilter = new Reports.ReportFilter();
			cpuFilter.setColumn('Commission__c.CPUSuffix__c');
			cpuFilter.setOperator('equals');
			cpuFilter.setValue(cpu);
			cpuFilter.setFilterType('fieldValue');
			repFilters.add(cpuFilter);
		}

		repMd.setStandardDateFilter(standardDateFilter);
		repMd.setReportFilters(repFilters);
		Reports.ReportInstance instance = Reports.ReportManager.runAsyncReport(reportId, repMd, true);
		return instance.getId();
	}

	@AuraEnabled
	public static String checkStatus(Id instanceId) {
		Reports.ReportInstance instance = Reports.ReportManager.getReportInstance(instanceId);
		return instance.getStatus();
	}

	public class ReportHeader {
		@AuraEnabled
		public String columnLabel;
		@AuraEnabled
		public String columnDevName;
		@AuraEnabled
		public Integer columnIndex;

		public ReportHeader(String colLabel, String colDevName, Integer colIdx) {
			this.columnLabel = colLabel;
			this.columnDevName = colDevName;
			this.columnIndex = colIdx;
		}
	}

	public class ReportTable {
		@AuraEnabled
		public Map<String, ReportHeader> reportHeader;
		@AuraEnabled
		public List<List<String>> reportData;
		@AuraEnabled
		public String entitlementAmount;
		@AuraEnabled
		public String pendingAmount;
		@AuraEnabled
		public String rowCount;
		public ReportTable(
			Map<String, ReportHeader> header,
			List<List<String>> data,
			String entitlementAmount,
			String pendingAmount,
			String rowCount
		) {
			this.reportHeader = header;
			this.reportData = data;
			this.entitlementAmount = entitlementAmount;
			this.pendingAmount = pendingAmount;
			this.rowCount = rowCount;
		}
	}

	@AuraEnabled
	//public static List<List<String>> getReportData(Id instanceId) {
	public static ReportTable getReportData(Id instanceId, String reportDevName) {
		//prepare header columns from metadata
		//getInstance method cannot be used because it truncates columns to 255 chars
		List<String> reportMdtColumns = [
				SELECT Columns__c
				FROM CommissionReports__mdt
				WHERE DeveloperName = :reportDevName
				LIMIT 1
			][0]
			.Columns__c.split(',');
		Map<String, String> reportMdtColumnsMap = new Map<String, String>();
		for (String rep : reportMdtColumns) {
			String localRep = rep.deleteWhitespace();
			if (!reportMdtColumnsMap.containsKey(localRep)) {
				reportMdtColumnsMap.put(localRep, localRep);
			}
		}

		Reports.ReportResults results = Reports.ReportManager.getReportInstance(instanceId).getReportResults();
		if (results == null) {
			return null;
		}

		//get report header
		Reports.ReportExtendedMetadata repExtendedMetadata = results.getReportExtendedMetadata();
		Map<String, Reports.DetailColumn> repDetailColumnInfo = repExtendedMetadata.getDetailColumnInfo();
		Map<String, ReportHeader> header = new Map<String, ReportHeader>();
		for (String key : reportMdtColumnsMap.keySet()) {
			Integer i = 0; //position of column in repDetailColumnInfo is needed
			for (String keyColumn : repDetailColumnInfo.keySet()) {
				if (key == keyColumn) {
					header.put(
						repDetailColumnInfo.get(key).getName(),
						new ReportHeader(
							repDetailColumnInfo.get(key).getLabel(),
							repDetailColumnInfo.get(key).getName(),
							i
						)
					);
				}
				i++;
			}
		}

		// get report rows.
		Reports.ReportFactWithDetails factDetails = (Reports.ReportFactWithDetails) results.getFactMap().get('T!T');
		List<String> result = new List<String>();
		List<List<String>> resultTable = new List<List<String>>();
		for (Reports.ReportDetailRow detailRow : factDetails.getRows()) {
			List<String> row = new List<String>();
			for (String key : header.keySet()) {
				row.add('' + detailRow.getDataCells()[header.get(key).columnIndex].getLabel());
			}
			resultTable.add(row);
			System.debug('Row: ' + row);
		}

		//get aggregates metadata and data
		Reports.ReportMetadata repMetadata = results.getReportMetadata();
		List<String> repAggregates = repMetadata.getAggregates();
		List<Reports.SummaryValue> repAggregatesData = factDetails.getAggregates();
		String entitlementAmount;
		String pendingAmount;
		String rowCount;
		Integer j = 0;
		for (String aggregate : repAggregates) {
			switch on aggregate {
				when 's!Commission__c.PendingAmount__c' {
					PendingAmount = repAggregatesData[j].getLabel();
				}
				when 's!Commission__c.EntitlementAmount__c' {
					EntitlementAmount = repAggregatesData[j].getLabel();
				}
				when 'RowCount' {
					RowCount = repAggregatesData[j].getLabel();
				}
			}
			j++;
		}

		return new ReportTable(header, resultTable, entitlementAmount, pendingAmount, rowCount);
	}
}