cmss/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/Commission__c/fields/BillingDate__c.field-meta.xml
<CustomField>
    <fullName>BillingDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BillingDate</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/CPUSuffix__c.field-meta.xml
<CustomField>
    <fullName>CPUSuffix__c</fullName>
    <label>CPUSuffix</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/EntitlementAmount__c.field-meta.xml
<CustomField>
    <fullName>EntitlementAmount__c</fullName>
    <label>EntitlementAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/OwnerCommissionAcountBase__c.field-meta.xml
<CustomField>
    <fullName>OwnerCommissionAcountBase__c</fullName>
    <label>OwnerCommissionAcountBase</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/PendingAmount__c.field-meta.xml
<CustomField>
    <fullName>PendingAmount__c</fullName>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/Commission__c/fields/RecordNumber__c.field-meta.xml
<CustomField>
    <fullName>RecordNumber__c</fullName>
    <label>RecordNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/ContactInformation__c.object-meta.xml
<CustomObject>
    <description>An object to store contact information about clients/prospects/leads/agents/assets</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ContactInformation__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Oblast</description>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>100016</fullName>
            </value>
            <value>
                <fullName>100017</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
            <value>
                <fullName>200026</fullName>
            </value>
            <value>
                <fullName>200027</fullName>
            </value>
            <value>
                <fullName>200030</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200051</fullName>
            </value>
            <value>
                <fullName>1000003</fullName>
                <label>sídlo živnostníka</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typ kontaktní informace (domáci telefon, hlavni telefon, mobil, další telefon, hlavni email, další email, trvalá adresa, kontaktní adresa, přechodní adresa, sídlo, …..) - potřeba ješte dořešit číselník a updatnout hodnoty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>200054</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>20007</fullName>
            </value>
            <value>
                <fullName>20008</fullName>
            </value>
            <value>
                <fullName>200081</fullName>
            </value>
            <value>
                <fullName>200082</fullName>
            </value>
            <value>
                <fullName>200088</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference na uživatele, kterému patří kontaktní informace</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ContactInformation</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Shows values from fields Phone, Address, Email or Data Box Number based on the picklist value in field Type__c.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <label>Commission Account Number Base</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/classes/CommissionRunReportControllerTest.cls
@IsTest
public without sharing class CommissionRunReportControllerTest {
	@IsTest
	private static void createTestData() {
		User user = TestDataFactory.getUser(new User(CommissionAccountBase__c = '001'));
		insert user;
		ContactInformation__c conInfo = new ContactInformation__c(
			User__c = user.Id,
			Type__c = '1',
			Value__c = 'ABC',
			Subtype__c = '1000003',
			Area__c = '0'
		);
		insert conInfo;
		List<Commission__c> comms = new List<Commission__c>();
		Commission__c comm1 = new Commission__c(
			BillingDate__c = Date.today(),
			RecordNumber__c = 1,
			CPUSuffix__c = 2,
			EntitlementAmount__c = 12000,
			PendingAmount__c = 5000,
			OwnerCommissionAcountBase__c = 1234
		);
		comms.add(comm1);
		Commission__c comm2 = new Commission__c(
			BillingDate__c = Date.today(),
			RecordNumber__c = 2,
			CPUSuffix__c = 2,
			EntitlementAmount__c = 12000,
			PendingAmount__c = 5000,
			OwnerCommissionAcountBase__c = 1234
		);
		comms.add(comm2);
		insert comms;
	}

	@IsTest
	static void getUserInfoTest() {
		System.assertEquals(UserInfo.getUserId(), CommissionRunReportController.getUserInfo().Id);
	}

	@IsTest
	static void getUserInfoTribeCpuTest() {
		createTestData();
		User usr = [SELECT Id, CommissionAccountBase__c FROM User WHERE CommissionAccountBase__c = '001' LIMIT 1][0];
		System.assertEquals(usr.Id, CommissionRunReportController.getUserInfo(usr.CommissionAccountBase__c).Id);
	}

	@IsTest
	static void checkPermissionSetsTest() {
		createTestData();
		System.assert(CommissionRunReportController.checkPermissionSets() > -1);
	}

	@IsTest
	static void getContactInfoTest() {
		createTestData();
		ContactInformation__c conInfo = [SELECT Id FROM ContactInformation__c WHERE Subtype__c = '1000003'][0];
		User user = [SELECT Id FROM User WHERE CommissionAccountBase__c = '001'][0];
		System.assertEquals(conInfo.Id, CommissionRunReportController.getContactInfo(user.Id).Id);
	}

	@IsTest
	static void getKnowledgeCommissionArticleURLTest() {
		System.assert(CommissionRunReportController.getKnowledgeCommissionArticleURL().length() > 0);
	}

	@IsTest
	static void getReportsMapTest() {
		System.assert(CommissionRunReportController.getReportsMap().size() > 0);
	}

	@isTest(SeeAllData='true')
	static void getReportFiltersTest() {
		Report r = [SELECT Id FROM Report LIMIT 1][0];
		System.assert(
			CommissionRunReportController.getReportFilters(r.Id) != null ||
			CommissionRunReportController.getReportFilters(r.Id) == null
		);
	}

	@isTest(SeeAllData='true')
	static void runTabularReportTest() {
		Report r = [SELECT Id, DeveloperName FROM Report WHERE DeveloperName = 'CommissionReport1020' LIMIT 1];
		createTestData();
		Test.startTest();
		Id rInstanceId = CommissionRunReportController.runReport(
			r.Id,
			String.valueOf(System.Today().year()),
			String.valueOf(System.Today().month()),
			String.valueOf(System.Today().year()),
			String.valueOf(System.Today().month()),
			'1',
			'5',
			'2',
			'1234'
		);
		Test.stopTest();
		System.assertEquals(CommissionRunReportController.checkStatus(rInstanceId), 'Success');
		CommissionRunReportController.ReportTable rData = CommissionRunReportController.getReportData(
			rInstanceId,
			'CommissionReport1020'
		);
		System.assert(rData.reportHeader.size() > 0);
	}

	@isTest(SeeAllData='true')
	static void runSummaryReportTest() {
		Report r = [SELECT Id, DeveloperName FROM Report WHERE DeveloperName = 'CommissionReportExpFlatRate' LIMIT 1];
		createTestData();
		Test.startTest();
		Id rInstanceId = CommissionRunReportController.runReport(
			r.Id,
			String.valueOf(System.Today().year()),
			String.valueOf(System.Today().month()),
			String.valueOf(System.Today().year()),
			String.valueOf(System.Today().month()),
			'1',
			'5',
			'2',
			'1234'
		);
		Test.stopTest();
		System.assertEquals(CommissionRunReportController.checkStatus(rInstanceId), 'Success');
		CommissionRunReportController.ReportTable rData = CommissionRunReportController.getReportData(
			rInstanceId,
			'CommissionReportExpFlatRate'
		);
		System.assert(rData.reportHeader.size() > 0);
	}
}