cmss/main/default/objects/Case/fields/AccountComplainerNameEquals__c.field-meta.xml
<CustomField>
    <fullName>AccountComplainerNameEquals__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Account.FirstName + Account.LastName == ComplainerFirstName + ComplainerLastName</description>
    <label>Account Complainer Name Equals</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Case/fields/AccountContractorNameEquals__c.field-meta.xml
<CustomField>
    <fullName>AccountContractorNameEquals__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Account.CombinedName__c == Contractor.CombinedName__c</description>
    <label>Account Contractor Name Equals</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Case/fields/ComplainerContractor__c.field-meta.xml
<CustomField>
    <fullName>ComplainerContractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Jméno podávajícího smluvního partnera</description>
    <label>Complainer Contractor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CasesUser</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Case/fields/ComplainerFirstName__c.field-meta.xml
<CustomField>
    <fullName>ComplainerFirstName__c</fullName>
    <description>Křestní jméno podávajícího</description>
    <inlineHelpText>If account is selected, attribute is filled automatically after save</inlineHelpText>
    <label>Complainer First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Case/fields/ComplainerLastName__c.field-meta.xml
<CustomField>
    <fullName>ComplainerLastName__c</fullName>
    <description>Příjmení podávajícího</description>
    <inlineHelpText>If account is selected, attribute is filled automatically after save</inlineHelpText>
    <label>Complainer Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Case/fields/ContractorNameEquals__c.field-meta.xml
<CustomField>
    <fullName>ContractorNameEquals__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updates in Case Trigger. 
If ComplainerContractor&apos;s Name is Equal to ComplainerFirstName + ComplainerLastName then true.</description>
    <label>Contractor Name Equals</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/classes/ContractorNameEqualsFieldRecalcBatch.cls
public class ContractorNameEqualsFieldRecalcBatch implements Database.Batchable<sObject> {
	public Database.QueryLocator start(Database.BatchableContext jobId) {
		return Database.getQueryLocator(
			[
				SELECT
					Id,
					ComplainerLastName__c,
					ComplainerFirstName__c,
					ComplainerContractor__c,
					ComplainerContractor__r.FirstName,
					ComplainerContractor__r.LastName,
					Account.FirstName,
					Account.LastName,
					AccountId,
					AccountComplainerNameEquals__c,
					AccountContractorNameEquals__c,
					ContractorNameEquals__c
				FROM Case
				WHERE IsClosed != TRUE
			]
		);
	}
	public void execute(Database.BatchableContext jobId, List<Case> caseList) {
		List<Case> toUpdateCaseList = new List<Case>();

		for (Case c : caseList) {
			setAccountContractorNameEquals(c);
			setAccountComplainerNameEquals(c);
			setContractorNameEquals(c);

			toUpdateCaseList.add(c);
		}
		try {
			update toUpdateCaseList;
		} catch (Exception e) {
			Logger.error('An unhandled exception thrown', e);
			throw e;
		} finally {
			Logger.saveLogs();
		}
	}

	public void finish(Database.BatchableContext jobId) {
	}

	private void setContractorNameEquals(Case c) {
		if (c.ComplainerContractor__c != null) {
			if (
				c.ComplainerFirstName__c == c.ComplainerContractor__r.FirstName &&
				c.ComplainerLastName__c == c.ComplainerContractor__r.LastName
			) {
				c.ContractorNameEquals__c = true;
			} else {
				c.ContractorNameEquals__c = false;
			}
		} else {
			c.ContractorNameEquals__c = false;
		}
	}

	private void setAccountContractorNameEquals(Case c) {
		if (c.Account != null && c.ComplainerContractor__c != null) {
			if (
				c.Account.FirstName == c.ComplainerContractor__r.FirstName &&
				c.Account.LastName == c.ComplainerContractor__r.LastName
			) {
				c.AccountContractorNameEquals__c = true;
			} else {
				c.AccountContractorNameEquals__c = false;
			}
		} else {
			c.AccountContractorNameEquals__c = false;
		}
	}
	private void setAccountComplainerNameEquals(Case c) {
		if (c.Account != null) {
			if (c.ComplainerFirstName__c == c.Account.FirstName && c.ComplainerLastName__c == c.Account.LastName) {
				c.AccountComplainerNameEquals__c = true;
			} else {
				c.AccountComplainerNameEquals__c = false;
			}
		} else {
			c.AccountComplainerNameEquals__c = false;
		}
	}
}