cmss/main/default/objects/Case/fields/CaseID__c.field-meta.xml
<CustomField>
    <fullName>CaseID__c</fullName>
    <externalId>true</externalId>
    <label>Case ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Case/recordTypes/GDPR.recordType-meta.xml
<RecordType>
    <fullName>GDPR</fullName>
    <active>true</active>
    <businessProcess>Client Claim</businessProcess>
    <description>GDPR claim</description>
    <label>GDPR</label>
</RecordType>

cmss/main/default/objects/Case/recordTypes/NewClientClaim.recordType-meta.xml
<RecordType>
    <fullName>NewClientClaim</fullName>
    <active>true</active>
    <businessProcess>Client Claim</businessProcess>
    <label>New Client Claim</label>
</RecordType>

cmss/main/default/objects/NumericalSeriesSettings__c/NumericalSeriesSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores numerical series</description>
    <label>Numerical Series Settings</label>
</CustomObject>

cmss/main/default/objects/NumericalSeriesSettings__c/fields/ClientClaimID__c.field-meta.xml
<CustomField>
    <fullName>ClientClaimID__c</fullName>
    <label>Client Claim ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/NumericalSeriesSettings__c/fields/GDPRClaimID__c.field-meta.xml
<CustomField>
    <fullName>GDPRClaimID__c</fullName>
    <label>GDPR Claim ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/case-management/classes/CaseServiceTest.cls
@IsTest
private class CaseServiceTest {
	@IsTest
	static void assignCaseIDTest() {
		Case newClientCase = TestDataFactory.getCase(
			new Case(
				RecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByDeveloperName()
					.get('NewClientClaim')
					.getRecordTypeId()
			)
		);
		Case newGDPRCase = TestDataFactory.getCase(
			new Case(
				RecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByDeveloperName().get('GDPR').getRecordTypeId()
			)
		);
		NumericalSeriesSettings__c customSettingsValue = new NumericalSeriesSettings__c();
		customSettingsValue.ClientClaimID__c = 2.0;
		customSettingsValue.GDPRClaimID__c = 5.0;
		insert customSettingsValue;

		Test.startTest();
		insert new List<Case>{ newClientCase, newGDPRCase };
		Test.stopTest();

		NumericalSeriesSettings__c newIssuedClaimID = [
			SELECT ClientClaimID__c, GDPRClaimID__c
			FROM NumericalSeriesSettings__c
			LIMIT 1
		];

		newClientCase = [SELECT CaseID__c FROM Case WHERE Id = :newClientCase.Id LIMIT 1];
		newGDPRCase = [SELECT CaseID__c FROM Case WHERE Id = :newGDPRCase.Id LIMIT 1];

		System.assertEquals(3, newIssuedClaimID.ClientClaimID__c);
		System.assertEquals(6, newIssuedClaimID.GDPRClaimID__c);
		System.assertEquals('' + Date.today().year() + '3', newClientCase.CaseID__c);
		System.assertEquals('6' + '' + Date.today().year(), newGDPRCase.CaseID__c);
	}
}