cmss/main/default/objects/Case/fields/CaseID__c.field-meta.xml
<CustomField>
    <fullName>CaseID__c</fullName>
    <externalId>true</externalId>
    <label>Case ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Case/recordTypes/ClientClaimConfirmationSent.recordType-meta.xml
<RecordType>
    <fullName>ClientClaimConfirmationSent</fullName>
    <active>true</active>
    <businessProcess>Client Claim</businessProcess>
    <label>Client Claim Confirmation Sent</label>
</RecordType>

cmss/main/default/objects/Case/recordTypes/ClosedClientClaim.recordType-meta.xml
<RecordType>
    <fullName>ClosedClientClaim</fullName>
    <active>true</active>
    <businessProcess>Client Claim</businessProcess>
    <description>The client claim record type with a non editable layout for closed cases</description>
    <label>Closed Client Claim</label>
</RecordType>

cmss/main/default/objects/Case/recordTypes/ClosedGDPRClaim.recordType-meta.xml
<RecordType>
    <fullName>ClosedGDPRClaim</fullName>
    <active>true</active>
    <businessProcess>Client Claim</businessProcess>
    <description>Record type with read-only fields for closed GDPR claims</description>
    <label>Closed GDPR Claim</label>
</RecordType>

cmss/main/default/objects/Case/recordTypes/GDPR.recordType-meta.xml
<RecordType>
    <fullName>GDPR</fullName>
    <active>true</active>
    <businessProcess>Client Claim</businessProcess>
    <description>GDPR claim</description>
    <label>GDPR</label>
</RecordType>

cmss/main/default/objects/Case/recordTypes/NewClientClaim.recordType-meta.xml
<RecordType>
    <fullName>NewClientClaim</fullName>
    <active>true</active>
    <businessProcess>Client Claim</businessProcess>
    <label>New Client Claim</label>
</RecordType>

cmss/main/default/objects/NumericalSeriesSettings__c/NumericalSeriesSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores numerical series</description>
    <label>Numerical Series Settings</label>
</CustomObject>

cmss/main/default/objects/NumericalSeriesSettings__c/fields/ClientClaimID__c.field-meta.xml
<CustomField>
    <fullName>ClientClaimID__c</fullName>
    <label>Client Claim ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/NumericalSeriesSettings__c/fields/GDPRClaimID__c.field-meta.xml
<CustomField>
    <fullName>GDPRClaimID__c</fullName>
    <label>GDPR Claim ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/case-management/classes/CaseService.cls
public with sharing class CaseService {
	public static void assignCaseID(List<Case> newCaseList) {
		Set<Id> ClientClaimRecordTypes = new Set<Id>{
			SObjectType.Case.getRecordTypeInfosByDeveloperName().get('NewClientClaim').getRecordTypeId(),
			SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ClientClaimConfirmationSent').getRecordTypeId(),
			SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ClosedClientClaim').getRecordTypeId()
		};
		Set<Id> GDPRRecordTypes = new Set<Id>{
			SObjectType.Case.getRecordTypeInfosByDeveloperName().get('GDPR').getRecordTypeId(),
			SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ClosedGDPRClaim').getRecordTypeId()
		};

		NumericalSeriesSettings__c lastIssuedCaseID = NumericalSeriesSettings__c.getOrgDefaults();

		if (lastIssuedCaseID.GDPRClaimID__c == null) {
			lastIssuedCaseID.GDPRClaimID__c = 0;
		} else if (lastIssuedCaseID.ClientClaimID__c == null) {
			lastIssuedCaseID.ClientClaimID__c = 0;
		}
		for (Case caseItem : newCaseList) {
			if (GDPRRecordTypes.contains(caseItem.RecordTypeId)) {
				lastIssuedCaseID.GDPRClaimID__c += 1;
				caseItem.CaseID__c = '' + Integer.valueOf(lastIssuedCaseID.GDPRClaimID__c) + Date.today().year();
			} else if (ClientClaimRecordTypes.contains(caseItem.RecordTypeId)) {
				lastIssuedCaseID.ClientClaimID__c += 1;
				caseItem.CaseID__c = '' + Date.today().year() + Integer.valueOf(lastIssuedCaseID.ClientClaimID__c);
			}
		}
		upsert lastIssuedCaseID;
	}
}