cmss/main/default/objects/Case/fields/NewPortfolioManager__c.field-meta.xml
<CustomField>
    <fullName>NewPortfolioManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nový (požadovaný) správce</description>
    <label>New Portfolio Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NewPortfolioManagerCases</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Case/fields/RegionalManager__c.field-meta.xml
<CustomField>
    <fullName>RegionalManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Regionální manager (a zároveň schvalovatel, není-li zadavatelem centrála)</description>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RegionalManagerCases</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Case/fields/RegionalManagerAssistant__c.field-meta.xml
<CustomField>
    <fullName>RegionalManagerAssistant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asistentnka regionálního managera (a zároveň 2. schvalovatel, není-li zadavatelem centrála)</description>
    <label>Regional Manager Assistant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RegionalManagerAssistantCases</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Case/recordTypes/PortfolioManagementChangeRequest.recordType-meta.xml
<RecordType>
    <fullName>PortfolioManagementChangeRequest</fullName>
    <active>true</active>
    <businessProcess>Portfolio Management Change Request</businessProcess>
    <label>Portfolio Management Change Request</label>
</RecordType>

cmss/portfolio-management/classes/ApprovalRecallServiceTest.cls
@IsTest
private class ApprovalRecallServiceTest {
	@TestSetup
	static void makeData() {
		insert TestDataFactory.getNumericalSettings();
	}

	@IsTest
	static void recallApprovalsTest() {
		Test.setMock(HttpCalloutMock.class, new MailSOAPServiceHttpMock());
		insert TestDataFactory.getIntegrationSettings();
		Id userId = UserInfo.getUserId();
		Case testCase = TestDataFactory.getCase(
			new Case(
				OwnerId = userId,
				RecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByDeveloperName()
					.get('PortfolioManagementChangeRequest')
					.getRecordTypeId(),
				NewPortfolioManager__c = userId,
				RegionalManager__c = userId,
				RegionalManagerAssistant__c = userId
			)
		);
		insert testCase;

		Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
		request.setObjectId(testCase.id);
		request.setProcessDefinitionNameOrId('Case_Approval');
		request.setSkipEntryCriteria(true);
		Approval.ProcessResult result = Approval.process(request);

		Test.startTest();
		System.assertEquals('Pending', result.getInstanceStatus());
		ApprovalRecallService.recallApprovals(new List<List<String>>{ new List<String>{ testCase.Id } });
		ProcessInstance processInstance = [
			SELECT Id, Status, TargetObject.type, TargetObject.Id, CompletedDate
			FROM ProcessInstance
			WHERE TargetObject.Id = :testCase.Id
		][0];
		System.assertEquals('Removed', processInstance.Status);
		Test.stopTest();
	}
}