cmss/main/default/objects/AccessShare__c/AccessShare__c.object-meta.xml
<CustomObject>
    <label>Access Share</label>
    <nameField>
        <displayFormat>AS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Search Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Share</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/AccessShare__c/fields/AccessTo__c.field-meta.xml
<CustomField>
    <fullName>AccessTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Share</relationshipLabel>
    <relationshipName>Search_Accesses</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason</label>
    <type>TextArea</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Search_Accesses</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Tandem</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>KA Delegation</fullName>
            </value>
            <value>
                <fullName>SEZ Delegation</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/customer-search/classes/AccessShareDao.cls
public class AccessShareDao {

    public static List<AccessShare__c> getAllRecordsFromAccessShare() {
        return [SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c,
        IsDeleted, LastModifiedById, LastModifiedDate, Name, Reason__c, RequestedBy__c, StartDate__c, SystemModstamp, Type__c
        FROM AccessShare__c];
    }

    public static List<AccessShare__c> getAllNonExpiredRecordsFromAccessShare() {
        return [SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c, IsDeleted, LastModifiedById, LastModifiedDate,
        Name, Reason__c, RequestedBy__c, StartDate__c, SystemModstamp, Type__c
        FROM AccessShare__c
        WHERE ExpirationDate__c > :datetime.now().date()];
    }

    public static List<AccessShare__c> getAllNonExpiredRecordsFromAccessShareByRequestedByIdsAndType(Set<Id> requestedByIds, String typeAccSh) {
        return [SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c, IsDeleted, LastModifiedById, LastModifiedDate,
        Name, Reason__c, RequestedBy__c, StartDate__c, SystemModstamp, Type__c
        FROM AccessShare__c
        WHERE ExpirationDate__c >= :date.today()
        AND RequestedBy__c IN : requestedByIds
        AND Type__c =: typeAccSh];
    }

    public static List<AccessShare__c> getAllExpiredRecordsFromAccessShare() {
        return [SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c, IsDeleted, LastModifiedById, LastModifiedDate,
        Name, Reason__c, RequestedBy__c, StartDate__c, SystemModstamp, Type__c
        FROM AccessShare__c
        WHERE ExpirationDate__c <:datetime.now().date() OR ExpirationDate__c =:datetime.now().date()];
    }

    public static List<AccessShare__c> getAccessShareByUserIdAndRecordId(Id userId, Id recordId) {
        return [SELECT RequestedBy__c, AccessTo__c, Type__c
        FROM AccessShare__c
        WHERE AccessTo__c =:recordId AND RequestedBy__c =:userId];
    }

    public static List<AccessShare__c> getAccessShareByUserIdsAndRecordIds(Set<Id> userIds, Set<Id> recordIds) {
        return [SELECT RequestedBy__c, AccessTo__c, ExpirationDate__c, Type__c
        FROM AccessShare__c
        WHERE AccessTo__c IN :recordIds AND RequestedBy__c IN :userIds];
    }

    public static List<AccessShare__c> getAccessShareByUserIdAndRecordIdAndType(Id userId, Id recordId, String type) {
        return [SELECT RequestedBy__c, AccessTo__c, Type__c
        FROM AccessShare__c
        WHERE AccessTo__c =:recordId AND RequestedBy__c =:userId AND Type__c =:type];
    }

    public static List<AccessShare__c> getAccessShareByUserIdsAndRecordIdAndType(Set<Id> userIds,
                                                                                   Id recordId,
                                                                                   String typeAccSh) {
        return [SELECT RequestedBy__c, AccessTo__c, Type__c
        FROM AccessShare__c
        WHERE AccessTo__c =:recordId AND RequestedBy__c IN :userIds AND Type__c =:typeAccSh];
    }

    public static List<AccessShare__c> getAccessShareByRecordIdsAndType(Set<Id> recordIds, String typeAccSh) {
        return [SELECT RequestedBy__c, AccessTo__c, Type__c
        FROM AccessShare__c
        WHERE AccessTo__c IN :recordIds AND Type__c =:typeAccSh];
    }

    public static List<AccessShare__c> getNonExpiredAccessShareByRecordIdsAndType(Set<Id> recordIds, String typeAccSh) {
        return [SELECT RequestedBy__c, AccessTo__c, Type__c
        FROM AccessShare__c
        WHERE AccessTo__c IN :recordIds AND Type__c =:typeAccSh AND ExpirationDate__c >=: Date.today()];
    }

    public static List<AccessShare__c> getNonExpiredAccessShareByRecordIdsAndRequestedByAndType(Set<Id> recordIds, Set<Id> userIds, String typeAccSh) {
        return [SELECT RequestedBy__c, AccessTo__c, Type__c
        FROM AccessShare__c
        WHERE AccessTo__c IN :recordIds AND RequestedBy__c IN : userIds AND Type__c =:typeAccSh AND ExpirationDate__c >=: Date.today() ORDER BY StartDate__c DESC];
    }

    public static List<AccessShare__c> getAccessShareByRecordId(Id recordId) {
        return [SELECT RequestedBy__c, AccessTo__c, Type__c, Reason__c
        FROM AccessShare__c
        WHERE AccessTo__c =:recordId];
    }

    public static List<AccessShare__c> getAccessShareByUserAndAccountIds(Set<Id> userIds, Set<Id> accountIds) {
        return [
            SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c, IsDeleted, LastModifiedById, LastModifiedDate, Name, Reason__c,
                RequestedBy__c, StartDate__c, SystemModstamp, Type__c
            FROM AccessShare__c
            WHERE RequestedBy__c IN: userIds AND AccessTo__c IN: accountIds
        ];
    }

    public static List<AccessShare__c> getAccessShareByAccountIds(Set<Id> accountIds) {
        return [
            SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c, IsDeleted, LastModifiedById, LastModifiedDate, Name, Reason__c,
                RequestedBy__c, StartDate__c, SystemModstamp, Type__c
            FROM AccessShare__c
            WHERE AccessTo__c IN: accountIds
        ];
    }

    public static List<AccessShare__c> getAccessShareByUserIds(Set<Id> userIds) {
        return [SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c, IsDeleted, LastModifiedById, LastModifiedDate, Name, Reason__c, RequestedBy__c, StartDate__c, SystemModstamp, Type__c
        FROM AccessShare__c
        WHERE RequestedBy__c IN :userIds];
    }

    public static List<AccessShare__c> getAccessShareByUserIdsAndAccoutnIds(Set<Id> userIds, Set<Id> accIds) {
        return [SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c, IsDeleted, LastModifiedById, LastModifiedDate, Name, Reason__c, RequestedBy__c, StartDate__c, SystemModstamp, Type__c
        FROM AccessShare__c
        WHERE RequestedBy__c IN :userIds AND AccessTo__c IN :accIds];
    }

    public static List<AccessShare__c> getAccessShareByUserId(Id userId) {
        return [SELECT AccessTo__c, CreatedById, CreatedDate, ExpirationDate__c, IsDeleted, LastModifiedById, LastModifiedDate, Name, Reason__c, RequestedBy__c, StartDate__c, SystemModstamp, Type__c
        FROM AccessShare__c
        WHERE RequestedBy__c = :userId];
    }
    
    public static List<AccessShare__c> getAccessShareByUserIdAndAccoutnIds(Id userIds, Set<Id> accIds) {
        return [SELECT AccessTo__c, ExpirationDate__c, Reason__c, RequestedBy__c, Type__c
        FROM AccessShare__c
        WHERE RequestedBy__c = :userIds AND AccessTo__c IN :accIds];
    }
}