cmss/main/default/objects/AccessShare__c/AccessShare__c.object-meta.xml
<CustomObject>
    <label>Access Share</label>
    <nameField>
        <displayFormat>AS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Search Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Share</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/AccessShare__c/fields/AccessTo__c.field-meta.xml
<CustomField>
    <fullName>AccessTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Share</relationshipLabel>
    <relationshipName>Search_Accesses</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason</label>
    <type>TextArea</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Search_Accesses</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/RoleId__c.field-meta.xml
<CustomField>
    <fullName>RoleId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Role Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Tandem</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>KA Delegation</fullName>
            </value>
            <value>
                <fullName>SEZ Delegation</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/AssetAccountRelation__c.object-meta.xml
<CustomObject>
    <label>Asset Account Relation</label>
    <nameField>
        <label>Asset Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AssetAccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference na klienta/prospekta</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Reference na smlouvu</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/RelationType__c.field-meta.xml
<CustomField>
    <fullName>RelationType__c</fullName>
    <description>Typ role (dlžník/spoludlžník...)
Pro UP:  FK CIS_ROLE_UP::KOD
Pro SS/MU/USS/RZP:  FK CIS_DRUH_DISPOZICIE::KOD</description>
    <label>Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>103</fullName>
            </value>
            <value>
                <fullName>104</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>106</fullName>
            </value>
            <value>
                <fullName>107</fullName>
            </value>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>109</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>201</fullName>
            </value>
            <value>
                <fullName>202</fullName>
            </value>
            <value>
                <fullName>203</fullName>
            </value>
            <value>
                <fullName>204</fullName>
            </value>
            <value>
                <fullName>205</fullName>
            </value>
            <value>
                <fullName>206</fullName>
            </value>
            <value>
                <fullName>207</fullName>
            </value>
            <value>
                <fullName>208</fullName>
            </value>
            <value>
                <fullName>209</fullName>
            </value>
            <value>
                <fullName>210</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/access-share/classes/AccessSharingUtils.cls
public without sharing class AccessSharingUtils {
	public static List<AccessShare__c> getNewAccessShareList(
		Map<User, Map<Datetime, Set<Id>>> userIdAndExpirationDateAndAccountIds,
		String type,
		String reason
	) {
		Set<AccessShare__c> accessShareSet = new Set<AccessShare__c>();
		if (userIdAndExpirationDateAndAccountIds != null && userIdAndExpirationDateAndAccountIds.isEmpty()) {
			return new List<AccessShare__c>(accessShareSet);
		} else {
			for (User user : userIdAndExpirationDateAndAccountIds.keySet()) {
				for (Datetime expirationDate : userIdAndExpirationDateAndAccountIds.get(user).keySet()) {
					for (Id accountId : userIdAndExpirationDateAndAccountIds.get(user).get(expirationDate)) {
						accessShareSet.add(
							new AccessShare__c(
								AccessTo__c = accountId,
								RequestedBy__c = user.Id,
								StartDate__c = datetime.now(),
								Type__c = type,
								Reason__c = reason,
								ExpirationDate__c = expirationDate
							)
						);
					}
				}
			}

			return new List<AccessShare__c>(accessShareSet);
		}
	}

	//in development
	public static List<AccessShare__c> getNewAccessShareList2(Set<AccessShareDTO> accessSharesDtos, String type) {
		Set<AccessShare__c> accessShareSet = new Set<AccessShare__c>();

		if (accessSharesDtos != null && accessSharesDtos.isEmpty()) {
			return new List<AccessShare__c>(accessShareSet);
		} else {
			for (AccessShareDTO accessShareDto : accessSharesDtos) {
				accessShareSet.add(
					new AccessShare__c(
						AccessTo__c = accessShareDto.accountIdToShare,
						RequestedBy__c = accessShareDto.userToShareWith.Id,
						StartDate__c = datetime.now(),
						Type__c = type,
						Reason__c = accessShareDto.reason,
						ExpirationDate__c = accessShareDto.expirationDate,
						RoleId__c = accessShareDto.roleId
					)
				);
			}

			return new List<AccessShare__c>(accessShareSet);
		}
	}

	public static Set<AccessShareDTO> getRelatedAccessShareDTOs(Set<AccessShareDTO> accessShareDtos) {
		Set<Id> accountIds = new Set<Id>();
		for (AccessShareDTO dto : accessShareDtos) {
			accountIds.add(dto.accountIdToShare);
		}

		List<AssetAccountRelation__c> assetAccountRelations = [
			SELECT Id, Asset__c, Asset__r.Id, Asset__r.EndDate__c, Asset__r.AccountId, Account__c
			FROM AssetAccountRelation__c
			WHERE Account__c IN :accountIds AND RelationType__c != '1'
		];

		Map<Id, Set<Id>> accountAssetsMap = new Map<Id, Set<Id>>();
		Map<Id, Id> assetsToParentAccountsMap = new Map<Id, Id>();

		for (AssetAccountRelation__c relation : assetAccountRelations) {
			if (!assetsToParentAccountsMap.containsKey(relation.Asset__c)) {
				assetsToParentAccountsMap.put(relation.Asset__c, relation.Asset__r.AccountId);
			}
			Set<Id> assetIds = new Set<Id>();
			if (accountAssetsMap.containsKey(relation.Account__c)) {
				assetIds = accountAssetsMap.get(relation.Account__c);
			}
			assetIds.add(relation.Asset__c);
			accountAssetsMap.put(relation.Account__c, assetIds);
		}

		Set<AccessShareDTO> newShareDtos = new Set<AccessShareDTO>();
		for (AccessShareDTO assessShareDto : accessShareDtos) {
			Set<Id> assetIdsForActualAccount = accountAssetsMap.get(assessShareDto.accountIdToShare);
			if (assetIdsForActualAccount != null) {
				for (Id assetId : assetIdsForActualAccount) {
					AccessShareDTO newAccessShareDto = new AccessShareDTO();
					newAccessShareDto.accountIdToShare = assetsToParentAccountsMap.get(assetId);
					newAccessShareDto.expirationDate = assessShareDto.expirationDate;
					newAccessShareDto.reason = assessShareDto.reason;
					newAccessShareDto.userToShareWith = assessShareDto.userToShareWith;
					newAccessShareDto.roleId = assessShareDto.roleId;

					newShareDtos.add(newAccessShareDto);
				}
			}
		}
		return newShareDtos;
	}
}