cmss/main/default/objects/AccessShare__c/AccessShare__c.object-meta.xml
<CustomObject>
    <label>Access Share</label>
    <nameField>
        <displayFormat>AS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Search Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Share</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/AccessShare__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Tandem</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>KA Delegation</fullName>
            </value>
            <value>
                <fullName>SEZ Delegation</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/customer-search/classes/AccessShareHandler.cls
// public class AccessShareHandler implements iTrigger{
public class AccessShareHandler {
	public static List<AccessShare__c> ownerTypeAccShares = new List<AccessShare__c>();

	public void afterInsert(List<SObject> soList) {
		// if (DataFactoryTest.shouldRunTrigger()) {
		List<AccessShare__c> ownerTypeAccShares = new List<AccessShare__c>();
		List<AccessShare__c> newAccessShares = (List<AccessShare__c>) soList;
		for (AccessShare__c accSh : newAccessShares) {
			if (accSh.Type__c == 'Owner') {
				ownerTypeAccShares.add(accSh);
			}
		}
		if (!ownerTypeAccShares.isEmpty()) {
			AccessShareService.updateOwnershipOnAccounts(ownerTypeAccShares);
		}
		// }
	}

	public void afterUpdate(List<SObject> oldListSo, List<SObject> newListSo) {
		// if (DataFactoryTest.shouldRunTrigger()) {
		List<AccessShare__c> ownerTypeAccShares = new List<AccessShare__c>();
		List<AccessShare__c> newAccessShares = (List<AccessShare__c>) newListSo;
		for (AccessShare__c accSh : newAccessShares) {
			if (accSh.Type__c == 'Owner') {
				ownerTypeAccShares.add(accSh);
			}
		}
		if (!ownerTypeAccShares.isEmpty()) {
			AccessShareService.updateOwnershipOnAccounts(ownerTypeAccShares);
		}
		// }
	}

	public void afterDelete(List<SObject> soList) {
		// if (DataFactoryTest.shouldRunTrigger()) {
		List<AccessShare__c> ownerTypeAccShares = new List<AccessShare__c>();
		List<AccessShare__c> newAccessShares = (List<AccessShare__c>) soList;
		for (AccessShare__c accSh : newAccessShares) {
			if (accSh.Type__c == 'Owner') {
				ownerTypeAccShares.add(accSh);
			}
		}
		if (!ownerTypeAccShares.isEmpty()) {
			AccessShareService.updateOwnershipOnAccounts(ownerTypeAccShares);
		}
		// }
	}

	// public void andFinally() {
	// 	// if (DataFactoryTest.shouldRunTrigger()) {
	// 	// }
	// }
}