cmss/main/default/objects/GoogleCalendarSyncSettings__c/GoogleCalendarSyncSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Google Calendar Sync Settings</label>
</CustomObject>

cmss/main/default/objects/GoogleCalendarSyncSettings__c/fields/GoogleTechnicalUser__c.field-meta.xml
<CustomField>
    <fullName>GoogleTechnicalUser__c</fullName>
    <label>Google technical user</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/UserCalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Used for synchronisation with Google Calendar</description>
    <label>User Calendar Setting</label>
    <nameField>
        <displayFormat>UCS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>User Calendar Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Calendar Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/UserCalendarSetting__c/fields/ResourceId__c.field-meta.xml
<CustomField>
    <fullName>ResourceId__c</fullName>
    <externalId>true</externalId>
    <label>Resource Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncActive__c.field-meta.xml
<CustomField>
    <fullName>SyncActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Active</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncToken__c.field-meta.xml
<CustomField>
    <fullName>SyncToken__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCalendarSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/UserCalendarID__c.field-meta.xml
<CustomField>
    <fullName>UserCalendarID__c</fullName>
    <externalId>true</externalId>
    <label>User Calendar ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchExpirationDateTime__c.field-meta.xml
<CustomField>
    <fullName>WatchExpirationDateTime__c</fullName>
    <label>Watch Expiration DateTime</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchId__c.field-meta.xml
<CustomField>
    <fullName>WatchId__c</fullName>
    <label>Watch Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/controllers/CalendarSyncStatusController.cls
public without sharing class CalendarSyncStatusController {
	@AuraEnabled(cacheable=true)
	public static String getTechnicalUserMail() {
		return JSON.serialize(GoogleCalendarSyncSettings__c.getOrgDefaults()?.GoogleTechnicalUser__c);
	}

	@AuraEnabled(cacheable=true)
	public static UserCalendarSetting__c getUserCalendarSetting() {
		UserCalendarSetting__c setting;
		try {
			List<UserCalendarSetting__c> settings = [
				SELECT
					Id,
					ResourceId__c,
					SyncActive__c,
					SyncToken__c,
					User__c,
					UserCalendarID__c,
					WatchExpirationDateTime__c,
					WatchId__c
				FROM UserCalendarSetting__c
				WHERE User__c = :UserInfo.getUserId()
				LIMIT 1
			];
			setting = settings.size() > 0 ? settings[0] : null;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return setting;
	}

	@AuraEnabled
	public static Boolean validateCalendarConnection(String googleCalendarId) {
		Boolean isCalendarConnected = false;
		try {
			GoogleCalendarSyncService service = new GoogleCalendarSyncService();
			isCalendarConnected = service.isCalendarConnected(googleCalendarId);
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		} finally {
			Logger.saveLogs();
		}
		return isCalendarConnected;
	}

	@AuraEnabled
	public static void createWatch(Id calendarId) {
		UserCalendarSetting__c calendarSetting = (UserCalendarSetting__c) [
			SELECT Id, WatchId__c, WatchExpirationDateTime__c, ResourceId__c, UserCalendarID__c
			FROM UserCalendarSetting__c
			WHERE Id = :calendarId
		];
		if (calendarSetting == null) {
			return;
		}
		String watchUrl = '';
		if (!Test.isRunningTest()) {
			Site mySite = [SELECT Id FROM Site WHERE Name = 'googleApiWebhooks'];
			SiteDetail mySiteDetail = [SELECT SecureURL FROM SiteDetail WHERE DurableId = :mySite.Id];
			watchUrl = mySiteDetail.SecureURL + '/services/apexrest/api/webhooks/google/';
		}

		GoogleCalendarSyncService syncService = new GoogleCalendarSyncService();

		GoogleCalendarSyncService.WatchResponse watchResponse = syncService.createWatch(
			calendarSetting.UserCalendarId__c,
			((Long) ((Datetime) System.Today().addMonths(1)).getTime()),
			watchUrl
		);
		calendarSetting.WatchId__c = watchResponse.id;
		calendarSetting.ResourceId__c = watchResponse.resourceId;
		calendarSetting.WatchExpirationDateTime__c = DateTime.now().addMonths(1);
		update calendarSetting;
	}
}