cmss/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>choose debug log level, default is 1st value [debug]</description>
    <inlineHelpText>choose debug log level, default is 1st value [debug]</inlineHelpText>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>debug</fullName>
                <default>true</default>
                <label>debug</label>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>warn</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/util/classes/LoggerCleanUpBatchTest.cls
@IsTest
public class LoggerCleanUpBatchTest {
	@IsTest
	private static void deleteLogsTest() {
		Log__c logDebug = new Log__c(Message__c = 'debugTest', Level__c = 'debug');
		Log__c logError = new Log__c(Message__c = 'errorTest', Level__c = 'error');
		Log__c logWarn = new Log__c(Message__c = 'warnTest', Level__c = 'warn');
		Log__c logInfo = new Log__c(Message__c = 'infoTest', Level__c = 'info');
		List<Log__c> logs = new List<Log__c>{ logDebug, logError, logWarn, logInfo };
		insert logs;

		for (Log__c log : logs) {
			Test.setCreatedDate(log.Id, Date.Today() - 31);
		}

		Test.startTest();
		Database.executeBatch(new LoggerCleanUpBatch());
		Test.stopTest();

		logs = [SELECT Id FROM Log__c];
		System.assertEquals(0, logs.size());
	}
}