cmss/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Log__c/fields/ClassMethodName__c.field-meta.xml
<CustomField>
    <fullName>ClassMethodName__c</fullName>
    <label>Class method name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Log__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

cmss/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>choose debug log level, default is 1st value [debug]</description>
    <inlineHelpText>choose debug log level, default is 1st value [debug]</inlineHelpText>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>debug</fullName>
                <default>true</default>
                <label>debug</label>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>warn</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Log__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

cmss/main/default/objects/Log__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Transaction UUID used to related logs into one transaction.</description>
    <externalId>true</externalId>
    <label>TransactionId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/LogEvent__e/fields/ClassMethodName__c.field-meta.xml
<CustomField>
    <fullName>ClassMethodName__c</fullName>
    <label>Class method name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/LogEvent__e/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

cmss/main/default/objects/LogEvent__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>possible values same as on Log__c object [debug, info, warn, error]</description>
    <label>Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/LogEvent__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Transaction UUID</description>
    <label>TransactionId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

cmss/main/util/classes/LogEventTriggerHandler.cls
public class LogEventTriggerHandler {

	public static void afterInsert(List<LogEvent__e> newEvents) {
		List<Log__c> logsToSave = new List<Log__c>();

		for (LogEvent__e logEvent : newEvents) {
			Log__c log = createLog(logEvent);
			logsToSave.add(log);
		}
		insertLogs(logsToSave);
	}

	private static Log__c createLog(LogEvent__e logEvent) {
		Log__c log = new Log__c();
        log.TransactionId__c = logEvent.TransactionId__c;
		log.ClassMethodName__c = logEvent.ClassMethodName__c;
		log.Exception__c = logEvent.Exception__c;
		log.Level__c = logEvent.Level__c;
		log.Payload__c = logEvent.Payload__c;
		log.Message__c = logEvent.Message__c;
		return log;
	}

	private static void insertLogs(List<Log__c> logsToSave) {
		List<Database.SaveResult> results = Database.insert(logsToSave);
		for (Database.SaveResult sr : results) {
			if (!sr.isSuccess()) {
				for (Database.Error err : sr.getErrors()) {
					System.debug('Error while saving log returned: ' +
							err.getStatusCode() +
							' - ' +
							err.getMessage());
				}
			}
		}
	}
}