cmss/main/default/objects/ContactInformation__c/ContactInformation__c.object-meta.xml
<CustomObject>
    <description>An object to store contact information about clients/prospects/leads/agents/assets</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ContactInformation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/DataBoxNumber__c.field-meta.xml
<CustomField>
    <fullName>DataBoxNumber__c</fullName>
    <description>Číslo datové schránky</description>
    <label>Data Box Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>Telefónní číslo</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typ kontaktní informace (domáci telefon, hlavni telefon, mobil, další telefon, hlavni email, další email, trvalá adresa, kontaktní adresa, přechodní adresa, sídlo, …..) - potřeba ješte dořešit číselník a updatnout hodnoty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>200054</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>20007</fullName>
            </value>
            <value>
                <fullName>20008</fullName>
            </value>
            <value>
                <fullName>200081</fullName>
            </value>
            <value>
                <fullName>200082</fullName>
            </value>
            <value>
                <fullName>200088</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Shows values from fields Phone, Address, Email or Data Box Number based on the picklist value in field Type__c.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/customer-360/classes/ContactInformationTriggerHandlerTest.cls
@IsTest
private class ContactInformationTriggerHandlerTest {
	@IsTest
	static void createContactInformationValueTest() {
		ContactInformation__c contactInfo = TestDataFactory.getContactInformation(new ContactInformation__c());
		ContactInformation__c contactInfo2 = TestDataFactory.getContactInformation(
			new ContactInformation__c(Type__c = '2', PhoneNumber__c = '777556541')
		);

		Test.startTest();
		insert new List<ContactInformation__c>{contactInfo, contactInfo2};
		Test.stopTest();

		List<ContactInformation__c> contactInfoValues = [
			SELECT Value__c
			FROM ContactInformation__c
			WHERE Type__c = '1'
		];
		List<ContactInformation__c> contactInfoPhoneValues = [
			SELECT Value__c
			FROM ContactInformation__c
			WHERE Type__c = '2'
		];

		for (ContactInformation__c cItem : contactInfoValues) {
			String cItemValue = cItem.Value__c;
			System.assertEquals('Street 52 City 100 00 CZ', cItemValue);
		}
		for (ContactInformation__c cItemPhone : contactInfoPhoneValues) {
			String cItemPhoneValue = cItemPhone.Value__c;
			System.assertEquals('777556541', cItemPhoneValue);
		}
	}
	@IsTest
	static void createContactInformationNullValueTest() {
		ContactInformation__c contactInfo = TestDataFactory.getContactInformation(new ContactInformation__c());
		ContactInformation__c contactInfo2 = TestDataFactory.getContactInformation(
			new ContactInformation__c(City__c = null)
		);
		ContactInformation__c contactInfo3 = TestDataFactory.getContactInformation(
			new ContactInformation__c(Type__c = '3', Email__c = 'test@test.com', DataBoxNumber__c = null)
		);

		Test.startTest();
		insert new List<ContactInformation__c>{contactInfo, contactInfo2};
		Test.stopTest();

		List<ContactInformation__c> contactInfoValues = [SELECT Value__c FROM ContactInformation__c];

		for (ContactInformation__c cItem : contactInfoValues) {
			String cItemValue = cItem.Value__c;
			System.assert(!cItemValue.contains('null'));
		}
	}
}