cmss/main/default/objects/ContactInformation__c/ContactInformation__c.object-meta.xml
<CustomObject>
    <description>An object to store contact information about clients/prospects/leads/agents/assets</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ContactInformation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CountryPicklist</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/DataBoxNumber__c.field-meta.xml
<CustomField>
    <fullName>DataBoxNumber__c</fullName>
    <description>Číslo datové schránky</description>
    <label>Data Box Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/HouseNumber__c.field-meta.xml
<CustomField>
    <fullName>HouseNumber__c</fullName>
    <description>Č. p. / Č. o.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>House Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>Telefónní číslo</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>PSČ</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Ulice</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typ kontaktní informace (domáci telefon, hlavni telefon, mobil, další telefon, hlavni email, další email, trvalá adresa, kontaktní adresa, přechodní adresa, sídlo, …..) - potřeba ješte dořešit číselník a updatnout hodnoty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>200054</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>20007</fullName>
            </value>
            <value>
                <fullName>20008</fullName>
            </value>
            <value>
                <fullName>200081</fullName>
            </value>
            <value>
                <fullName>200082</fullName>
            </value>
            <value>
                <fullName>200088</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Shows values from fields Phone, Address, Email or Data Box Number based on the picklist value in field Type__c.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/globalValueSets/CountryPicklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Undefined</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>AE</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>AF</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>AG</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>AI</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>AL</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>AM</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>AO</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>AQ</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>AR</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>AS</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>AT</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>AU</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>AW</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>CZ</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>AZ</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>BB</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>BD</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>BE</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>BF</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>BG</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>BH</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>BI</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>BJ</label>
    </customValue>
    <customValue>
        <fullName>27</fullName>
        <label>BM</label>
    </customValue>
    <customValue>
        <fullName>28</fullName>
        <label>BN</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>BO</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>BR</label>
    </customValue>
    <masterLabel>CountryPicklist</masterLabel>
</GlobalValueSet>

cmss/customer-360/classes/ContactInformationTriggerHandler.cls
public with sharing class ContactInformationTriggerHandler extends TriggerHandler {
	public static void createContactInformationValue(List<ContactInformation__c> contactInfoList) {
		Map<String, String> countryValueLabelMap = new Map<String, String>();

		Schema.DescribeFieldResult fieldResult = ContactInformation__c.Country__c.getDescribe();
		List<Schema.PicklistEntry> pte = fieldResult.getPicklistValues();
		for (Schema.PicklistEntry pickListVal : pte) {
			countryValueLabelMap.put(pickListVal.getValue(), pickListVal.getLabel());
		}
		for (ContactInformation__c contactInfoItem : contactInfoList) {
			contactInfoItem.Value__c = 'neuvedeno';
			if (contactInfoItem.Type__c == '1') {
				contactInfoItem.Value__c =
					contactInfoItem.Street__c +
					' ' +
					contactInfoItem.HouseNumber__c +
					' ' +
					contactInfoItem.City__c +
					' ' +
					contactInfoItem.PostalCode__c +
					' ' +
					countryValueLabelMap.get(contactInfoItem.Country__c);
			}
			if (contactInfoItem.Type__c == '2') {
				contactInfoItem.Value__c = contactInfoItem.PhoneNumber__c;
			}
			if (contactInfoItem.Type__c == '3') {
				contactInfoItem.Value__c = contactInfoItem.Email__c + ' ' + contactInfoItem.DataBoxNumber__c;
			}
			if (contactInfoItem.Type__c == '4') {
				contactInfoItem.Value__c = contactInfoItem.DataBoxNumber__c;
			}
		}
	}
}