cmss/main/default/objects/InternalConsent__c/InternalConsent__c.object-meta.xml
<CustomObject>
    <label>Internal Consent</label>
    <nameField>
        <displayFormat>MS-{000000}</displayFormat>
        <label>Internal Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Consents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/InternalConsent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Internal Consents</relationshipLabel>
    <relationshipName>InternalConsents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/InternalConsentType__c.field-meta.xml
<CustomField>
    <fullName>InternalConsentType__c</fullName>
    <label>Internal Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/InternalConsentValue__c.field-meta.xml
<CustomField>
    <fullName>InternalConsentValue__c</fullName>
    <label>Internal Consent Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>46</fullName>
            </value>
            <value>
                <fullName>47</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/consent-management/classes/InternalConsentUpsertInvocable.cls
public with sharing class InternalConsentUpsertInvocable {
    
    @InvocableMethod
    public static List<Results> execute (List<Request> requestList) {
        List<Results> responseWrapper = new List<Results>();
        for (Request curRequest : requestList) {
            InternalConsent__c inputRecord = curRequest.inputRecord;

            if ( inputRecord != null) {
                InternalConsent__c tempInputRecord = new InternalConsent__c ();
                // Picklist values needs to be casted to the String, known issue.
                tempInputRecord.InternalConsentType__c = String.valueOf(inputRecord.InternalConsentType__c);
                tempInputRecord.Source__c = String.valueOf(inputRecord.Source__c);
                tempInputRecord.InternalConsentValue__c = String.valueOf(inputRecord.InternalConsentValue__c);
                tempInputRecord.ValidFrom__c = inputRecord.ValidFrom__c;
                tempInputRecord.ValidTo__c = inputRecord.ValidTo__c;
                tempInputRecord.Account__c = inputRecord.Account__c;
                tempInputRecord.ExternalId__c = inputRecord.ExternalId__c;
                Upsert tempInputRecord ExternalId__c;
            }
            
            Results response = new Results();

            responseWrapper.add(response);
        }     
        
        return responseWrapper;
    
    }

    public class Request {
        @InvocableVariable
        public InternalConsent__c inputRecord;
    }
    
    public class Results {
        @InvocableVariable
        public String placeholder; // Will not work without this.
    }

    public class InvocableActionException extends Exception {}
}