cmss/main/default/objects/Production__c/Production__c.object-meta.xml
<CustomObject>
    <description>Serves for reporting of production of OZ&apos;s and managers.</description>
    <label>Production</label>
    <nameField>
        <displayFormat>P-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/Production__c/fields/RegionManager__c.field-meta.xml
<CustomField>
    <fullName>RegionManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RegionManagerProduction</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Production__c/fields/SalesNetManager__c.field-meta.xml
<CustomField>
    <fullName>SalesNetManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Net Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesNetManagerProduction</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Production__c/fields/TeamManager__c.field-meta.xml
<CustomField>
    <fullName>TeamManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamManagerProduction</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/classes/ProductionSharingRecalc.cls
public class ProductionSharingRecalc implements Database.Batchable<sObject> {
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(
			[
				SELECT Id, TeamManager__c, RegionManager__c, SalesNetManager__c
				FROM Production__c
			]
		);
	}

	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		List<Production__c> productions = new List<Production__c>((List<Production__c>) scope);
		ProductionService.deleteProductionSharing(Trigger.old);
		ProductionService.insertProductionSharing(Trigger.new);
	}

	public void finish(Database.BatchableContext BC) {
		System.debug('Apex Sharing Recalculation Completed.');
	}
}