cmss/main/default/objects/EventSync__c/EventSync__c.object-meta.xml
<CustomObject>
    <description>Queable object for Event synchronisation with Google Calendar</description>
    <label>Event Sync</label>
    <nameField>
        <displayFormat>ES-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Event Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Syncs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/EventSync__c/fields/ChangeFromGoogle__c.field-meta.xml
<CustomField>
    <fullName>ChangeFromGoogle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Change From Google</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/EventSync__c/fields/GoogleEventId__c.field-meta.xml
<CustomField>
    <fullName>GoogleEventId__c</fullName>
    <externalId>true</externalId>
    <label>Google Event Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/EventSync__c/fields/IsNew__c.field-meta.xml
<CustomField>
    <fullName>IsNew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is New</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/EventSync__c/fields/SFEventId__c.field-meta.xml
<CustomField>
    <fullName>SFEventId__c</fullName>
    <label>SF Event Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/UserCalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Used for synchronisation with Google Calendar</description>
    <label>User Calendar Setting</label>
    <nameField>
        <displayFormat>UCS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>User Calendar Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Calendar Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/UserCalendarSetting__c/fields/ResourceId__c.field-meta.xml
<CustomField>
    <fullName>ResourceId__c</fullName>
    <externalId>true</externalId>
    <label>Resource Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncActive__c.field-meta.xml
<CustomField>
    <fullName>SyncActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Active</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/SyncToken__c.field-meta.xml
<CustomField>
    <fullName>SyncToken__c</fullName>
    <label>Sync Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchExpirationDateTime__c.field-meta.xml
<CustomField>
    <fullName>WatchExpirationDateTime__c</fullName>
    <label>Watch Expiration DateTime</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchId__c.field-meta.xml
<CustomField>
    <fullName>WatchId__c</fullName>
    <label>Watch Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/triggerHandlers/UserCalendarSettingTriggerHandlerTest.cls
@isTest
class UserCalendarSettingTriggerHandlerTest {
	// tests whether sync token and sync active is updated
	@isTest
	static void testAfterInsertSyncTokenUpdate() {
		User u = TestDataFactory.getUser(new User());
		insert u;
		UserCalendarSetting__c setting = InitialCalendarSyncControllerTest.makeCalendarSetting(u.Id);
		UserCalendarSettingTriggerHandler.shouldNotRunAfterInsertTrigger();
		insert setting;
		UserCalendarSettingTriggerHandler.shouldRunAfterInsertTrigger();

		GoogleCalendarSyncUtility.GoogleEventRespDTO respFromGoogle = new GoogleCalendarSyncUtility.GoogleEventRespDTO();
		respFromGoogle.nextSyncToken = InitialCalendarSyncControllerTest.SYNC_TOKEN;
		respFromGoogle.items = new List<GoogleCalendarSyncUtility.GoogleEventDTO>{};
		CalloutServiceMockImpl fakeResponse = new CalloutServiceMockImpl(
			200,
			'OK',
			GoogleCalendarSyncUtility.placeReserved(JSON.serialize(respFromGoogle), new List<string>{ 'start', 'end' }),
			null,
			null
		);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
		Test.startTest();
		UserCalendarSettingTriggerHandler.initialEventSync(new List<UserCalendarSetting__c>{ setting });
		Test.stopTest();

		setting = [SELECT Id, SyncToken__c, SyncActive__c FROM UserCalendarSetting__c WHERE Id = :setting.Id];
		System.assertEquals(InitialCalendarSyncControllerTest.SYNC_TOKEN, setting.SyncToken__c);
		System.assertEquals(true, setting.SyncActive__c);
	}
	// tests whether new event syncs are created for events that are not returned by Google
	@isTest
	static void testAfterInsertUnsynced() {
		User u = TestDataFactory.getUser(new User());
		insert u;
		UserCalendarSetting__c setting = InitialCalendarSyncControllerTest.makeCalendarSetting(u.Id);
		UserCalendarSettingTriggerHandler.shouldNotRunAfterInsertTrigger();
		insert setting;
		UserCalendarSettingTriggerHandler.shouldRunAfterInsertTrigger();

		List<Event> events = InitialCalendarSyncControllerTest.makeUnsyncedEvents(u.Id);
		insert events;

		GoogleCalendarSyncUtility.GoogleEventRespDTO respFromGoogle = new GoogleCalendarSyncUtility.GoogleEventRespDTO();
		respFromGoogle.nextSyncToken = InitialCalendarSyncControllerTest.SYNC_TOKEN;
		respFromGoogle.items = new List<GoogleCalendarSyncUtility.GoogleEventDTO>{};
		CalloutServiceMockImpl fakeResponse = new CalloutServiceMockImpl(
			200,
			'OK',
			GoogleCalendarSyncUtility.placeReserved(JSON.serialize(respFromGoogle), new List<string>{ 'start', 'end' }),
			null,
			null
		);
		Test.setMock(HttpCalloutMock.class, fakeResponse);

		List<EventSync__c> eventSyncsBefore = [
			SELECT Id, GoogleEventId__c, SFEventID__c, ChangeFromGoogle__c, IsNew__c
			FROM EventSync__c
		];
		delete eventSyncsBefore;
		Test.startTest();
		UserCalendarSettingTriggerHandler.initialEventSync(new List<UserCalendarSetting__c>{ setting });
		Test.stopTest();

		List<EventSync__c> eventSyncs = [
			SELECT Id, GoogleEventId__c, SFEventID__c, ChangeFromGoogle__c, IsNew__c
			FROM EventSync__c
		];

		System.assertEquals(2, eventSyncs.size(), '2 unsynced events were inserted, expected 2 event syncs');
		System.assert(eventSyncs.get(0).SFEventID__c != eventSyncs.get(1).SFEventID__c);
		for (EventSync__c event : eventSyncs) {
			System.assertEquals(null, event.GoogleEventId__C);
			System.assertEquals(false, event.ChangeFromGoogle__c);
			System.assertEquals(true, event.IsNew__c);
		}
	}

	@isTest
	static void testBeforeUpdate() {
		UserCalendarSetting__c setting = new UserCalendarSetting__c();
		setting.SyncActive__c = true;
		setting.WatchId__c = 'abc';
		setting.ResourceId__c = 'def';
		setting.WatchExpirationDateTime__c = DateTime.newInstance(2022, 4, 15);

		List<UserCalendarSetting__c> oldSettings = new List<UserCalendarSetting__c>();
		oldSettings.add(setting);

		Map<Id, UserCalendarSetting__c> newSettingsMap = new Map<Id, UserCalendarSetting__c>();
		UserCalendarSetting__c newSetting = setting.clone(true, true);
		newSetting.SyncActive__c = false;
		newSettingsMap.put(newSetting.Id, newSetting);

		CalloutServiceMockImpl fakeResponse = new CalloutServiceMockImpl(200, 'OK', null, null, null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);

		Test.startTest();
		UserCalendarSettingTriggerHandler.stopWatchingUpdate(oldSettings, newSettingsMap);
		Test.stopTest();

		System.assertEquals(null, newSetting.WatchId__c, 'Watch Id should be removed when stopping watching');
		System.assertEquals(
			null,
			newSetting.WatchExpirationDateTime__c,
			'Watch Expiration should be removed when stopping watching'
		);
	}

	@isTest
	static void testInitialEventSync() {
	}
}