cmss/main/default/objects/EventSync__c/EventSync__c.object-meta.xml
<CustomObject>
    <description>Queable object for Event synchronisation with Google Calendar</description>
    <label>Event Sync</label>
    <nameField>
        <displayFormat>ES-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Event Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Syncs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/EventSync__c/fields/ChangeFromGoogle__c.field-meta.xml
<CustomField>
    <fullName>ChangeFromGoogle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Change From Google</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/UserCalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Used for synchronisation with Google Calendar</description>
    <label>User Calendar Setting</label>
    <nameField>
        <displayFormat>UCS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>User Calendar Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Calendar Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/UserCalendarSetting__c/fields/ResourceId__c.field-meta.xml
<CustomField>
    <fullName>ResourceId__c</fullName>
    <externalId>true</externalId>
    <label>Resource Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/fields/WatchId__c.field-meta.xml
<CustomField>
    <fullName>WatchId__c</fullName>
    <label>Watch Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/classes/GoogleApiWebhooksUtility.cls
public without sharing class GoogleApiWebhooksUtility {
	public static void handleWebhookRequest(RestRequest request, RestResponse response) {
		String token = request.headers.get('X-Goog-Channel-Token');
		String calendarId = request.headers.get('X-Goog-Resource-ID');

		if (calendarId == null || token == null) {
			System.debug(LoggingLevel.DEBUG, 'Malformed request, Calendar ID or Token missing');
			response.statusCode = 400;
			return;
		}

		List<UserCalendarSetting__c> settings = [
			SELECT WatchId__c
			FROM UserCalendarSetting__c
			WHERE ResourceId__c = :calendarId
		];

		if (settings == null || settings.isEmpty()) {
			System.debug(LoggingLevel.DEBUG, 'Corresponding User Settings not found');
			response.statusCode = 404;
			return;
		}

		UserCalendarSetting__c setting = settings.get(0);

		if (!token.equals(setting.WatchId__c)) {
			System.debug(
				LoggingLevel.DEBUG,
				'Request Token does not correspond to User Settings Token. Token in request: ' +
				token +
				', token in setting: ' +
				setting.WatchId__c
			);
			response.statusCode = 401;
			return;
		}

		List<EventSync__c> existingSyncForResource = [
			SELECT ResourceId__c, ChangeFromGoogle__c
			FROM EventSync__c
			WHERE ResourceId__c = :calendarId AND ChangeFromGoogle__c = TRUE
		];

		if (existingSyncForResource.size() == 0) {
			EventSync__c eventSync = new EventSync__c();
			eventSync.ResourceId__c = calendarId;
			eventSync.ChangeFromGoogle__c = true;
			insert eventSync;
		}

		response.statusCode = 200;
	}
}