cmss/main/default/objects/Contact/fields/AgentActivityType__c.field-meta.xml
<CustomField>
    <fullName>AgentActivityType__c</fullName>
    <label>Agent Activity Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Contact/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <label>Commission Account Base</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Contact/fields/IsAgentActive__c.field-meta.xml
<CustomField>
    <fullName>IsAgentActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Agent Active</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Zobrazení veškerých informací o OZ, kontaktech a správě stavu</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/User/fields/AgentActivityType__c.field-meta.xml
<CustomField>
    <fullName>AgentActivityType__c</fullName>
    <description>Jedinečný identifikátor pro entitu Typ činnosti přidruženou k entitě Odbytový orgán.</description>
    <label>Agent Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/User/fields/AgentId__c.field-meta.xml
<CustomField>
    <fullName>AgentId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Agent Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <label>Commission Account Number Base</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/IsAgentActive__c.field-meta.xml
<CustomField>
    <fullName>IsAgentActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Určuje jestli je uživatel opravdu neaktivní, nebo jestli jde jen o aktivního agenta, který nemá přístup do CRM = může být správce stavu</description>
    <label>Active Agent</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/User/fields/Phone1__c.field-meta.xml
<CustomField>
    <fullName>Phone1__c</fullName>
    <description>První telefonní číslo kontaktu</description>
    <label>Phone 1</label>
    <type>Phone</type>
</CustomField>

cmss/main/default/objects/UserCalendarSetting__c/UserCalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Used for synchronisation with Google Calendar</description>
    <label>User Calendar Setting</label>
    <nameField>
        <displayFormat>UCS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>User Calendar Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Calendar Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmss/main/default/objects/UserCalendarSetting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCalendarSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/customer-360/classes/UserTriggerHandlerTest.cls
@IsTest
private class UserTriggerHandlerTest {
	@TestSetup
	static void makeData() {
		UserRole userRole = new UserRole(Name = 'TestRole');
		insert userRole;
	}

	@IsTest
	static void relatedUserCalendarSettingsDeletedTest() {
		User oldUser = TestDataFactory.getUser(new User());
		oldUser.IsActive = true;
		insert oldUser;

		User newUser = oldUser.clone(true, true);
		newUser.IsActive = false;

		UserCalendarSetting__c setting = new UserCalendarSetting__c();
		setting.User__c = oldUser.Id;
		insert setting;
		Id idOfSetting = setting.Id;

		Map<Id, User> oldMap = new Map<Id, User>();
		oldMap.put(oldUser.Id, oldUser);
		Map<Id, User> newMap = new Map<Id, User>();
		newMap.put(newUser.Id, newUser);

		CalloutServiceMockImpl fakeResponse = new CalloutServiceMockImpl(200, 'OK', null, null, null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);

		Test.startTest();
		UserTriggerHandler.checkChangeForActiveAndDeleteRelatedCalendarSettings(oldMap, newMap);
		Test.stopTest();

		List<UserCalendarSetting__c> settings = [SELECT Id FROM UserCalendarSetting__c WHERE Id = :idOfSetting];
		System.assert(settings.isEmpty());
	}

	@IsTest
	static void contactInfoUpdatedTest() {
		Profile adminProfile = [SELECT id, Name FROM Profile WHERE name = 'System Administrator'].get(0);
		UserRole userRole = [SELECT Id FROM UserRole WHERE Name = 'TestRole'];

		User runningUser = TestDataFactory.getUser(
			new User(
				profileId = adminProfile.id,
				UserRoleId = userRole.Id,
				LastName = 'Jackson',
				Username = 'samuelel@jackson.com'
			)
		);
		insert runningUser;

		User communityUser;
		Contact portalContact;
		System.runAs(runningUser) {
			Account portalAccount = new Account(Name = 'Test');
			insert portalAccount;

			portalContact = new contact(LastName = 'Test', AccountId = portalAccount.Id);
			insert portalContact;

			Id communityProfileId = [SELECT Id FROM Profile WHERE Name = 'CMSS Experience User'].Id;

			communityUser = TestDataFactory.getUser(
				new User(
					AgentId__c = '12355',
					AgentActivityType__c = '2',
					CommissionAccountBase__c = '2',
					IsAgentActive__c = true,
					FirstName = 'Kamil',
					LastName = 'Testovič',
					Email = 'kamil@test.cz',
					Phone1__c = '123456789',
					ProfileId = communityProfileId,
					ContactId = portalContact.Id,
					IsActive = true
				)
			);
			insert communityUser;
		}

		Test.startTest();
		UserTriggerHandler.updateCommunityUsersContacts(new Set<Id>{ communityUser.Id });
		Test.stopTest();

		portalContact = [
			SELECT AgentActivityType__c, CommissionAccountBase__c, IsAgentActive__c, FirstName, LastName, Email, Phone
			FROM Contact
			WHERE Id = :portalContact.Id
		];

		System.assertEquals(portalContact.LastName, 'Testovič');
		System.assertEquals(portalContact.FirstName, 'Kamil');
		System.assertEquals(portalContact.Email, 'kamil@test.cz');
		System.assertEquals(portalContact.Phone, '123456789');
		System.assertEquals(portalContact.IsAgentActive__c, true);
		System.assertEquals(portalContact.CommissionAccountBase__c, '2');
		System.assertEquals(portalContact.AgentActivityType__c, '2');
	}
}