cmss/main/default/objects/Contact/fields/AgentActivityType__c.field-meta.xml
<CustomField>
    <fullName>AgentActivityType__c</fullName>
    <label>Agent Activity Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Contact/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <label>Commission Account Base</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Contact/fields/CooperationPartnerType__c.field-meta.xml
<CustomField>
    <fullName>CooperationPartnerType__c</fullName>
    <label>Cooperation Partner Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Contact/fields/IsAgentActive__c.field-meta.xml
<CustomField>
    <fullName>IsAgentActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Agent Active</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Zobrazení veškerých informací o OZ, kontaktech a správě stavu</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/User/fields/AgentActivityType__c.field-meta.xml
<CustomField>
    <fullName>AgentActivityType__c</fullName>
    <description>Jedinečný identifikátor pro entitu Typ činnosti přidruženou k entitě Odbytový orgán.</description>
    <label>Agent Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <label>Commission Account Number Base</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CooperationPartnerType__c.field-meta.xml
<CustomField>
    <fullName>CooperationPartnerType__c</fullName>
    <description>Typ kooperačního partnera (zpr_cis_koop_partneri)</description>
    <label>Cooperation Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/User/fields/IsAgentActive__c.field-meta.xml
<CustomField>
    <fullName>IsAgentActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Určuje jestli je uživatel opravdu neaktivní, nebo jestli jde jen o aktivního agenta, který nemá přístup do CRM = může být správce stavu</description>
    <label>Active Agent</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/User/fields/Phone1__c.field-meta.xml
<CustomField>
    <fullName>Phone1__c</fullName>
    <description>První telefonní číslo kontaktu</description>
    <label>Phone 1</label>
    <type>Phone</type>
</CustomField>

cmss/customer-360/classes/UserTriggerHandler.cls
public class UserTriggerHandler extends TriggerHandler {
	public override void afterInsert() {
		updateCommunityUsersContacts(Trigger.newMap.keySet());
	}

	public override void afterUpdate() {
		if (!System.isBatch()) {
			updateCommunityUsersContacts(Trigger.newMap.keySet());
		}
	}

	@TestVisible
	@Future
	private static void updateCommunityUsersContacts(Set<Id> userIds) {
		Map<Id, User> contactsToUsersMap = getContactsToUsersMap(userIds);

		if (contactsToUsersMap.size() > 0) {
			updateContacts(contactsToUsersMap);
		}
	}

	private static Map<Id, User> getContactsToUsersMap(Set<Id> userIds) {
		List<User> users = [
			SELECT
				AgentActivityType__c,
				CommissionAccountBase__c,
				CooperationPartnerType__c,
				IsAgentActive__c,
				FirstName,
				LastName,
				Email,
				Phone1__c,
				IsActive,
				ContactId
			FROM User
			WHERE Id IN :userIds
		];

		Map<Id, User> contactsToUsersMap = new Map<Id, User>();

		for (User u : users) {
			if (u.ContactId != null && u.IsActive) {
				contactsToUsersMap.put(u.ContactId, u);
			}
		}
		return contactsToUsersMap;
	}

	private static void updateContacts(Map<Id, User> contactsToUsersMap) {
		List<Contact> contacts = [
			SELECT
				AgentActivityType__c,
				CommissionAccountBase__c,
				CooperationPartnerType__c,
				IsAgentActive__c,
				User__c,
				FirstName,
				LastName,
				Email,
				Phone
			FROM Contact
			WHERE Id IN :contactsToUsersMap.keySet()
		];

		User actualUser;
		for (Contact c : contacts) {
			actualUser = contactsToUsersMap.get(c.Id);
			c.AgentActivityType__c = actualUser.AgentActivityType__c;
			c.CommissionAccountBase__c = actualUser.CommissionAccountBase__c;
			c.CooperationPartnerType__c = actualUser.CooperationPartnerType__c;
			c.IsAgentActive__c = actualUser.IsAgentActive__c;
			c.User__c = actualUser.Id;
			c.FirstName = actualUser.FirstName;
			c.LastName = actualUser.LastName;
			c.Email = actualUser.Email;
			c.Phone = actualUser.Phone1__c;
		}
		update contacts;
	}
}