cmss/main/default/objects/Asset/fields/CampaignMember__c.field-meta.xml
<CustomField>
    <fullName>CampaignMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Member</label>
    <referenceTo>CampaignMember__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ProductCloseDate__c.field-meta.xml
<CustomField>
    <fullName>ProductCloseDate__c</fullName>
    <description>Datum kdy byl produkt uzavřen</description>
    <label>Product Close Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>0 = úverový případ
1 = Úvěr ze Stavebního Spoření (USS)
2 = Meziúvěr (MU)
7 = Účet Rizikového Životního Pojištění (RZP)
9 = účet Stavebního Spoření (SS)&quot;</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Campaign/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/CampaignMember__c/CampaignMember__c.object-meta.xml
<CustomObject>
    <label>Campaign Member</label>
    <nameField>
        <label>Campaign Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/CampaignMember__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/CampaignMember__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/CampaignMember__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/CampaignMember__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Campaign__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

cmss/main/default/classes/UpdateCampaignMemberOnAsset_BatchTest.cls
@IsTest
public class UpdateCampaignMemberOnAsset_BatchTest {
	@IsTest
	private static void UpdateCampaignMemberOnAssetWithDifferentProducts() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		Asset asset1 = new Asset(
			AccountId = account.Id,
			Name = 'Asset',
			ProductCloseDate__c = System.today(),
			ProductType__c = '1'
		);
		insert asset1;
		Campaign existingCampaign1 = new Campaign();
		existingCampaign1.Name = 'Campaign1';
		existingCampaign1.StartDate = System.today().addDays(-10);
		existingCampaign1.EndDate = System.today();
		existingCampaign1.Product__c = '2';
		existingCampaign1.Type = '1';
		existingCampaign1.Status = 'Planned';
		insert existingCampaign1;
		Campaign existingCampaign2 = new Campaign();
		existingCampaign2.Name = 'Campaign2';
		existingCampaign2.Type = '1';
		existingCampaign2.Status = 'Planned';
		existingCampaign2.StartDate = System.today().addDays(-1);
		existingCampaign2.EndDate = System.today().addDays(10);
		insert existingCampaign2;
		CampaignMember__c campMember1 = new CampaignMember__c(
			Account__c = account.Id,
			Name = 'CampaignMember1',
			Campaign__c = existingCampaign1.Id,
			Asset__c = asset1.Id
		);
		insert campMember1;

		CampaignMember__c campMember2 = new CampaignMember__c(
			Account__c = account.Id,
			Name = 'CampaignMember2',
			Campaign__c = existingCampaign2.Id,
			Asset__c = asset1.Id
		);
		insert campMember2;
		UpdateCampaignMemberOnAsset_Batch batch = new UpdateCampaignMemberOnAsset_Batch();

		Test.startTest();
		Database.executeBatch(batch);
		Test.stopTest();

		Asset asset = [SELECT Id, CampaignMember__c FROM Asset];
		System.assertEquals(asset.CampaignMember__c, campMember2.Id);
	}
	@IsTest
	private static void UpdateCampaignMemberOnAssetWithSameProducts() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		Asset asset1 = new Asset(
			AccountId = account.Id,
			Name = 'Asset',
			ProductCloseDate__c = System.today(),
			ProductType__c = '2'
		);
		insert asset1;
		Campaign existingCampaign1 = new Campaign();
		existingCampaign1.Name = 'Campaign1';
		existingCampaign1.StartDate = System.today().addDays(-1);
		existingCampaign1.EndDate = System.today();
		existingCampaign1.Product__c = '2';
		existingCampaign1.Type = '1';
		existingCampaign1.Status = 'Planned';
		insert existingCampaign1;
		Campaign existingCampaign2 = new Campaign();
		existingCampaign2.Name = 'Campaign2';
		existingCampaign2.Type = '1';
		existingCampaign2.Status = 'Planned';
		existingCampaign2.StartDate = System.today().addDays(-10);
		existingCampaign2.EndDate = System.today().addDays(10);
		insert existingCampaign2;
		CampaignMember__c campMember1 = new CampaignMember__c(
			Account__c = account.Id,
			Name = 'CampaignMember1',
			Campaign__c = existingCampaign1.Id,
			Asset__c = asset1.Id
		);
		insert campMember1;

		CampaignMember__c campMember2 = new CampaignMember__c(
			Account__c = account.Id,
			Name = 'CampaignMember2',
			Campaign__c = existingCampaign2.Id,
			Asset__c = asset1.Id
		);
		insert campMember2;
		UpdateCampaignMemberOnAsset_Batch batch = new UpdateCampaignMemberOnAsset_Batch();

		Test.startTest();
		Database.executeBatch(batch);
		Test.stopTest();

		Asset asset = [SELECT Id, CampaignMember__c FROM Asset];
		System.assertEquals(asset.CampaignMember__c, campMember1.Id);
	}
}