cmss/main/default/objects/Asset/fields/CampaignMember__c.field-meta.xml
<CustomField>
    <fullName>CampaignMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Member</label>
    <referenceTo>CampaignMember__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ProductCloseDate__c.field-meta.xml
<CustomField>
    <fullName>ProductCloseDate__c</fullName>
    <description>Datum kdy byl produkt uzavřen</description>
    <label>Product Close Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>0 = úverový případ
1 = Úvěr ze Stavebního Spoření (USS)
2 = Meziúvěr (MU)
7 = Účet Rizikového Životního Pojištění (RZP)
9 = účet Stavebního Spoření (SS)&quot;</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/CampaignMember__c/CampaignMember__c.object-meta.xml
<CustomObject>
    <label>Campaign Member</label>
    <nameField>
        <label>Campaign Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/CampaignMember__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/CampaignMember__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/CampaignMember__c/fields/CampaignEndDate__c.field-meta.xml
<CustomField>
    <fullName>CampaignEndDate__c</fullName>
    <formula>Campaign__r.EndDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign End Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/CampaignMember__c/fields/CampaignStartDate__c.field-meta.xml
<CustomField>
    <fullName>CampaignStartDate__c</fullName>
    <formula>Campaign__r.StartDate</formula>
    <label>Campaign Start Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/CampaignMember__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Campaign__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

cmss/main/default/classes/UpdateCampaignMemberOnAsset_Batch.cls
public class UpdateCampaignMemberOnAsset_Batch implements Database.Batchable<sObject>, Schedulable {
	/**
	 * Batchable start - do the query.
	 */
	public Database.QueryLocator start(Database.BatchableContext jobId) {
		return Database.getQueryLocator(
			[
				SELECT
					Id,
					AccountId,
					ProductCloseDate__c,
					ProductType__c,
					(
						SELECT Id, Name, Account__c, CampaignEndDate__c, CampaignStartDate__c, Product__c
						FROM CampaignMembers__r
						ORDER BY CampaignStartDate__c DESC NULLS LAST
					)
				FROM Asset
				WHERE
					AccountId IN (
						SELECT Account__c
						FROM CampaignMember__c
						WHERE CampaignStartDate__c != NULL AND CampaignEndDate__c != NULL
					)
					AND ProductCloseDate__c != NULL
			]
		);
	}

	public void execute(Database.BatchableContext jobId, List<Asset> assets) {
		try {
			List<Asset> assetsToUpdate = new List<Asset>();
			for (Asset a : assets) {
				if (a.CampaignMembers__r.size() == 0) {
					continue;
				}
				List<CampaignMember__c> campaignMembersToProceed = new List<CampaignMember__c>();
				for (CampaignMember__c cm : a.CampaignMembers__r) {
					if (
						a.ProductCloseDate__c > cm.CampaignStartDate__c &&
						a.ProductCloseDate__c < cm.CampaignEndDate__c + 30
					) {
						campaignMembersToProceed.add(cm);
					}
				}

				if (campaignMembersToProceed.size() == 0) {
					continue;
				}
				Boolean foundCMWithSameProduct = false;

				for (CampaignMember__c cm : campaignMembersToProceed) {
					if (a.ProductType__c == cm.Product__c) {
						a.CampaignMember__c = cm.Id;
						foundCMWithSameProduct = true;
						break;
					}
				}
				if (!foundCMWithSameProduct) {
					a.CampaignMember__c = campaignMembersToProceed[0].Id;
				}

				assetsToUpdate.add(a);
			}
			if (assetsToUpdate.size() > 0) {
				System.debug('Updating ' + assetsToUpdate.size() + ' assets.');
				List<Database.SaveResult> results = Database.update(assetsToUpdate, false);
				for (Database.SaveResult result : results) {
					if (!result.isSuccess()) {
						for (Database.Error err : result.getErrors()) {
							Logger.error('Erorr message: ' + err.getMessage() + ' Fields:' + err.getFields());
						}
					}
				}
			}
		} catch (Exception e) {
			Logger.error('An unhandled exception thrown', e);
			throw e;
		} finally {
			Logger.saveLogs();
		}
	}
	/**
	 * Batchable finish - mandatory
	 */
	public void finish(Database.BatchableContext jobId) {
		System.debug('Execution of UpdateCampaignMemberOnAsset_Batch finished');
	}

	public void execute(SchedulableContext sc) {
		Database.executeBatch(this);
	}
}