cmss/main/default/objects/Asset/fields/ClosingAgentId__c.field-meta.xml
<CustomField>
    <fullName>ClosingAgentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Zprostředkovatel smlouvy - Uzavírajíci OZ</description>
    <label>Closing Agent Id</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Asset/fields/CreditAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditAmount__c</fullName>
    <description>Po 1.čerpání úvěrových prostředků z účtu ÚSS, výška úvěru, jinak prázdná hodnota.</description>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/Asset/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>Datum ukončení</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID produktu zdrojových systémů</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Asset/fields/LoanAmount__c.field-meta.xml
<CustomField>
    <fullName>LoanAmount__c</fullName>
    <description>Smluvní výše úvěru. Výše úvěru MU/USS stanovená v rámci rozhodnutí o UP. V případě USS je hodnota pola definitivně stanovena při prvním čerpání úvěru.</description>
    <label>Loan Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ProductCloseDate__c.field-meta.xml
<CustomField>
    <fullName>ProductCloseDate__c</fullName>
    <description>Datum kdy byl produkt uzavřen</description>
    <label>Product Close Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>0 = úverový případ
1 = Úvěr ze Stavebního Spoření (USS)
2 = Meziúvěr (MU)
7 = Účet Rizikového Životního Pojištění (RZP)
9 = účet Stavebního Spoření (SS)&quot;</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Asset/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <description>&quot;Stav záznamu typu Produkt (Smlouva) - Stav hodnoty v extraktu:
1 = platný
0 = neplatný&quot;</description>
    <label>State Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Asset/fields/TargetAmount__c.field-meta.xml
<CustomField>
    <fullName>TargetAmount__c</fullName>
    <description>Aktuální cílová částka smlouvy SS.</description>
    <label>Target Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/Asset/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>Update Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/recordTypes/BuildingSavings.recordType-meta.xml
<RecordType>
    <fullName>BuildingSavings</fullName>
    <active>true</active>
    <description>Stavební spoření</description>
    <label>Building Savings</label>
</RecordType>

cmss/main/default/objects/Asset/recordTypes/CreditCases.recordType-meta.xml
<RecordType>
    <fullName>CreditCases</fullName>
    <active>true</active>
    <description>Úvěrové případy</description>
    <label>Credit cases</label>
</RecordType>

cmss/main/default/objects/Opportunity/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>Autor, který vytvořil opportunitu</description>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/CreatedDateTime__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateTime__c</fullName>
    <label>Created Date Time</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>Termín pro dokončení příležitosti -do kdy má OZ příležitost zpracovat</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Opportunity/fields/OriginalAsset__c.field-meta.xml
<CustomField>
    <fullName>OriginalAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asset from which was the opportunity created</description>
    <label>Original Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Typ produktu - Product2</description>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>State Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Open</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Won</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Lost</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>Update Date</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/User/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/customer-360/classes/AssetTriggerHandler.cls
public with sharing class AssetTriggerHandler extends TriggerHandler {
	public static void pairOpportunity(List<Asset> assetsList) {
       Set<Id> clientIds = new Set<Id>();
       for (Asset asset: assetsList){
           clientIds.add(asset.AccountId);
       }

       List<Opportunity> oppsToUpsert = new List<Opportunity>();

       List<Opportunity> oppsToCheck = [SELECT 
            Id, AccountId, Amount, Author__c, Category__c, CloseDate, CreatedDateTime__c, Description, DueDate__c, ExternalId__c, 
            Name, OriginalAsset__c, OwnerId, Probability, ProductType__c, Reason__c, StageName, UpdateDate__c,
            ValidFrom__c, ValidTo__c, StateCode__c FROM Opportunity 
            WHERE AccountId IN: clientIds];

            for (Asset asset: assetsList){
                List<Opportunity> currentOppsToUpdate = new List<Opportunity>();
                for (Opportunity opp: oppsToCheck){
                    if (opp.AccountId == asset.AccountId &&
                        opp.OwnerId == asset.ClosingAgentId__c &&
                        opp.ProductType__c == Asset.ProductType__c &&
                        asset.ProductCloseDate__c >= opp.ValidFrom__c &&
                        asset.ProductCloseDate__c <= opp.ValidTo__c.addDays(30)
                    ) {
                        currentOppsToUpdate.add(addOpportunityInfo(opp, asset));                      
                    } 
                }
                if (currentOppsToUpdate.size() > 0) { //if opp (or more opps) was found, add it to the upsert list
                    oppsToUpsert.addAll(currentOppsToUpdate);
                } else { //if no opp was paired, we will create a new one
                    Opportunity newOpp = new Opportunity();
                    oppsToUpsert.add(addOpportunityInfo(newOpp,asset));
                }                   
            }  
            
        upsert oppsToUpsert;
        }

    private static Opportunity addOpportunityInfo(Opportunity opp, Asset asset){
        opp.Reason__c = '3';
        opp.StageName = '7';

        // all other fields in this function are changed only if they don't have any value already
        opp.AccountId = String.isEmpty(opp.AccountId) ? asset.AccountId : opp.AccountId;
        opp.Amount = opp.Amount == NULL ? getOppAmount(asset) : opp.Amount;
        opp.Author__c = 'Integrace'; //TODO integration user?? je to jenom string
        opp.Category__c = String.isEmpty(opp.Category__c) ? '2' : opp.Category__c;
        opp.CloseDate = opp.CloseDate == NULL ? Asset.ProductCloseDate__c : opp.CloseDate; //TODO cannot be empty
        opp.CreatedDateTime__c = opp.CreatedDateTime__c == NULL ? System.now() : opp.CreatedDateTime__c ;
        opp.Description = String.isEmpty(opp.Description) ? 'Příležitost automaticky založena při vzniku smlouvy': opp.Description;
        opp.DueDate__c = opp.DueDate__c == NULL ? System.today() : opp.DueDate__c; 
        List<String> oppNameList = new List<String>{'Sjednání smlouvy', asset.ProductType__c, asset.Name};
        opp.Name = String.isEmpty(opp.Name) ? String.join(oppNameList,' ') : opp.Name;
        opp.OriginalAsset__c = String.isEmpty(opp.OriginalAsset__c) ? asset.Id : opp.OriginalAsset__c;
        opp.OwnerId = String.isEmpty(opp.OwnerId) ? asset.ClosingAgentId__c : opp.OwnerId; //TODO cannot be empty!
        opp.Probability = opp.Probability == NULL ? 100 : opp.Probability; //TODO nema to byt vzdycky 100?
        opp.ProductType__c = opp.ProductType__c == NULL ? asset.ProductType__c : opp.ProductType__c; 
        opp.UpdateDate__c = opp.UpdateDate__c == NULL ? System.now() : opp.UpdateDate__c; 
        opp.ValidFrom__c = opp.ValidFrom__c == NULL ? System.now().addMinutes(-30) : opp.ValidFrom__c; 
        opp.ValidTo__c = opp.ValidTo__c == NULL ? System.now() : opp.ValidTo__c; 
        opp.StateCode__c = String.isEmpty(opp.StateCode__c) ? '1' : opp.StateCode__c;

    return opp;     
    }

    private static Double getOppAmount(Asset asset){
        if (asset.RecordTypeId == Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('BuildingSavings').getRecordTypeId()){
            return asset.TargetAmount__c;
        } else if (asset.RecordTypeId == Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('CreditCases').getRecordTypeId()){
            return asset.CreditAmount__c;
        } 

        return asset.LoanAmount__c;
    }
}