cmss/main/default/objects/Asset/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <formula>Account.PortfolioMngmtA__r.CommissionAccountBase__c</formula>
    <label>Commission Account Number Base</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Asset/fields/CreditAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditAmount__c</fullName>
    <description>Po 1.čerpání úvěrových prostředků z účtu ÚSS, výška úvěru, jinak prázdná hodnota.</description>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID produktu zdrojových systémů</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Asset/fields/PurposeOfUse2__c.field-meta.xml
<CustomField>
    <fullName>PurposeOfUse2__c</fullName>
    <label>Purpose Of Use 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Asset/fields/PurposeOfUse__c.field-meta.xml
<CustomField>
    <fullName>PurposeOfUse__c</fullName>
    <label>Purpose Of Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Asset/fields/RequestSignDate__c.field-meta.xml
<CustomField>
    <fullName>RequestSignDate__c</fullName>
    <description>Datum podpisu řádné žádosti</description>
    <label>Request Sign Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/SecondDecissionDate__c.field-meta.xml
<CustomField>
    <fullName>SecondDecissionDate__c</fullName>
    <description>Datum 2. rozhodnutí</description>
    <label>Second Decission Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10006</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>10010</fullName>
            </value>
            <value>
                <fullName>10011</fullName>
            </value>
            <value>
                <fullName>10012</fullName>
            </value>
            <value>
                <fullName>10013</fullName>
            </value>
            <value>
                <fullName>11001</fullName>
            </value>
            <value>
                <fullName>11002</fullName>
            </value>
            <value>
                <fullName>11003</fullName>
            </value>
            <value>
                <fullName>11004</fullName>
            </value>
            <value>
                <fullName>11005</fullName>
            </value>
            <value>
                <fullName>11006</fullName>
            </value>
            <value>
                <fullName>11007</fullName>
            </value>
            <value>
                <fullName>11008</fullName>
            </value>
            <value>
                <fullName>11009</fullName>
            </value>
            <value>
                <fullName>11010</fullName>
            </value>
            <value>
                <fullName>11011</fullName>
            </value>
            <value>
                <fullName>11012</fullName>
            </value>
            <value>
                <fullName>11013</fullName>
            </value>
            <value>
                <fullName>11014</fullName>
            </value>
            <value>
                <fullName>11015</fullName>
            </value>
            <value>
                <fullName>11016</fullName>
            </value>
            <value>
                <fullName>11017</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Asset/fields/TipsterId__c.field-meta.xml
<CustomField>
    <fullName>TipsterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>čpú tipaře v SSOS</description>
    <label>Tipster Id</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/LoanSurchargeDiscount__c/LoanSurchargeDiscount__c.object-meta.xml
<CustomObject>
    <description>Přirážky a slevy u smlouvy - pro úvěrový případ a meziúvěr</description>
    <label>Loan Surcharge Discount</label>
    <nameField>
        <label>Loan Surcharge Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Surcharge Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/LoanSurchargeDiscount__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Odkaz na smlouvu</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Loan Surcharge Discounts</relationshipLabel>
    <relationshipName>Loan_Surcharge_Discounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/LoanSurchargeDiscount__c/fields/SurchargeDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>SurchargeDiscountAmount__c</fullName>
    <description>Výše přirážky / slevy</description>
    <label>Surcharge Discount Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

cmss/main/default/objects/LoanSurchargeDiscount__c/fields/SurchargeDiscountId__c.field-meta.xml
<CustomField>
    <fullName>SurchargeDiscountId__c</fullName>
    <description>Kód slevy</description>
    <label>Surcharge Discount Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <label>Commission Account Number Base</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/classes/LoanAssetsServices.cls
public class LoanAssetsServices {
    
    public static String  updateLoanDetailInfo(UpdateLoanAssetsFlowController.LoanDetailInfoResult result,UpdateLoanAssetsFlowController.Request request){
        try{
            List<Asset> assetsToUpdate = new List<Asset>();
            String errorMessage;
            assetsToUpdate.add(getAsset(result, request.assetId));  
            List<Database.SaveResult> updateResults = Database.update(assetsToUpdate, false);
            for (Database.SaveResult updateResult : updateResults) {
                if (!updateResult.isSuccess()) {
                    for (Database.Error err : updateResult.getErrors()) {
                        errorMessage = 'Update erorr message: ' + err.getMessage() + ' Fields:' + err.getFields();
                        Logger.error('Update erorr message: ' + err.getMessage() + ' Fields:' + err.getFields());
                    }
                    return errorMessage;
                }
            }
            return null;
        }catch(Exception ex){
            
            if(ex.getLineNumber() == 80){
                return 'Update erorr message: Nepodařilo se najít usera s tímto TipsterId__c';
            }else{
                return 'Update erorr message: ' + ex.getMessage();}
        }
        
    }
    public static String  updateLoadPackages(List<UpdateLoanAssetsFlowController.LoadPackagesCalloutResult> results,UpdateLoanAssetsFlowController.Request request){
        try{
            String errorMessage;
            List<LoanSurchargeDiscount__c> loanSurchargeDiscountToUpdate = new   List<LoanSurchargeDiscount__c>();
            loanSurchargeDiscountToUpdate = getLoanSurchargeDiscount(results, request.assetId);
            List<Database.SaveResult> updateResults = Database.update(loanSurchargeDiscountToUpdate, false);
            for (Database.SaveResult updateResult : updateResults) {
                if (!updateResult.isSuccess()) {
                    for (Database.Error err : updateResult.getErrors()) {
                        errorMessage = 'Update erorr message: ' + err.getMessage() + ' Fields:' + err.getFields();
                        Logger.error('Update erorr message: ' + err.getMessage() + ' Fields:' + err.getFields());
                    }
                    return errorMessage;
                }
            }return null;
            
        }
        
        catch(Exception ex){
            return 'Update erorr message: ' + ex.getMessage();
            
        }}
    
    private static List<LoanSurchargeDiscount__c> getLoanSurchargeDiscount(List<UpdateLoanAssetsFlowController.LoadPackagesCalloutResult> results, String assetId){
        LoanSurchargeDiscount__c[] loanSurchargeDiscount = [Select Id,ExternalId__c, SurchargeDiscountAmount__c, SurchargeDiscountId__c,ValidFrom__c,ValidTo__c FROM LoanSurchargeDiscount__c WHERE Asset__c =: assetId];
        List<LoanSurchargeDiscount__c> loanSurchargeDiscountToUpdate = new   List<LoanSurchargeDiscount__c>();
        if (loanSurchargeDiscount.size() > 0 ){ 
            for(LoanSurchargeDiscount__c lsd : loanSurchargeDiscount){
                for(UpdateLoanAssetsFlowController.LoadPackagesCalloutResult result: results){
                    if(lsd.ExternalId__c == result.packageId){
                        lsd.ExternalId__c = result.packageId;
                        lsd.SurchargeDiscountId__c = result.packageType;
                        lsd.ValidTo__c = result.validTo;
                        lsd.ValidFrom__c = result.validFrom;
                        if(result.fee != null){
                            result.fee = result.fee.replace(',', '.');
                            lsd.SurchargeDiscountAmount__c = Decimal.valueOf(result.fee);
                        }
                        else{
                            result.discount = result.discount.replace(',', '.');
                            lsd.SurchargeDiscountAmount__c = Decimal.valueOf(result.discount);
                        }
                        loanSurchargeDiscountToUpdate.add(lsd);  
                        break;
                    }
                    
                }
            }
        }return loanSurchargeDiscountToUpdate;
    }
    private static Asset getAsset(UpdateLoanAssetsFlowController.LoanDetailInfoResult result, String assetId){
        String personNumber = result.personNumber;
        String userId = [Select Id from User WHERE CommissionAccountBase__c =: personNumber LIMIT 1].Id;
        Asset asset = new Asset(Id = assetId);
        asset.CreditAmount__c = result.variableAmount;
        asset.PurposeOfUse__c = result.loanUsageCode;
        asset.PurposeOfUse2__c = result.loanUsage2Code;
        asset.RequestSignDate__c = result.signDate;
        asset.SecondDecissionDate__c = result.approvalDate2;
        asset.Status__c = result.loanStateCode;
        asset.TipsterId__c = userId;
        
        return asset;
    }
}