cmss/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>0 = úverový případ
1 = Úvěr ze Stavebního Spoření (USS)
2 = Meziúvěr (MU)
7 = Účet Rizikového Životního Pojištění (RZP)
9 = účet Stavebního Spoření (SS)&quot;</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/AssetAccountRelation__c.object-meta.xml
<CustomObject>
    <label>Asset Account Relation</label>
    <nameField>
        <label>Asset Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AssetAccountRelation__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Reference na smlouvu</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/AssetsProductType__c.field-meta.xml
<CustomField>
    <fullName>AssetsProductType__c</fullName>
    <label>Assets Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Is filled by AssetAccountRelationTriggerHandler from related Asset__r.ProductType</description>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <description>0 = Úvěrový případ
1 = Úvěr
2 = Meziúvěr
7 = Rizikového životního pojištění
9 = Spořící účet
11 = Hypotéka
12 = ČSOB Půjčky
13 = ČSOB Účty
14 = Penzijní produkty
15 = Investiční životní pojištění
16 = Pojištění majetku a odpovědnosti</description>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

cmss/customer-360/classes/AssetAccountRelationTriggerHandlerTest.cls
@IsTest
public class AssetAccountRelationTriggerHandlerTest {
	@IsTest
	static void createAssetAccountRelationProductTypeTest() {
		AssetAccountRelation__c relation = TestDataFactory.getAssetAccountRelation(new AssetAccountRelation__c());

		Test.startTest();
		insert relation;
		Test.stopTest();

		AssetAccountRelation__c assetAccountRelation = [
			SELECT AssetsProductType__c, Asset__c
			FROM AssetAccountRelation__c
		];

		Asset asset = [SELECT ProductType__c FROM Asset];

		System.assertEquals(asset.ProductType__c, assetAccountRelation.AssetsProductType__c);
	}
}