cmss/main/default/objects/PortfolioManagementRequest__c/PortfolioManagementRequest__c.object-meta.xml
<CustomObject>
    <description>Request objekt pro Spravu Stavu.</description>
    <label>Portfolio Management Request</label>
    <nameField>
        <displayFormat>PMR-{0000000000}</displayFormat>
        <label>Portfolio Management Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Management Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/PortfolioManager__c.field-meta.xml
<CustomField>
    <fullName>PortfolioManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Požadovaný správce stavu</description>
    <label>Portfolio Manager</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Zadejte aktivního obchodního zástupce.</errorMessage>
        <filterItems>
            <field>User.IsAgentActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PortfolioManagementRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/PortfolioManagerCPU__c.field-meta.xml
<CustomField>
    <fullName>PortfolioManagerCPU__c</fullName>
    <description>Portfolio Manager ČPÚ</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Portfolio Manager CPU</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/services/PortfolioManagementRequestServiceTest.cls
@isTest
private class PortfolioManagementRequestServiceTest {

    @isTest
    static void testSetPortfolioManager() {
        User u = TestDataFactory.getUser(new User(CommissionAccountNr__c = 'CPU0'));
        User u2 = TestDataFactory.getUser(new User(CommissionAccountNr__c = 'CPU1'));
        insert new User[]{ u, u2 };

        Test.setMock(WebServiceMock.class, new PortfolioManagementServiceMock());
        PortfolioManagementRequest__c pmr = TestDataFactory.getPortfolioManagementRequest(new PortfolioManagementRequest__c());
        insert pmr;

        PortfolioManagementRequest__c queriedPMR = [SELECT PortfolioManager__c FROM PortfolioManagementRequest__c WHERE Id =: pmr.Id];
        System.assertEquals(u.Id, queriedPMR.PortfolioManager__c);

        pmr.PortfolioManagerCPU__c = u2.CommissionAccountNr__c;
        update pmr;

        queriedPMR = [SELECT PortfolioManager__c FROM PortfolioManagementRequest__c WHERE Id =: pmr.Id];
        System.assertEquals(u2.Id, queriedPMR.PortfolioManager__c);
    }

    @isTest
    static void testSetPortfolioManagerNotFound() {
        Test.setMock(WebServiceMock.class, new PortfolioManagementServiceMock());
        PortfolioManagementRequest__c pmr = TestDataFactory.getPortfolioManagementRequest(
            new PortfolioManagementRequest__c(PortfolioManagerCPU__c = '43429643927')
        );
        Boolean exceptionThrown = false;

        try {
            insert pmr;
        } catch(DmlException e) {
            exceptionThrown = true;
        }
        System.assertEquals(true, exceptionThrown);

        PortfolioManagementRequest__c[] queriedPMRs = [SELECT PortfolioManager__c FROM PortfolioManagementRequest__c WHERE Id =: pmr.Id];
        System.assertEquals(0, queriedPMRs.size());
    }

    @isTest
    static void testChangeCPEClientState() {
        User u = TestDataFactory.getUser(new User(CommissionAccountNr__c = 'CPU0'));
        insert new User[]{ u };
        Test.setMock(WebServiceMock.class, new PortfolioManagementServiceMock());
        PortfolioManagementRequest__c pmr = TestDataFactory.getPortfolioManagementRequest(new PortfolioManagementRequest__c());
        insert pmr;
    }
}