cmss/main/default/objects/PortfolioManagementRequest__c/PortfolioManagementRequest__c.object-meta.xml
<CustomObject>
    <description>Request objekt pro Spravu Stavu.</description>
    <label>Portfolio Management Request</label>
    <nameField>
        <displayFormat>PMR-{0000000000}</displayFormat>
        <label>Portfolio Management Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Management Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/RequestStatus__c.field-meta.xml
<CustomField>
    <fullName>RequestStatus__c</fullName>
    <description>Stav requestu</description>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/customer-360/classes/PortfolioManagementRequestTriggerHandler.cls
public with sharing class PortfolioManagementRequestTriggerHandler extends TriggerHandler {
	public static final String DEFAULT_REQUEST_STATUS = '4';

	public override void beforeInsert() {
		setDefaultRequestStatus(Trigger.new);
	}

	public override void beforeUpdate() {
		PortfolioManagementRequestService.setPortfolioManager(
			Trigger.new,
			(Map<Id, PortfolioManagementRequest__c>) Trigger.oldMap
		);
	}

	// ***************************** handlers and helping methods***************************************** //

    private static void setDefaultRequestStatus(List<PortfolioManagementRequest__c> requests) {
		for (PortfolioManagementRequest__c request : requests) {
			request.RequestStatus__c = DEFAULT_REQUEST_STATUS;
		}
	}
}