cmss/main/default/objects/PortfolioManagementRequest__c/PortfolioManagementRequest__c.object-meta.xml
<CustomObject>
    <description>Request objekt pro Spravu Stavu.</description>
    <label>Portfolio Management Request</label>
    <nameField>
        <displayFormat>PMR-{0000000000}</displayFormat>
        <label>Portfolio Management Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Management Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Klient</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portfolio Management Requests</relationshipLabel>
    <relationshipName>PortfolioManagementRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/BatchID__c.field-meta.xml
<CustomField>
    <fullName>BatchID__c</fullName>
    <description>Unikatni Batch ID manualniho importu csv souboru.</description>
    <label>Batch ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/PortfolioManagementType__c.field-meta.xml
<CustomField>
    <fullName>PortfolioManagementType__c</fullName>
    <description>Typ správy stavu</description>
    <label>Portfolio Management Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/PortfolioManager__c.field-meta.xml
<CustomField>
    <fullName>PortfolioManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Požadovaný správce stavu</description>
    <label>Portfolio Manager</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Zadejte aktivního obchodního zástupce.</errorMessage>
        <filterItems>
            <field>User.IsAgentActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PortfolioManagementRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/PortfolioManagerCPU__c.field-meta.xml
<CustomField>
    <fullName>PortfolioManagerCPU__c</fullName>
    <description>Portfolio Manager ČPÚ</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Portfolio Manager CPU</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/PortfolioManChangeReason__c.field-meta.xml
<CustomField>
    <fullName>PortfolioManChangeReason__c</fullName>
    <description>Důvod změny správy stavu</description>
    <label>Portfolio Management Change Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <description>Platnost od</description>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/services/PortfolioManagementRequestService.cls
public with sharing class PortfolioManagementRequestService {

    public static final String NO_USER_WITH_SUCH_CPU_ERR = 'No user exists with this CPU. Please insert a different user\'s CPU.';
    public static final String MULTIPLE_BATCH_IDS_ERR = 'All created requests must contain identical Batch ID.';

    public static void setPortfolioManager(PortfolioManagementRequest__c[] newPMRs, Map<Id, PortfolioManagementRequest__c> oldPMRs) {
        Map<String, PortfolioManagementRequest__c[]> portfolioManagerCPUsToPMRs = new Map<String, PortfolioManagementRequest__c[]>();
        Set<String> pmCPUs = new Set<String>();

        if (oldPMRs == null) {
            for (PortfolioManagementRequest__c newPMR : newPMRs) {
                if (newPMR.PortfolioManagerCPU__c != null) {
                    setupPortfolioManagerCPUsToPMRs(portfolioManagerCPUsToPMRs, newPMR);
                    pmCPUs.add(newPMR.PortfolioManagerCPU__c);
                }
            }
        } else {
            for (PortfolioManagementRequest__c newPMR : newPMRs) {
                PortfolioManagementRequest__c oldPMR = oldPMRs.get(newPMR.Id);
                if (newPMR.PortfolioManagerCPU__c != null && newPMR.PortfolioManagerCPU__c != oldPMR.PortfolioManagerCPU__c) {
                    setupPortfolioManagerCPUsToPMRs(portfolioManagerCPUsToPMRs, newPMR);
                    pmCPUs.add(newPMR.PortfolioManagerCPU__c);
                } else if (newPMR.PortfolioManagerCPU__c == null) {
                    newPMR.PortfolioManagerCPU__c = null;
                }
            }
        }
        
        for (User u : [
            SELECT CommissionAccountNr__c 
            FROM User 
            WHERE CommissionAccountNr__c IN :portfolioManagerCPUsToPMRs.keySet()
        ]) {
            PortfolioManagementRequest__c[] pmrs = portfolioManagerCPUsToPMRs.get(u.CommissionAccountNr__c);
            pmCPUs.remove(u.CommissionAccountNr__c);

            for (PortfolioManagementRequest__c pmr : pmrs) {
                pmr.PortfolioManager__c = u.Id;
            }
        }

        if (pmCPUs.size() > 0) {
            throw new NoUserWithSuchCPUException(NO_USER_WITH_SUCH_CPU_ERR);
        }
    }

    public static void changeCPEClientState(PortfolioManagementRequest__c[] newPMRs) {
        String batchId = newPMRs[0].BatchID__c;

        for (PortfolioManagementRequest__c pmr : newPMRs) {
            if (batchId != pmr.BatchID__c) {
                throw new MultipleBatchIdsException(MULTIPLE_BATCH_IDS_ERR);
            }
        }

        changeCPEClientStateFuture(new Map<Id, PortfolioManagementRequest__c>(newPMRs).keySet(), batchId);
    }

    @future(callout=true)
    private static void changeCPEClientStateFuture(Set<Id> pmrIds, String batchId) {
        PortfolioManagementRequest__c[] pmrs = [
            SELECT Account__c, PortfolioManChangeReason__c, ValidFrom__c, PortfolioManagementType__c, PortfolioManagerCPU__c
            FROM PortfolioManagementRequest__c
            WHERE Id IN :pmrIds
        ];

        PortfolioManagementService.ListOfClientsStatesType clientStates = new PortfolioManagementService.ListOfClientsStatesType();
        clientStates.listOfClientsStatesItem = new PortfolioManagementService.ListOfClientsStatesItemType[]{};

        for (PortfolioManagementRequest__c pmr : pmrs) {
            PortfolioManagementService.ListOfClientsStatesItemType item = new PortfolioManagementService.ListOfClientsStatesItemType();
            item.stateChangeRequestId = pmr.Id;
            item.accountId_x = pmr.Account__c;
            item.stateChangeReason = pmr.PortfolioManChangeReason__c;
            item.validFrom = String.valueOfGmt(pmr.ValidFrom__c);
            item.portfolioManagementType = pmr.PortfolioManagementType__c;
            if (pmr.PortfolioManagementType__c == 'A') {
                item.spS_A = pmr.PortfolioManagerCPU__c;
            } else if (pmr.PortfolioManagementType__c == 'C') {
                item.spS_C = pmr.PortfolioManagerCPU__c;
            }

            clientStates.listOfClientsStatesItem.add(item);
        }

        PortfolioManagementService.ChangeCPEClientStateRequestHeader header = new PortfolioManagementService.ChangeCPEClientStateRequestHeader();
        header.timestamp = System.now();
        header.messageId = MockServicesUtil.generateUUID();
        header.sourceSystem = 'SalesForce';
        header.physicalSource = Url.getSalesforceBaseUrl().toExternalForm();
        header.userId = UserInfo.getUserId();
        PortfolioManagementService.ChangeCPEClientStateRequestBody body = new PortfolioManagementService.ChangeCPEClientStateRequestBody();
        body.batchId = batchId;
        body.listOfClientStates = clientStates;

        PortfolioManagementService.PortfolioManagementServicePort stub = new PortfolioManagementService.PortfolioManagementServicePort();
        PortfolioManagementService.ChangeCPEClientStateResponseBody response = stub.changeCPEClientState(body, header);

        Logger.debug('ChangeCPEClientState response', JSON.serialize(response));
        Logger.saveLogs();
    }

    private static void setupPortfolioManagerCPUsToPMRs(Map<String, PortfolioManagementRequest__c[]> portfolioManagerCPUsToPMRs, PortfolioManagementRequest__c pmr) {
        PortfolioManagementRequest__c[] pmrs = portfolioManagerCPUsToPMRs.get(pmr.PortfolioManagerCPU__c);
        if (pmrs == null) {
            portfolioManagerCPUsToPMRs.put(pmr.PortfolioManagerCPU__c, new PortfolioManagementRequest__c[]{ pmr });
        } else {
            pmrs.add(pmr);
            portfolioManagerCPUsToPMRs.put(pmr.PortfolioManagerCPU__c, pmrs);
        }
    }

    public class MultipleBatchIdsException extends Exception {}
    public class NoUserWithSuchCPUException extends Exception {}
}