cmss/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <description>Stav klienta - overit ciselnik a hodnoty NEJSOU DEFINITIVNI</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Asset/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <description>Stav účtu</description>
    <label>Account Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/AssetAccountRelation__c.object-meta.xml
<CustomObject>
    <label>Asset Account Relation</label>
    <nameField>
        <label>Asset Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AssetAccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference na klienta/prospekta</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <description>Reference na smlouvu</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Account Relations</relationshipLabel>
    <relationshipName>AssetAccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AssetAccountRelation__c/fields/RelationType__c.field-meta.xml
<CustomField>
    <fullName>RelationType__c</fullName>
    <description>Typ role (dlžník/spoludlžník...)
Pro UP:  FK CIS_ROLE_UP::KOD
Pro SS/MU/USS/RZP:  FK CIS_DRUH_DISPOZICIE::KOD</description>
    <label>Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>103</fullName>
            </value>
            <value>
                <fullName>104</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>106</fullName>
            </value>
            <value>
                <fullName>107</fullName>
            </value>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>109</fullName>
            </value>
            <value>
                <fullName>110</fullName>
            </value>
            <value>
                <fullName>201</fullName>
            </value>
            <value>
                <fullName>202</fullName>
            </value>
            <value>
                <fullName>203</fullName>
            </value>
            <value>
                <fullName>204</fullName>
            </value>
            <value>
                <fullName>205</fullName>
            </value>
            <value>
                <fullName>206</fullName>
            </value>
            <value>
                <fullName>207</fullName>
            </value>
            <value>
                <fullName>208</fullName>
            </value>
            <value>
                <fullName>209</fullName>
            </value>
            <value>
                <fullName>210</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

cmss/main/access-share/classes/AccessSharingUtilsTest.cls
@isTest
private class AccessSharingUtilsTest {
	@isTest
	static void getRelatedAccessShareDTOsTest() {
		Account client1 = TestDataFactory.getPersonAccount(
			new Account(
				FirstName = 'Gerard',
				LastName = 'Hověz',
				RecordTypeId = RecordTypeUtils.getRecordTypeIdByDeveloperName('PersonAccount', 'Account'),
				AccountStatus__c = '1'
			)
		);
		Account client2 = TestDataFactory.getPersonAccount(
			new Account(
				FirstName = 'Marcela',
				LastName = 'Obdržálková',
				RecordTypeId = RecordTypeUtils.getRecordTypeIdByDeveloperName('PersonAccount', 'Account'),
				AccountStatus__c = '1'
			)
		);
		insert new List<Account>{client1, client2};

		Asset asset = TestDataFactory.getAsset(
			new Asset(AccountId = client1.Id, EndDate__c = System.today().addDays(20))
		);
		insert asset;

		AssetAccountRelation__c relation = TestDataFactory.getAssetAccountRelation(
			new AssetAccountRelation__c(Account__c = client2.Id, Asset__c = asset.Id, RelationType__c = '2')
		);
		insert relation;
		User actualUser = [SELECT Id FROM USER WHERE Id = :UserInfo.getUserId()];
		AccessShareDTO originalDTO = new AccessShareDTO();
		originalDTO.userToShareWith = actualUser;
		originalDTO.reason = 'CustomerSearch';
		originalDTO.expirationDate = System.today().addDays(2);
		originalDTO.accountIdToShare = client2.Id;

		Set<AccessShareDTO> resultDTOs = AccessSharingUtils.getRelatedAccessShareDTOs(
			new Set<AccessShareDTO>{originalDTO}
		);

		List<AccessShareDTO> resultInList = new List<AccessShareDTO>(resultDTOs);

		System.assertEquals(1, resultDTOs.size());
		System.assertEquals(actualUser, resultInList[0].userToShareWith);
		System.assertEquals('CustomerSearch', resultInList[0].reason);
		System.assertEquals(client1.Id, resultInList[0].accountIdToShare);
	}
}