cmss/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <description>Stav klienta - overit ciselnik a hodnoty NEJSOU DEFINITIVNI</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/DateOfDeletion__c.field-meta.xml
<CustomField>
    <fullName>DateOfDeletion__c</fullName>
    <label>Date Of Deletion</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Account/fields/HasEmail__c.field-meta.xml
<CustomField>
    <fullName>HasEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Email</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/HasPhone__c.field-meta.xml
<CustomField>
    <fullName>HasPhone__c</fullName>
    <formula>IF(ISBLANK(Phone), false, true)</formula>
    <label>Has Phone</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/IsInvalid__c.field-meta.xml
<CustomField>
    <fullName>IsInvalid__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This account has been invalidated due to conslidation. Account is hidden and will be deleted in future.</inlineHelpText>
    <label>Is Invalid</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/LastPortfolioManagerA__c.field-meta.xml
<CustomField>
    <fullName>LastPortfolioManagerA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Datum poslední změny správy stavu A, plněno při změně Portfolio Manager A</description>
    <label>Last Portfolio Manager A</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LastPortfoloManagerAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Account/fields/LastPtfManAChangeDate__c.field-meta.xml
<CustomField>
    <fullName>LastPtfManAChangeDate__c</fullName>
    <description>Datum poslední změny správy stavu A, plněno při změně Portfolio Manager A</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Ptf Man A Change Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Account/fields/PortfolioMngmtA__c.field-meta.xml
<CustomField>
    <fullName>PortfolioMngmtA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Správce stavu A - Jedinečný identifikátor pro entitu Odbytový orgán přidruženou k entitě Klient</description>
    <label>Portfolio Management A</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagedAccountsA</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/CommonSetting__c/CommonSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Various settings for this org</description>
    <label>Common Settings</label>
</CustomObject>

cmss/main/default/objects/CommonSetting__c/fields/AccountDefaultOwner__c.field-meta.xml
<CustomField>
    <fullName>AccountDefaultOwner__c</fullName>
    <description>Id of an user that will own accounts where portfolio manager A cannot be determined.</description>
    <inlineHelpText>Id of an user that will own accounts where portfolio manager A cannot be determined.</inlineHelpText>
    <label>AccountDefaultOwner</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/CommonSetting__c/fields/OwnerForHiddenRecords__c.field-meta.xml
<CustomField>
    <fullName>OwnerForHiddenRecords__c</fullName>
    <inlineHelpText>Id of an user that should be used as an owner for hidden records. This user should not belong to any role.</inlineHelpText>
    <label>Owner For Hidden Records</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cmss/customer-360/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler extends TriggerHandler {
	public override void beforeInsert() {
		validateAccount(Trigger.new);
		invalidateAccount(Trigger.new);
		setOwner(Trigger.new);
        setHasEmailHasPhoneFields(null, (List<Account>) Trigger.new);
	}

	public override void beforeUpdate() {
		validateAccount(Trigger.new);
		invalidateAccount(Trigger.new);
		setOwner(Trigger.new);
		setLastPortfolioManager((Map<Id, Account>) Trigger.oldMap, (List<Account>) Trigger.new);
        setHasEmailHasPhoneFields((Map<Id, Account>) Trigger.oldMap, (List<Account>) Trigger.new);
	}

	public override void beforeDelete() {
		AQMessageService.handleDelete(Trigger.old, Account.SObjectType);
	}

	public override void afterInsert() {
		AQMessageService.handleInsert(Trigger.new, Account.SObjectType);
	}

	public override void afterUpdate() {
		AQMessageService.handleUpdate(Trigger.new, Trigger.oldMap, Account.SObjectType);
	}

	public override void afterUndelete() {
		AQMessageService.handleInsert(Trigger.new, Account.SObjectType);
	}

	// ***************************** handlers and helping methods***************************************** //

    @TestVisible
    private static void setHasEmailHasPhoneFields(Map<Id, Account> oldMap, List<Account> newList) {
        for (Account acc : newList) {
            if (oldMap == null) {
                updateHasFields(acc);
            } else {
                if (oldMap.get(acc.Id).Phone != acc.Phone 
                        || oldMap.get(acc.Id).PersonEmail != acc.PersonEmail 
                        || acc.HasEmail__c == null 
                        || acc.HasPhone__c == null) {

                    updateHasFields(acc);
                }
            }
        }
    }

    private static void updateHasFields(Account acc) {
        if (acc.Phone != null) {
            acc.HasPhone__c = true;
        } else {
            acc.HasPhone__c = false;
        }
        if (acc.PersonEmail != null) {
            acc.HasEmail__c = true;
        } else {
            acc.HasEmail__c = false;
        }
    }

	@TestVisible
	private static void setOwner(List<Account> accounts) {
		CommonSetting__c commonSetting = CommonSetting__c.getOrgDefaults();
		Id communityRecordType = [
			SELECT Id
			FROM RecordType
			WHERE SobjectType = 'Account' AND Name = 'Community Account'
		]
		.Id;
		for (Account a : accounts) {
			if (a.RecordTypeId == communityRecordType) {
				continue;
			}
			if (commonSetting.OwnerForHiddenRecords__c != null && a.IsInvalid__c) {
				a.OwnerId = commonSetting.OwnerForHiddenRecords__c;
			} else if (a.PortfolioMngmtA__c != null) {
				a.OwnerId = a.PortfolioMngmtA__c;
			} else if (commonSetting.AccountDefaultOwner__c != null) {
				a.OwnerId = commonSetting.AccountDefaultOwner__c;
			}
		}
	}

	@TestVisible
	private static void setLastPortfolioManager(Map<Id, Account> oldAccountsMap, List<Account> newAccounts) {
		for (Account account : newAccounts) {
			if (oldAccountsMap.get(account.Id).PortfolioMngmtA__c != account.PortfolioMngmtA__c) {
				account.LastPortfolioManagerA__c = oldAccountsMap.get(account.Id).PortfolioMngmtA__c;
				account.LastPtfManAChangeDate__c = System.today();
			}
		}
	}

	@TestVisible
	private static void invalidateAccount(List<Account> accounts) {
		for (Account a : accounts) {
			if (a.DateOfDeletion__c != null || a.AccountStatus__c == '5') {
				a.IsInvalid__c = true;
			}
		}
	}

	@TestVisible
	private static void validateAccount(List<Account> accounts) {
		for (Account a : accounts) {
			if (a.IsInvalid__c == true && a.DateOfDeletion__c == null && a.AccountStatus__c != '5') {
				a.IsInvalid__c = false;
			}
		}
	}
}