cmss/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <description>Stav klienta - overit ciselnik a hodnoty NEJSOU DEFINITIVNI</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/DateOfDeletion__c.field-meta.xml
<CustomField>
    <fullName>DateOfDeletion__c</fullName>
    <label>Date Of Deletion</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Account/fields/IsInvalid__c.field-meta.xml
<CustomField>
    <fullName>IsInvalid__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This account has been invalidated due to conslidation. Account is hidden and will be deleted in future.</inlineHelpText>
    <label>Is Invalid</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/LastPortfolioManagerA__c.field-meta.xml
<CustomField>
    <fullName>LastPortfolioManagerA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Datum poslední změny správy stavu A, plněno při změně Portfolio Manager A</description>
    <label>Last Portfolio Manager A</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LastPortfoloManagerAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Account/fields/LastPtfManAChangeDate__c.field-meta.xml
<CustomField>
    <fullName>LastPtfManAChangeDate__c</fullName>
    <description>Datum poslední změny správy stavu A, plněno při změně Portfolio Manager A</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Ptf Man A Change Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Account/fields/PortfolioMngmtA__c.field-meta.xml
<CustomField>
    <fullName>PortfolioMngmtA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Správce stavu A - Jedinečný identifikátor pro entitu Odbytový orgán přidruženou k entitě Klient</description>
    <label>Portfolio Management A</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagedAccountsA</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/CommonSetting__c/CommonSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Various settings for this org</description>
    <label>Common Settings</label>
</CustomObject>

cmss/main/default/objects/CommonSetting__c/fields/AccountDefaultOwner__c.field-meta.xml
<CustomField>
    <fullName>AccountDefaultOwner__c</fullName>
    <description>Id of an user that will own accounts where portfolio manager A cannot be determined.</description>
    <inlineHelpText>Id of an user that will own accounts where portfolio manager A cannot be determined.</inlineHelpText>
    <label>AccountDefaultOwner</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/CommonSetting__c/fields/OwnerForHiddenRecords__c.field-meta.xml
<CustomField>
    <fullName>OwnerForHiddenRecords__c</fullName>
    <inlineHelpText>Id of an user that should be used as an owner for hidden records. This user should not belong to any role.</inlineHelpText>
    <label>Owner For Hidden Records</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cmss/customer-360/classes/AccountTriggerHandlerTest.cls
@IsTest
private class AccountTriggerHandlerTest {
	@IsTest
	static void changeOwnerOfInvalidatedAccountsTest() {
		User u = TestDataFactory.getUser(new User());
		insert u;
		CommonSetting__c setting = CommonSetting__c.getOrgDefaults();
		setting.OwnerForHiddenRecords__c = u.Id;
		insert setting;
		Account a1 = TestDataFactory.getAccount(new Account());
		insert a1;
		Account a2 = TestDataFactory.getAccount(new Account());
		Account a3 = TestDataFactory.getAccount(new Account());

		Test.startTest();
		a1.IsInvalid__c = true;
		a2.IsInvalid__c = true;
		AccountTriggerHandler.setOwner(new List<Account>{ a1, a2, a3 });
		Test.stopTest();

		System.assertEquals(u.Id, a1.OwnerId);
		System.assertEquals(u.Id, a2.OwnerId);
		System.assertNotEquals(u.Id, a3.OwnerId);
	}

	@IsTest
	static void setOwnerTest() {
		Id communityRecordType = [
			SELECT Id
			FROM RecordType
			WHERE SobjectType = 'Account' AND Name = 'Community Account'
		]
		.Id;
		User defaultOwner = TestDataFactory.getUser(new User());
		User portfolioManager = TestDataFactory.getUser(new User());
		insert new List<User>{ defaultOwner, portfolioManager };
		CommonSetting__c setting = CommonSetting__c.getOrgDefaults();
		setting.AccountDefaultOwner__c = defaultOwner.Id;
		insert setting;
		Account a1 = TestDataFactory.getAccount(new Account());
		insert a1;
		Account a2 = TestDataFactory.getAccount(new Account());
		Account a3 = TestDataFactory.getAccount(new Account());
		Account a4 = TestDataFactory.getAccount(new Account(recordTypeId = communityRecordType));

		Test.startTest();
		a1.PortfolioMngmtA__c = portfolioManager.Id;
		a2.PortfolioMngmtA__c = portfolioManager.Id;
		AccountTriggerHandler.setOwner(new List<Account>{ a1, a2, a3, a4 });
		Test.stopTest();

		System.assertEquals(portfolioManager.Id, a1.OwnerId);
		System.assertEquals(portfolioManager.Id, a2.OwnerId);
		System.assertEquals(defaultOwner.Id, a3.OwnerId);
		System.assertEquals(null, a4.OwnerId);
	}

	@IsTest
	static void setLastPortfolioManagerTest() {
		User testPm1 = TestDataFactory.getUser(new User());
		User testPm2 = TestDataFactory.getUser(new User());
		insert new List<User>{ testPm1, testPm2 };

		Account testAccount1 = TestDataFactory.getPersonAccount(new Account(PortfolioMngmtA__c = testPm1.Id));
		Account testAccount2 = TestDataFactory.getPersonAccount(new Account(PortfolioMngmtA__c = testPm1.Id));
		insert new List<Account>{ testAccount1, testAccount2 };

		Account testAccount2Modified = testAccount2.clone(true, true, true, true);
		testAccount2Modified.PortfolioMngmtA__c = testPm2.Id;

		Map<Id, Account> oldAccountsMap = new Map<Id, Account>(new List<Account>{ testAccount1, testAccount2 });
		List<Account> newAccounts = new List<Account>{ testAccount1, testAccount2Modified };
		AccountTriggerHandler.setLastPortfolioManager(oldAccountsMap, newAccounts);

		System.assertEquals(null, testAccount1.LastPortfolioManagerA__c);
		System.assertEquals(null, testAccount1.LastPtfManAChangeDate__c);
		System.assertEquals(testPm1.Id, testAccount2Modified.LastPortfolioManagerA__c);
		System.assertEquals(System.today(), testAccount2Modified.LastPtfManAChangeDate__c);
	}

	@IsTest
	static void invalidateAccountTest() {
		Datetime myDateTime = Datetime.newInstance(2006, 3, 16, 12, 6, 13);
		Account a1 = TestDataFactory.getAccount(new Account(DateOfDeletion__c = myDateTime));
		Account a2 = TestDataFactory.getAccount(new Account(AccountStatus__c = '4'));
		Account a3 = TestDataFactory.getAccount(new Account(AccountStatus__c = '5'));
		Account a4 = TestDataFactory.getAccount(new Account());

		Test.startTest();
		AccountTriggerHandler.invalidateAccount(new List<Account>{ a1, a2, a3, a4 });
		Test.stopTest();

		System.assertEquals(true, a1.IsInvalid__c);
		System.assertEquals(false, a2.IsInvalid__c);
		System.assertEquals(true, a3.IsInvalid__c);
		System.assertEquals(false, a4.IsInvalid__c);
	}

	@IsTest
	static void validateAccountTest() {
		Datetime myDateTime = Datetime.newInstance(2006, 3, 16, 12, 6, 13);
		Account a1 = TestDataFactory.getAccount(
			new Account(DateOfDeletion__c = myDateTime, IsInvalid__c = true, AccountStatus__c = '5')
		);
		Account a2 = TestDataFactory.getAccount(new Account(AccountStatus__c = '3', IsInvalid__c = true));
		Account a3 = TestDataFactory.getAccount(new Account(AccountStatus__c = '5', IsInvalid__c = true));

		Test.startTest();
		AccountTriggerHandler.validateAccount(new List<Account>{ a1, a2, a3 });
		Test.stopTest();

		System.assertEquals(true, a1.IsInvalid__c);
		System.assertEquals(false, a2.IsInvalid__c);
		System.assertEquals(true, a3.IsInvalid__c);
	}
}