cmss/main/default/objects/Account/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/fields/DateOfCreation__c.field-meta.xml
<CustomField>
    <fullName>DateOfCreation__c</fullName>
    <description>Datum vzniku PO</description>
    <label>Date of Creation</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>ContractNumber__c</fullName>
    <label>Contract Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/MailServiceNotification__c.object-meta.xml
<CustomObject>
    <label>MailServiceNotification</label>
    <nameField>
        <label>MailServiceNotification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MailServiceNotifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

cmss/main/default/objects/MailServiceNotification__c/fields/FromEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>FromEmailAddress__c</fullName>
    <label>FromEmailAddress</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/NotSentDueToError__c.field-meta.xml
<CustomField>
    <fullName>NotSentDueToError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NotSentDueToError</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/ToEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>ToEmailAddress__c</fullName>
    <label>ToEmailAddress</label>
    <type>Email</type>
</CustomField>

cmss/integrations/classes/handlers/MailNotificationsHandlerTest.cls
@IsTest
public class MailNotificationsHandlerTest {
	@TestSetup
	static void makeData() {
		RecordType personAccountRecordType = [
			SELECT Id
			FROM RecordType
			WHERE Name = 'Person Account' AND SObjectType = 'Account'
		];

		Account account = new Account();
		account.RecordType = personAccountRecordType;
		account.FirstName = 'Karel';
		account.LastName = 'Novák';
		account.Alias__c = 'KaNov1234';
		insert account;

		ClientZone__c clientZone = new clientZone__c();
		clientZone.ContractNumber__c = '1234';
		clientZone.Account__c = account.Id;
		insert clientZone;
	}

	@IsTest
	static void testHandler() {
		Test.setMock(HttpCalloutMock.class, new MailSOAPServiceHttpMock());
		insert TestDataFactory.getIntegrationSettings();
		Account testAccount = [SELECT FirstName, LastName FROM Account WHERE Alias__c = 'KaNov1234'];

		Opportunity opportunity = new Opportunity();
		opportunity.Name = 'Test Opportunity';
		opportunity.StageName = 'New';
		opportunity.CloseDate = Date.valueOf(System.now().addDays(5));
		opportunity.AccountId = testAccount.Id;
		insert opportunity;

		MailNotificationsHandler testHandler = new MailNotificationsHandler();
		testHandler.setEmailTemplate(new EmailTemplate())
			.setEmailTemplate('UnfinishedContractNotification')
			.setSpecialVariables(new Map<String, String>{ 'DateOfCreation__c' => 'NOW', 'ORG_URL' => 'some url' })
			.setSender('test@sender.invalid')
			.setReceivers(new List<String>{ 'notthismail1@test.com' })
			.setContext('DIGIKZ');

		Test.startTest();
		testHandler.generateNotifications(opportunity, new List<String>{ 'tomail1@test.com', 'tomail2@test.com' });
		testHandler.handleInsertNotifications();
		Test.stopTest();
		List<MailServiceNotification__c> createdNotifications = [
			SELECT Body__c, Subject__c, ToEmailAddress__c, FromEmailAddress__c, NotSentDueToError__c
			FROM MailServiceNotification__c
		];

		System.assertEquals(2, createdNotifications.size());
		System.assert(createdNotifications[0].Subject__c.contains('Novák Karel'), createdNotifications[0].Subject__c);
		System.assertEquals('test@sender.invalid', createdNotifications[0].FromEmailAddress__c);
		System.assert(
			createdNotifications[0].ToEmailAddress__c == 'tomail1@test.com' &&
			createdNotifications[1].ToEmailAddress__c == 'tomail2@test.com'
		);
		System.assertEquals(true, createdNotifications[0].NotSentDueToError__c);
	}
}