cmss/main/default/objects/Account/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>Datum narození</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Account/fields/DataBoxNumber__c.field-meta.xml
<CustomField>
    <fullName>DataBoxNumber__c</fullName>
    <description>Číslo datové schránky</description>
    <label>Data Box Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Pohlaví</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Account/fields/IsPoliticallyExposed__c.field-meta.xml
<CustomField>
    <fullName>IsPoliticallyExposed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Politicky exponovaná osoba</description>
    <label>Is Politically Exposed</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/IsResident__c.field-meta.xml
<CustomField>
    <fullName>IsResident__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Rezident</description>
    <label>Is Resident</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/PersonalIdentificationNr__c.field-meta.xml
<CustomField>
    <fullName>PersonalIdentificationNr__c</fullName>
    <description>Rodné číslo</description>
    <label>Personal Identification Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/fields/PortfolioMngmtA__c.field-meta.xml
<CustomField>
    <fullName>PortfolioMngmtA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Správce stavu A - Jedinečný identifikátor pro entitu Odbytový orgán přidruženou k entitě Klient</description>
    <label>Portfolio Management A</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagedAccountsA</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Account/fields/PortfolioMngmtC__c.field-meta.xml
<CustomField>
    <fullName>PortfolioMngmtC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Správce stavu C - Jedinečný identifikátor pro entitu Odbytový orgán přidruženou k entitě Klient</description>
    <label>Portfolio Management C</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagedAccountsC</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Account/fields/SbId__c.field-meta.xml
<CustomField>
    <fullName>SbId__c</fullName>
    <description>Starbuild ID</description>
    <externalId>true</externalId>
    <label>SB Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <label>Business Account</label>
</RecordType>

cmss/main/default/objects/ContactInformation__c/ContactInformation__c.object-meta.xml
<CustomObject>
    <description>An object to store contact information about clients/prospects/leads/agents/assets</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ContactInformation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CountryPicklist</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/DataBoxNumber__c.field-meta.xml
<CustomField>
    <fullName>DataBoxNumber__c</fullName>
    <description>Číslo datové schránky</description>
    <label>Data Box Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/HouseNumber__c.field-meta.xml
<CustomField>
    <fullName>HouseNumber__c</fullName>
    <description>Č. p. / Č. o.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>House Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>Telefónní číslo</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>PSČ</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Ulice</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/StreetAndHouseNumber__c.field-meta.xml
<CustomField>
    <fullName>StreetAndHouseNumber__c</fullName>
    <description>Combination of Street and House Number</description>
    <formula>IF( NOT( OR( ISBLANK( Street__c ), ISBLANK( HouseNumber__c ) ) ), 
     Street__c + &#39; &#39; + HouseNumber__c,
     IF( NOT( ISBLANK( Street__c )), 
         Street__c,
         IF( NOT( ISBLANK(  HouseNumber__c )),
             HouseNumber__c,
             &#39;&#39;
         )
     )
 )</formula>
    <label>Street and House Number</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typ kontaktní informace (domáci telefon, hlavni telefon, mobil, další telefon, hlavni email, další email, trvalá adresa, kontaktní adresa, přechodní adresa, sídlo, …..) - potřeba ješte dořešit číselník a updatnout hodnoty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>200054</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>20007</fullName>
            </value>
            <value>
                <fullName>20008</fullName>
            </value>
            <value>
                <fullName>200081</fullName>
            </value>
            <value>
                <fullName>200082</fullName>
            </value>
            <value>
                <fullName>200088</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <description>Platnost od</description>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <description>Platnost do</description>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Shows values from fields Phone, Address, Email or Data Box Number based on the picklist value in field Type__c.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/soap/SF_PersonManagementSOAPServiceTest.cls
@IsTest
private class SF_PersonManagementSOAPServiceTest {

	private static String clientPersonNumber = '0123';
	private static String clientPersonalIdentityNumber = '012345';
	private static String prefixTitle = 'prefix';
	private static String suffixTitle = 'suffix';
	private static String clientGlobalId = '0123456789';
	private static Date birthDate = Date.today().addYears(-20);
	private static String gender = 'male';
	private static Boolean isPoliticallyExposed = false;
	private static Boolean isResident = false;

	private static String city = 'Prague';
	private static String country = '16';
	private static String streetName = 'StreetName';
	private static String houseNumber = '123';
	private static String zipCode = '110000';
	private static Date validFrom = Date.today().addMonths(-3);
	private static Date validTo = Date.today();

	private static String phone = '987654321';
	private static String dataBoxA = 'a1b2c3d4';
	private static String dataBoxZ = 'z9y8x7w6';
	private static String email = 'test@mail.invalid';

	@IsTest
	static void createClientPersonTest() {
		User userSpaA = createUser('testUserSpaA', 'spsA');
		User userSpaC = createUser('testUserSpaC', 'spsC');

		SF_PersonManagementSOAPService.CreateClientRequest clientRequest = prepareData(true, true);

		Test.startTest();
		Id accountId = SF_PersonManagementSOAPService.createClient(clientRequest);
		Test.stopTest();

		List<Account> accounts = [SELECT Id, SbId__c, PortfolioMngmtA__c, PortfolioMngmtC__c, RecordTypeId, PersonalIdentificationNr__c, PersonTitle, Suffix, GlobalId__c, Birthdate__c, Gender__c, IsPoliticallyExposed__c, IsResident__c FROM Account WHERE Id = :accountId];
		System.assertEquals(1, accounts.size());
		System.assertEquals(clientPersonNumber, accounts.get(0).SbId__c);
		System.assertEquals(clientPersonalIdentityNumber, accounts.get(0).PersonalIdentificationNr__c);
		System.assertEquals(userSpaA.Id, accounts.get(0).PortfolioMngmtA__c);
		System.assertEquals(userSpaC.Id, accounts.get(0).PortfolioMngmtC__c);
		System.assertEquals(Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(), accounts.get(0).RecordTypeId);
		System.assertEquals(prefixTitle, accounts.get(0).PersonTitle);
		System.assertEquals(suffixTitle, accounts.get(0).Suffix);
		System.assertEquals(clientGlobalId, accounts.get(0).GlobalId__c);
		System.assertEquals(birthDate, accounts.get(0).Birthdate__c);
		System.assertEquals(gender, accounts.get(0).Gender__c);
		System.assertEquals(isPoliticallyExposed, accounts.get(0).IsPoliticallyExposed__c);
		System.assertEquals(isResident, accounts.get(0).IsResident__c);

		List<ContactInformation__c> contactInfos = [SELECT Id, PhoneNumber__c, Email__c, DataBoxNumber__c, PostalCode__c, HouseNumber__c, Street__c, StreetAndHouseNumber__c, Country__c, City__c, Value__c, ValidFrom__c, ValidTo__c, Type__c FROM ContactInformation__c];
		System.assertEquals(5, contactInfos.size());
		for (ContactInformation__c contactInfo : contactInfos) {
			System.debug('LTE conInfo: ' + contactInfo);
			if ('1'.equals(contactInfo.Type__c)) {
				System.assertEquals(city, contactInfo.City__c);
				System.assertEquals(streetName, contactInfo.Street__c);
				System.assertEquals(houseNumber, contactInfo.HouseNumber__c);
				System.assertEquals(zipCode, contactInfo.PostalCode__c);
				System.assertEquals(validFrom, contactInfo.ValidFrom__c);
				System.assertEquals(validTo, contactInfo.ValidTo__c);
				System.assertEquals(country, contactInfo.Country__c);
			} else if ('2'.equals(contactInfo.Type__c)) {
				System.assertEquals(phone, contactInfo.PhoneNumber__c);
			} else if ('3'.equals(contactInfo.Type__c)) {
				System.debug('LTE is type 3: ' + contactInfo);
				if (contactInfo.Email__c != null) {
					System.assertEquals(email, contactInfo.Email__c);
				} else {
					System.assertEquals(dataBoxA, contactInfo.DataBoxNumber__c);
				}
			} else if ('4'.equals(contactInfo.Type__c)) {
				System.assertEquals(dataBoxZ, contactInfo.DataBoxNumber__c);
			}
		}
	}

	@IsTest
	static void createClientBusinessTest() {
		User userSpaA = createUser('testUserSpaA', 'spsA');
		User userSpaC = createUser('testUserSpaC', 'spsC');

		SF_PersonManagementSOAPService.CreateClientRequest clientRequest = prepareData(false, true);

		Test.startTest();
		Id accountId = SF_PersonManagementSOAPService.createClient(clientRequest);
		Test.stopTest();

		List<Account> accounts = [SELECT Id, SbId__c, PortfolioMngmtA__c, PortfolioMngmtC__c, RecordTypeId, PersonalIdentificationNr__c, PersonTitle, Suffix, GlobalId__c, Birthdate__c, Gender__c, IsPoliticallyExposed__c, IsResident__c FROM Account WHERE Id = :accountId];
		System.assertEquals(1, accounts.size());
		System.assertEquals(Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId(), accounts.get(0).RecordTypeId);
	}

	@IsTest
	static void createClientWithEmptyContactInfoTest() {
		User userSpaA = createUser('testUserSpaA', 'spsA');
		User userSpaC = createUser('testUserSpaC', 'spsC');

		SF_PersonManagementSOAPService.CreateClientRequest clientRequest = prepareData(true, false);
		System.debug('LTE request with empty contactInfos: ' + clientRequest);

		Test.startTest();
		Id accountId = SF_PersonManagementSOAPService.createClient(clientRequest);
		Test.stopTest();

		List<Account> accounts = [
				SELECT Id, SbId__c, PortfolioMngmtA__c, PortfolioMngmtC__c, RecordTypeId, PersonalIdentificationNr__c, PersonTitle, Suffix, GlobalId__c, Birthdate__c, Gender__c, IsPoliticallyExposed__c, IsResident__c
				FROM Account
				WHERE Id = :accountId
		];
		System.assertEquals(1, accounts.size());
		System.assertEquals(Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(), accounts.get(0).RecordTypeId);
	}

	private static SF_PersonManagementSOAPService.CreateClientRequest prepareData(Boolean personAccount, Boolean createPersonCommunications) {
		SF_PersonManagementSOAPService.CreateClientRequest request = new SF_PersonManagementSOAPService.CreateClientRequest();
		SF_PersonManagementSOAPService.ClientType clientType = new SF_PersonManagementSOAPService.ClientType();
		request.client = clientType;
		if (createPersonCommunications) {
			request.personCommunications = new List<SF_PersonManagementSOAPService.PersonCommunicationType>();
		}
		request.client.personNumber = clientPersonNumber;
		request.client.personalIdentityNumber = clientPersonalIdentityNumber;
		request.client.name = 'ClientName';
		if (personAccount) {
			request.client.firstName = 'FirstName';
			request.client.lastName = 'LastName';
		} else {
			request.client.name = 'justName';
		}
		request.client.prefixTitle = prefixTitle;
		request.client.suffixTitle = suffixTitle;
		request.client.clientGlobalId = clientGlobalId;
		request.client.birthDate = birthDate;
		request.client.gender = gender;
		request.client.spSa = 'spsA';
		request.client.spSc = 'spsC';
		request.client.isPoliticallyExposed = String.valueOf(isPoliticallyExposed);
		request.client.isCrResident = String.valueOf(isResident);

		if (createPersonCommunications) {
			request.personCommunications.add(createCommType(1, ''));
			request.personCommunications.add(createCommType(2, '987654321'));
			request.personCommunications.add(createCommType(3, 'a1b2c3d4'));
			request.personCommunications.add(createCommType(3, 'test@mail.invalid'));
			request.personCommunications.add(createCommType(4, 'z9y8x7w6'));
		}

		return request;
	}

	private static SF_PersonManagementSOAPService.PersonCommunicationType createCommType(Integer contactType, String contactValue) {
		SF_PersonManagementSOAPService.PersonCommunicationType commType = new SF_PersonManagementSOAPService.PersonCommunicationType();
		commType.extCommunicationId = '0123';
		commType.contactType = String.valueOf(contactType);

		if (contactType == 1) {
			commType.address = createAddressType();
			System.debug('LTE ret commType add: ' + commType);
			return commType;
		}

		commType.contactValue = contactValue;
		System.debug('LTE ret commType: ' + commType);
		return commType;
	}

	private static SF_PersonManagementSOAPService.AddressType createAddressType() {
		SF_PersonManagementSOAPService.AddressType addressType = new SF_PersonManagementSOAPService.AddressType();
		addressType.city = city;
		addressType.country = country;
		addressType.streetName = streetName;
		addressType.houseNumber = houseNumber;
		addressType.zipCode = zipCode;
		addressType.validFrom = validFrom;
		addressType.validTo = validTo;
		return addressType;
	}

	private static User createUser(String userName, String commissionAccountNr) {
		Id standardProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User'].Id;
		System.debug(standardProfileId);
		User user = new User();
		user.LastName = userName;
		user.Username = userName + '@mail.invalid';
		user.Email = userName + '@mail.invalid';
		user.CommissionAccountNr__c = commissionAccountNr;
		user.ProfileId = standardProfileId;
		user.Alias = 'tstU';
		user.TimeZoneSidKey = 'Europe/Prague';
		user.LocaleSidKey = 'cs_CZ';
		user.EmailEncodingKey = 'UTF-8';
		user.LanguageLocaleKey = 'en_US';
		insert user;
		return user;
	}
}