cmss/main/default/objects/Account/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>Datum narození</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Account/fields/DataBoxNumber__c.field-meta.xml
<CustomField>
    <fullName>DataBoxNumber__c</fullName>
    <description>Číslo datové schránky</description>
    <label>Data Box Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Pohlaví</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Account/fields/IsPoliticallyExposed__c.field-meta.xml
<CustomField>
    <fullName>IsPoliticallyExposed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Politicky exponovaná osoba</description>
    <label>Is Politically Exposed</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/IsResident__c.field-meta.xml
<CustomField>
    <fullName>IsResident__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Rezident</description>
    <label>Is Resident</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <description>Státní občanství</description>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/PersonalIdentificationNr__c.field-meta.xml
<CustomField>
    <fullName>PersonalIdentificationNr__c</fullName>
    <description>Rodné číslo</description>
    <label>Personal Identification Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/fields/PortfolioMngmtA__c.field-meta.xml
<CustomField>
    <fullName>PortfolioMngmtA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Správce stavu A - Jedinečný identifikátor pro entitu Odbytový orgán přidruženou k entitě Klient</description>
    <label>Portfolio Management A</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagedAccountsA</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Account/fields/PortfolioMngmtC__c.field-meta.xml
<CustomField>
    <fullName>PortfolioMngmtC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Správce stavu C - Jedinečný identifikátor pro entitu Odbytový orgán přidruženou k entitě Klient</description>
    <label>Portfolio Management C</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagedAccountsC</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Account/fields/SbId__c.field-meta.xml
<CustomField>
    <fullName>SbId__c</fullName>
    <description>Starbuild ID</description>
    <externalId>true</externalId>
    <label>SB Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <label>Business Account</label>
</RecordType>

cmss/main/default/objects/ContactInformation__c/ContactInformation__c.object-meta.xml
<CustomObject>
    <description>An object to store contact information about clients/prospects/leads/agents/assets</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ContactInformation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Reference na klienta, kterému patří kontaktní informace</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>ContactInformation</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CountryPicklist</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/DataBoxNumber__c.field-meta.xml
<CustomField>
    <fullName>DataBoxNumber__c</fullName>
    <description>Číslo datové schránky</description>
    <label>Data Box Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/HouseNumber__c.field-meta.xml
<CustomField>
    <fullName>HouseNumber__c</fullName>
    <description>Č. p. / Č. o.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>House Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>Telefónní číslo</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>PSČ</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Ulice</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>100016</fullName>
            </value>
            <value>
                <fullName>100017</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
            <value>
                <fullName>200026</fullName>
            </value>
            <value>
                <fullName>200027</fullName>
            </value>
            <value>
                <fullName>200030</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200051</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typ kontaktní informace (domáci telefon, hlavni telefon, mobil, další telefon, hlavni email, další email, trvalá adresa, kontaktní adresa, přechodní adresa, sídlo, …..) - potřeba ješte dořešit číselník a updatnout hodnoty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>200054</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>20007</fullName>
            </value>
            <value>
                <fullName>20008</fullName>
            </value>
            <value>
                <fullName>200081</fullName>
            </value>
            <value>
                <fullName>200082</fullName>
            </value>
            <value>
                <fullName>200088</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <description>Platnost od</description>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <description>Platnost do</description>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

cmss/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>-1</fullName>
        <label>Foreigner</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Undefined</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>AE</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>AF</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>AG</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>AI</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>AL</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>AM</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>AO</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>AQ</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>AR</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>AS</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>AT</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>AU</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>AW</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>CZ</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>AZ</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>BB</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>BD</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>BE</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>BF</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>BG</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>BH</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>BI</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>BJ</label>
    </customValue>
    <customValue>
        <fullName>27</fullName>
        <label>BM</label>
    </customValue>
    <customValue>
        <fullName>28</fullName>
        <label>BN</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>BO</label>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

cmss/main/default/globalValueSets/CountryPicklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Undefined</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>AE</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>AF</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>AG</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>AI</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>AL</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>AM</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>AO</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>AQ</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>AR</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>AS</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>AT</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>AU</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>AW</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>CZ</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>AZ</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>BB</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>BD</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>BE</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>BF</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>BG</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>BH</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>BI</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>BJ</label>
    </customValue>
    <customValue>
        <fullName>27</fullName>
        <label>BM</label>
    </customValue>
    <customValue>
        <fullName>28</fullName>
        <label>BN</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>BO</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>BR</label>
    </customValue>
    <masterLabel>CountryPicklist</masterLabel>
</GlobalValueSet>

cmss/integrations/classes/services/ClientService.cls
public with sharing class ClientService {

	private static List<ContactInformation__c> contactInfoList = new List<ContactInformation__c>();

	public static Id createClientAndContactInfos(
		SF_PersonManagementSOAPService.ClientType client,
		List<SF_PersonManagementSOAPService.PersonCommunicationType> personCommunications
	) {
		Id accountId = ClientService.insertAccount(client);
		ClientService.createContactInfos(personCommunications, accountId);
		return accountId;
	}

	public static Id insertAccount(SF_PersonManagementSOAPService.ClientType clientType) {
        Validation.requireAttribute(clientType.spSa, 'spSa');
		if (accountAlreadyExists(clientType.clientGlobalId)) {
			throw new SOAPCommonTypes.BusinessException(202, 'Record already exists: Client - Global ID: ' + clientType.clientGlobalId);
		}
		Account client = new Account(
			SbId__c = clientType.personNumber,
			PersonalIdentificationNr__c = clientType.personalIdentityNumber,
			GlobalId__c = clientType.clientGlobalId,
            Birthdate__c = clientType.birthDate,
            Nationality__c = clientType.citizenship,
			Gender__c = clientType.gender,
            PortfolioMngmtA__c = ReferenceUtility.getUserByCPU(clientType.spSa).Id,
			IsPoliticallyExposed__c = clientType.isPoliticallyExposed,
			IsResident__c = clientType.isCrResident
        );
        if (clientType.spSc != null) {
            client.PortfolioMngmtC__c = ReferenceUtility.getUserByCPU(clientType.spSc).Id;
        }
		if (clientType.lastName != null) {
			client.FirstName = clientType.firstName;
			client.LastName = clientType.lastName;
			client.PersonTitle = clientType.prefixTitle;
			client.Suffix = clientType.suffixTitle;
			client.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
		} else {
			client.Name = clientType.name;
			client.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
		}
		DmlUtility.insertRecord(client);
		Logger.debug('Inserted account', JSON.serialize(client));
		return client.Id;
	}

	public static void createContactInfos(List<SF_PersonManagementSOAPService.PersonCommunicationType> communicationTypes, Id accountId) {
		if (communicationTypes == null || communicationTypes.isEmpty()) {
			return;
		}
		for (SF_PersonManagementSOAPService.PersonCommunicationType commType : communicationTypes) {
			createContactInformation(commType, accountId);
		}
		DmlUtility.insertRecords(contactInfoList);
		Logger.debug('Inserted ContactInformation__c list', JSON.serialize(contactInfoList));
	}

	private static void createContactInformation(SF_PersonManagementSOAPService.PersonCommunicationType commType, Id accountId) {
		ContactInformation__c contactInfo = new ContactInformation__c(
			Account__c = accountId,
			Type__c = commType.contactType,
			SubType__c = commType.contactSubType
		);
		if ('1'.equals(commType.contactType)) {
			contactInfo.City__c = commType.address.city;
			contactInfo.Country__c = commType.address.country;
			contactInfo.Street__c = commType.address.streetName;
			contactInfo.HouseNumber__c = commType.address.houseNumber;
			contactInfo.PostalCode__c = commType.address.zipCode;
			contactInfo.ValidFrom__c = commType.address.validFrom;
			contactInfo.ValidTo__c = commType.address.validTo;
		} else if ('2'.equals(commType.contactType)) {
			contactInfo.PhoneNumber__c = commType.contactValue;
		} else if ('3'.equals(commType.contactType)) {
			if (commType.contactValue.contains('@')) {
				contactInfo.Email__c = commType.contactValue;
			} else {
				contactInfo.DataBoxNumber__c = commType.contactValue;
			}
		} else if ('4'.equals(commType.contactType)) {
			contactInfo.DataBoxNumber__c = commType.contactValue;
		}
		contactInfoList.add(contactInfo);
	}

	private static Boolean accountAlreadyExists(String globalId) {
		for (Account a : [SELECT Id FROM Account WHERE GlobalId__c = :globalId LIMIT 1]) {
			return true;
		}
		return false;
	}
}