cmss/main/default/objects/Account/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>Datum narození</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Account/fields/DataBoxNumber__c.field-meta.xml
<CustomField>
    <fullName>DataBoxNumber__c</fullName>
    <description>Číslo datové schránky</description>
    <label>Data Box Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Pohlaví</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Account/fields/IsPoliticallyExposed__c.field-meta.xml
<CustomField>
    <fullName>IsPoliticallyExposed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Politicky exponovaná osoba</description>
    <label>Is Politically Exposed</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/IsResident__c.field-meta.xml
<CustomField>
    <fullName>IsResident__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Rezident</description>
    <label>Is Resident</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/PersonalIdentificationNr__c.field-meta.xml
<CustomField>
    <fullName>PersonalIdentificationNr__c</fullName>
    <description>Rodné číslo</description>
    <label>Personal Identification Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/fields/SbId__c.field-meta.xml
<CustomField>
    <fullName>SbId__c</fullName>
    <description>Starbuild ID</description>
    <externalId>true</externalId>
    <label>SB Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/ContactInformation__c.object-meta.xml
<CustomObject>
    <description>An object to store contact information about clients/prospects/leads/agents/assets</description>
    <label>Contact Information</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>Contact Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ContactInformation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Reference na klienta, kterému patří kontaktní informace</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Information</relationshipLabel>
    <relationshipName>ContactInformation</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CountryPicklist</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/DataBoxNumber__c.field-meta.xml
<CustomField>
    <fullName>DataBoxNumber__c</fullName>
    <description>Číslo datové schránky</description>
    <label>Data Box Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Fax</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/HouseNumber__c.field-meta.xml
<CustomField>
    <fullName>HouseNumber__c</fullName>
    <description>Č. p. / Č. o.</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>House Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>Telefónní číslo</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>PSČ</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Ulice</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>100016</fullName>
            </value>
            <value>
                <fullName>100017</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
            <value>
                <fullName>200026</fullName>
            </value>
            <value>
                <fullName>200027</fullName>
            </value>
            <value>
                <fullName>200030</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200051</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typ kontaktní informace (domáci telefon, hlavni telefon, mobil, další telefon, hlavni email, další email, trvalá adresa, kontaktní adresa, přechodní adresa, sídlo, …..) - potřeba ješte dořešit číselník a updatnout hodnoty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>100010</fullName>
            </value>
            <value>
                <fullName>100012</fullName>
            </value>
            <value>
                <fullName>100014</fullName>
            </value>
            <value>
                <fullName>100015</fullName>
            </value>
            <value>
                <fullName>20004</fullName>
            </value>
            <value>
                <fullName>200012</fullName>
            </value>
            <value>
                <fullName>200054</fullName>
            </value>
            <value>
                <fullName>20001</fullName>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>20007</fullName>
            </value>
            <value>
                <fullName>20008</fullName>
            </value>
            <value>
                <fullName>200081</fullName>
            </value>
            <value>
                <fullName>200082</fullName>
            </value>
            <value>
                <fullName>200088</fullName>
            </value>
            <value>
                <fullName>200010</fullName>
            </value>
            <value>
                <fullName>200011</fullName>
            </value>
            <value>
                <fullName>200020</fullName>
            </value>
            <value>
                <fullName>200021</fullName>
            </value>
            <value>
                <fullName>200022</fullName>
            </value>
            <value>
                <fullName>200023</fullName>
            </value>
            <value>
                <fullName>200024</fullName>
            </value>
            <value>
                <fullName>200025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <description>Platnost od</description>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ContactInformation__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <description>Platnost do</description>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementA__c/PortfolioManagementA__c.object-meta.xml
<CustomObject>
    <label>Portfolio Management A</label>
    <nameField>
        <displayFormat>PMA-{000000}</displayFormat>
        <label>Portfolio Management A Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Management A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/PortfolioManagementA__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portfolio Management A</relationshipLabel>
    <relationshipName>PortfolioManagementA</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementA__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementA__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementC__c/PortfolioManagementC__c.object-meta.xml
<CustomObject>
    <label>Portfolio Management C</label>
    <nameField>
        <displayFormat>PMC-{000000}</displayFormat>
        <label>Portfolio Management C Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Management C</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/PortfolioManagementC__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portfolio Management C</relationshipLabel>
    <relationshipName>PortfolioManagementC</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/globalValueSets/CountryPicklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Undefined</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>AE</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>AF</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>AG</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>AI</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>AL</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>AM</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>AO</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>AQ</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>AR</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>AS</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>AT</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>AU</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>AW</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>CZ</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>AZ</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>BB</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>BD</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>BE</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>BF</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>BG</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>BH</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>BI</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>BJ</label>
    </customValue>
    <customValue>
        <fullName>27</fullName>
        <label>BM</label>
    </customValue>
    <customValue>
        <fullName>28</fullName>
        <label>BN</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>BO</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>BR</label>
    </customValue>
    <masterLabel>CountryPicklist</masterLabel>
</GlobalValueSet>

cmss/integrations/classes/service/ClientService.cls
public with sharing class ClientService {

	private static List<ContactInformation__c> contactInfoList = new List<ContactInformation__c>();

	public static Id createClientAndContactInfos(SF_PersonManagementSOAPService.CreateClientRequest request) {
		try {
			Logger.info('createClient request data', null, request.toString());
			Id accountId = ClientService.insertAccount(request);
			ClientService.createContactInfos(request.personCommunications, accountId);
			return accountId;
		} catch (Exception exc) {
			Logger.error('SF_PersonManagementSOAPService.createClient ContactInformation insert failed', exc, request.toString());
			throw exc;
		} finally {
			Logger.saveLogs();
		}
	}

	public static Id insertAccount(SF_PersonManagementSOAPService.CreateClientRequest request) {
		Account client = new Account(
				SbId__c = request.client.personNumber,
				PersonalIdentificationNr__c = request.client.personalIdentityNumber,
				PersonTitle = request.client.prefixTitle,
				Suffix = request.client.suffixTitle,
				GlobalId__c = request.client.clientGlobalId,
				Birthdate__c = request.client.birthDate,
				Gender__c = request.client.gender,
//				PortfolioManagementA__r = request.client.spSa,
//				PortfolioManagementC__r = request.client.spSc,
//				loyalty program ??
				IsPoliticallyExposed__c = Boolean.valueOf(request.client.isPoliticallyExposed),
				IsResident__c = Boolean.valueOf(request.client.isCrResident)
		);

		if (request.client.lastName != null) {
			client.FirstName = request.client.firstName;
			client.LastName = request.client.lastName;
		} else {
			client.Name = request.client.name;
		}

		try {
			insert client;
		} catch (Exception ex) {
			Logger.error('SF_PersonManagementSOAPService.createClient Account insert failed', ex, request.toString());
		}
		return client.Id;
	}

	public static void createContactInfos(List<SF_PersonManagementSOAPService.PersonCommunicationType> communicationTypes, Id accountId) {
		for (SF_PersonManagementSOAPService.PersonCommunicationType commType : communicationTypes) {
			createContactInformation(commType, accountId);
		}
		if (!contactInfoList.isEmpty()) {
			try {
				System.debug('contactInfoList toString(): ' + contactInfoList.toString());
				insert contactInfoList;
			} catch (Exception ex) {
				Logger.error('SF_PersonManagementSOAPService.createContactInfos Contact info list insert failed', ex, contactInfoList.toString());
				throw ex;
			}
		}
	}

	private static void createContactInformation(SF_PersonManagementSOAPService.PersonCommunicationType commType, Id accountId) {
		ContactInformation__c contactInfo = new ContactInformation__c(
				Account__c = accountId,
				Type__c = commType.contactType,
				SubType__c = commType.contactSubType,
				Email__c = commType.email,
				PhoneNumber__c = commType.phone,
//				Fax__c = commType.??,
//				DataBoxNumber__c = commType.??,
				City__c = commType.address.city,
				Country__c = commType.address.country,
				Street__c = commType.address.streetName,
				HouseNumber__c = commType.address.houseNumber,
				PostalCode__c = commType.address.zipCode,
				ValidFrom__c = commType.address.validFrom,
				ValidTo__c = commType.address.validTo
		);
		contactInfoList.add(contactInfo);
	}
}