cmss/main/default/objects/Account/fields/ClientZoneAccess__c.field-meta.xml
<CustomField>
    <fullName>ClientZoneAccess__c</fullName>
    <description>Information about KZ access</description>
    <label>Client Zone Access</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Account/fields/ClientZonewithLatestAgreementDate__c.field-meta.xml
<CustomField>
    <fullName>ClientZonewithLatestAgreementDate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Zone with Latest Created Date</label>
    <referenceTo>ClientZone__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/AgreementDate__c.field-meta.xml
<CustomField>
    <fullName>AgreementDate__c</fullName>
    <description>Date when the agreement was made</description>
    <label>Agreement Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Client zone access role</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Limited</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Self-registration</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Self-registration Verified Contacts</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Pre-verified User</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Verified User</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>User Agreement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Full Access</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>No Access</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/integrations/classes/triggerHandlers/ClientZoneTriggerHandlerTest.cls
@IsTest
public class ClientZoneTriggerHandlerTest {
	@IsTest
	static void setClientZoneTest() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone1 = TestDataFactory.getClientZone(
			new ClientZone__c(
				AgreementDate__c = Date.Today().addDays(-10),
				Account__c = account.Id,
				Role__c = 'Limited'
			)
		);
		insert clientZone1;

		ClientZone__c clientZone2 = TestDataFactory.getClientZone(
			new ClientZone__c(AgreementDate__c = Date.Today(), Account__c = account.Id, Role__c = 'No Access')
		);

		Test.startTest();
		insert clientZone2;
		Test.stopTest();
		Account acc = [SELECT Id, ClientZonewithLatestAgreementDate__c, ClientZoneAccess__c FROM Account];
		System.assertEquals(acc.ClientZonewithLatestAgreementDate__c, clientZone2.Id);
		System.assertEquals(acc.ClientZoneAccess__c, clientZone2.Role__c);
	}

	@IsTest
	static void setClientZoneAfterUpdateTest() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone1 = TestDataFactory.getClientZone(
			new ClientZone__c(
				AgreementDate__c = Date.Today().addDays(-10),
				Account__c = account.Id,
				Role__c = 'Limited'
			)
		);
		insert clientZone1;

		ClientZone__c clientZone2 = TestDataFactory.getClientZone(
			new ClientZone__c(AgreementDate__c = Date.Today(), Account__c = account.Id, Role__c = 'No Access')
		);
		insert clientZone2;

		Test.startTest();
		clientZone2.AgreementDate__c = Date.Today().addDays(-15);
		update clientZone2;
		Test.stopTest();
		Account acc = [SELECT Id, ClientZonewithLatestAgreementDate__c, ClientZoneAccess__c FROM Account];
		System.assertEquals(acc.ClientZonewithLatestAgreementDate__c, clientZone1.Id);
		System.assertEquals(acc.ClientZoneAccess__c, clientZone1.Role__c);
	}

	@IsTest
	static void deleteClientZoneTest() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone1 = TestDataFactory.getClientZone(
			new ClientZone__c(
				AgreementDate__c = Date.Today().addDays(-10),
				Account__c = account.Id,
				Role__c = 'Limited'
			)
		);
		insert clientZone1;

		ClientZone__c clientZone2 = TestDataFactory.getClientZone(
			new ClientZone__c(AgreementDate__c = Date.Today(), Account__c = account.Id, Role__c = 'No Access')
		);
		insert clientZone2;

		Test.startTest();
		delete clientZone2;
		Test.stopTest();
		Account acc = [SELECT Id, ClientZonewithLatestAgreementDate__c, ClientZoneAccess__c FROM Account];
		System.assertEquals(acc.ClientZonewithLatestAgreementDate__c, clientZone1.Id);
		System.assertEquals(acc.ClientZoneAccess__c, clientZone1.Role__c);
	}
	@IsTest
	static void deleteAllClientZonesTest() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone1 = TestDataFactory.getClientZone(
			new ClientZone__c(
				AgreementDate__c = Date.Today().addDays(-10),
				Account__c = account.Id,
				Role__c = 'Limited'
			)
		);
		insert clientZone1;

		ClientZone__c clientZone2 = TestDataFactory.getClientZone(
			new ClientZone__c(AgreementDate__c = Date.Today(), Account__c = account.Id, Role__c = 'No Access')
		);
		insert clientZone2;

		Test.startTest();
		delete clientZone1;
		delete clientZone2;
		Test.stopTest();
		Account acc = [SELECT Id, ClientZonewithLatestAgreementDate__c, ClientZoneAccess__c FROM Account];
		System.assertEquals(acc.ClientZonewithLatestAgreementDate__c, null);
		System.assertEquals(acc.ClientZoneAccess__c, null);
	}
}