cmss/main/default/objects/Account/fields/ClientZoneAccess__c.field-meta.xml
<CustomField>
    <fullName>ClientZoneAccess__c</fullName>
    <description>Information about KZ access</description>
    <label>Client Zone Access</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Client zone access role</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Limited</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Self-registration</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Self-registration Verified Contacts</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Pre-verified User</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Verified User</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>User Agreement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Full Access</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>No Access</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/classes/UpdateClientZoneOnAccount_Batch.cls
public class UpdateClientZoneOnAccount_Batch implements Database.Batchable<sObject> {
	/**
	 * Batchable start - do the query.
	 */
	public Database.QueryLocator start(Database.BatchableContext jobId) {
		String queryString =
			'SELECT Id, (' +
			'SELECT Id, CreatedDate, toLabel(Role__c) ' +
			'FROM ClientZones__r ' +
			'ORDER BY CreatedDate DESC ' +
			'LIMIT 1) FROM Account ' +
			'WHERE Id IN (SELECT Account__c FROM ClientZone__c)';

		return Database.getQueryLocator(queryString);
	}

	/**
	 * Batchable execute - process a block of Activities.
	 */
	public void execute(Database.BatchableContext jobId, List<Account> acc) {
		try {
			List<Account> accountsToUpdate = new List<Account>();
			for (Account a : acc) {
				if (a.ClientZones__r.size() == 0) {
					continue;
				}
				a.ClientZoneAccess__c = a.ClientZones__r[0].Role__c;
				accountsToUpdate.add(a);
			}
			if (accountsToUpdate.size() > 0) {
				System.debug('Updating ' + accountsToUpdate.size() + ' accounts.');
				List<Database.SaveResult> results = Database.update(accountsToUpdate, false);
				for (Database.SaveResult result : results) {
					if (!result.isSuccess()) {
						for (Database.Error err : result.getErrors()) {
							Logger.error('Erorr message: ' + err.getMessage() + ' Fields:' + err.getFields());
						}
					}
				}
			}
		} catch (Exception e) {
			Logger.error('An unhandled exception thrown', e);
			throw e;
		} finally {
			Logger.saveLogs();
		}
	}
	/**
	 * Batchable finish - mandatory
	 */
	public void finish(Database.BatchableContext jobId) {
		System.debug('Execution of UpdateClientZoneOnAccount_Batch finished');
	}
}