cmss/main/default/objects/Account/fields/CombinedName__c.field-meta.xml
<CustomField>
    <fullName>CombinedName__c</fullName>
    <description>Combine the important information to be shown in the pinned part of compact layout.</description>
    <formula>IF( IsPersonAccount = true,
	
    IF( ISBLANK( PersonTitle ), &quot;&quot;, PersonTitle &amp; &quot; &quot; ) &amp; FirstName &amp; &quot; &quot; &amp; LastName &amp; BLANKVALUE( Suffix , &quot;&quot; ) &amp; &quot;, RČ: &quot; &amp; PersonalIdentificationNr__c  &amp; &quot;, tel.: &quot; &amp; Phone
		 	,
			 Name &amp; &quot;, IČO: &quot; &amp; CompanyRegistrationNumber__c &amp; &quot;, tel.: &quot; &amp; Phone)</formula>
    <label>Combined Name</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/PortfolioManagementRequest__c.object-meta.xml
<CustomObject>
    <description>Request objekt pro Spravu Stavu.</description>
    <label>Portfolio Management Request</label>
    <nameField>
        <displayFormat>PMR-{0000000000}</displayFormat>
        <label>Portfolio Management Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Management Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Klient</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portfolio Management Requests</relationshipLabel>
    <relationshipName>PortfolioManagementRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/PortfolioManagementRequest__c/fields/BatchID__c.field-meta.xml
<CustomField>
    <fullName>BatchID__c</fullName>
    <description>Unikatni Batch ID manualniho importu csv souboru.</description>
    <label>Batch ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CombinedName__c.field-meta.xml
<CustomField>
    <fullName>CombinedName__c</fullName>
    <formula>IF(ISBLANK(Title), &quot;&quot;, 	Title &amp; &quot; &quot; ) &amp; FirstName &amp; &quot; &quot; &amp; LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Combined Name</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountBase__c</fullName>
    <label>Commission Account Number Base</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/PersonType__c.field-meta.xml
<CustomField>
    <fullName>PersonType__c</fullName>
    <label>Person Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/portfolio-management/classes/AccountRelatedListController.cls
public with sharing class AccountRelatedListController {
	@AuraEnabled(cacheable=true)
	public static AccountInfo getAccounts(
		Id userId,
		String portManType,
		String city,
		String billingPostalCode,
		Integer recordsToShow,
		Integer offset
	) {
		AccountInfo ai = new AccountInfo();
		ai.accountCount = Database.countQuery(
			'SELECT COUNT() ' +
			'FROM Account ' +
			'WHERE PortfolioMngmt' +
			portManType +
			'__c = :userId ' +
			(String.isNotBlank(city) ? 'AND City__c = :city ' : '') +
			(String.isNotBlank(billingPostalCode) ? 'AND BillingPostalCode LIKE :billingPostalCode ' : '')
		);
		ai.accounts = queryAccounts(userId, portManType, city, billingPostalCode, recordsToShow, offset);

		return ai;
	}

	@AuraEnabled(cacheable=true)
	public static Id getUserId(String commAccountBase) {
		User[] users = [SELECT Id FROM User WHERE CommissionAccountBase__c = :commAccountBase];
		return users.size() > 0 ? users[0].Id : null;
	}

	@AuraEnabled(cacheable=true)
	public static Boolean checkPermission(String permissionName) {
		return FeatureManagement.checkPermission(permissionName);
	}

	@AuraEnabled
	public static String createPortManRequestsForUsersClients(
		PortfolioManagementRequest__c pmr,
		Id userId,
		String portManType
	) {
		try {
			PortfolioManagementRequest__c[] pmrs = new List<PortfolioManagementRequest__c>{};
			Integer index = 0;
			String message = Label.RecordsCreated;
			for (Account a : queryAccounts(userId, portManType, null, null, 50000, 0)) {
				if (index == 5000) {
					message = Label.TooManyClients;
					break;
				}
				clonePMR(pmrs, pmr, a.Id);
				index++;
			}
			insert pmrs;
			return message;
		} catch (Exception e) {
			Logger.error('An unhandled exception thrown', e);
			throw e;
		} finally {
			Logger.saveLogs();
		}
	}

	@AuraEnabled
	public static String createPortManRequests(PortfolioManagementRequest__c pmr, String[] accountIds) {
		try {
			PortfolioManagementRequest__c[] pmrs = new List<PortfolioManagementRequest__c>{};
			Integer index = 0;
			String message = Label.RecordsCreated;
			for (Id accId : accountIds) {
				if (index == 5000) {
					message = Label.TooManyClients;
					break;
				}
				clonePMR(pmrs, pmr, accId);
				index++;
			}
			insert pmrs;
			return message;
		} catch (Exception e) {
			Logger.error('An unhandled exception thrown', e);
			throw e;
		} finally {
			Logger.saveLogs();
		}
	}

	private static void clonePMR(PortfolioManagementRequest__c[] pmrs, PortfolioManagementRequest__c pmr, Id accId) {
		PortfolioManagementRequest__c newPMR = pmr.clone(false, true, false, false);
		newPMR.Account__c = accId;
		newPMR.BatchID__c = '1';
		pmrs.add(newPMR);
	}

	private static Account[] queryAccounts(
		Id userId,
		String portManType,
		String city,
		String billingPostalCode,
		Integer recordsToShow,
		Integer offset
	) {
		return Database.query(
			'SELECT CombinedName__c, BillingStreet, City__c, BillingPostalCode, Phone, PersonEmail, PersonType__c ' +
			'FROM Account ' +
			'WHERE PortfolioMngmt' +
			portManType +
			'__c = :userId ' +
			(String.isNotBlank(city) ? 'AND City__c = :city ' : '') +
			(String.isNotBlank(billingPostalCode) ? 'AND BillingPostalCode LIKE :billingPostalCode ' : '') +
			'LIMIT ' +
			recordsToShow +
			' ' +
			'OFFSET ' +
			offset
		);
	}

	public class AccountInfo {
		@AuraEnabled
		public Integer accountCount;
		@AuraEnabled
		public Account[] accounts;
	}
}