cmss/main/default/objects/Account/fields/ConsolidationResult__c.field-meta.xml
<CustomField>
    <fullName>ConsolidationResult__c</fullName>
    <label>Consolidation Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Case/fields/ConsolidationResult__c.field-meta.xml
<CustomField>
    <fullName>ConsolidationResult__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consolidation Result</label>
    <referenceTo>ConsolidationResult__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Case/recordTypes/Client_Consolidation.recordType-meta.xml
<RecordType>
    <fullName>Client_Consolidation</fullName>
    <active>true</active>
    <businessProcess>Client Consolidation</businessProcess>
    <label>Client Consolidation</label>
</RecordType>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ConsolidationResult__c/ConsolidationResult__c.object-meta.xml
<CustomObject>
    <label>Consolidation Result</label>
    <nameField>
        <label>Consolidation Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consolidation Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ConsolidationResult__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consolidation Results</relationshipLabel>
    <relationshipName>ConsolidationResults</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ConsolidationResult__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ConsolidationResult__c/fields/NewGlobalID__c.field-meta.xml
<CustomField>
    <fullName>NewGlobalID__c</fullName>
    <label>New Global ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ConsolidationResult__c/fields/OldGlobalID__c.field-meta.xml
<CustomField>
    <fullName>OldGlobalID__c</fullName>
    <label>Old Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/customer-360/classes/AccountConsolidationUtility.cls
public without sharing class AccountConsolidationUtility {

	public static final String MERGE = '1';
	public static final String PARTIAL_MERGE = '2';
	public static final String SPLIT = '3';
	public static final Id CLIENT_CONSOLIDATION_RT = Case.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Client_Consolidation').recordTypeId;

	private List<ConsolidationResult__c> toBeMerged = new List<ConsolidationResult__c>();
	private List<ConsolidationResult__c> toCreateCases = new List<ConsolidationResult__c>();

	Map<String, Account> oldAccountsByGlobalIdsMap;
	Map<String, Account> newAccountsByGlobalIdsMap;

	List<Case> casesToUpdate = new List<Case>();
	List<Case> opportunitiesToUpdate = new List<Case>();
	List<Case> tasksToUpdate = new List<Case>();
	List<Case> clientZonesToUpdate = new List<Case>();


	public AccountConsolidationUtility(List<ConsolidationResult__c> consolidationResults) {
		for (ConsolidationResult__c consolidationResult : consolidationResults) {
			if (consolidationResult.ActionType__c == MERGE) {
				toBeMerged.add(consolidationResult);
			} else {
				toCreateCases.add(consolidationResult);
			}
		}
		initAccountsMaps(consolidationResults);
	}

	private void initAccountsMaps(List<ConsolidationResult__c> consolidationResults) {
		Set<Id> oldGlobalIds = new Set<Id>();
		Set<Id> newGlobalIds = new Set<Id>();
		for (ConsolidationResult__c result : consolidationResults) {
			oldGlobalIds.add(result.OldGlobalID__c);
			newGlobalIds.add(result.NewGlobalID__c);
		}
		oldAccountsByGlobalIdsMap = mapAccountsByGlobalId([
			SELECT
				Id, GlobalId__c, (SELECT Id, AccountId FROM Cases), (SELECT Id, AccountId FROM Opportunities), (SELECT Id, WhatId FROM Tasks), (SELECT Id, Account__c FROM ClientZones__r)
			FROM Account
			WHERE GlobalId__c IN :oldGlobalIds
		]);
		newAccountsByGlobalIdsMap = mapAccountsByGlobalId([
			SELECT Id, GlobalId__c, (SELECT Id, Account__c FROM ClientZones__r)
			FROM Account
			WHERE GlobalId__c IN :newGlobalIds
		]);
	}

	private Map<String, Account> mapAccountsByGlobalId(List<Account> accounts) {
		Map<String, Account> accountMap = new Map<String, Account>();
		for (Account a : accounts) {
			accountMap.put(a.GlobalId__c, a);
		}
		return accountMap;
	}

	public void process() {
		processMerges();
		processCaseCreations();
		update casesToUpdate;
		update opportunitiesToUpdate;
		update tasksToUpdate;
		update clientZonesToUpdate;
		insert toCreateCases;
	}

	private void processMerges() {
		for (ConsolidationResult__c result : toBeMerged) {
			Account oldAccount = oldAccountsByGlobalIdsMap.get(result.OldGlobalID__c);
			Account newAccount = newAccountsByGlobalIdsMap.get(result.NewGlobalID__c);
			if (!oldAccount.ClientZones__r.isEmpty() && !newAccount.ClientZones__r.isEmpty()) {
				toCreateCases.add(result);
				continue;
			}
			reparentCases(oldAccount.Cases, newAccount.Id);
			reparentOpportunities(oldAccount.Opportunities, newAccount.Id);
			reparentTasks(oldAccount.Tasks, newAccount.Id);
			reparentClientZones(oldAccount.ClientZones__r, newAccount.Id);
		}
	}

	private void processCaseCreations() {
		for (ConsolidationResult__c result : toCreateCases) {
			toCreateCases.add(new Case(
				RecordTypeId = CLIENT_CONSOLIDATION_RT,
				Subject = 'Manual client consolidation',
				AccountId = oldAccountsByGlobalIdsMap.get(result.OldGlobalID__c).Id,
				ConsolidationResult__c = result.Id
			));
		}
	}

	private void reparentCases(List<Case> cases, Id newAccountId) {
		for (Case c : cases) {
			casesToUpdate.add(new Case(
				Id = c.Id,
				AccountId = newAccountId
			));
		}
	}

	private void reparentOpportunities(List<Opportunity> opportunities, Id newAccountId) {
		for (Opportunity o : opportunities) {
			opportunitiesToUpdate.add(new Opportunity(
				Id = o.Id,
				AccountId = newAccountId
			));
		}
	}

	private void reparentTasks(List<Task> tasks, Id newAccountId) {
		for (Task t : tasks) {
			tasksToUpdate.add(new Task(
				Id = t.Id,
				WhatId = newAccountId
			));
		}
	}

	private void reparentClientZones(List<ClientZone__c> clientZones, Id newAccountId) {
		for (ClientZone__c cz : clientZones) {
			clientZonesToUpdate.add(new ClientZone__c(
				Id = cz.Id,
				Account__c = newAccountId
			));
		}
	}
}