cmss/main/default/objects/Account/fields/ConsolidationResult__c.field-meta.xml
<CustomField>
    <fullName>ConsolidationResult__c</fullName>
    <label>Consolidation Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/ConsolidationResult__c/ConsolidationResult__c.object-meta.xml
<CustomObject>
    <label>Consolidation Result</label>
    <nameField>
        <label>Consolidation Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consolidation Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/ConsolidationResult__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ConsolidationResult__c/fields/NewGlobalID__c.field-meta.xml
<CustomField>
    <fullName>NewGlobalID__c</fullName>
    <label>New Global ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ConsolidationResult__c/fields/OldGlobalID__c.field-meta.xml
<CustomField>
    <fullName>OldGlobalID__c</fullName>
    <label>Old Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cmss/customer-360/classes/ConsolidationResultTriggerHandlerTest.cls
@IsTest
private class ConsolidationResultTriggerHandlerTest {

	@IsTest
	static void testBehavior() {
		// logic itself is tested in AccountConsolidationUtilityTest
		Account a1 = TestDataFactory.getAccount(new Account(
			GlobalId__c = 'G1'
		));
		Account a2 = TestDataFactory.getAccount(new Account(
			GlobalId__c = 'G2'
		));
		insert new List<Account>{
			a1, a2
		};
		Test.startTest();
		insert new ConsolidationResult__c(
			ActionType__c = '2',
			OldGlobalID__c = 'G1',
			NewGlobalID__c = 'G2'
		);
		Test.stopTest();
	}

}