cmss/main/default/objects/Account/fields/DateOfCreation__c.field-meta.xml
<CustomField>
    <fullName>DateOfCreation__c</fullName>
    <description>Datum vzniku PO</description>
    <label>Date of Creation</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ContractNumber__c.field-meta.xml
<CustomField>
    <fullName>ContractNumber__c</fullName>
    <label>Contract Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/handlers/SendNotificationHandlerTest.cls
@IsTest
public class SendNotificationHandlerTest {
	public class MailServiceMockImpl implements WebServiceMock {
		public void doInvoke(
			Object stub,
			Object request,
			Map<String, Object> response,
			String endpoint,
			String soapAction,
			String requestName,
			String responseNS,
			String responseName,
			String responseType
		) {
			if (request instanceof MailSOAPService.SendEmailType) {
				response.put('response_x', new MailSOAPService.sendEmailResponse_element());
			}
		}
	}

	@IsTest
	static void testHandler() {
		Test.setMock(WebServiceMock.class, new MailServiceMockImpl());
		RecordType personAccountRecordType = [
			SELECT Id
			FROM RecordType
			WHERE Name = 'Person Account' AND SObjectType = 'Account'
		];

		Account account = new Account();
		account.RecordType = personAccountRecordType;
		account.FirstName = 'Karel';
		account.LastName = 'Novák';
		insert account;

		Opportunity opportunity = new Opportunity();
		opportunity.Name = 'Test Opportunity';
		opportunity.StageName = 'New';
		opportunity.CloseDate = Date.valueOf(System.now().addDays(5));
		opportunity.Account = account;
		insert opportunity;

		ClientZone__c clientZone = new clientZone__c();
		clientZone.ContractNumber__c = '1234';
		clientZone.Account__c = account.Id;
		insert clientZone;

		SendNotificationHandler handlerWithSpecialVars = new SendNotificationHandler(
			opportunity,
			'UnfinishedContractNotification',
			'mail@test.com',
			new Map<String, String>{ 'DateOfCreation__c' => 'NOW', 'ORG_URL' => 'some url' }
		);

		SendNotificationHandler handler = new SendNotificationHandler(
			clientZone,
			'UnsignedContractNotification',
			'mail@test.com'
		);

		Test.startTest();
		handlerWithSpecialVars.handle();
		handler.handle();
		Test.stopTest();

		System.assert(!handlerWithSpecialVars.emailBody.contains('{!'));
		System.assert(handlerWithSpecialVars.emailBody.contains('Karel'));
		System.assert(handlerWithSpecialVars.emailBody.contains('Novák'));
	}
}