cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AmendmentNumber__c.field-meta.xml
<CustomField>
    <fullName>AmendmentNumber__c</fullName>
    <label>Amendment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AmendmentSignDate__c.field-meta.xml
<CustomField>
    <fullName>AmendmentSignDate__c</fullName>
    <label>Amendment Sign Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <description>Global Id of Account__c</description>
    <formula>Account__r.GlobalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Id</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelationTypeNEL__c.field-meta.xml
<CustomField>
    <fullName>RelationTypeNEL__c</fullName>
    <label>Relation Type NEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/integrations/classes/handlers/SignCZContractRelationHandlerTest.cls
@IsTest
private class SignCZContractRelationHandlerTest {

	@IsTest
	static void testBehavior() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		Account otherAccount = TestDataFactory.getAccount(new Account(
			GlobalId__c = 'G2'
		));
		insert otherAccount;
		ClientZone__c clientZone = TestDataFactory.getClientZone(new ClientZone__c(
			Account__c = account.Id
		));
		insert clientZone;
		AccountRelation__c accountRelation1 = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			Account__c = otherAccount.Id,
			AmendmentNumber__c = 5,
			RelationTypeNEL__c = '5'
		));
		AccountRelation__c accountRelation2 = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			Account__c = otherAccount.Id,
			AmendmentNumber__c = 6,
			RelationTypeNEL__c = '5'
		));
		insert new List<AccountRelation__c>{
			accountRelation1, accountRelation2
		};

		SF_PersonManagementSOAPService.SignCZContractRelationsRequestBody request = new SF_PersonManagementSOAPService.SignCZContractRelationsRequestBody();
		request.clientZoneId = clientZone.Id;
		request.amendmentNumber = 6;
		request.signDate = Date.today().addDays(-10);
		request.relatedClientGlobalId = otherAccount.GlobalId__c;

		Test.startTest();
		ClientZoneService.signCZContractRelations(request);
		Test.stopTest();

		accountRelation1 = [SELECT Id, AmendmentSignDate__c FROM AccountRelation__c WHERE Id = :accountRelation1.Id];
		accountRelation2 = [SELECT Id, AmendmentSignDate__c FROM AccountRelation__c WHERE Id = :accountRelation2.Id];
		System.assertEquals(null, accountRelation1.AmendmentSignDate__c);
		System.assertEquals(Date.today().addDays(-10), accountRelation2.AmendmentSignDate__c);
	}

	@IsTest
	static void testErrors() {
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		Account otherAccount = TestDataFactory.getAccount(new Account(
			GlobalId__c = 'G2'
		));
		insert otherAccount;
		ClientZone__c clientZone = TestDataFactory.getClientZone(new ClientZone__c(
			Account__c = account.Id
		));
		insert clientZone;

		SF_PersonManagementSOAPService.SignCZContractRelationsRequestBody request = new SF_PersonManagementSOAPService.SignCZContractRelationsRequestBody();
		request.clientZoneId = clientZone.Id;
		request.amendmentNumber = 6;
		request.signDate = Date.today().addDays(-10);
		request.relatedClientGlobalId = otherAccount.GlobalId__c;

		Test.startTest();
		try {
			ClientZoneService.signCZContractRelations(request);
		} catch (SOAPCommonTypes.BusinessException e) {
			System.assertEquals(205, e.getErrorNumber());
		}
		Test.stopTest();
	}
}