cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <description>Global Id of Account__c</description>
    <formula>Account__r.GlobalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Id</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelationTypeNEL__c.field-meta.xml
<CustomField>
    <fullName>RelationTypeNEL__c</fullName>
    <label>Relation Type NEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/CancelationNotificationSentDate__c.field-meta.xml
<CustomField>
    <fullName>CancelationNotificationSentDate__c</fullName>
    <label>Cancelation Notification Sent Date</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ClosedBy__c.field-meta.xml
<CustomField>
    <fullName>ClosedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that closed the contract about the client zone</description>
    <label>Closed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClientZones</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Client zone access role</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Limited</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Self-registration</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Self-registration Verified Contacts</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Pre-verified User</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Verified User</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>User Agreement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Full Access</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>No Access</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the client zone - active/inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/integrations/classes/asyncApex/DeleteClientZoneNotification_BatchTest.cls
@IsTest
public class DeleteClientZoneNotification_BatchTest {
	@TestSetup
	static void prepareTestData() {
		RecordType personAccountRecordType = [
			SELECT Id
			FROM RecordType
			WHERE Name = 'Person Account' AND SObjectType = 'Account'
		];

		Account account1 = new Account();
		account1.RecordType = personAccountRecordType;
		account1.FirstName = 'Karel';
		account1.LastName = 'Novák';

		Account account2 = new Account();
		account2.RecordType = personAccountRecordType;
		account2.FirstName = 'Mirek';
		account2.LastName = 'Novák';
		insert new List<Account>{ account1, account2 };

		account1.GlobalId__c = account1.Id;
		account2.GlobalId__c = account2.Id;

		update new List<Account>{ account1, account2 };

		ClientZone__c clientZone1 = new ClientZone__c();
		clientZone1.ClosedBy__c = null;
		clientZone1.Role__c = '7';
		clientZone1.Status__c = '1';
		clientZone1.Account__c = account1.Id;
		clientZone1.CreatedDate__c = System.now().addDays(-16);
		clientZone1.CancelationNotificationSentDate__c = null;

		ClientZone__c clientZone2 = new ClientZone__c();
		clientZone2.ClosedBy__c = null;
		clientZone2.Role__c = '7';
		clientZone2.Status__c = '1';
		clientZone2.Account__c = account2.Id;
		clientZone2.CreatedDate__c = System.now().addDays(-50);
		clientZone2.CancelationNotificationSentDate__c = System.now().addDays(-35);

		insert new List<ClientZone__c>{ clientZone1, clientZone2 };

		AccountRelation__c accountRelation = new AccountRelation__c();
		accountRelation.RelationTypeNEL__c = '1';
		accountRelation.Account__c = account1.Id;
		accountRelation.RelatedAccount__c = account2.Id;
		insert accountRelation;
	}

	@isTest
	static void testBatchRun() {
		Test.startTest();
		DeleteClientZoneNotification_Batch batch = new DeleteClientZoneNotification_Batch();
		Id batchId = Database.executeBatch(batch);
		Test.stopTest();
	}
}