cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/integrations/classes/services/ReferenceUtility.cls
public with sharing class ReferenceUtility {

	public static Account getAccountByGlobalId(String globalId) {
		for (Account a : [SELECT Id FROM Account WHERE GlobalId__c = :globalId LIMIT 1]) {
			return a;
		}
		throw new SOAPCommonTypes.BusinessException(201, 'Record not found: Client - Global ID: ' + globalId);
	}

	public static Asset getAssetByNumber(String assetNumber) {
		for (Asset a : [SELECT Id FROM Asset WHERE Name = :assetNumber LIMIT 1]) {
			return a;
		}
		throw new SOAPCommonTypes.BusinessException(201, 'Record not found: Asset - contractNumber: ' + assetNumber);
	}

	public static ClientZone__c getClientZoneById(Id clientZoneId) {
		for (ClientZone__c cz : [SELECT Id FROM ClientZone__c WHERE Id = :clientZoneId LIMIT 1]) {
			return cz;
		}
		throw new SOAPCommonTypes.BusinessException(201, 'Record not found: ClientZone - Id: ' + clientZoneId);
	}
}