cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AccountRole__c.field-meta.xml
<CustomField>
    <fullName>AccountRole__c</fullName>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1501</fullName>
            </value>
            <value>
                <fullName>1502</fullName>
            </value>
            <value>
                <fullName>1503</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>256</fullName>
            </value>
            <value>
                <fullName>512</fullName>
            </value>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>4096</fullName>
            </value>
            <value>
                <fullName>8192</fullName>
            </value>
            <value>
                <fullName>16384</fullName>
            </value>
            <value>
                <fullName>32768</fullName>
            </value>
            <value>
                <fullName>65536</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <description>Global Id of Account__c</description>
    <formula>Account__r.GlobalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Id</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccountRole__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccountRole__c</fullName>
    <label>Related Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1501</fullName>
            </value>
            <value>
                <fullName>1502</fullName>
            </value>
            <value>
                <fullName>1503</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>256</fullName>
            </value>
            <value>
                <fullName>512</fullName>
            </value>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>4096</fullName>
            </value>
            <value>
                <fullName>8192</fullName>
            </value>
            <value>
                <fullName>16384</fullName>
            </value>
            <value>
                <fullName>32768</fullName>
            </value>
            <value>
                <fullName>65536</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <description>Platnost vztahu od</description>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <description>Platnost vztahu do</description>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/util/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {

	private static Integer accountCounter = 0;
	private static Integer opportunityCounter = 0;
	private static Integer assetCounter = 0;
	private static Integer userCounter = 0;

	public static Account getAccount() {
		return getAccount(new Account());
	}

	public static Account getAccount(Account so) {
		Account template = new Account(
			Name = 'Test account ' + ++accountCounter,
			GlobalId__c = 'G' + accountCounter
		);
		copyFields(so, template);
		return template;
    }

    public static Account getDefaultPersonAccount(Account so) {
		so.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Person Account' AND SObjectType = 'Account'].Id;
		return getPersonAccount(so);
	}

    public static Account getPersonAccount(Account so) {
		Account template = new Account(
            FirstName = 'Test firstName ' + ++accountCounter,
			LastName = 'Test lastName ' + ++accountCounter,
            GlobalId__c = 'G' + accountCounter
		);
		copyFields(so, template);
		return template;
	}

	public static AccountRelation__c getAccountRelation(AccountRelation__c so) {
		AccountRelation__c template = new AccountRelation__c(
			AccountRole__c = '1',
			RelatedAccountRole__c = '2',
			ValidFrom__c = Date.today().addDays(-1),
			ValidTo__c = Date.today().addDays(1)
		);
		copyFields(so, template);
		if (template.Account__c == null) {
			Account a = getAccount();
			insert a;
			template.Account__c = a.Id;
		}
		if (template.RelatedAccount__c == null) {
			Account a = getAccount();
			insert a;
			template.RelatedAccount__c = a.Id;
		}
		return template;
	}

	public static ClientZone__c getClientZone(ClientZone__c so) {
		ClientZone__c template = new ClientZone__c(

		);
		copyFields(so, template);
		if (template.Account__c == null) {
			Account a = getAccount();
			insert a;
			template.Account__c = a.Id;
		}
		return template;
	}

	public static Opportunity getOpportunity() {
		return getOpportunity(new Opportunity());
	}

	public static Opportunity getOpportunity(Opportunity so) {
		Opportunity template = new Opportunity(
			Name = 'Opportunity ' + ++opportunityCounter,
			StageName = '1',
			CloseDate = Date.today()
		);
		copyFields(so, template);
		if (template.AccountId == null) {
			Account a = getAccount();
			insert a;
			template.AccountId = a.Id;
		}
		return template;
	}

	public static Task getTask(Task so) {
		Task template = new Task(
			Subject = 'Test task'
		);
		copyFields(so, template);
		if (template.WhatId == null) {
			Account a = getAccount();
			insert a;
			template.WhatId = a.Id;
		}
		return template;
	}

	public static Asset getAsset(Asset so) {
		Asset template = new Asset(
			Name = 'Asset' + ++assetCounter
		);
		copyFields(so, template);
		if (template.AccountId == null) {
			Account a = getAccount();
			insert a;
			template.AccountId = a.Id;
		}
		return template;
	}

	public static Case getCase(Case so) {
		Case template = new Case(
			Subject = 'Case' + ++assetCounter
		);
		copyFields(so, template);
		if (template.AccountId == null) {
			Account a = getAccount();
			insert a;
			template.AccountId = a.Id;
		}
		return template;
	}

	public static User getUser(User so) {
		Id profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
		String username = 'user' + ++userCounter;
		User template = new User(
			LastName = username,
			Username = username + '@mail.invalid',
			Email = username + '@mail.invalid',
			CommissionAccountNr__c = 'CPU' + userCounter,
			ProfileId = profileId,
			Alias = 'tstU',
			TimeZoneSidKey = 'Europe/Prague',
			LocaleSidKey = 'cs_CZ',
			EmailEncodingKey = 'UTF-8',
			LanguageLocaleKey = 'en_US'
		);
		copyFields(so, template);
		return template;
	}

	private static void copyFields(SObject source, SObject destination) {
		if (source == null) {
			return;
		}
		Map<String, Object> soMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(source));
		for (String fieldName : soMap.keySet()) {
			if (fieldName != 'attributes') {
				destination.put(fieldName, source.get(fieldName));
			}
		}
	}
}