cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/InternalConsent__c/InternalConsent__c.object-meta.xml
<CustomObject>
    <label>Internal Consent</label>
    <nameField>
        <displayFormat>MS-{000000}</displayFormat>
        <label>Internal Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Consents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/InternalConsent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Internal Consents</relationshipLabel>
    <relationshipName>InternalConsents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/InternalConsentType__c.field-meta.xml
<CustomField>
    <fullName>InternalConsentType__c</fullName>
    <label>Internal Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/InternalConsentValue__c.field-meta.xml
<CustomField>
    <fullName>InternalConsentValue__c</fullName>
    <label>Internal Consent Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>46</fullName>
            </value>
            <value>
                <fullName>47</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

cmss/main/consent-management/classes/InternalConsentUpsertInvocableTest.cls
@isTest
public with sharing class InternalConsentUpsertInvocableTest {

	@testSetup
	static void testSetup() {
		Account acc = new Account(
			RecordTypeId = RecordTypeUtils.getRecordTypeIdByDeveloperName('PersonAccount', 'Account'),
			FirstName = 'Test',
			LastName = 'Test',
			Phone = '000000000',
			GlobalId__c = 'Test000001'
		);
		insert acc;
	}

	@isTest
	private static void testExecute() {
		List<InternalConsentUpsertInvocable.Request> requestWrapper = new List<InternalConsentUpsertInvocable.Request>();
		InternalConsentUpsertInvocable.Request request = new InternalConsentUpsertInvocable.Request();
		Id accId = [SELECT Id FROM Account LIMIT 1].Id;
		request.inputRecord = new InternalConsent__c();
		request.inputRecord.InternalConsentType__c = '1';
		request.inputRecord.Source__c = '1';
		request.inputRecord.InternalConsentValue__c = '1';
		request.inputRecord.ValidFrom__c = Date.today();
		request.inputRecord.ValidTo__c = Date.today();
		request.inputRecord.Account__c = accId;
		request.inputRecord.ExternalId__c = 'Test';
		requestWrapper.add(request);
		InternalConsentUpsertInvocable.execute(requestWrapper);
		requestWrapper[0].inputRecord.ValidTo__c = Date.today().addDays(3);
		InternalConsentUpsertInvocable.execute(requestWrapper);
		Integer lenOfInternalConsent = [SELECT Id FROM InternalConsent__c].size();
		System.assert(lenOfInternalConsent == 1, 'There must be only one consent as it is upserted based on ExternlId__c.');
	}
}