cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Case/fields/CaseType__c.field-meta.xml
<CustomField>
    <fullName>CaseType__c</fullName>
    <description>Typ podání</description>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Case/fields/ComplainerFirstName__c.field-meta.xml
<CustomField>
    <fullName>ComplainerFirstName__c</fullName>
    <description>Křestní jméno podávajícího</description>
    <inlineHelpText>If account is selected, attribute is filled automatically after save</inlineHelpText>
    <label>Complainer First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Case/fields/ReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>ReceivedDate__c</fullName>
    <description>Datum přijetí podání do ČMSS</description>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Case/fields/ReceivingConfirmationDate__c.field-meta.xml
<CustomField>
    <fullName>ReceivingConfirmationDate__c</fullName>
    <description>Pole obsahující informaci kdy došlo k odeslání potvrzení o přijetí podání podávájícímu</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Receiving Confirmation Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Case/fields/ResponseSentDate__c.field-meta.xml
<CustomField>
    <fullName>ResponseSentDate__c</fullName>
    <description>Pole obsahující informaci kdy došlo k odeslání odpovědi na podání podávájícímu</description>
    <label>Response Sent Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Zdroj případu</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Case/recordTypes/NewClientClaim.recordType-meta.xml
<RecordType>
    <fullName>NewClientClaim</fullName>
    <active>true</active>
    <businessProcess>Client Claim</businessProcess>
    <label>New Client Claim</label>
</RecordType>

cmss/main/default/objects/CaseType__c/CaseType__c.object-meta.xml
<CustomObject>
    <description>Holds different types of cases which are linked to one parent case</description>
    <label>Case Type</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CaseType Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/CaseType__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>vazba na klientské podání</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Types</relationshipLabel>
    <relationshipName>CaseTypes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientClaimEntitlement__c/ClientClaimEntitlement__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores the information necessary to manage milestones and entitlement on Case for Client Claim record type</description>
    <label>Client Claim Entitlement</label>
</CustomObject>

cmss/main/default/objects/ClientClaimEntitlement__c/fields/EntitlementId__c.field-meta.xml
<CustomField>
    <fullName>EntitlementId__c</fullName>
    <description>The Id of the entitlement used for Client Claim cases</description>
    <label>EntitlementId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ClientClaimEntitlement__c/fields/ReceivingConfirmationMilestoneName__c.field-meta.xml
<CustomField>
    <fullName>ReceivingConfirmationMilestoneName__c</fullName>
    <description>Name of the Milestone Type that tracks the filling of the case field ReceivingConfirmationDate__c</description>
    <label>Receiving Confirmation Milestone Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/ClientClaimEntitlement__c/fields/ResponseSentMilestoneName__c.field-meta.xml
<CustomField>
    <fullName>ResponseSentMilestoneName__c</fullName>
    <description>Name of the Milestone Type that tracks the filling of the case field ResponseSent__c. When the field is filled in, it means that the case is resolved and closed.</description>
    <label>Response Sent Milestone Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

cmss/case-management/classes/CaseTriggerHandler_Test.cls
/**
 * Created by a.olexova on 5/21/2020.
 */

@IsTest
private class CaseTriggerHandler_Test {
	static Case c1;
	static Case c2;
	static Case c3;

	static void testSetup() {
		Account acc = new Account(
			RecordTypeId = RecordTypeUtils.getRecordTypeIdByDeveloperName('PersonAccount', 'Account'),
			FirstName = 'Filip',
			LastName = 'Fiala',
			Phone = '111222333',
			GlobalId__c = 'Test123'
		);
		insert acc;
		Entitlement ent = new Entitlement(
			Name = 'Default',
			AccountId = acc.Id,
			SlaProcessId = [SELECT Id FROM SlaProcess WHERE Name = 'claim management' LIMIT 1]
				.Id,
			StartDate = Date.today().addDays(-100),
			EndDate = Date.today().addDays(20000)
		);
		insert ent;
		ClientClaimEntitlement__c csEntitlement = new ClientClaimEntitlement__c(
			SetupOwnerId = UserInfo.getOrganizationId(),
			EntitlementId__c = ent.Id,
			ReceivingConfirmationMilestoneName__c = 'Odeslání potvrzení o přijetí podání',
			ResponseSentMilestoneName__c = 'Odeslání odpovědi na podání'
		);
		insert csEntitlement;

		String clientClaimRTId = RecordTypeUtils.getRecordTypeIdByDeveloperName('NewClientClaim', 'Case');
		c1 = TestDataFactory.getCase(new Case(
			RecordTypeId = clientClaimRTId,
			ReceivedDate__c = Date.today().addDays(-50),
			Origin = '1',
			Source__c = '1',
			AccountId = acc.Id,
			EntitlementId = ent.Id
		));
		c2 = TestDataFactory.getCase(new Case(
			RecordTypeId = clientClaimRTId,
			ReceivedDate__c = Date.today().addDays(-10),
			Origin = '1',
			Source__c = '1',
			AccountId = acc.Id,
			EntitlementId = ent.Id
		));
		c3 = TestDataFactory.getCase(new Case(
			RecordTypeId = clientClaimRTId,
			ReceivedDate__c = Date.today().addDays(-3),
			Origin = '1',
			Source__c = '1',
			AccountId = acc.Id,
			EntitlementId = ent.Id
		));
		insert new List<Case>{
			c1, c2, c3
		};
		CaseType__c ct1 = TestDataFactory.getCaseType(new CaseType__c(Case__c = c1.Id));
		CaseType__c ct2 = TestDataFactory.getCaseType(new CaseType__c(Case__c = c2.Id));
		CaseType__c ct3 = TestDataFactory.getCaseType(new CaseType__c(Case__c = c3.Id));
		insert new List<CaseType__c>{
			ct1, ct2, ct3
		};
	}

	@IsTest
	static void testHandleMilestoneCompletionNoUpdate() {
		User caseManager = TestDataFactory.getUser(new User());
		insert caseManager;
		insert TestDataFactory.getPermissionSetAssignments(caseManager.Id);
		TestDataFactory.defaultCaseOwner = caseManager;
		System.runAs(caseManager) {
			testSetup();
			Set<Id> caseIds = new Set<Id>{
				c1.Id, c2.Id, c3.Id
			};
			Date completionDate = Date.today().addDays(-1);

			c1.ReceivedDate__c = completionDate;
			c1.ComplainerFirstName__c = 'testFirstName';
			c1.ComplainerFirstName__c = 'testLastName';
			c2.Source__c = '2';
			c2.Description = 'descrioption 123';
			c3.Origin = '2';

			Test.startTest();
			update new List<Case>{
				c1, c2, c3
			};
			Test.stopTest();

			List<CaseMilestone> caseMilestones = [
				SELECT Id, CaseId, CompletionDate, MilestoneType.Name, IsCompleted, IsViolated
				FROM CaseMilestone
				WHERE CaseId IN :caseIds
			];
			System.assert(!caseMilestones.isEmpty(), 'Case Milestones not found.');
			for (CaseMilestone cm : caseMilestones) {
				System.assertEquals(false, cm.IsCompleted, 'Case Milestone should NOT be completed yet.');
				System.assertEquals(
					null,
					cm.CompletionDate,
					'Case Milestone Completion Date should be not filled for for Milestone Type: ' + cm.MilestoneType.Name
				);
			}
		}
	}

	@IsTest
	static void testHandleMilestoneCompletionResponse() {
		User caseManager = TestDataFactory.getUser(new User());
		insert caseManager;
		insert TestDataFactory.getPermissionSetAssignments(caseManager.Id);
		TestDataFactory.defaultCaseOwner = caseManager;
		System.runAs(caseManager) {
			testSetup();
			Set<Id> caseIds = new Set<Id>{
				c1.Id, c2.Id, c3.Id
			};
			Date completionDate = Date.today().addDays(-2);

			c1.ResponseSentDate__c = completionDate;
			c2.ResponseSentDate__c = completionDate.addDays(1);
			c3.Description = 'response sent test - no milestone update for c3';

			Test.startTest();
			update new List<Case>{
				c1, c2, c3
			};
			Test.stopTest();

			List<CaseMilestone> caseMilestones = [
				SELECT Id, CaseId, Case.ResponseSentDate__c, CompletionDate, MilestoneType.Name, IsCompleted, IsViolated
				FROM CaseMilestone
				WHERE CaseId IN :caseIds
			];
			System.assert(!caseMilestones.isEmpty(), 'Case Milestones not found.');
			ClientClaimEntitlement__c csEntitlement = ClientClaimEntitlement__c.getOrgDefaults();
			for (CaseMilestone cm : caseMilestones) {
				if (c3.Id == cm.CaseId || csEntitlement.ReceivingConfirmationMilestoneName__c == cm.MilestoneType.Name) {
					System.assertEquals(false, cm.IsCompleted, 'Case Milestone should NOT be completed yet.');
					System.assertEquals(
						null,
						cm.CompletionDate,
						'Case Milestone Completion Date should be not filled for for c3'
					);
				} else if (csEntitlement.ResponseSentMilestoneName__c == cm.MilestoneType.Name) {
					System.assertEquals(true, cm.IsCompleted, 'Case Milestone should be completed.');
					System.assertEquals(
						cm.Case.ResponseSentDate__c,
						Date.newInstance(cm.CompletionDate.year(), cm.CompletionDate.month(), cm.CompletionDate.day()),
						'Case Milestone Completion Date not as expected.'
					);
				}
			}
		}
	}

	@IsTest
	static void testHandleMilestoneCompletionConfirmation() {
		User caseManager = TestDataFactory.getUser(new User());
		insert caseManager;
		insert TestDataFactory.getPermissionSetAssignments(caseManager.Id);
		TestDataFactory.defaultCaseOwner = caseManager;
		System.runAs(caseManager) {
			testSetup();
			Set<Id> caseIds = new Set<Id>{
				c1.Id, c2.Id, c3.Id
			};
			Date completionDate = Date.today().addDays(-2);

			c1.ReceivingConfirmationDate__c = completionDate;
			c2.ReceivingConfirmationDate__c = completionDate.addDays(1);
			c3.Description = 'confirmation sent test - no milestone update for c3';

			Test.startTest();
			update new List<Case>{
				c1, c2, c3
			};
			Test.stopTest();

			List<CaseMilestone> caseMilestones = [
				SELECT
					Id,
					CaseId,
					Case.ReceivingConfirmationDate__c,
					CompletionDate,
					MilestoneType.Name,
					IsCompleted,
					IsViolated
				FROM CaseMilestone
				WHERE CaseId IN :caseIds
			];
			System.assert(!caseMilestones.isEmpty(), 'Case Milestones not found.');
			ClientClaimEntitlement__c csEntitlement = ClientClaimEntitlement__c.getOrgDefaults();
			for (CaseMilestone cm : caseMilestones) {
				if (c3.Id == cm.CaseId || csEntitlement.ResponseSentMilestoneName__c == cm.MilestoneType.Name) {
					System.assertEquals(false, cm.IsCompleted, 'Case Milestone should NOT be completed yet.');
					System.assertEquals(
						null,
						cm.CompletionDate,
						'Case Milestone Completion Date should be not filled for for c3'
					);
				} else if (csEntitlement.ReceivingConfirmationMilestoneName__c == cm.MilestoneType.Name) {
					System.assertEquals(true, cm.IsCompleted, 'Case Milestone should be completed.');
					System.assertEquals(
						cm.Case.ReceivingConfirmationDate__c,
						Date.newInstance(cm.CompletionDate.year(), cm.CompletionDate.month(), cm.CompletionDate.day()),
						'Case Milestone Completion Date not as expected.'
					);
				}
			}
		}
	}

	@IsTest
	static void testHandleMilestoneCompletionConfirmationAndResponse() {
		User caseManager = TestDataFactory.getUser(new User());
		insert caseManager;
		insert TestDataFactory.getPermissionSetAssignments(caseManager.Id);
		TestDataFactory.defaultCaseOwner = caseManager;
		System.runAs(caseManager) {
			testSetup();
			Set<Id> caseIds = new Set<Id>{
				c1.Id, c2.Id, c3.Id
			};
			Date completionDateResponse = Date.today().addDays(-1);
			Date completionDateConfirmation = Date.today().addDays(-2);

			c1.ReceivingConfirmationDate__c = completionDateConfirmation;
			c1.ResponseSentDate__c = completionDateResponse;
			c2.ReceivingConfirmationDate__c = completionDateConfirmation.addDays(1);
			c2.ResponseSentDate__c = completionDateResponse.addDays(1);
			c3.Description = 'confirmation and response sent test - no milestone update for c3';

			Test.startTest();
			update new List<Case>{
				c1, c2, c3
			};
			Test.stopTest();

			List<CaseMilestone> caseMilestones = [
				SELECT
					Id,
					CaseId,
					Case.ResponseSentDate__c,
					Case.ReceivingConfirmationDate__c,
					CompletionDate,
					MilestoneType.Name,
					IsCompleted,
					IsViolated
				FROM CaseMilestone
				WHERE CaseId IN :caseIds
			];
			System.assert(!caseMilestones.isEmpty(), 'Case Milestones not found.');
			ClientClaimEntitlement__c csEntitlement = ClientClaimEntitlement__c.getOrgDefaults();
			for (CaseMilestone cm : caseMilestones) {
				if (c3.Id == cm.CaseId) {
					System.assertEquals(false, cm.IsCompleted, 'Case Milestone should NOT be completed yet.');
					System.assertEquals(
						null,
						cm.CompletionDate,
						'Case Milestone Completion Date should be not filled for for c3'
					);
				} else if (
					csEntitlement.ResponseSentMilestoneName__c == cm.MilestoneType.Name ||
						csEntitlement.ReceivingConfirmationMilestoneName__c == cm.MilestoneType.Name
					) {
					System.assertEquals(true, cm.IsCompleted, 'Case Milestone should be completed');
					if (csEntitlement.ResponseSentMilestoneName__c == cm.MilestoneType.Name) {
						System.assertEquals(
							cm.Case.ResponseSentDate__c,
							Date.newInstance(cm.CompletionDate.year(), cm.CompletionDate.month(), cm.CompletionDate.day()),
							'Case Milestone Completion Date not as expected.'
						);
					} else if (csEntitlement.ReceivingConfirmationMilestoneName__c == cm.MilestoneType.Name) {
						System.assertEquals(
							cm.Case.ReceivingConfirmationDate__c,
							Date.newInstance(cm.CompletionDate.year(), cm.CompletionDate.month(), cm.CompletionDate.day()),
							'Case Milestone Completion Date not as expected.'
						);
					}
				}
			}
		}
	}
}