cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Asset/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>Autor, který vytvořil opportunitu</description>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/CreatedDateTime__c.field-meta.xml
<CustomField>
    <fullName>CreatedDateTime__c</fullName>
    <label>Created Date Time</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/DelegatedDate__c.field-meta.xml
<CustomField>
    <fullName>DelegatedDate__c</fullName>
    <description>Datum, kdy byla OP naposledy delegována</description>
    <label>Delegated Date</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/OriginalAsset__c.field-meta.xml
<CustomField>
    <fullName>OriginalAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asset from which was the opportunity created</description>
    <label>Original Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/integrations/classes/soap/SF_OpportunitySOAPServiceTest.cls
@IsTest
private class SF_OpportunitySOAPServiceTest {

	private static Datetime dtPast = Datetime.now().addDays(-2);
	private static Date dNow = Date.today();
	private static Datetime dtFuture = Datetime.now().addDays(2);

	@IsTest
	static void createOpportunityTest() {
		User user = TestDataFactory.getUser(new User(CommissionAccountNr__c = 'CPU111'));
		insert user;
		Account account = TestDataFactory.getAccount(new Account(GlobalId__c = 'G111'));
		insert account;
		Asset asset = TestDataFactory.getAsset(new Asset(AccountId = account.Id, Name = 'A111'));
		insert asset;

		SF_OpportunitySOAPService.OpportunityRequestType request = new SF_OpportunitySOAPService.OpportunityRequestType();
		SF_OpportunitySOAPService.OpportunityType oppType = new SF_OpportunitySOAPService.OpportunityType();
		oppType.customerGlobalId = 'G111';
		oppType.description = 'description';
		oppType.subject = 'subject';
		oppType.stateReason = '2';
		oppType.result = '2';
		oppType.author = 'author';
		oppType.statusManagerCPU = 'CPU111';
		oppType.validFrom = dtPast;
		oppType.validTo = dtFuture;
		oppType.category = '1';
		oppType.contractNumber = 'A111';
		oppType.delegatedDate = dNow;
		request.requestBody = oppType;

		Test.startTest();
		SF_OpportunitySOAPService.OpportunityResponseType response = SF_OpportunitySOAPService.createOpportunity(request);
		Test.stopTest();

		System.assert(response.isFault == false, JSON.serializePretty(response.fault));
		Opportunity opp = [
			SELECT
				Id, AccountId, Description, Name, StageName, Reason__c, Author__c, OwnerId, CreatedDateTime__c,
				ValidFrom__c, CloseDate, ValidTo__c, Category__c, OriginalAsset__c, DelegatedDate__c
			FROM Opportunity
			WHERE Id = :response.responseBody.opportunityId
		];
	}
}