cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/IntegrationSettings__c/IntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for integration (endpoints, usernames etc)</description>
    <label>Integration Settings</label>
</CustomObject>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/main/common-components/external-links/classes/ExternalLinksController.cls
public with sharing class ExternalLinksController {

	@AuraEnabled(Cacheable=true)
	public static String getClientGlobalId(Id accountOrTaskOrOpportunityId) {
		if (accountOrTaskOrOpportunityId == null) {
			return null;
		}
		if (accountOrTaskOrOpportunityId.getSobjectType() == Account.SObjectType) {
			for (Account a : [SELECT GlobalId__c FROM Account WHERE Id = :accountOrTaskOrOpportunityId]) {
				return a.GlobalId__c;
			}
		}
		if (accountOrTaskOrOpportunityId.getSobjectType() == Task.SObjectType) {
			for (Task t : [SELECT Account.GlobalId__c FROM Task WHERE Id = :accountOrTaskOrOpportunityId]) {
				return t.Account.GlobalId__c;
			}
		}
		if (accountOrTaskOrOpportunityId.getSobjectType() == Opportunity.SObjectType) {
			for (Opportunity o : [SELECT Account.GlobalId__c FROM Opportunity WHERE Id = :accountOrTaskOrOpportunityId]) {
				return o.Account.GlobalId__c;
			}
		}
		return null;
	}

	@AuraEnabled(Cacheable=true)
	public static IntegrationSettings__c getIntegrationSettings() {
		return IntegrationSettings__c.getInstance();
	}
}