cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AccountRole__c.field-meta.xml
<CustomField>
    <fullName>AccountRole__c</fullName>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1501</fullName>
            </value>
            <value>
                <fullName>1502</fullName>
            </value>
            <value>
                <fullName>1503</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>256</fullName>
            </value>
            <value>
                <fullName>512</fullName>
            </value>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>4096</fullName>
            </value>
            <value>
                <fullName>8192</fullName>
            </value>
            <value>
                <fullName>16384</fullName>
            </value>
            <value>
                <fullName>32768</fullName>
            </value>
            <value>
                <fullName>65536</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <description>Global Id of Account__c</description>
    <formula>Account__r.GlobalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Id</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccountRole__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccountRole__c</fullName>
    <label>Related Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1501</fullName>
            </value>
            <value>
                <fullName>1502</fullName>
            </value>
            <value>
                <fullName>1503</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>256</fullName>
            </value>
            <value>
                <fullName>512</fullName>
            </value>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>4096</fullName>
            </value>
            <value>
                <fullName>8192</fullName>
            </value>
            <value>
                <fullName>16384</fullName>
            </value>
            <value>
                <fullName>32768</fullName>
            </value>
            <value>
                <fullName>65536</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <description>Platnost vztahu do</description>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ClosedBy__c.field-meta.xml
<CustomField>
    <fullName>ClosedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that closed the contract about the client zone</description>
    <label>Closed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClientZones</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email of the client that owns the client zone</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id of the client zone used by external systems</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Client zone access role</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Limited</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Self-registration</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Self-registration Verified Contacts</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Pre-verified User</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Verified User</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>User Agreement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Full Access</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>No Access</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username of the client for signing in to his client zone</description>
    <label>Username</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/VerificationPhone__c.field-meta.xml
<CustomField>
    <fullName>VerificationPhone__c</fullName>
    <description>Phone of the client used for confirmation when logging to his client zone</description>
    <label>Verification Phone</label>
    <type>Phone</type>
</CustomField>

cmss/main/default/objects/User/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/integrations/classes/services/ClientZoneServiceTest.cls
@IsTest
private class ClientZoneServiceTest {

	private static String contractNumber = '012345';
	private static String userName = 'user@name.invalid';
	private static String verPhone = '987654321';
	private static String mail = 'user@mail.invalid';
	private static String clientRole = '7';
	private static User closedBy = createUser('testUser');
	private static String globalId = '01234';
	private static Account client = createAccount('TestAcc', globalId);

	private static Date validTo1 = Date.today().addMonths(12);
	private static Date validTo2 = Date.today().addMonths(12);
	private static Date validTo3 = Date.today().addMonths(12);

	@IsTest
	static void createClientZoneTest() {
		List<ClientZone__c> clientZonesEmpty = [SELECT Id FROM ClientZone__c WHERE Account__c = :client.Id LIMIT 1];
		System.assert(clientZonesEmpty.isEmpty());

		List<SF_PersonManagementSOAPService.ClientRelationType> accountRelationTypes = new List<SF_PersonManagementSOAPService.ClientRelationType>();
		accountRelationTypes.add(prepareAccountRelationType(validTo1));
		accountRelationTypes.add(prepareAccountRelationType(validTo2));
		accountRelationTypes.add(prepareAccountRelationType(validTo3));
		SF_PersonManagementSOAPService.CreateClientZoneRequest clientZoneRequest = prepareData(accountRelationTypes);
		System.debug('LTEST prepared req: ' + clientZoneRequest);

		Test.startTest();
		SF_PersonManagementSOAPService.CreateCZContractResponseType czContractResponseType = SF_PersonManagementSOAPService.createClientZone(clientZoneRequest);
		Test.stopTest();

		System.debug('LTEST resp: ' + czContractResponseType);
		List<ClientZone__c> clientZones = [SELECT Id, Name, Username__c, VerificationPhone__c, Email__c, Role__c, ClosedBy__c, ExternalId__c, Account__c FROM ClientZone__c WHERE Account__c = :client.Id LIMIT 1];
		System.assertEquals(1, clientZones.size());
		ClientZone__c clientZone = clientZones.get(0);
		System.assertEquals(clientZone.Name, contractNumber);
		System.assertEquals(clientZone.Username__c, userName);
		System.assertEquals(clientZone.VerificationPhone__c, verPhone);
		System.assertEquals(clientZone.Email__c, mail);
		System.assertEquals(clientZone.Role__c, clientRole);
		System.assertEquals(clientZone.ClosedBy__c, closedBy.Id);
		System.assertEquals(clientZone.ExternalId__c, globalId);
		System.assertEquals(clientZone.Account__c, client.Id);

		List<AccountRelation__c> accountRelations = [
				SELECT Id, Account__c, AccountRole__c, RelatedAccount__c, RelatedAccountRole__c, ValidTo__c
				FROM AccountRelation__c
		];
		System.assertEquals(3, accountRelations.size());
		Integer correctValidToCount = 0;
		for (AccountRelation__c accountRelation : accountRelations) {
			System.assertEquals(client.Id, accountRelation.RelatedAccount__c);
			System.assertEquals(clientRole, accountRelation.RelatedAccountRole__c);
			System.assertEquals(clientRole, accountRelation.AccountRole__c);
			if (validTo1 == accountRelation.ValidTo__c || validTo2 == accountRelation.ValidTo__c || validTo3 == accountRelation.ValidTo__c) {
				correctValidToCount ++;
				System.debug('LTEST validTo upped: ' + correctValidToCount);
			}
		}
		System.assertEquals(3, correctValidToCount);
	}

	private static SF_PersonManagementSOAPService.CreateClientZoneRequest prepareData(List<SF_PersonManagementSOAPService.ClientRelationType> accountRelationTypes) {
		SF_PersonManagementSOAPService.CreateClientZoneRequest request = new SF_PersonManagementSOAPService.CreateClientZoneRequest();
		SF_PersonManagementSOAPService.ClientZoneType clientZoneType = new SF_PersonManagementSOAPService.ClientZoneType();
		request.clientZone = clientZoneType;

		request.clientZone.contractNumber = contractNumber;
		request.clientZone.userName = userName;
		request.clientZone.verificationPhone = verPhone;
		request.clientZone.email = mail;
		request.clientZone.role = clientRole;
		request.clientZone.closedBy = closedBy.Id;
		request.clientZone.globalId = globalId;
		request.clientZone.clientId = client.Id;

		request.accountRelations = accountRelationTypes;

		return request;
	}

	private static SF_PersonManagementSOAPService.ClientRelationType prepareAccountRelationType(Date validTo) {
		SF_PersonManagementSOAPService.ClientRelationType accountRelationType = new SF_PersonManagementSOAPService.ClientRelationType();
		accountRelationType.relatedClientId = client.Id;
		accountRelationType.clientRole = clientRole;
		accountRelationType.validTo = validTo;
		accountRelationType.externalId = generateRandomNumberInString();

		return accountRelationType;
	}

	private static Account createAccount(String lastName, String globalId) {
		Account account = new Account();
		account.LastName = lastName;
		account.GlobalId__c = globalId;
		insert account;
		return account;
	}

	private static User createUser(String userName) {
		Id standardProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User'].Id;
		System.debug(standardProfileId);
		User user = new User();
		user.LastName = userName;
		user.Username = userName + '@mail.invalid';
		user.Email = userName + '@mail.invalid';
		user.ProfileId = standardProfileId;
		user.Alias = 'tstU';
		user.TimeZoneSidKey = 'Europe/Prague';
		user.LocaleSidKey = 'cs_CZ';
		user.EmailEncodingKey = 'UTF-8';
		user.LanguageLocaleKey = 'en_US';
		insert user;
		return user;
	}

	public static String generateRandomNumberInString() {
		return String.valueOf(Math.random()).substringAfterLast('.').left(8);
	}
}