cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <description>Object represents &quot;velké souhlasy&quot;</description>
    <label>Consent</label>
    <nameField>
        <label>Consent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Consent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Klient</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consents</relationshipLabel>
    <relationshipName>Consents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/Consent__c/fields/AllConsent__c.field-meta.xml
<CustomField>
    <fullName>AllConsent__c</fullName>
    <label>All Consent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID souhlasu - externí klíč</description>
    <label>ExternalId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Consent__c/fields/SubstitutePerson__c.field-meta.xml
<CustomField>
    <fullName>SubstitutePerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Substitute Person</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consents (Substitute Person)</relationshipLabel>
    <relationshipName>SubstitutePerson</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/integrations/classes/services/GeneralConsentEnablement.cls
public with sharing class GeneralConsentEnablement {

	private static CommonMessageService.RequestHeader header = new CommonMessageService.RequestHeader();
	private static ConsentCalloutService.ConsentServicePort stub = new ConsentCalloutService.ConsentServicePort();

	@AuraEnabled
	public static String enableGeneralConsents(Consent__c c) {
		try {
			Set<Id> accountIds = new Set<Id>();
			accountIds.add(c.Account__c);
			if (String.isNotBlank(c.SubstitutePerson__c)) {
				accountIds.add(c.SubstitutePerson__c);
			}

			Map<Id, Account> idsToAccounts = new Map<Id, Account>([
				SELECT GlobalId__c
				FROM Account
				WHERE Id IN :accountIds
			]);

			ConsentDataTypesService.EnableGeneralConsentRequestBodyType body = ConsentService.getEnableGeneralWSDefinition(c, idsToAccounts);
			ConsentDataTypesService.EnableGeneralConsentResponseBodyType response = stub.enableGeneralConsent_Http(header, body);
			if (response != null) {
				if (response.consentGuid != null) {
					String finalResponse = 'OK';
					if (c.AllConsent__c == '2') {
						finalResponse = disableGeneralConsents(c, idsToAccounts, response.consentGuid);
					}

					c.ExternalId__c = response.consentGuid;
					upsert c ExternalId__c;

					return finalResponse;
				} else {
					return response.responseMessage;
				}
			}
			return null;
		} catch (Exception e) {
			Logger.error('An unhandled exception thrown', e);
			return e.getMessage();
		} finally {
			Logger.saveLogs();
		}
	}

	private static String disableGeneralConsents(Consent__c c, Map<Id, Account> idsToAccounts, String externalId) {
		ConsentDataTypesService.DisableGeneralConsentRequestBodyType body = ConsentService.getDisableGeneralWSDefinition(c, idsToAccounts, externalId);
		ConsentDataTypesService.DisableGeneralConsentResponseBodyType response = stub.disableGeneralConsent_Http(header, body);
		if (response != null) {
			if (response.success != null && response.success.Successful == true) {
				return 'OK';
			} else {
				return response.responseMessage;
			}
		}
		return null;
	}
}