cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AmendmentNumber__c.field-meta.xml
<CustomField>
    <fullName>AmendmentNumber__c</fullName>
    <label>Amendment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AmendmentSignDate__c.field-meta.xml
<CustomField>
    <fullName>AmendmentSignDate__c</fullName>
    <label>Amendment Sign Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <description>Global Id of Account__c</description>
    <formula>Account__r.GlobalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Id</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelationTypeNEL__c.field-meta.xml
<CustomField>
    <fullName>RelationTypeNEL__c</fullName>
    <label>Relation Type NEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/integrations/classes/handlers/SignCZContractRelationHandler.cls
public with sharing class SignCZContractRelationHandler {

	private String relatedClientGlobalId;
	private ClientZone__c clientZone;
	private Integer amendmentNumber;
	private Date signDate;

	public SignCZContractRelationHandler(SF_PersonManagementSOAPService.SignCZContractRelationsRequestBody request) {
		clientZone = ReferenceUtility.getClientZoneById(request.clientZoneId);
		relatedClientGlobalId = request.relatedClientGlobalId;
		amendmentNumber = request.amendmentNumber;
		signDate = request.signDate;
	}

	public void handle() {
		AccountRelation__c relation = getRelationToBeSigned();
		relation.AmendmentSignDate__c = signDate;
		DmlUtility.updateRecord(relation);
	}

	private AccountRelation__c getRelationToBeSigned() {
		for (AccountRelation__c relation : [
			SELECT Id
			FROM AccountRelation__c
			WHERE RelatedAccount__c = :clientZone.Account__c
			AND Account__r.GlobalId__c = :relatedClientGlobalId
			AND RelationTypeNEL__c = '5'
			AND AmendmentNumber__c = :amendmentNumber
		]) {
			return relation;
		}
		throw new SOAPCommonTypes.BusinessException(205, 'There are no relations to be signed.');
	}
}