cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/InternalConsent__c/InternalConsent__c.object-meta.xml
<CustomObject>
    <label>Internal Consent</label>
    <nameField>
        <displayFormat>MS-{000000}</displayFormat>
        <label>Internal Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Consents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/InternalConsent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Internal Consents</relationshipLabel>
    <relationshipName>InternalConsents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/InternalConsentType__c.field-meta.xml
<CustomField>
    <fullName>InternalConsentType__c</fullName>
    <label>Internal Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/InternalConsentValue__c.field-meta.xml
<CustomField>
    <fullName>InternalConsentValue__c</fullName>
    <label>Internal Consent Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/integrations/classes/services/InternalConsentEnablement.cls
public with sharing class InternalConsentEnablement {
    
    @InvocableMethod
    public static List<String> enableInternalConsents(List<SObject> consents) {
        Set<Id> accountIds = new Set<Id>();
        for (InternalConsent__c c : (List<InternalConsent__c>) consents) {
            accountIds.add(c.Account__c);
        }

        Map<Id, Account> idsToAccounts = new Map<Id, Account>([
            SELECT GlobalId__c
            FROM Account 
            WHERE Id IN :accountIds
        ]);

        List<String> externalIds = new List<String>();
        SOAPCommonTypes.OutboundRequestHeader header = new SOAPCommonTypes.OutboundRequestHeader();
        ConsentWebService.ConsentServicePort stub = new ConsentWebService.ConsentServicePort();
        Integer index = 0;
        for (InternalConsent__c c : (List<InternalConsent__c>) consents) {
            if (index == 100) {
                break;
            } else if (c.InternalConsentValue__c != '1') {
                continue;
            }

            Account client = idsToAccounts.get(c.Account__c);

            ConsentWebServiceDataTypes.EnableInternalConsentRequestBodyType body = new ConsentWebServiceDataTypes.EnableInternalConsentRequestBodyType();
            body.globalId = client == null ? null : client.GlobalId__c;
            body.consentKind = c.InternalConsentType__c;
            body.consentValidFrom = String.valueOfGmt(Datetime.now());
            body.consentSourceId = 'SalesForce';
            ConsentWebServiceDataTypes.EnableInternalConsentResponseBodyType response = stub.enableInternalConsent(body, header);
            Logger.debug('EnableInternalConsent response', JSON.serialize(response));
            if (response != null) {
                externalIds.add(response.consentGuid);
            }

            index++;
        }

        Logger.saveLogs();

        return externalIds;
    }
}