cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/IntegrationSettings__c/IntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for integration (endpoints, usernames etc)</description>
    <label>Integration Settings</label>
</CustomObject>

cmss/main/default/objects/IntegrationSettings__c/fields/NELBaseUrl__c.field-meta.xml
<CustomField>
    <fullName>NELBaseUrl__c</fullName>
    <description>URL to NEL website</description>
    <label>NEL Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/main/common-components/external-links/classes/ExternalLinksControllerTest.cls
@IsTest
private class ExternalLinksControllerTest {

    @IsTest
	static void testGetNelBaseUrl() {
        IntegrationSettings__c settings = IntegrationSettings__c.getInstance();
        settings.NELBaseUrl__c = 'https://some.url';
        upsert settings;

        Test.startTest();
        IntegrationSettings__c urls = ExternalLinksController.getIntegrationSettings();
        Test.stopTest();

        System.assertEquals(settings.NELBaseUrl__c, urls.NELBaseUrl__c);
	}

    @IsTest
    static void testGetClientGlobalId() {
        Account a = TestDataFactory.getAccount(new Account(GlobalId__c = 'GLID'));
        Account another = TestDataFactory.getAccount(new Account());
        insert new List<Account> {a, another};
        Task t = TestDataFactory.getTask(new Task(WhatId = a.Id));
        insert t;
        Opportunity o = TestDataFactory.getOpportunity(new Opportunity(AccountId = a.Id));
        insert o;

        Test.startTest();
        String globalIdFromAccount = ExternalLinksController.getClientGlobalId(a.Id);
        String globalIdFromTask = ExternalLinksController.getClientGlobalId(t.Id);
        String globalIdFromOpportunity = ExternalLinksController.getClientGlobalId(o.Id);
        Test.stopTest();

        System.assertEquals(a.GlobalId__c, globalIdFromAccount);
        System.assertEquals(a.GlobalId__c, globalIdFromTask);
        System.assertEquals(a.GlobalId__c, globalIdFromOpportunity);
    }

    @IsTest
    static void testGetObjectApiName() {
        Account account = TestDataFactory.getAccount(new Account());
        insert account;
        Opportunity opportunity = TestDataFactory.getOpportunity(new Opportunity());
        insert opportunity;

        String accountApiName = ExternalLinksController.getObjectApiName(account.Id);
        String opportunityApiName = ExternalLinksController.getObjectApiName(opportunity.Id);

        System.assertEquals(accountApiName, 'Account');
        System.assertEquals(opportunityApiName, 'Opportunity');
    }
}