cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <description>Global Id of Account__c</description>
    <formula>Account__r.GlobalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Id</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedGlobalId__c.field-meta.xml
<CustomField>
    <fullName>RelatedGlobalId__c</fullName>
    <description>Global Id of RelatedAccount</description>
    <formula>RelatedAccount__r.GlobalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related Global Id</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelationTypeNEL__c.field-meta.xml
<CustomField>
    <fullName>RelationTypeNEL__c</fullName>
    <label>Relation Type NEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Asset/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10001</fullName>
            </value>
            <value>
                <fullName>10002</fullName>
            </value>
            <value>
                <fullName>10003</fullName>
            </value>
            <value>
                <fullName>10004</fullName>
            </value>
            <value>
                <fullName>10005</fullName>
            </value>
            <value>
                <fullName>10006</fullName>
            </value>
            <value>
                <fullName>10007</fullName>
            </value>
            <value>
                <fullName>10008</fullName>
            </value>
            <value>
                <fullName>10009</fullName>
            </value>
            <value>
                <fullName>10010</fullName>
            </value>
            <value>
                <fullName>10011</fullName>
            </value>
            <value>
                <fullName>10012</fullName>
            </value>
            <value>
                <fullName>10013</fullName>
            </value>
            <value>
                <fullName>11001</fullName>
            </value>
            <value>
                <fullName>11002</fullName>
            </value>
            <value>
                <fullName>11003</fullName>
            </value>
            <value>
                <fullName>11004</fullName>
            </value>
            <value>
                <fullName>11005</fullName>
            </value>
            <value>
                <fullName>11006</fullName>
            </value>
            <value>
                <fullName>11007</fullName>
            </value>
            <value>
                <fullName>11008</fullName>
            </value>
            <value>
                <fullName>11009</fullName>
            </value>
            <value>
                <fullName>11010</fullName>
            </value>
            <value>
                <fullName>11011</fullName>
            </value>
            <value>
                <fullName>11012</fullName>
            </value>
            <value>
                <fullName>11013</fullName>
            </value>
            <value>
                <fullName>11014</fullName>
            </value>
            <value>
                <fullName>11015</fullName>
            </value>
            <value>
                <fullName>11016</fullName>
            </value>
            <value>
                <fullName>11017</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/CancelationNotificationSentDate__c.field-meta.xml
<CustomField>
    <fullName>CancelationNotificationSentDate__c</fullName>
    <label>Cancelation Notification Sent Date</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ClosedBy__c.field-meta.xml
<CustomField>
    <fullName>ClosedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that closed the contract about the client zone</description>
    <label>Closed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClientZones</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Client zone access role</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Limited</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Self-registration</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Self-registration Verified Contacts</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Pre-verified User</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Verified User</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>User Agreement</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Full Access</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>No Access</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the client zone - active/inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/integrations/classes/asyncApex/DeleteClientZoneNotification_Batch.cls
public without sharing class DeleteClientZoneNotification_Batch implements Database.Batchable<sObject>, Schedulable {
	private DateTime actualDate;
	private final String CANCELATION_TEMPLATE_NAME = 'ClientZoneCancelationNotification';

	public DeleteClientZoneNotification_Batch() {
		this.actualDate = System.today();
	}

	public void execute(SchedulableContext sc) {
		Database.executeBatch(this);
	}

	public List<ClientZone__c> start(Database.BatchableContext jobId) {
		return (List<ClientZone__c>) [
			SELECT
				Id,
				ClosedBy__c,
				Role__c,
				Status__c,
				Account__c,
				Account__r.PersonEmail,
				CreatedDate__c,
				CancelationNotificationSentDate__c
			FROM ClientZone__c
			WHERE ClosedBy__c = NULL AND (Role__c = '7' OR Role__c = '9') AND Status__c = '1'
		];
	}

	public void execute(Database.BatchableContext jobId, List<ClientZone__c> recordList) {
		Map<Id, ClientZone__c> accountToClientZoneMap = new Map<Id, ClientZone__c>();
		for (ClientZone__c record : recordList) {
			accountToClientZoneMap.put(record.Account__c, record);
		}

		Map<Id, AccountRelation__c> validAccountRelations = getAssociatedAccounts(accountToClientZoneMap.keySet());
		Map<Id, Task> associatedTasks = getAssociatedTasks(accountToClientZoneMap.keySet());
		List<ClientZone__c> clientZonesToUpdate = new List<ClientZone__c>();

		for (ClientZone__c clientZone : accountToClientZoneMap.values()) {
			if (
				!validAccountRelations.containsKey(clientZone.Account__c) ||
				!associatedTasks.containsKey(clientZone.Account__c)
			) {
				if (
					clientZone.CreatedDate__c < actualDate.addDays(-15) &&
					clientZone.CancelationNotificationSentDate__c == null
				) {
					SendNotificationHandler handler = new SendNotificationHandler(
						clientZone,
						CANCELATION_TEMPLATE_NAME,
						clientZone.Account__r.PersonEmail
					);
					handler.handle();
					clientZone.CancelationNotificationSentDate__c = System.now();
					clientZonesToUpdate.add(clientZone);
				} else if (
					clientZone.CancelationNotificationSentDate__c != null &&
					clientZone.CancelationNotificationSentDate__c < actualDate.addDays(-15) &&
					clientZone.CancelationNotificationSentDate__c > actualDate.addDays(-75)
				) {
					CancelCZContractHandler handler = new CancelCZContractHandler(clientZone);
					handler.handle();
				}
			}
		}
		update clientZonesToUpdate;
	}

	private Map<Id, AccountRelation__c> getAssociatedAccounts(Set<Id> accountIds) {
		List<AccountRelation__c> accountRelations = [
			SELECT GlobalId__c, RelatedGlobalId__c, RelationTypeNEL__c
			FROM AccountRelation__c
			WHERE (GlobalId__c IN :accountIds OR RelatedGlobalId__c IN :accountIds) AND RelationTypeNEL__c = '1'
		];

		Map<Id, AccountRelation__c> associatedAccounts = new Map<Id, AccountRelation__c>();
		Map<Id, Id> otherToOriginalAccountIds = new Map<Id, Id>();

		for (AccountRelation__c relation : accountRelations) {
			if (relation.GlobalId__c != null && accountIds.contains(relation.GlobalId__c)) {
				associatedAccounts.put(relation.GlobalId__c, relation);
				if (relation.RelatedGlobalId__c != null) {
					otherToOriginalAccountIds.put(relation.RelatedGlobalId__c, relation.GlobalId__c);
				}
			}
			if (relation.RelatedGlobalId__c != null && accountIds.contains(relation.RelatedGlobalId__c)) {
				associatedAccounts.put(relation.RelatedGlobalId__c, relation);
				if (relation.GlobalId__c != null) {
					otherToOriginalAccountIds.put(relation.GlobalId__c, relation.RelatedGlobalId__c);
				}
			}
		}

		List<Asset> otherAccountAssets = [
			SELECT Id, AccountId, Active__c
			FROM Asset
			WHERE AccountId IN :otherToOriginalAccountIds.keySet() AND Active__c = TRUE
		];

		Map<Id, AccountRelation__c> validAssociatedAccounts = new Map<Id, AccountRelation__c>();
		for (Asset asset : otherAccountAssets) {
			Id originalAccountId = otherToOriginalAccountIds.get(asset.AccountId);
			validAssociatedAccounts.put(originalAccountId, associatedAccounts.get(originalAccountId));
		}

		return validAssociatedAccounts;
	}

	private Map<Id, Task> getAssociatedTasks(Set<Id> accountIds) {
		List<Task> tasks = [SELECT WhoId, Type FROM Task WHERE WhoId IN :accountIds AND Type = '5'];

		Map<Id, Task> associatedTasks = new Map<Id, Task>();
		for (Task task : tasks) {
			associatedTasks.put(task.WhoId, task);
		}
		return associatedTasks;
	}

	public void finish(Database.BatchableContext jobId) {
	}
}