cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ClosedBy__c.field-meta.xml
<CustomField>
    <fullName>ClosedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that closed the contract about the client zone</description>
    <label>Closed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClientZones</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email of the client that owns the client zone</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the client zone - active/inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username of the client for signing in to his client zone</description>
    <label>Username</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/VerificationPhone__c.field-meta.xml
<CustomField>
    <fullName>VerificationPhone__c</fullName>
    <description>Phone of the client used for confirmation when logging to his client zone</description>
    <label>Verification Phone</label>
    <type>Phone</type>
</CustomField>

cmss/integrations/classes/services/ClientZoneService.cls
public with sharing class ClientZoneService {

	public static SF_PersonManagementSOAPService.CreateCZContractResponseType createClientZone(String globalId, SF_PersonManagementSOAPService.CreateClientZoneRequest request) {
		if (globalId == null) {
			throw new ClientZoneServiceException('GlobalId in request was null!');
		}
		List<Account> accounts = [SELECT Id FROM Account WHERE GlobalId__c = :globalId LIMIT 1];
		if (accounts.isEmpty()) {
			throw new ClientZoneServiceException('No client found for globalId specified in request!');
		}
		SF_PersonManagementSOAPService.CreateCZContractResponseType response = new SF_PersonManagementSOAPService.CreateCZContractResponseType();

		List<ClientZone__c> clientZones = [SELECT Id FROM ClientZone__c WHERE Account__c = :accounts.get(0).Id AND Status__c = ''];
		if (clientZones.isEmpty()) {
			response.clientZoneId = insertClientZone(request.clientZone);
			response.isSuccess = true;
		} else {
			updateClientZone(clientZones.get(0), request.clientZone);
			response.isSuccess = true;
		}
		if (request.accountRelations != null || !request.accountRelations.isEmpty()) {
			createAccountRelations(request.accountRelations);
		}

		return response;
	}

	private static Id insertClientZone(SF_PersonManagementSOAPService.ClientZoneType clientZoneRequest) {
		ClientZone__c clientZone = new ClientZone__c(
				Name = clientZoneRequest.contractNumber,
				VerificationPhone__c = clientZoneRequest.verificationPhone,
				Username__c = clientZoneRequest.userName,
				ClosedBy__c = clientZoneRequest.closedBy
		);
		insert clientZone;
		return clientZone.Id;
	}

	private static void updateClientZone(ClientZone__c clientZone, SF_PersonManagementSOAPService.ClientZoneType clientZoneRequest) {
		clientZone.ClosedBy__c = clientZoneRequest.closedBy;
		clientZone.Name = clientZoneRequest.contractNumber;
		clientZone.Username__c = clientZoneRequest.userName;
		clientZone.VerificationPhone__c = clientZoneRequest.verificationPhone;
		clientZone.Email__c = clientZoneRequest.email;
		update clientZone;
	}

	private static void createAccountRelations(List<SF_PersonManagementSOAPService.AccountRelationType> accountRelations) {
		for (SF_PersonManagementSOAPService.AccountRelationType accountRelation : accountRelations) {

		}
	}

	private class ClientZoneServiceException extends Exception {
	}
}