cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <description>Object represents &quot;velké souhlasy&quot;</description>
    <label>Consent</label>
    <nameField>
        <label>Consent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Consent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Klient</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consents</relationshipLabel>
    <relationshipName>Consents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/consent-management/objects/Consent__c/fields/AgentCPU__c.field-meta.xml
<CustomField>
    <fullName>AgentCPU__c</fullName>
    <label>Agent CPU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Consent__c/fields/EmailConsent__c.field-meta.xml
<CustomField>
    <fullName>EmailConsent__c</fullName>
    <description>Souhlas e-mail</description>
    <label>EmailConsent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/EntityConsent__c.field-meta.xml
<CustomField>
    <fullName>EntityConsent__c</fullName>
    <description>Entita souhlasu</description>
    <label>EntityConsent</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ČMSS</fullName>
            </value>
            <value>
                <fullName>ČSOB</fullName>
            </value>
            <value>
                <fullName>ČSOB Asset</fullName>
            </value>
            <value>
                <fullName>ČSOB Group (ALL)</fullName>
            </value>
            <value>
                <fullName>ČSOB leasing</fullName>
            </value>
            <value>
                <fullName>ČSOB penzijní společnost</fullName>
            </value>
            <value>
                <fullName>ČSOB pojišťovna</fullName>
            </value>
            <value>
                <fullName>Hypoteční banka</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Patria Finance</fullName>
            </value>
            <value>
                <fullName>Síť</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID souhlasu - externí klíč</description>
    <label>ExternalId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Consent__c/fields/PhoneConsent__c.field-meta.xml
<CustomField>
    <fullName>PhoneConsent__c</fullName>
    <description>Souhals telefon</description>
    <label>PhoneConsent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/PortalConsent__c.field-meta.xml
<CustomField>
    <fullName>PortalConsent__c</fullName>
    <description>Souhlas el. portál</description>
    <label>Portal Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/PostConsent__c.field-meta.xml
<CustomField>
    <fullName>PostConsent__c</fullName>
    <description>Souhlas pošta</description>
    <label>Post Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/SMSConsent__c.field-meta.xml
<CustomField>
    <fullName>SMSConsent__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Souhlas SMS</description>
    <label>SMSConsent</label>
    <type>Checkbox</type>
</CustomField>

cmss/integrations/objects/ConsentChannelIdsMapping__mdt/ConsentChannelIdsMapping__mdt.object-meta.xml
<CustomObject>
    <description>Maps channel field names on Consent__c to channel Ids from CMSS</description>
    <fields>
        <fullName>ConsentChannelId__c</fullName>
        <label>Consent Channel Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>Consent field API Name</description>
        <label>Field Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ForTestingOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>For Testing Only</label>
        <type>Checkbox</type>
    </fields>
    <label>Consent Channel Ids Mapping</label>
    <pluralLabel>Consent Channel Ids Mappings</pluralLabel>
</CustomObject>

cmss/main/default/objects/InternalConsent__c/InternalConsent__c.object-meta.xml
<CustomObject>
    <label>Internal Consent</label>
    <nameField>
        <displayFormat>MS-{000000}</displayFormat>
        <label>Internal Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Consents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/InternalConsent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Internal Consents</relationshipLabel>
    <relationshipName>InternalConsents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/InternalConsentType__c.field-meta.xml
<CustomField>
    <fullName>InternalConsentType__c</fullName>
    <label>Internal Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/InternalConsent__c/fields/InternalConsentValue__c.field-meta.xml
<CustomField>
    <fullName>InternalConsentValue__c</fullName>
    <label>Internal Consent Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/integrations/classes/services/ConsentService.cls
public with sharing class ConsentService {

    private static final List<String> CHANNEL_FIELD_NAMES = new List<String>{
        'EmailConsent__c', 'PhoneConsent__c', 'PortalConsent__c', 'PostConsent__c', 'SMSConsent__c'
    };

    public static void processChannelConsent(List<SObject> newConsents, Map<Id, SObject> oldIdsToConsents) {
        List<List<ConsentDataTypesService.EnableChannelConsentRequestBodyType>> listOfEnableChannelRequestLists = 
            new List<List<ConsentDataTypesService.EnableChannelConsentRequestBodyType>>
        {
            new List<ConsentDataTypesService.EnableChannelConsentRequestBodyType>(),
            new List<ConsentDataTypesService.EnableChannelConsentRequestBodyType>(),
            new List<ConsentDataTypesService.EnableChannelConsentRequestBodyType>(),
            new List<ConsentDataTypesService.EnableChannelConsentRequestBodyType>()
        };
        List<List<ConsentDataTypesService.DisableChannelConsentRequestBodyType>> listOfDisableChannelRequestLists = 
            new List<List<ConsentDataTypesService.DisableChannelConsentRequestBodyType>>
        {
            new List<ConsentDataTypesService.DisableChannelConsentRequestBodyType>(),
            new List<ConsentDataTypesService.DisableChannelConsentRequestBodyType>(),
            new List<ConsentDataTypesService.DisableChannelConsentRequestBodyType>(),
            new List<ConsentDataTypesService.DisableChannelConsentRequestBodyType>()
        };

        Map<String, String> fieldNamesToConsentChannelIds = new Map<String, String>();
        ConsentChannelIdsMapping__mdt[] consentChannelIdsMapping = [
            SELECT FieldName__c, ConsentChannelId__c 
            FROM ConsentChannelIdsMapping__mdt
            WHERE ForTestingOnly__c = :Test.isRunningTest()
        ];
        for (ConsentChannelIdsMapping__mdt ccim : consentChannelIdsMapping) {
            fieldNamesToConsentChannelIds.put(ccim.FieldName__c, ccim.ConsentChannelId__c);
        }

        Set<Id> accountIds = new Set<Id>();
        for (Consent__c c : (List<Consent__c>) newConsents) {
            Validation.requireAttribute(c.Account__c, 'Account__c');
            accountIds.add(c.Account__c);
        }
        Map<Id, Account> idsToAccounts = new Map<Id, Account>([
            SELECT GlobalId__c
            FROM Account 
            WHERE Id IN :accountIds
        ]);

        if (oldIdsToConsents != null) {
            for (Integer i = 0; i < newConsents.size(); i++) {
                SObject oldConsent = oldIdsToConsents.get((Id) newConsents[i].get('Id'));

                Validation.requireAttribute(newConsents[i].get('EntityConsent__c'), 'EntityConsent__c');
                Account acc = idsToAccounts.get((Id) newConsents[i].get('Account__c'));
                Validation.requireAttribute(acc, 'Account');
                Validation.requireAttribute(acc.GlobalId__c, 'GlobalId__c');

                for (String fieldName : CHANNEL_FIELD_NAMES) {
                    String consentChannelId = fieldNamesToConsentChannelIds.get(fieldName);
                    
                    if (newConsents[i].get(fieldName) != oldConsent.get(fieldName) && newConsents[i].get(fieldName) == '1') {
                        listOfEnableChannelRequestLists[i/50].add(getEnableChannelWSDefinition((Consent__c) newConsents[i], consentChannelId, acc.GlobalId__c));
                    } else if (newConsents[i].get(fieldName) != oldConsent.get(fieldName) && newConsents[i].get(fieldName) == '2') {
                        listOfDisableChannelRequestLists[i/50].add(getDisableChannelWSDefinition((Consent__c) newConsents[i], consentChannelId, acc.GlobalId__c));
                    }
                }
            }
        } else {
            for (Integer i = 0; i < newConsents.size(); i++) {
                Validation.requireAttribute(newConsents[i].get('EntityConsent__c'), 'EntityConsent__c');
                Account acc = idsToAccounts.get((Id) newConsents[i].get('Account__c'));
                Validation.requireAttribute(acc, 'Account');
                Validation.requireAttribute(acc.GlobalId__c, 'GlobalId__c');

                for (String fieldName : CHANNEL_FIELD_NAMES) {
                    String consentChannelId = fieldNamesToConsentChannelIds.get(fieldName);
                    
                    if (newConsents[i].get(fieldName) == '1') {
                        listOfEnableChannelRequestLists[i/50].add(getEnableChannelWSDefinition((Consent__c) newConsents[i], consentChannelId, acc.GlobalId__c));
                    } else if (newConsents[i].get(fieldName) == '2') {
                        listOfDisableChannelRequestLists[i/50].add(getDisableChannelWSDefinition((Consent__c) newConsents[i], consentChannelId, acc.GlobalId__c));
                    }
                }
            }
        }

        for (Integer i = 0; i < 4; i++) {
            if (listOfEnableChannelRequestLists[i].size() > 0 || listOfDisableChannelRequestLists[i].size() > 0) {
                makeChannelConsentCallout(
                    JSON.serialize(listOfEnableChannelRequestLists[i]), JSON.serialize(listOfDisableChannelRequestLists[i])
                );
            }
        }
    }

    public static void processInternalConsent(List<InternalConsent__c> newConsents, Map<Id, InternalConsent__c> oldIdsToConsents) {
        List<List<ConsentDataTypesService.EnableInternalConsentRequestBodyType>> listOfEnableConsentRequestLists = 
            new List<List<ConsentDataTypesService.EnableInternalConsentRequestBodyType>>
        {
            new List<ConsentDataTypesService.EnableInternalConsentRequestBodyType>(),
            new List<ConsentDataTypesService.EnableInternalConsentRequestBodyType>(),
            new List<ConsentDataTypesService.EnableInternalConsentRequestBodyType>(),
            new List<ConsentDataTypesService.EnableInternalConsentRequestBodyType>()
        };
        List<List<ConsentDataTypesService.DisableInternalConsentRequestBodyType>> listOfDisableConsentRequestLists = 
            new List<List<ConsentDataTypesService.DisableInternalConsentRequestBodyType>>
        {
            new List<ConsentDataTypesService.DisableInternalConsentRequestBodyType>(),
            new List<ConsentDataTypesService.DisableInternalConsentRequestBodyType>(),
            new List<ConsentDataTypesService.DisableInternalConsentRequestBodyType>(),
            new List<ConsentDataTypesService.DisableInternalConsentRequestBodyType>()
        };

        Set<Id> accountIds = new Set<Id>();
        for (InternalConsent__c c : newConsents) {
            accountIds.add(c.Account__c);
        }

        Map<Id, Account> idsToAccounts = new Map<Id, Account>([
            SELECT GlobalId__c
            FROM Account 
            WHERE Id IN :accountIds
        ]);

        for (Integer i = 0; i < newConsents.size(); i++) {
            InternalConsent__c oldConsent = oldIdsToConsents.get(newConsents[i].Id);

            if (newConsents[i].InternalConsentValue__c != oldConsent.InternalConsentValue__c && newConsents[i].InternalConsentValue__c == '1') {
                Validation.requireAttribute(newConsents[i].InternalConsentType__c, 'InternalConsentType__c');
                listOfEnableConsentRequestLists[i/50].add(getEnableInternalConsentWSDefinition(newConsents[i], idsToAccounts.get(newConsents[i].Account__c)));
            } else if (newConsents[i].InternalConsentValue__c != oldConsent.InternalConsentValue__c && newConsents[i].InternalConsentValue__c == '2') {
                Validation.requireAttribute(newConsents[i].ExternalId__c, 'ExternalId__c');
                listOfDisableConsentRequestLists[i/50].add(getDisableInternalConsentWSDefinition(newConsents[i]));
            }
        }

        for (Integer i = 0; i < 4; i++) {
            if (listOfEnableConsentRequestLists[i].size() > 0 || listOfDisableConsentRequestLists[i].size() > 0) {
                makeInternalConsentCallout(
                    JSON.serialize(listOfEnableConsentRequestLists[i]), JSON.serialize(listOfDisableConsentRequestLists[i])
                );
            }
        }
    }

    @future(callout=true)
    private static void makeChannelConsentCallout(String enableConsentRequestsJSON, String disableConsentRequestsJSON) {

        List<ConsentDataTypesService.EnableChannelConsentRequestBodyType> enableConsentRequests = 
            (List<ConsentDataTypesService.EnableChannelConsentRequestBodyType>) JSON.deserialize(
                enableConsentRequestsJSON, List<ConsentDataTypesService.EnableChannelConsentRequestBodyType>.class
        );
        List<ConsentDataTypesService.DisableChannelConsentRequestBodyType> disableConsentRequests = 
            (List<ConsentDataTypesService.DisableChannelConsentRequestBodyType>) JSON.deserialize(
                disableConsentRequestsJSON, List<ConsentDataTypesService.DisableChannelConsentRequestBodyType>.class
        );

        CommonMessageService.RequestHeader header = new CommonMessageService.RequestHeader();
        ConsentCalloutService.ConsentServicePort stub = new ConsentCalloutService.ConsentServicePort();
        for (ConsentDataTypesService.EnableChannelConsentRequestBodyType body : enableConsentRequests) {
            ConsentDataTypesService.EnableChannelConsentResponseBodyType response = stub.enableChannelConsent_Http(header, body);
        }
        for (ConsentDataTypesService.DisableChannelConsentRequestBodyType body : disableConsentRequests) {
            ConsentDataTypesService.DisableChannelConsentResponseBodyType response = stub.disableChannelConsent_Http(header, body);
        }

        Logger.saveLogs();
    }

    @future(callout=true)
    private static void makeInternalConsentCallout(String enableConsentRequestsJSON, String disableConsentRequestsJSON) {

        List<ConsentDataTypesService.EnableInternalConsentRequestBodyType> enableConsentRequests = 
            (List<ConsentDataTypesService.EnableInternalConsentRequestBodyType>) JSON.deserialize(
                enableConsentRequestsJSON, List<ConsentDataTypesService.EnableInternalConsentRequestBodyType>.class
        );
        List<ConsentDataTypesService.DisableInternalConsentRequestBodyType> disableConsentRequests = 
            (List<ConsentDataTypesService.DisableInternalConsentRequestBodyType>) JSON.deserialize(
                disableConsentRequestsJSON, List<ConsentDataTypesService.DisableInternalConsentRequestBodyType>.class
        );

        CommonMessageService.RequestHeader header = new CommonMessageService.RequestHeader();
        ConsentCalloutService.ConsentServicePort stub = new ConsentCalloutService.ConsentServicePort();
        for (ConsentDataTypesService.EnableInternalConsentRequestBodyType body : enableConsentRequests) {
            ConsentDataTypesService.EnableInternalConsentResponseBodyType response = stub.enableInternalConsent_Http(header, body);
        }
        for (ConsentDataTypesService.DisableInternalConsentRequestBodyType body : disableConsentRequests) {
            ConsentDataTypesService.DisableInternalConsentResponseBodyType response = stub.disableInternalConsent_Http(header, body);
        }

        Logger.saveLogs();
    }

    private static ConsentDataTypesService.EnableChannelConsentRequestBodyType getEnableChannelWSDefinition(Consent__c c, String consentChannelId, String clientId) {
        ConsentDataTypesService.EnableChannelConsentRequestBodyType body = new ConsentDataTypesService.EnableChannelConsentRequestBodyType();
        body.consentEntityId = c.EntityConsent__c;
        body.consentChannelId = consentChannelId;
        body.globalId = clientId;
        body.consentSourceId = '20';
        body.validFrom = Datetime.now().formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');
        body.validFrom = body.validFrom.substring(0, body.validFrom.length() - 2) + ':00'; 
        body.agentCPU = c.AgentCPU__c;
        return body;
    }
    
    private static ConsentDataTypesService.DisableChannelConsentRequestBodyType getDisableChannelWSDefinition(Consent__c c, String consentChannelId, String clientId) {
        ConsentDataTypesService.DisableChannelConsentRequestBodyType body = new ConsentDataTypesService.DisableChannelConsentRequestBodyType();
        body.consentEntityId = c.EntityConsent__c;
        body.consentChannelId = consentChannelId;
        body.globalId = clientId;
        body.consentSourceId = '20';
        body.validFrom = Datetime.now().formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');
        body.validFrom = body.validFrom.substring(0, body.validFrom.length() - 2) + ':00'; 
        body.agentCPU = c.AgentCPU__c;
        return body;
    }

    public static ConsentDataTypesService.EnableInternalConsentRequestBodyType getEnableInternalConsentWSDefinition(InternalConsent__c c, Account client) {
        ConsentDataTypesService.EnableInternalConsentRequestBodyType body = new ConsentDataTypesService.EnableInternalConsentRequestBodyType();
        if (client != null) {
            body.globalId = client.GlobalId__c;
        }
        body.consentKind = c.InternalConsentType__c;
        body.consentValidFrom = Datetime.now().formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');
        body.consentValidFrom = body.consentValidFrom.substring(0, body.consentValidFrom.length() - 2) + ':00'; 
        body.consentSourceId = '20';
        return body;
    }
    
    private static ConsentDataTypesService.DisableInternalConsentRequestBodyType getDisableInternalConsentWSDefinition(InternalConsent__c c) {
        ConsentDataTypesService.DisableInternalConsentRequestBodyType body = new ConsentDataTypesService.DisableInternalConsentRequestBodyType();
        body.consentCrmGuid = c.ExternalId__c;
        body.consentSourceId = '20';
        return body;
    }
}