cmss/main/default/objects/Account/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Global Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/AccountRelation__c/AccountRelation__c.object-meta.xml
<CustomObject>
    <label>Account Relation</label>
    <nameField>
        <label>Account Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/AccountRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations</relationshipLabel>
    <relationshipName>AccountRelations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AccountRole__c.field-meta.xml
<CustomField>
    <fullName>AccountRole__c</fullName>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1501</fullName>
            </value>
            <value>
                <fullName>1502</fullName>
            </value>
            <value>
                <fullName>1503</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>256</fullName>
            </value>
            <value>
                <fullName>512</fullName>
            </value>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>4096</fullName>
            </value>
            <value>
                <fullName>8192</fullName>
            </value>
            <value>
                <fullName>16384</fullName>
            </value>
            <value>
                <fullName>32768</fullName>
            </value>
            <value>
                <fullName>65536</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/AmendmentNumber__c.field-meta.xml
<CustomField>
    <fullName>AmendmentNumber__c</fullName>
    <label>Amendment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/GlobalId__c.field-meta.xml
<CustomField>
    <fullName>GlobalId__c</fullName>
    <description>Global Id of Account__c</description>
    <formula>Account__r.GlobalId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Id</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Navázaná osoba</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relations (Related Account)</relationshipLabel>
    <relationshipName>AccountRelations_Related</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/RelatedAccountRole__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccountRole__c</fullName>
    <label>Related Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1501</fullName>
            </value>
            <value>
                <fullName>1502</fullName>
            </value>
            <value>
                <fullName>1503</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>256</fullName>
            </value>
            <value>
                <fullName>512</fullName>
            </value>
            <value>
                <fullName>1024</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>4096</fullName>
            </value>
            <value>
                <fullName>8192</fullName>
            </value>
            <value>
                <fullName>16384</fullName>
            </value>
            <value>
                <fullName>32768</fullName>
            </value>
            <value>
                <fullName>65536</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <description>Platnost vztahu od</description>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/AccountRelation__c/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <description>Platnost vztahu do</description>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/ClientZone__c.object-meta.xml
<CustomObject>
    <description>An object specifying access of a client to his or her client zone</description>
    <label>Client Zone</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Client Zone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/ClientZone__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Reference to client that is owner of the client zone</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Zones</relationshipLabel>
    <relationshipName>ClientZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ClosedBy__c.field-meta.xml
<CustomField>
    <fullName>ClosedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that closed the contract about the client zone</description>
    <label>Closed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClientZones</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id of the client zone used by external systems</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/main/default/objects/ClientZone__c/fields/NumberOfAnnexes__c.field-meta.xml
<CustomField>
    <fullName>NumberOfAnnexes__c</fullName>
    <description>Number of annexes related to the contract about the client zone</description>
    <label>Number of Annexes</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cmss/integrations/classes/handlers/ChangeCZContractRelationsHandlerTest.cls
@IsTest
private class ChangeCZContractRelationsHandlerTest {

	@IsTest
	static void testBehavior() {
		User user = TestDataFactory.getUser(new User(
			CommissionAccountNr__c = 'CPU1'
		));
		insert user;
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone = TestDataFactory.getClientZone(new ClientZone__c(
			NumberOfAnnexes__c = 5,
			Account__c = account.Id
		));
		insert clientZone;
		AccountRelation__c accountRelation = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			ExternalId__c = 'ABCD1'
		));
		insert accountRelation;

		Account anotherAccount1 = TestDataFactory.getAccount(new Account());
		Account anotherAccount2 = TestDataFactory.getAccount(new Account());
		insert new List<Account>{
			anotherAccount1, anotherAccount2
		};

		SF_PersonManagementSOAPService.ChangeCZContractRelationsRequestBody request = new SF_PersonManagementSOAPService.ChangeCZContractRelationsRequestBody();
		request.clientZoneId = clientZone.ExternalId__c;
		request.closedByCPU = user.CommissionAccountNr__c;
		request.amendmentNumber = 6;
		SF_PersonManagementSOAPService.ClientRelationType relation1 = new SF_PersonManagementSOAPService.ClientRelationType();
		relation1.validTo = Date.today().addDays(10);
		relation1.externalId = 'ABCD1';
		relation1.role = 'R1';
		SF_PersonManagementSOAPService.ClientRelationType relation2 = new SF_PersonManagementSOAPService.ClientRelationType();
		relation2.relatedClientId = anotherAccount2.GlobalId__c;
		relation2.validTo = Date.today().addDays(10);
		relation2.externalId = 'ABCD2';
		request.relations = new List<SF_PersonManagementSOAPService.ClientRelationType>{
			relation1, relation2
		};

		Test.startTest();
		ClientZoneService.changeCZContractRelations(request);
		Test.stopTest();

		clientZone = [SELECT Id, ClosedBy__c, NumberOfAnnexes__c FROM ClientZone__c WHERE Id = :clientZone.Id];
		System.assertEquals(user.Id, clientZone.ClosedBy__c);
		System.assertEquals(6, clientZone.NumberOfAnnexes__c);

		accountRelation = [SELECT Id, Account__c, AccountRole__c, RelatedAccount__c, RelatedAccountRole__c, AmendmentNumber__c, ValidFrom__c, ValidTo__c FROM AccountRelation__c WHERE ExternalId__c = 'ABCD1'];
		System.assertEquals(account.Id, accountRelation.RelatedAccount__c);
		System.assertEquals('1502', accountRelation.RelatedAccountRole__c);
		System.assertEquals('1501', accountRelation.AccountRole__c);
		System.assertEquals(6, accountRelation.AmendmentNumber__c);
		System.assertEquals(Date.today(), accountRelation.ValidFrom__c);
		System.assertEquals(Date.today().addDays(10), accountRelation.ValidTo__c);

		accountRelation = [SELECT Id, Account__c, AccountRole__c, RelatedAccount__c, RelatedAccountRole__c, AmendmentNumber__c, ValidFrom__c, ValidTo__c FROM AccountRelation__c WHERE ExternalId__c = 'ABCD2'];
		System.assertEquals(account.Id, accountRelation.RelatedAccount__c);
		System.assertEquals('1502', accountRelation.RelatedAccountRole__c);
		System.assertEquals(anotherAccount2.Id, accountRelation.Account__c);
		System.assertEquals('1501', accountRelation.AccountRole__c);
		System.assertEquals(6, accountRelation.AmendmentNumber__c);
		System.assertEquals(Date.today(), accountRelation.ValidFrom__c);
		System.assertEquals(Date.today().addDays(10), accountRelation.ValidTo__c);
	}

	@IsTest
	static void testErrors() {
		User user = TestDataFactory.getUser(new User(
			CommissionAccountNr__c = 'CPU1'
		));
		insert user;
		Account account = TestDataFactory.getAccount(new Account());
		insert account;
		ClientZone__c clientZone = TestDataFactory.getClientZone(new ClientZone__c(
			NumberOfAnnexes__c = 5,
			Account__c = account.Id
		));
		insert clientZone;
		AccountRelation__c accountRelation = TestDataFactory.getAccountRelation(new AccountRelation__c(
			RelatedAccount__c = account.Id,
			ExternalId__c = 'ABCD1'
		));
		insert accountRelation;

		Account anotherAccount1 = TestDataFactory.getAccount(new Account());
		insert anotherAccount1;

		SF_PersonManagementSOAPService.ChangeCZContractRelationsRequestBody request = new SF_PersonManagementSOAPService.ChangeCZContractRelationsRequestBody();
		request.clientZoneId = clientZone.Id;
		request.closedByCPU = user.CommissionAccountNr__c;
		request.amendmentNumber = 6;
		SF_PersonManagementSOAPService.ClientRelationType relation1 = new SF_PersonManagementSOAPService.ClientRelationType();
		relation1.relatedClientId = anotherAccount1.GlobalId__c;
		relation1.validTo = Date.today().addDays(10);
		relation1.externalId = 'ABCD1';
		relation1.role = 'R1';
		request.relations = new List<SF_PersonManagementSOAPService.ClientRelationType>{
			relation1
		};

		try {
			request.clientZoneId = account.Id;
			ClientZoneService.changeCZContractRelations(request);
		} catch (SOAPCommonTypes.BusinessException e) {
			System.assertEquals(201, e.getErrorNumber());
			request.clientZoneId = clientZone.Id;
		}
		try {
			request.closedByCPU = 'invalidCPU';
			ClientZoneService.changeCZContractRelations(request);
		} catch (SOAPCommonTypes.BusinessException e) {
			System.assertEquals(201, e.getErrorNumber());
			request.closedByCPU = user.CommissionAccountNr__c;
		}
		try {
			relation1.relatedClientId = 'invalidGlobalID';
			ClientZoneService.changeCZContractRelations(request);
		} catch (SOAPCommonTypes.BusinessException e) {
			System.assertEquals(201, e.getErrorNumber());
			relation1.relatedClientId = anotherAccount1.GlobalId__c;
		}

		try {
			request.clientZoneId = null;
			ClientZoneService.changeCZContractRelations(request);
		} catch (SOAPCommonTypes.BusinessException e) {
			System.assertEquals(101, e.getErrorNumber());
			request.clientZoneId = clientZone.Id;
		}
		try {
			request.amendmentNumber = null;
			ClientZoneService.changeCZContractRelations(request);
		} catch (SOAPCommonTypes.BusinessException e) {
			System.assertEquals(101, e.getErrorNumber());
			request.amendmentNumber = 6;
		}
	}

}