cmss/main/default/objects/Account/fields/HasEmail__c.field-meta.xml
<CustomField>
    <fullName>HasEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Email</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/Account/fields/HasPhone__c.field-meta.xml
<CustomField>
    <fullName>HasPhone__c</fullName>
    <formula>IF(ISBLANK(Phone), false, true)</formula>
    <label>Has Phone</label>
    <type>Checkbox</type>
</CustomField>

cmss/customer-360/classes/AccountMassUpdateBatch.cls
global class AccountMassUpdateBatch implements Database.Batchable<sObject> 
{
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = 'SELECT Id, Phone, PersonEmail, HasPhone__c, HasEmail__c FROM Account WHERE HasPhone__c = null OR HasEmail__c = null';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Account> scope) 
    {
        for (Account acc : scope) {
            acc.HasPhone__c = false;
            acc.HasEmail__c = false;
        }
        update scope;
    }
    global void finish(Database.BatchableContext BC) {
    }
}