cmss/main/default/objects/Account/fields/IsInvalid__c.field-meta.xml
<CustomField>
    <fullName>IsInvalid__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This account has been invalidated due to conslidation. Account is hidden and will be deleted in future.</inlineHelpText>
    <label>Is Invalid</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/CommonSetting__c/CommonSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Various settings for this org</description>
    <label>Common Settings</label>
</CustomObject>

cmss/main/default/objects/CommonSetting__c/fields/OwnerForHiddenRecords__c.field-meta.xml
<CustomField>
    <fullName>OwnerForHiddenRecords__c</fullName>
    <inlineHelpText>Id of an user that should be used as an owner for hidden records. This user should not belong to any role.</inlineHelpText>
    <label>Owner For Hidden Records</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cmss/customer-360/classes/AccountConsolidationUtilityTest.cls
@IsTest
private class AccountConsolidationUtilityTest {

	@IsTest
	static void changeOwnerOfInvalidatedAccountsTest() {
		User u = TestDataFactory.getUser(new User());
		insert u;
		CommonSetting__c setting = CommonSetting__c.getOrgDefaults();
		setting.OwnerForHiddenRecords__c = u.Id;
		insert setting;
		Account a1 = TestDataFactory.getAccount(new Account());
		insert a1;
		Account a2 = TestDataFactory.getAccount(new Account());
		Account a3 = TestDataFactory.getAccount(new Account());

		Test.startTest();
		a1.IsInvalid__c = true;
		a2.IsInvalid__c = true;
		AccountConsolidationUtility.changeOwnerOfInvalidatedAccounts(new List<Account>{
			a1, a2, a3
		});
		Test.stopTest();

		System.assertEquals(u.Id, a1.OwnerId);
		System.assertEquals(u.Id, a2.OwnerId);
		System.assertNotEquals(u.Id, a3.OwnerId);
	}
}