cmss/main/default/objects/Account/fields/NACE__c.field-meta.xml
<CustomField>
    <fullName>NACE__c</fullName>
    <label>NACE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Account/fields/VatNumber__c.field-meta.xml
<CustomField>
    <fullName>VatNumber__c</fullName>
    <description>DIČ</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Vat Number</label>
    <type>TextArea</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/CustomSearchConfiguration__c.object-meta.xml
<CustomObject>
    <label>Custom Search Configuration</label>
    <nameField>
        <label>CustomSearchConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Search Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/FieldsetName__c.field-meta.xml
<CustomField>
    <fullName>FieldsetName__c</fullName>
    <label>Fieldset Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/FilterCondition__c.field-meta.xml
<CustomField>
    <fullName>FilterCondition__c</fullName>
    <label>Filter Condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchConfiguration__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ObjectType</valueSetName>
    </valueSet>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchFilter__c/CustomSearchFilter__c.object-meta.xml
<CustomObject>
    <label>Custom Search Filter</label>
    <nameField>
        <label>Custom Search Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Search Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/micro-campaign-custom-search/default/objects/CustomSearchFilter__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <label>Field Api Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchFilter__c/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>exact match</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>start with</fullName>
            </value>
            <value>
                <fullName>end with</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/micro-campaign-custom-search/default/objects/CustomSearchFilter__c/fields/RelatedObject__c.field-meta.xml
<CustomField>
    <fullName>RelatedObject__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ObjectType</valueSetName>
    </valueSet>
</CustomField>

cmss/main/default/objects/CustomSearchFilter__c/recordTypes/Number.recordType-meta.xml
<RecordType>
    <fullName>Number</fullName>
    <active>true</active>
    <label>Number</label>
</RecordType>

cmss/micro-campaign-custom-search/default/objects/CustomSearchFilter__c/recordTypes/Text.recordType-meta.xml
<RecordType>
    <fullName>Text</fullName>
    <active>true</active>
    <label>Text</label>
</RecordType>

cmss/main/default/globalValueSets/ObjectType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Asset</fullName>
    </customValue>
    <masterLabel>Object Type</masterLabel>
</GlobalValueSet>

cmss/micro-campaign-custom-search/default/classes/CustomSoqlServiceTest.cls
@IsTest
private class CustomSoqlServiceTest {
	@TestSetup
	static void beforeTest() {
		Account myAcc = new Account(Name = 'Sportisimo', VatNumber__c = 'CZ6397685965', NACE__c = 'AAA');
		insert myAcc;

		CustomSearchConfiguration__c myCustomSearchConfiguration = new CustomSearchConfiguration__c(
			FieldsetName__c = 'Search_Component',
			FILTERCONDITION__C = 'Name LIKE \'%s%\' ',
			ObjectType__c = 'Account'
		);
		insert myCustomSearchConfiguration;

		CustomSearchFilter__c csf = new CustomSearchFilter__c(
			FieldApiName__c = 'api',
			RecordTypeId = RecordTypeUtils.getRecordTypeIdByDeveloperName('Text', 'CustomSearchFilter__c'),
			RelatedObject__c = 'Account',
			Filter__c = 'contains'
		);
		insert csf;
	}
	@IsTest
	static void getOperatorToSelectStatementTest() {
		Test.startTest();
		String em = CustomSoqlService.getOperatorToSelectStatement('name', 'exact match', 'sport', 'Text');
		String co = CustomSoqlService.getOperatorToSelectStatement('name', 'contains', 'sport', 'Text');
		String sv = CustomSoqlService.getOperatorToSelectStatement('name', 'start with', 'sport', 'Text');
		String ev = CustomSoqlService.getOperatorToSelectStatement('name', 'end with', 'sport', 'Text');
		String nm = CustomSoqlService.getOperatorToSelectStatement('VatNumber__c', '<=', '1234', 'number');
		System.assertEquals(em, 'name = \'sport\'');
		System.assertEquals(co, 'name LIKE \'%sport%\'');
		System.assertEquals(sv, 'name LIKE \'sport%\'');
		System.assertEquals(ev, 'name LIKE \'%sport\'');
		System.assertEquals(nm, 'VatNumber__c <= 1234');
		Test.stopTest();
	}

	@IsTest
	static void customSoqlServiceTestgetDataFromDbdto() {
		CustomSearchFilterRequestDto mydto = new CustomSearchFilterRequestDto();
		CustomSearchConfiguration__c myCustomSearchConfiguration = [
			SELECT FieldsetName__c, FilterCondition__c, ObjectType__c
			FROM CustomSearchConfiguration__c
			LIMIT 1
		];

		mydto.configuration = myCustomSearchConfiguration;
		mydto.objectName = 'Account';
		List<CustomSearchFilterRequestDto.CustomFilterItemDto> myfilterItemList = new List<CustomSearchFilterRequestDto.CustomFilterItemDto>();
		CustomSearchFilterRequestDto.CustomFilterItemDto myCustomFilterItemDto = new CustomSearchFilterRequestDto.CustomFilterItemDto();
		CustomSearchFilterRequestDto.CustomFilterItemDto myCustomFilterItemDto2 = new CustomSearchFilterRequestDto.CustomFilterItemDto();
		List<CustomSearchFilterRequestDto.CustomFilterItemDto> myCustomFilterItemDtoList = new List<CustomSearchFilterRequestDto.CustomFilterItemDto>();

		myCustomFilterItemDto.objectName = 'Account';
		myCustomFilterItemDto.fieldName = 'Name';
		myCustomFilterItemDto.dataType = 'Text';
		myCustomFilterItemDto.filters = new List<CustomSearchFilterRequestDto.FilterOptionDto>();

		CustomSearchFilterRequestDto.FilterOptionDto filter1 = new CustomSearchFilterRequestDto.FilterOptionDto();
		filter1.type = 'exact match';
		filter1.value = 'Sportisimo';
		CustomSearchFilterRequestDto.FilterOptionDto filter2 = new CustomSearchFilterRequestDto.FilterOptionDto();
		filter2.type = 'contains';
		filter2.value = 'Sport';

		myCustomFilterItemDto.filters.add(filter1);
		myCustomFilterItemDto.filters.add(filter2);

		myCustomFilterItemDtoList.add(myCustomFilterItemDto);
		mydto.filterItemList = myCustomFilterItemDtoList;
		System.debug(mydto);
		Test.startTest();
		CustomSoqlService service = new CustomSoqlService(mydto);
		List<SObject> my = new List<SObject>();
		my = service.getDataFromDbDto();
		Test.stopTest();
		system.System.debug(my);
		System.assertEquals(1, my.size());
	}
}