cmss/main/default/objects/Account/fields/PortfolioMngmtA__c.field-meta.xml
<CustomField>
    <fullName>PortfolioMngmtA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Správce stavu A - Jedinečný identifikátor pro entitu Odbytový orgán přidruženou k entitě Klient</description>
    <label>Portfolio Management A</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagedAccountsA</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ClosingAgentId__c.field-meta.xml
<CustomField>
    <fullName>ClosingAgentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Zprostředkovatel smlouvy - Uzavírajíci OZ</description>
    <label>Closing Agent Id</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Asset/fields/PortfolioMngmtA__c.field-meta.xml
<CustomField>
    <fullName>PortfolioMngmtA__c</fullName>
    <formula>Account.PortfolioMngmtA__r.LastName + &apos; &apos; +  Account.PortfolioMngmtA__r.FirstName</formula>
    <label>Portfolio Management A</label>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ProductCloseDate__c.field-meta.xml
<CustomField>
    <fullName>ProductCloseDate__c</fullName>
    <description>Datum kdy byl produkt uzavřen</description>
    <label>Product Close Date</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Asset/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>0 = úverový případ
1 = Úvěr ze Stavebního Spoření (USS)
2 = Meziúvěr (MU)
7 = Účet Rizikového Životního Pojištění (RZP)
9 = účet Stavebního Spoření (SS)&quot;</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Asset/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Typ produktu - Product2</description>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidFrom__c.field-meta.xml
<CustomField>
    <fullName>ValidFrom__c</fullName>
    <label>Valid From</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/Opportunity/fields/ValidTo__c.field-meta.xml
<CustomField>
    <fullName>ValidTo__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

cmss/customer-360/classes/AssetTriggerHandlerTest.cls
@IsTest
public class AssetTriggerHandlerTest {
    
	@IsTest
	static void pairWithExistingOppTest() {
        Account acc = TestDataFactory.getAccount();
        insert acc;

        User owner = new User();
        owner.FirstName = 'Joe';
        owner.LastName = 'Tester';
        owner = TestDataFactory.getUser(owner);
        insert owner;

        Opportunity opp = new Opportunity();
        opp.Name = 'Test opp';
        opp.CloseDate = System.today().addDays(10);
        opp.AccountId = acc.Id;
        opp.OwnerId = owner.Id;
        opp.ProductType__c = '1';
        opp.StageName = '1';
        opp.ValidFrom__c = System.today().addDays(-10);
        opp.ValidTo__c = System.today().addDays(10);
        insert opp;

        Asset asset = new Asset();
        asset.name = 'Test asset';
        asset.AccountID = acc.Id;
        asset.ClosingAgentId__c = owner.Id;
        asset.ProductType__c = '1';
        asset.ProductCloseDate__c = System.today();

        Test.startTest();
        insert asset;
        Test.stopTest();

        opp = [SELECT Id, StageName, Reason__c, Category__c, Probability from Opportunity WHERE Id = : opp.Id];

        System.assertEquals('7', opp.StageName);
        System.assertEquals('3', opp.Reason__c);
        System.assertEquals('2', opp.Category__c);
        System.assertEquals(100, opp.Probability);
	}

	@IsTest
	static void pairWithNewOppTest() {
        Account acc = TestDataFactory.getAccount();
        insert acc;

        User owner = new User();
        owner.FirstName = 'Joe';
        owner.LastName = 'Tester';
        owner = TestDataFactory.getUser(owner);
        insert owner;

        Asset asset = new Asset();
        asset.name = 'Test asset';
        asset.AccountID = acc.Id;
        asset.ClosingAgentId__c = owner.Id;
        asset.ProductType__c = '1';
        asset.ProductCloseDate__c = System.today();

        Test.startTest();
        insert asset;
        Test.stopTest();

        Opportunity opp = [SELECT Id, StageName, Reason__c, Category__c, Probability, Account.Id from Opportunity LIMIT 1];

        System.assertEquals('7', opp.StageName);
        System.assertEquals('3', opp.Reason__c);
        System.assertEquals('2', opp.Category__c);
        System.assertEquals(100, opp.Probability);
	}

	@IsTest
	static void pairWithNewOppUseAccountIfo() {
        User owner = new User();
        owner.FirstName = 'Joe';
        owner.LastName = 'Tester';
        owner = TestDataFactory.getUser(owner);
        insert owner;

        Account acc = TestDataFactory.getAccount();
        acc.PortfolioMngmtA__c = owner.Id;
        insert acc;

        Asset asset = new Asset();
        asset.name = 'Test asset';
        asset.AccountID = acc.Id;
        asset.ProductType__c = '1';
        asset.ProductCloseDate__c = System.today();

        Test.startTest();
        insert asset;
        Test.stopTest();

        Opportunity opp = [SELECT Id, OwnerId, StageName, Reason__c, Category__c, Probability, Account.Id from Opportunity LIMIT 1];

        System.assertEquals('7', opp.StageName);
        System.assertEquals('3', opp.Reason__c);
        System.assertEquals('2', opp.Category__c);
        System.assertEquals(acc.PortfolioMngmtA__c, opp.OwnerId);
        System.assertEquals(100, opp.Probability);
	}

	@IsTest
	static void pairNewExistingOppUnsufficient() {
        Account acc = TestDataFactory.getAccount();
        insert acc;

        User owner = new User();
        owner.FirstName = 'Joe';
        owner.LastName = 'Tester';
        owner = TestDataFactory.getUser(owner);
        insert owner;

        Opportunity opp = new Opportunity();
        opp.Name = 'Test opp';
        opp.CloseDate = System.today().addDays(10);
        opp.AccountId = acc.Id;
        opp.OwnerId = owner.Id;
        opp.ProductType__c = '1';
        opp.StageName = '1';
        opp.Category__c = '6'; //category which should cause this opp will not be paired
        opp.ValidFrom__c = System.today().addDays(-10);
        opp.ValidTo__c = System.today().addDays(10);
        insert opp;

        Asset asset = new Asset();
        asset.name = 'Test asset';
        asset.AccountID = acc.Id;
        asset.ClosingAgentId__c = owner.Id;
        asset.ProductType__c = '1';
        asset.ProductCloseDate__c = System.today();

        Test.startTest();
        insert asset;
        Test.stopTest();

        List<Opportunity> oppsWithAccountId = [SELECT Id, StageName, Reason__c, Category__c, Probability from Opportunity WHERE AccountId = : asset.AccountId];
        System.assertEquals(2, oppsWithAccountId.size());

        Opportunity pairedOpp = [SELECT Id, StageName, Reason__c, Category__c, Probability from Opportunity WHERE AccountId = : asset.AccountId and Probability = 100 LIMIT 1];

        System.assertEquals('7', pairedOpp.StageName);
        System.assertEquals('3', pairedOpp.Reason__c);
        System.assertEquals('2', pairedOpp.Category__c);
	}



}