cmss/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <description>Object represents &quot;velké souhlasy&quot;</description>
    <label>Consent</label>
    <nameField>
        <label>Consent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Consent__c/fields/EmailConsent__c.field-meta.xml
<CustomField>
    <fullName>EmailConsent__c</fullName>
    <description>Souhlas e-mail</description>
    <label>EmailConsent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/SMSConsent__c.field-meta.xml
<CustomField>
    <fullName>SMSConsent__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Souhlas SMS</description>
    <label>SMSConsent</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/InternalConsent__c/InternalConsent__c.object-meta.xml
<CustomObject>
    <label>Internal Consent</label>
    <nameField>
        <displayFormat>MS-{000000}</displayFormat>
        <label>Internal Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Consents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cmss/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Log__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

cmss/integrations/classes/soap/ConsentWebServiceTest.cls
@isTest
private class ConsentWebServiceTest {
    
    @isTest
    static void testEnableGeneralConsents() {
        Test.setMock(WebServiceMock.class, new ConsentWebServiceMock.GeneralConsentMock());
        
		List<Consent__c> consents = TestDataFactory.getConsents(200, new Consent__c());
		Test.startTest();
		List<String> externalIds = GeneralConsentEnablement.enableGeneralConsents(consents);
        Test.stopTest();
        
        System.assertEquals(100, externalIds.size());
        for (String externalId : externalIds) {
            System.assert(externalId.contains('3267wergjs'));
        }
    }

    @isTest
    static void testEnableInternalConsents() {
        Test.setMock(WebServiceMock.class, new ConsentWebServiceMock.InternalConsentMock());
        
		List<InternalConsent__c> internalConsents = TestDataFactory.getInternalConsents(200, new InternalConsent__c());
		Test.startTest();
		List<String> externalIds = InternalConsentEnablement.enableInternalConsents(internalConsents);
        Test.stopTest();
        
        System.assertEquals(100, externalIds.size());
        for (String externalId : externalIds) {
            System.assert(externalId.contains('kdslfn450'));
        }
    }

    @isTest
    static void testProcessChannelConsent() {
        Test.setMock(WebServiceMock.class, new ConsentWebServiceMock.ChannelConsentMock());
		
        Test.startTest();
        List<Consent__c> consents = TestDataFactory.getConsents(200, new Consent__c());
        insert consents;
        
        for (Consent__c c : consents) {
            c.EmailConsent__c = '1';
            c.SMSConsent__c = '2';
        }
        update consents;
        Test.stopTest();
        
        List<Log__c> logs = [SELECT Message__c, Payload__c FROM Log__c WHERE Message__c = 'EnableChannelConsent response' OR Message__c = 'DisableChannelConsent response'];
        System.assertEquals(400, logs.size());
        for (Log__c l : logs) {
            if (l.Message__c == 'EnableChannelConsent response') {
                System.assert(((String) ((Map<String, Object>) JSON.deserializeUntyped(l.Payload__c)).get('consentGuid')).contains('3267wergjs'));
            } else if (l.Message__c == 'DisableChannelConsent response') {
                ConsentWebServiceDataTypes.DisableChannelConsentResponseBodyType resp = 
                    (ConsentWebServiceDataTypes.DisableChannelConsentResponseBodyType) JSON.deserialize(l.Payload__c, ConsentWebServiceDataTypes.DisableChannelConsentResponseBodyType.class);
                System.assert(resp.success.Successful);
            }
        }
    }
}