cmss/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <description>Object represents &quot;velké souhlasy&quot;</description>
    <label>Consent</label>
    <nameField>
        <label>Consent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Consent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Klient</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consents</relationshipLabel>
    <relationshipName>Consents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

cmss/main/default/objects/Consent__c/fields/EmailConsent__c.field-meta.xml
<CustomField>
    <fullName>EmailConsent__c</fullName>
    <description>Souhlas e-mail</description>
    <label>EmailConsent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/EntityConsent__c.field-meta.xml
<CustomField>
    <fullName>EntityConsent__c</fullName>
    <description>Entita souhlasu</description>
    <label>EntityConsent</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ČMSS</fullName>
            </value>
            <value>
                <fullName>ČSOB</fullName>
            </value>
            <value>
                <fullName>ČSOB Asset</fullName>
            </value>
            <value>
                <fullName>ČSOB Group (ALL)</fullName>
            </value>
            <value>
                <fullName>ČSOB leasing</fullName>
            </value>
            <value>
                <fullName>ČSOB penzijní společnost</fullName>
            </value>
            <value>
                <fullName>ČSOB pojišťovna</fullName>
            </value>
            <value>
                <fullName>Hypoteční banka</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Patria Finance</fullName>
            </value>
            <value>
                <fullName>Síť</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/GeneralConsent__c.field-meta.xml
<CustomField>
    <fullName>GeneralConsent__c</fullName>
    <description>Skupinový souhlas</description>
    <label>GeneralConsent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/GeneralConsentVersion__c.field-meta.xml
<CustomField>
    <fullName>GeneralConsentVersion__c</fullName>
    <description>Skupinový souhlas verze</description>
    <label>General Consent Version</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>400</fullName>
            </value>
            <value>
                <fullName>500</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/PhoneConsent__c.field-meta.xml
<CustomField>
    <fullName>PhoneConsent__c</fullName>
    <description>Souhals telefon</description>
    <label>PhoneConsent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/PortalConsent__c.field-meta.xml
<CustomField>
    <fullName>PortalConsent__c</fullName>
    <description>Souhlas el. portál</description>
    <label>Portal Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/PostConsent__c.field-meta.xml
<CustomField>
    <fullName>PostConsent__c</fullName>
    <description>Souhlas pošta</description>
    <label>Post Consent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/default/objects/Consent__c/fields/SMSConsent__c.field-meta.xml
<CustomField>
    <fullName>SMSConsent__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Souhlas SMS</description>
    <label>SMSConsent</label>
    <type>Checkbox</type>
</CustomField>

cmss/consent-icons/classes/ConsentIconsController.cls
/**
 * Created by a.olexova on 4/8/2020.
 */

public with sharing class ConsentIconsController {
	/**
	 * @author andrea olexova
	 * @description method to get a consent linked to the account with the ID from @param accountId
	 *     returns the latest created consent, although there should never be more than 1 consent per client
	 */
	@AuraEnabled(Cacheable=true)
	public static Consent__c getConsentForAccount(Id accountId) {
		if (String.isNotBlank(accountId)) {
			try {
				List<Consent__c> consents = [
					SELECT
						Id,
						Name,
						GeneralConsent__c,
						GeneralConsentVersion__c,
						Account__c,
						EmailConsent__c,
						EntityConsent__c,
						SMSConsent__c,
						PortalConsent__c,
						PhoneConsent__c,
						PostConsent__c
					FROM Consent__c
					WHERE Account__c = :accountId
					WITH SECURITY_ENFORCED
					ORDER BY CreatedDate DESC
					LIMIT 1
				];
				if (!consents.isEmpty()) {
					return consents.get(0);
				}
			} catch (QueryException qException) {
				String message = qException.getTypeName() + ': ' + qException.getMessage();
				AuraHandledException auraException = new AuraHandledException(message);
				auraException.setMessage(message);
				throw auraException;
			}
		} else {
			String message = 'Missing parameter: accountId.';
			AuraHandledException auraException = new AuraHandledException(message);
			auraException.setMessage(message);
			throw auraException;
		}
		return new Consent__c();
	}
}