cmss/main/default/objects/MailServiceNotification__c/MailServiceNotification__c.object-meta.xml
<CustomObject>
    <label>MailServiceNotification</label>
    <nameField>
        <label>MailServiceNotification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MailServiceNotifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

cmss/main/default/objects/MailServiceNotification__c/fields/DateSent__c.field-meta.xml
<CustomField>
    <fullName>DateSent__c</fullName>
    <label>DateSent</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/FromEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>FromEmailAddress__c</fullName>
    <label>FromEmailAddress</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/NotSentDueToError__c.field-meta.xml
<CustomField>
    <fullName>NotSentDueToError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NotSentDueToError</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/SendAfter__c.field-meta.xml
<CustomField>
    <fullName>SendAfter__c</fullName>
    <label>SendAfter</label>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/ToEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>ToEmailAddress__c</fullName>
    <label>ToEmailAddress</label>
    <type>Email</type>
</CustomField>

cmss/main/default/classes/MailServiceNotificationsQueue.cls
public class MailServiceNotificationsQueue implements Queueable, Finalizer, Database.AllowsCallouts {
	private MailSOAPService.MailServicePort mailService;
	DateTime currentTime = System.now();
	public void execute(QueueableContext context) {
		String jobId = '' + context.getJobId();
		List<MailServiceNotification__c> mailServiceNotificationsToUpdate = new List<MailServiceNotification__c>();
		try {
			Finalizer finalizer = new MailServiceNotificationsQueue();
			System.attachFinalizer(finalizer);
			this.mailService = new MailSOAPService.MailServicePort();
			for (MailServiceNotification__c mailServiceNotification : [
				SELECT FromEmailAddress__c, ToEmailAddress__c, Subject__c, Body__c
				FROM MailServiceNotification__c
				WHERE DateSent__c = NULL AND SendAfter__c <= :currentTime AND NotSentDueToError__c = FALSE
				ORDER BY SendAfter__c
				LIMIT 50
			]) {
				HttpResponse response = mailService.sendEmail_Http(
					mailServiceNotification.ToEmailAddress__c,
					mailServiceNotification.FromEmailAddress__c,
					mailServiceNotification.Subject__c,
					mailServiceNotification.Body__c
				);
				if (response.getStatusCode() == 200) {
					mailServiceNotification.DateSent__c = currentTime;
				} else {
					Logger.error('MailSOAPService callout failed');
					mailServiceNotification.ErrorMessage__c = response.getStatus();
					mailServiceNotification.NotSentDueToError__c = true;
				}
				mailServiceNotificationsToUpdate.add(mailServiceNotification);
			}
		} catch (Exception e) {
			Logger.error('Error executing the job [' + jobId + ']: ' + e.getMessage());
			throw e;
		} finally {
			if (mailServiceNotificationsToUpdate.size() > 0) {
				System.debug('Updating ' + mailServiceNotificationsToUpdate.size() + ' mailServiceNotifications.');
				update mailServiceNotificationsToUpdate;
			}
			Logger.debug('Completed: execution of queueable job: ' + jobId);
			Logger.saveLogs();
		}
	}
	public void execute(FinalizerContext context) {
		String parentJobId = '' + context.getAsyncApexJobId();
		System.debug('Begin: executing finalizer attached to queueable job: ' + parentJobId);
		List<MailServiceNotification__c> mailServiceNotifications = [
			SELECT FromEmailAddress__c, ToEmailAddress__c, Subject__c, Body__c
			FROM MailServiceNotification__c
			WHERE DateSent__c = NULL AND SendAfter__c <= :currentTime AND NotSentDueToError__c = FALSE
		];
		if (mailServiceNotifications.size() > 0) {
			System.enqueueJob(new MailServiceNotificationsQueue());
		}
	}
}