cmss/main/default/objects/MailServiceNotification__c/MailServiceNotification__c.object-meta.xml
<CustomObject>
    <label>MailServiceNotification</label>
    <nameField>
        <label>MailServiceNotification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MailServiceNotifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

cmss/main/default/objects/MailServiceNotification__c/fields/FromEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>FromEmailAddress__c</fullName>
    <label>FromEmailAddress</label>
    <type>Email</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/NotSentDueToError__c.field-meta.xml
<CustomField>
    <fullName>NotSentDueToError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NotSentDueToError</label>
    <type>Checkbox</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/fields/ToEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>ToEmailAddress__c</fullName>
    <label>ToEmailAddress</label>
    <type>Email</type>
</CustomField>

cmss/integrations/classes/handlers/ThreatDetectionNotificationHandlerTest.cls
@isTest
public class ThreatDetectionNotificationHandlerTest {

    @IsTest
	static void sendThreatDetectionEmailNotificatonsTest() {

        Test.setMock(HttpCalloutMock.class, new MailSOAPServiceHttpMock());
		insert TestDataFactory.getIntegrationSettings();

        String rawParams = '{"eventIdentifier":"123456789", "Score":"1"}';
        
        APIAnomalyEventStore apEventRecord = (APIAnomalyEventStore) JSON.deserialize(rawParams, APIAnomalyEventStore.class);
        CredentialStuffingEventStore csEventRecord = (CredentialStuffingEventStore) JSON.deserialize(rawParams, CredentialStuffingEventStore.class);
        ReportAnomalyEventStore raEventRecord = (ReportAnomalyEventStore) JSON.deserialize(rawParams, ReportAnomalyEventStore.class);
        SessionHijackingEventStore shEventRecord = (SessionHijackingEventStore) JSON.deserialize(rawParams, SessionHijackingEventStore.class);

        Test.startTest();
            ThreatDetectionNotificationHandler.sendThreatDetectionEmailNotificatons(new List<sObject> {apEventRecord, csEventRecord, raEventRecord, shEventRecord});
        Test.stopTest();
        
        List<MailServiceNotification__c> createdNotifications = [
			SELECT Body__c, Subject__c, ToEmailAddress__c, FromEmailAddress__c, NotSentDueToError__c
			FROM MailServiceNotification__c
		];
        System.assertEquals(4, createdNotifications.size());
    }

    @IsTest
	static void handleTest() {

        Test.setMock(HttpCalloutMock.class, new MailSOAPServiceHttpMock());
		insert TestDataFactory.getIntegrationSettings();

        String rawParams = '{"eventIdentifier":"123456789", "Score":"1"}';
        
        APIAnomalyEventStore apEventRecord = (APIAnomalyEventStore) JSON.deserialize(rawParams, APIAnomalyEventStore.class);
        CredentialStuffingEventStore csEventRecord = (CredentialStuffingEventStore) JSON.deserialize(rawParams, CredentialStuffingEventStore.class);
        ReportAnomalyEventStore raEventRecord = (ReportAnomalyEventStore) JSON.deserialize(rawParams, ReportAnomalyEventStore.class);
        SessionHijackingEventStore shEventRecord = (SessionHijackingEventStore) JSON.deserialize(rawParams, SessionHijackingEventStore.class);

        ThreatDetectionNotificationHandler handler = new ThreatDetectionNotificationHandler();
        Test.startTest();
            handler.handle(new List<sObject> {apEventRecord, csEventRecord, raEventRecord, shEventRecord});
        Test.stopTest();

        List<MailServiceNotification__c> createdNotifications = [
			SELECT Body__c, Subject__c, ToEmailAddress__c, FromEmailAddress__c, NotSentDueToError__c
			FROM MailServiceNotification__c
		];
        System.assertEquals(4, createdNotifications.size());
    }

    @IsTest
	static void handleTresholdTest() {

        Test.setMock(HttpCalloutMock.class, new MailSOAPServiceHttpMock());
		insert TestDataFactory.getIntegrationSettings();

        String rawParams = '{"eventIdentifier":"123456789", "Score":"-1"}';
        
        APIAnomalyEventStore apEventRecord = (APIAnomalyEventStore) JSON.deserialize(rawParams, APIAnomalyEventStore.class);
        CredentialStuffingEventStore csEventRecord = (CredentialStuffingEventStore) JSON.deserialize(rawParams, CredentialStuffingEventStore.class);
        ReportAnomalyEventStore raEventRecord = (ReportAnomalyEventStore) JSON.deserialize(rawParams, ReportAnomalyEventStore.class);
        SessionHijackingEventStore shEventRecord = (SessionHijackingEventStore) JSON.deserialize(rawParams, SessionHijackingEventStore.class);

        ThreatDetectionNotificationHandler handler = new ThreatDetectionNotificationHandler();
        Test.startTest();
            handler.handle(new List<sObject> {apEventRecord, csEventRecord, raEventRecord, shEventRecord});
        Test.stopTest();

        List<MailServiceNotification__c> createdNotifications = [
			SELECT Body__c, Subject__c, ToEmailAddress__c, FromEmailAddress__c, NotSentDueToError__c
			FROM MailServiceNotification__c
		];
        System.assertEquals(0, createdNotifications.size());
    }
}