cmss/main/default/objects/Access_Log__c/Access_Log__c.object-meta.xml
<CustomObject>
    <label>Access Log</label>
    <nameField>
        <displayFormat>AL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Access_Log__c/fields/AccessTo__c.field-meta.xml
<CustomField>
    <fullName>AccessTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Logs</relationshipLabel>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/MailServiceNotification__c/MailServiceNotification__c.object-meta.xml
<CustomObject>
    <label>MailServiceNotification</label>
    <nameField>
        <label>MailServiceNotification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MailServiceNotifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

cmss/main/default/objects/MailServiceNotification__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/activity-management/classes/ExceededLogsNotificationScheduleTest.cls
@isTest
class ExceededLogsNotificationScheduleTest {
	@TestSetup
	static void makeData() {
		insert TestDataFactory.getIntegrationSettings();

		User testUser1 = TestDataFactory.getUser(new User(LastName = 'Testovič'));
		User testUser2 = TestDataFactory.getUser(new User(LastName = 'Netestil'));
		insert new List<User>{ testUser1, testUser2 };

		Account testAccount = TestDataFactory.getAccount();
		insert testAccount;

		Access_Log__c log1 = new Access_Log__c();
		log1.RequestedBy__c = testUser1.Id;
		log1.AccessTo__c = testAccount.Id;

		Access_Log__c log2 = new Access_Log__c();
		log2.RequestedBy__c = testUser1.Id;
		log2.AccessTo__c = testAccount.Id;

		Access_Log__c log3 = new Access_Log__c();
		log3.RequestedBy__c = testUser2.Id;
		log3.AccessTo__c = testAccount.Id;

		insert new List<Access_Log__c>{ log1, log2, log3 };
		Integer month = System.today().month() == 1 ? 12 : System.today().month() - 1;
		Integer year = month == 12 ? System.today().year() - 1 : System.today().year();
		DateTime newDateTime = DateTime.newInstance(Date.newInstance(year, month, 15), Time.newInstance(12, 0, 0, 0));
		Test.setCreatedDate(log1.Id, newDateTime);
		Test.setCreatedDate(log2.Id, newDateTime);
		Test.setCreatedDate(log3.Id, newDateTime);
	}

	@isTest
	static void correctNotificationsCreatedTest() {
		EmailTemplate template = [
			SELECT Subject, HtmlValue
			FROM EmailTemplate
			WHERE DeveloperName = 'LogsAccessLimitExceeded'
		];

		Integer logsLimit = 1;
		List<String> receivers = new List<string>{ 'first@email.invalid', 'second@mail.invalid' };
		String reportURL = 'reportURL';

		Test.setMock(HttpCalloutMock.class, new MailSOAPServiceHttpMock());
		Test.startTest();
		ExceededLogsNotificationSchedule schedule = new ExceededLogsNotificationSchedule(
			logsLimit,
			receivers,
			reportURL
		);
		schedule.execute(null);
		Test.stopTest();
		List<MailServiceNotification__c> notifications = [SELECT Subject__c, Body__c FROM MailServiceNotification__c];

		System.assertEquals(2, notifications.size());
		System.assertEquals(template.Subject, notifications[0].Subject__c);
		System.assertEquals(true, notifications[0].Body__c.contains('Testovič'));
		System.assertEquals(false, notifications[0].Body__c.contains('Netestil'));
	}
}