cmss/main/default/objects/Access_Log__c/Access_Log__c.object-meta.xml
<CustomObject>
    <label>Access Log</label>
    <nameField>
        <displayFormat>AL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Access_Log__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Configuration__mdt/Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Generic table for all custom configurations.</description>
    <label>Configuration</label>
    <pluralLabel>Configurations</pluralLabel>
</CustomObject>

cmss/main/default/objects/Configuration__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/User/fields/CommissionAccountNr__c.field-meta.xml
<CustomField>
    <fullName>CommissionAccountNr__c</fullName>
    <description>Číslo provizního účtu</description>
    <externalId>true</externalId>
    <label>Commission Account Nr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/activity-management/classes/ExceededLogsNotificationSchedule.cls
public with sharing class ExceededLogsNotificationSchedule implements Schedulable {
	private Integer notificationLogsLimit;
	private List<String> notificationReceivers;
	private String notificationReportUrl;

	private final String MAIL_TEMPLATE_NAME = 'LogsAccessLimitExceeded';

	public ExceededLogsNotificationSchedule() {
	}

	public ExceededLogsNotificationSchedule(
		Integer notificationLogsLimit,
		List<String> notificationReceivers,
		String notificationReportUrl
	) {
		this.notificationLogsLimit = notificationLogsLimit;
		this.notificationReceivers = notificationReceivers;
		this.notificationReportUrl = notificationReportUrl;
	}

	public void execute(SchedulableContext sc) {
		try {
			if (notificationLogsLimit == null && notificationReceivers == null && notificationReportUrl == null) {
				loadConfig();
			}
			List<AggregateResult> accessLogAggregations = [
				SELECT COUNT(Id) logsCount, RequestedBy__c
				FROM Access_Log__c
				WHERE CreatedDate = LAST_MONTH
				GROUP BY RequestedBy__c
			];
			List<Id> usersToNotifyAbout = getUsersToNotifyAbout(accessLogAggregations);
			if (usersToNotifyAbout.size() > 0) {
				processLimitExceededForUsers(usersToNotifyAbout);
			}
		} catch (Exception e) {
			Logger.error('Error in ExceededLogsNotificationSchedule: ', e);
			throw e;
		} finally {
			Logger.saveLogs();
		}
	}

	private void loadConfig() {
		try {
			notificationLogsLimit = Integer.valueOf(
				Configuration__mdt.getInstance('LogsNotification_Limit').get('Value__c')
			);
			notificationReceivers = String.valueOf(
					Configuration__mdt.getInstance('LogsNotification_Receivers').get('Value__c')
				)
				.deleteWhitespace()
				.split(',');
			notificationReportUrl = String.valueOf(
				Configuration__mdt.getInstance('LogsNotification_ReportURL').get('Value__c')
			);
		} catch (Exception e) {
			throw new MissingOrMalformedConfigException(
				'LogsNotification records in Configuration__mdt are missing or maformed, please ensure their correctness.',
				e
			);
		}
	}

	private List<Id> getUsersToNotifyAbout(List<AggregateResult> accessLogAggregations) {
		List<Id> userIds = new List<Id>();
		for (AggregateResult singleUserLogs : accessLogAggregations) {
			if (Integer.valueOf(singleUserLogs.get('logsCount')) > notificationLogsLimit) {
				userIds.add((Id) singleUserLogs.get('RequestedBy__c'));
			}
		}
		return userIds;
	}

	private void processLimitExceededForUsers(List<Id> usersToNotifyAbout) {
		String listOfUsersFormated = getFormatedListOfUsers(usersToNotifyAbout);

		MailNotificationsHandler notificationsHandler = new MailNotificationsHandler();
		notificationsHandler.setEmailTemplate(MAIL_TEMPLATE_NAME)
			.setSpecialVariables(
				new Map<String, String>{
					'LIMIT' => String.valueOf(notificationLogsLimit),
					'CLIENTS_SUMMARY' => listOfUsersFormated,
					'REPORT_LINK' => notificationReportUrl
				}
			)
			.setReceivers(notificationReceivers)
			.generateNotifications();

		notificationsHandler.handleInsertNotifications();
	}

	private String getFormatedListOfUsers(List<Id> userIds) {
		String basicStyle = 'style="border: 1px solid black; border-collapse: collapse;"';
		String resultTable = getTableHeader(basicStyle);

		for (User user : [SELECT FirstName, LastName, CommissionAccountNr__c FROM User WHERE Id IN :userIds]) {
			resultTable += getTableRow(basicStyle, user);
		}
		resultTable += '</table>';
		return resultTable;
	}

	private String getTableHeader(String basicStyle) {
		return '\n <table ' +
			basicStyle +
			'><tr ' +
			basicStyle +
			'><th ' +
			basicStyle +
			'>ČPÚ</th><th ' +
			basicStyle +
			'>OZ příjmení jméno</th></tr>';
	}
	private String getTableRow(String basicStyle, User user) {
		return '<tr ' +
			basicStyle +
			'><td ' +
			basicStyle +
			'>' +
			user.CommissionAccountNr__c +
			'</td><td ' +
			basicStyle +
			'>' +
			user.LastName +
			' ' +
			user.FirstName +
			'</td></tr>';
	}

	public class MissingOrMalformedConfigException extends Exception {
	}
}