cmss/main/default/objects/Access_Log__c/Access_Log__c.object-meta.xml
<CustomObject>
    <label>Access Log</label>
    <nameField>
        <displayFormat>AL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Access_Log__c/fields/AccessTo__c.field-meta.xml
<CustomField>
    <fullName>AccessTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Logs</relationshipLabel>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/AccessShare__c.object-meta.xml
<CustomObject>
    <label>Access Share</label>
    <nameField>
        <displayFormat>AS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Search Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Share</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/AccessShare__c/fields/AccessTo__c.field-meta.xml
<CustomField>
    <fullName>AccessTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Share</relationshipLabel>
    <relationshipName>Search_Accesses</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Search_Accesses</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Tandem</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>KA Delegation</fullName>
            </value>
            <value>
                <fullName>SEZ Delegation</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/access-share/classes/AccessLogServiceTest.cls
@isTest
private class AccessLogServiceTest {
	@isTest
	static void testInsertLogsFromShares() {
		Account acc = TestDataFactory.getAccount();
		insert acc;

		AccessShare__c accessShare = new AccessShare__c();
		accessShare.AccessTo__c = acc.Id;
		accessShare.RequestedBy__c = UserInfo.getUserId();
		accessShare.Type__c = 'Search';
		accessShare.StartDate__c = Datetime.now();
		accessShare.ExpirationDate__c = Datetime.now().addDays(1);

		insert accessShare;

		AccessLogService.insertAccessLogsFromShares(new List<AccessShare__c>{ accessShare });

		List<Access_Log__c> accessLogs = [
			SELECT Id, AccessTo__c, RequestedBy__c, StartDate__c, ExpirationDate__c
			FROM Access_Log__c
		];
		System.assertEquals(1, accessLogs.size());
		System.assertEquals(acc.Id, accessLogs[0].AccessTo__c);
	}

	@isTest
	static void testInsertErrorLog() {
		AccessLogService.insertErrorLog('Error', 'Access Share creation failed');

		List<Access_Log__c> accessLogs = [SELECT Id, Type__c FROM Access_Log__c];

		System.assertEquals(1, accessLogs.size());
		System.assertEquals('Error', accessLogs[0].Type__c);
	}
}