cmss/main/default/objects/Access_Log__c/Access_Log__c.object-meta.xml
<CustomObject>
    <label>Access Log</label>
    <nameField>
        <displayFormat>AL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Access_Log__c/fields/AccessTo__c.field-meta.xml
<CustomField>
    <fullName>AccessTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Logs</relationshipLabel>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/AccessShare__c.object-meta.xml
<CustomObject>
    <label>Access Share</label>
    <nameField>
        <displayFormat>AS-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Search Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Share</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/AccessShare__c/fields/AccessTo__c.field-meta.xml
<CustomField>
    <fullName>AccessTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Share</relationshipLabel>
    <relationshipName>Search_Accesses</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Search_Accesses</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

cmss/main/default/objects/AccessShare__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Tandem</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>KA Delegation</fullName>
            </value>
            <value>
                <fullName>SEZ Delegation</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cmss/main/access-share/classes/AccessLogService.cls
/**
 * @description Helper methods for creating and updating Access Logs
 * @author Vaclav Moldan
 */
public without sharing class AccessLogService {
	private static Access_Log__c createAccessLog(
		Id accessTo,
		Id requestedBy,
		String type,
		Datetime startDate,
		Datetime expirationDate
	) {
		Access_Log__c accessLog = new Access_Log__c();
		accessLog.AccessTo__c = accessTo;
		accessLog.RequestedBy__c = requestedBy;
		accessLog.Type__c = type;
		accessLog.StartDate__c = startDate;
		accessLog.ExpirationDate__c = expirationDate;

		return accessLog;
	}

	public static void insertAccessLogsFromShares(List<AccessShare__c> accessShares) {
		List<Access_Log__c> logsToInsert = new List<Access_Log__c>();
		for (AccessShare__c accessShare : accessShares) {
			logsToInsert.add(
				createAccessLog(
					accessShare.AccessTo__c,
					accessShare.RequestedBy__c,
					accessShare.Type__c,
					accessShare.StartDate__c,
					accessShare.ExpirationDate__c
				)
			);
		}

		insert logsToInsert;
	}

	public static void insertErrorLog(String type, String errorMessage) {
		Access_Log__c errorLog = new Access_Log__c();
		errorLog.type__c = type;
		errorLog.Message__c = errorMessage;

		insert errorLog;
	}
}