cmss/main/default/objects/Access_Log__c/Access_Log__c.object-meta.xml
<CustomObject>
    <label>Access Log</label>
    <nameField>
        <displayFormat>AL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Access_Log__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/TaskID__c.field-meta.xml
<CustomField>
    <fullName>TaskID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TaskId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/TaskLetterId__c.field-meta.xml
<CustomField>
    <fullName>TaskLetterId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TaskLetterId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/TaskLetterType__c.field-meta.xml
<CustomField>
    <fullName>TaskLetterType__c</fullName>
    <label>TaskLetterType</label>
    <encryptionScheme>None</encryptionScheme>
    <length>50</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

cmss/main/default/classes/EDocumentController.cls
global with sharing class EDocumentController {
    public String base64Data { get; set; }
    public Boolean showPDF { get; set; }
    public Boolean isError { get; set; }
    public String recordId { get; set; }
    public String letterId { get; set; }
    public String letterType { get; set; }

    public EDocumentController(ApexPages.StandardController controller){
        recordId = Apexpages.currentPage().getParameters().get('recordId');
        isError = false;
        showPDF = false;

        try{
            Task sourceTask = [SELECT Id, LetterId__c, LetterType__c
                      FROM Task
                      WHERE Id = :recordId];

            letterId = sourceTask.LetterId__c;
            letterType = sourceTask.LetterType__c;

            CommonMessageService.RequestHeader header = new CommonMessageService.RequestHeader();
            EDocumentSOAPService.GetDocumentBySBIdRequestBody body = new EDocumentSOAPService.GetDocumentBySBIdRequestBody();
            body.documentSBId = letterId;
            EDocumentSOAPService.EDocumentServicePort stub = new EDocumentSOAPService.EDocumentServicePort();
            base64Data = stub.getDocumentBySBId_Http(header, body);
            showPDF = true;
        } catch (Exception e){
            Logger.error('Error in EDocumentController', e);
            isError = true;
            showPDF = false;
        } finally{
            Logger.saveLogs();
        }
    }

    @RemoteAction
    global static void createAccessLogRecord(String letterId, String letterType, String taskId){
        Access_Log__c log = new Access_Log__c();
        log.RequestedBy__c = UserInfo.getUserId();
        log.TaskLetterId__c = letterId;
        log.TaskLetterType__c = letterType;
        log.TaskId__c = taskId;
        insert log;
    }

}