cmss/main/default/objects/Access_Log__c/Access_Log__c.object-meta.xml
<CustomObject>
    <label>Access Log</label>
    <nameField>
        <displayFormat>AL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cmss/main/default/objects/Access_Log__c/fields/FilterCPUSuffix__c.field-meta.xml
<CustomField>
    <fullName>FilterCPUSuffix__c</fullName>
    <label>FilterCPUSuffix</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/FilterOwnerCommissionAccountBase__c.field-meta.xml
<CustomField>
    <fullName>FilterOwnerCommissionAccountBase__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FilterOwnerCommissionAccountBase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/FilterPeriod__c.field-meta.xml
<CustomField>
    <fullName>FilterPeriod__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FilterPeriod</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/FilterRecordNumber__c.field-meta.xml
<CustomField>
    <fullName>FilterRecordNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FilterRecordNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/FilterStatementType__c.field-meta.xml
<CustomField>
    <fullName>FilterStatementType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FilterStatementType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/fields/RequestedBy__c.field-meta.xml
<CustomField>
    <fullName>RequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Access_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cmss/main/default/objects/Access_Log__c/recordTypes/PVPDFExport.recordType-meta.xml
<RecordType>
    <fullName>PVPDFExport</fullName>
    <active>true</active>
    <label>PV PDF Export</label>
</RecordType>

cmss/main/default/classes/CommissionPdfGeneratorController.cls
public without sharing class CommissionPdfGeneratorController {
	public String html { get; set; }
	public String selectedReportName { get; set; }
	public String selectedPeriod { get; set; }
	public String commissionAccount { get; set; }
	public String combinedName { get; set; }
	public String address { get; set; }
	public String footerTimestamp { get; set; }
	public String cpu { get; set; }
	public String filterReport { get; set; }
	public String filterRecordRange { get; set; }

	public void insertAccessLog() {
		Access_Log__c accessLog = new Access_Log__c();
		accessLog.RequestedBy__c = UserInfo.getUserId();
		accessLog.Type__c = 'PV PDF Export';
		if (cpu.deleteWhitespace().isNumeric()) {
			accessLog.FilterCPUSuffix__c = Integer.valueOf(cpu.deleteWhitespace());
		}
		accessLog.FilterPeriod__c = selectedPeriod;
		accessLog.FilterStatementType__c = filterReport;
		accessLog.FilterRecordNumber__c = filterRecordRange;
		accessLog.FilterOwnerCommissionAccountBase__c = commissionAccount;
		accessLog.RecordTypeId = Schema.sObjectType.Access_Log__c.getRecordTypeInfosByDeveloperName()
			.get('PVPDFExport')
			.getRecordTypeId();
		insert accessLog;
	}

	public CommissionPdfGeneratorController() {
		html = ApexPages.currentPage().getParameters().get('html');
		selectedReportName = ApexPages.currentPage().getParameters().get('selectedReportName');
		selectedPeriod = ApexPages.currentPage().getParameters().get('selectedPeriod');
		commissionAccount = ApexPages.currentPage().getParameters().get('commissionAccount');
		combinedName = ApexPages.currentPage().getParameters().get('combinedName');
		address = ApexPages.currentPage().getParameters().get('address');
		footerTimestamp = ApexPages.currentPage().getParameters().get('footerTimestamp');
		cpu = ApexPages.currentPage().getParameters().get('cpu');
		filterReport = ApexPages.currentPage().getParameters().get('filterReport');
		filterRecordRange = ApexPages.currentPage().getParameters().get('filterRecordRange');
	}
}